### ISSUE TITLE
Adding Malay Translation

### ISSUE THREAD

**Issue by plokmi** [progit/progit2#1000]
Good evening, I have completed first chapter of translations into Malay.
The relevant repo is here: https://github.com/progit2-ms/progit2
Could you advise what should I do next to get my repository listed?

Regards,
plokmi

Contact: plokmi@live.com.my,plokmi#5120 on Discord.

**Comment by jnavila** [comment]
Hi,that's great! Can you grant me administrative privilege on the repository so that I can set up automatic compilation? Thanks.

**Comment by plokmi** [comment]
Not a problem, already sent the invite.

**Comment by plokmi** [comment]
Hello there, do keep me informed if you need me to do anything from my end. Thank you.

**Comment by jnavila** [comment]
Hi,

I sent you a request for more privileges. It seems I cannot set up the continuous integration without privileges to your organization.

**Comment by plokmi** [comment]
@jnavila I have invite you with administrative permission to the organization. You can visit this, https://github.com/progit2-ms to handle the invite, thank you!

**Comment by jnavila** [comment]
Done. The compilation is ok. The malay version should be visible on https://git-scm.com/book/ms by tomorrow. You can already see the generation of the book in ebook formats at https://github.com/progit2-ms/progit2/releases

**Comment by plokmi** [comment]
@jnavila Thank you, I will now close this issue.

**Comment by danialhx** [comment]
only the first chapter is in Malay?
