### ISSUE TITLE
Asciidoctor showing up as Author in GPB

### ISSUE THREAD

**Issue by jxramos** [progit/progit2#1009]
I just noticed in GooglePlayBooks that the author field is rendering as "Asciioctor" as seen in the snippet below. Should prove useful to see what governs it and populate it with the correct information.
![img_20180227_201907](https://user-images.githubusercontent.com/13857038/36769860-ce8acd82-1bfb-11e8-8370-7ce694884dc9.jpg)

**Comment by jnavila** [comment]
That's in the header of asciidoc. The work in progit/progit2-pub needs to be ported here.

**Comment by jnavila** [comment]
In fact, the problem seems to stem from asciidoctor itself.

**Comment by KZiemian** [comment]
How situation looks now?
