### ISSUE TITLE
`Git Internals`should have `Summary` be it's last part of the chapter

### ISSUE THREAD

**Issue by AjkP** [progit/progit2#1010]
`Git Internals`(Chapter 10) should have `Summary` be it's last part of the chapter.

It's confusing for the reader as he will likely implicitly think of the chapter as `complete` and move on.

I can make a pull request for this.

**Comment by AjkP** [comment]
Noting that the last section:
`10.10 Git Internals - Moving Files`
Is likely not even correctly in that chapter.

**Comment by jnavila** [comment]
*Moving Files* is a subsection of chapter 2. I guess there was a hiccup in the scripts for importing the book when we changed the architecture of the files. The script should delete from the DB any dangling section past the one that were imported.
