### ISSUE TITLE
Problem displaying VERSION and DATE

### ISSUE THREAD

**Issue by eyherabh** [progit/progit2#1033]
Commit eff61943be6f059e9e23e5dfa357b425b4d6e327 introduced VERSION and DATE, but the result is printed as follows: 

![image](https://user-images.githubusercontent.com/25811648/38717308-d716a230-3eee-11e8-9c50-c23654841fcb.png)

The compilation was conducted with "asciidoctor progit.asc", as indicated in REDME.md.

The problem is solved should I compile with "bundle" instead, but I have yet problems installing it due to missing zlib ( I'm using Elementary OS). In this respect, I think it would be a good idea to add a few lines indicating that one may need to install zlib1g-dev, ruby-dev and ruby-bundler before using bundle install (for example, as in my fork eyherabh/progit2).

**Comment by jnavila** [comment]
Ah, that's true that now the version and date are injected in the content with the Rakefile, so if you compile directly, you only get the placeholders.

**Comment by KZiemian** [comment]
Should this issue remain open?
