### ISSUE TITLE
Feature request - "git grep xxx"

### ISSUE THREAD

**Issue by yuriw** [progit/progit2#1036]
"git grep xxx" currently does not follow symlinks.
Please consider adding this functionality

**Comment by deoren** [comment]
> @yuriw: "git grep xxx" currently does not follow symlinks.
Please consider adding this functionality

Note: If you're asking for coverage of Git functionality you've posted to the wrong project. See the following remark from https://github.com/git/git:

> The user discussion and development of Git take place on the Git mailing list -- everyone is welcome to post bug reports, feature requests, comments and patches to git@vger.kernel.org (read Documentation/SubmittingPatches for instructions on patch submission). To subscribe to the list, send an email with just "subscribe git" in the body to majordomo@vger.kernel.org. The mailing list archives are available at https://public-inbox.org/git/, http://marc.info/?l=git and other archival sites.

This project is intended to track the work on the Pro Git 2 book (https://git-scm.com/book/en/v2), so if your request is instead coverage of an existing Git feature this is *likely* the right place to do it. 

I'm not affiliated with this project, but I saw this issue and figured I'd chime in. Hope that helps.

**Comment by yuriw** [comment]
ok thx !
