### ISSUE TITLE
Indonesian translation (id)

### ISSUE THREAD

**Issue by hanief** [progit/progit2#104]
Hi, I want to open a new translation to Indonesian. I have visited the https://progit.org/translations page, but there is no instructions about it yet.

**Comment by schacon** [comment]
I'm going to close this for now. If you get a chapter or two translated, go ahead and either re-open it or open a new one.

**Comment by michel-slm** [comment]
Yeah, process seems to be stalled. Will try and re-coordinate with @hanief
