### ISSUE TITLE
Contributors list is missing in recent electronic editions

### ISSUE THREAD

**Issue by sampablokuper** [progit/progit2#1040]
as published at https://git-scm.com/book/en/v2, including:

- [PDF Version 2.1.49, 2018-04-07](https://github.com/progit/progit2/releases/download/2.1.49/progit.pdf)
- [PDF Version 2.1.51, 2018-04-17](https://github.com/progit/progit2/releases/download/2.1.51/progit.pdf)

It should be on page 5 of those versions, but it isn't.

**Comment by deoren** [comment]
FWIW, the epub and mobi formats are similarly affected (as of 2.1.52).

**Comment by jnavila** [comment]
Fixed in 58e18046b1015446be8d3d28728fe0e67d1fae01. Now, using the Rakefile is mandatory.
