### ISSUE TITLE
ePub. mobi formats are missing the title page (and as a result the VERSION, DATE values)

### ISSUE THREAD

**Issue by deoren** [progit/progit2#1041]
I see that #1031 introduced VERSION and DATE values, but it appears that those values only show up for the PDF version. Looking closer I see that is because those formats do not appear to include the title page that the PDF format has.

I checked and v2.1.52 still has the issue. Please let me know if I can provide more info.

Thanks!

**Comment by jnavila** [comment]
It's mostly a issue with asciidoctor. The source of the book is correct, but the compilation chain does not include the provided data.

**Comment by KZiemian** [comment]
This is second open issue that I see, that is about problem with compilation chain of asciidoctor. Is there a reason for it to remain open?
