### ISSUE TITLE
Customizing-Git-An-Example-Git-Enforced-Policy need remark

### ISSUE THREAD

**Issue by ivanbogomoloff** [progit/progit2#1043]
Here https://git-scm.com/book/en/v2/Customizing-Git-An-Example-Git-Enforced-Policy

I think it must contain remark about git hook update when it is new branch.
oldrev will be 0 and hook will not work. And all commits will be passed.
```
missed_revs = `git rev-list #{$oldrev}..#{$newrev}`.split("\n")
```

https://stackoverflow.com/questions/3511057/git-receive-update-hooks-and-new-branches look at "right answer"

**Comment by ben** [comment]
Ooh, nice. If you have a handle on how this could be resolved, do you want to submit a PR?

**Comment by haianh2017** [comment]
Vào Th 7, 27 thg 7, 2024 lúc 00:26 ivan ***@***.***> đã viết:
