### ISSUE TITLE
3.2 Git branching effect of checkout on working directory

### ISSUE THREAD

**Issue by edenhochbaum** [progit/progit2#1051]
[The text says:](https://github.com/progit/progit2/blame/master/book/03-git-branching/sections/basic-branching-and-merging.asc#L75)

> This is an important point to remember: when you switch branches, Git resets your working directory to look like it did the last time you committed on that branch. It adds, removes, and modifies files automatically to make sure your working copy is what the branch looked like on your last commit to it.

This seems quite misleading (wrong) to me.  In particular, my understanding is that checking out a branch will carry-over your unstaged working directory changes (outside of merge conflicts.)  Am I just misunderstanding the claim being made here?

**Comment by ben** [comment]
You're absolutely correct. Remember, though, that this is pretty early in the book, and we're just introducing the concept of branching and checkouts to a reader who may never have heard those words before. We're trying to strike a fine balance by simplifying the explanation without being _too_ wrong.

Keeping all those requirements in mind, do you know of a better way of wording it? I'd love for this section to be better.

**Comment by edenhochbaum** [comment]
Thanks for the quick response, Ben.  (And of course, thanks for the project.)

Just for pragmatic reasons, with technical docs, I think it’s misguided to knowingly present false statements as fact.  Maybe I’d make some narrow exceptions (but not for this case.)

In the framework you provide, _simplifying the explanation without being too wrong_, I don’t have any improvements to offer.

I was just calling attention to what I thought was an oversight.  If this is already something that’s been considered, then I vote to close.

**Comment by lazarljubenovic** [comment]
> with technical docs

That's the thing, this is a book, not a technical documentation. It's always very difficult to be 100% concise and clear on your statements when teaching, so in the first few chapters of a book (or classes), the general tone of "this is not quite true but we'll get into details later" is assumed.
