### ISSUE TITLE
Adjusting the documentation - 1.5 installing git - `getopt` package

### ISSUE THREAD

**Issue by 4wk-** [progit/progit2#1053]
Small suggestion about compiling git documentation.
URL: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

**"Installing from Source" part:**

> In order to be able to add the documentation in various formats (doc, html, info), these additional dependencies are required (Note: users of RHEL and RHEL-derivatives like CentOS and Scientific Linux will have to enable the EPEL repository to download the docbook2X package):
> 
> $ sudo dnf install asciidoc xmlto docbook2X getopt
> $ sudo apt-get install asciidoc xmlto docbook2x getopt

-----

On a Debian Stretch 9.4 fresh install:
```
# apt-get install getopt
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package getopt
```

I was stucked a bit.
Why? Because package `getopt `is already installed:

```
# getopt --version
getopt from util-linux 2.29.2
```

- In order to avoid users to panic / loose time finding why we got this error, it might be usefull to add a sentence about this package? 

Thanks for your awesome work anyway, great doc.

**Comment by jnavila** [comment]
I guess https://github.com/progit/progit2/commit/d35b434f6c687bf14a16c141d5c05a2082919d42 was a bit too generic but only applied to rpm based distros. Dare to submit a PR for this? :+1:

**Comment by 4wk-** [comment]
@jnavila sure.

However even if I'm "fluent" with git, I am not with Github. I cloned the repo, create a branch, edit a file, and commit, but I'm not able to push (getting the 403 error through https). I tried with the remote url to `https://4wk-@github.com/progit/progit2.git/info/refs` and `https://git@github.com/progit/progit2.git/info/refs` 

What did I miss? -_-' I need to push before asking a PR, right?

**Comment by ben** [comment]
Yes, but you don't use a username with the HTTPS protocol. Try clicking the "Fork" button at the top right of this repo's screen, then setting your remote to `https://github.com/4wk-/progit2.git`. After you push to your fork, follow the directions [here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

**Comment by 4wk-** [comment]
Thank you @ben for the step I missed ;)
