### ISSUE TITLE
Incorrect naming in caption of Figure 32

### ISSUE THREAD

**Issue by grgbnc** [progit/progit2#1058]
In file `book/03-git-branching/sections/remote-branches.asc`, line 42 should read:

```
.`git fetch` updates your remote-tracking branches
```
Rationale (from [git-fetch(1)](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-fetch.html), 2nd sentence of 1st paragraph below **DESCRIPTION**): `Remote-tracking branches are updated`

**Comment by ben** [comment]
Hey, you're right! We're using the correct term everywhere else in that chapter, just not here.

Want to submit a PR? I'd love for you to have `git blame` credit for fixing this, and you'll show up in the contributors list.
