### ISSUE TITLE
Miss coloured console example in chapter 10.2

### ISSUE THREAD

**Issue by PhilipOakley** [progit/progit2#1061]
In the Chapter 10.2 there are at least two places (I believe) where the console display is miss-coloured because of the use of a line continuation "\".

The two I notied were for `git update-index` examples. I'm guessing that the colouring script either misses the continuation, or just colours lines starting with the `$` prompt.

```
$ git update-index --add --cacheinfo 100644 \
  1f7a7a472abf3dd9643fd615f6da379c4acb3e3a test.txt
```

**Comment by ben** [comment]
This must be a limitation in how Asciidoctor handles this then, that feature isn't specifically configured here.

**Comment by KZiemian** [comment]
Can we close this issue?
