### ISSUE TITLE
Macedonian(mk) Translation

### ISSUE THREAD

**Issue by krisfremen** [progit/progit2#1062]
Hello,

I'm starting to translate the Pro Git 2 book into Macedonian.

I translated the first chapter and the README.asc so far.

https://github.com/progit2-mk/progit2

Please let me know if there's something I need to do regarding automatic ebook generation as I set up the project in Travis as well.

Thanks!

**Comment by jnavila** [comment]
Hello, 

Good news that a new translation is started!

I haven't tried to compile your book, but I set up the compilation for most of the books by including the `.travis.yml` from https://github.com/progit/progit2-pub , which in turn pulls everything that is needed to compile the books and publish them.

To get more visibility, we usually:

* add a reference to the repo to https://github.com/progit/progit2/blob/master/TRANSLATING.md
* add the book to https:///git-scm.com , such as https://github.com/git/git-scm.com/pull/1132

**Comment by krisfremen** [comment]
Hello @jnavila,

I created the pull requests.

Thanks

**Comment by krisfremen** [comment]
@jnavila hmm, the link in the localisation that points to /book/mk doesn't seem to point to the v2 of the book, instead it points to v1.

Did I miss something?

**Comment by jnavila** [comment]
The static website is updated live and the cache is available around 4 hours after, but the books are compiled once a day, so this should be ok by tomorrow.

**Comment by krisfremen** [comment]
Ah, I see.

Perfect, thanks!
