### ISSUE TITLE
P2P transport chapter

### ISSUE THREAD

**Issue by renne** [progit/progit2#1071]
The acquisition of Github by Microsoft has shown that centralized public development approaches are not sustainable.

I suggest to implement a de-centralized P2P transport like [Gittorrent](https://github.com/cjb/GitTorrent) in Git. The Github web-interface can be imitated with a local web-server storing the content in a P2P Git repository.

**Comment by ben** [comment]
Sorry, this isn’t the right place to make feature requests for Git itself, this repo is just for the book about Git. You might want to try suggesting this on [the mailing list](https://git.wiki.kernel.org/index.php/GitCommunity).
