### ISSUE TITLE
P2P transport chapter

### ISSUE THREAD

**Issue by renne** [progit/progit2#1074]
The [acquisition of Github by Microsoft](https://blog.github.com/2018-06-04-github-microsoft/) has shown that centralized public development approaches are not sustainable.

I suggest to add a chapter/section about P2P transports like [Gittorrent](https://github.com/cjb/GitTorrent) as a replacement for Git SAAS.

**Comment by HonkingGoose** [comment]
@ben @jnavila Is this something we want to do?

I'm missing the use-case for this to be honest. A user/organization can put a git repository on any server they like, and let people push/pull/fetch from that. This is explained on: https://git-scm.com/book/en/v2/Git-on-the-Server-Getting-Git-on-a-Server

Also git is not equal to GitHub, GitHub itself still uses git as a protocol, it only adds a interface around some common things, and adds things like reviews. So people are free to move their git repository to another provider like Gitlab, Bitbucket, etc. Or roll their own server.

I'm also not sure of what collaboration model would not need a central repository, if 2/3 people each push/pull from each others repository that could work for them, but at any kind of scale you would need a central source of truth in a central repository.

**Comment by ben** [comment]
I've got to agree with @HonkingGoose on this one. Our goal is to be useful to the average Git user, both newbies and experienced users, and the need for a decentralized protocol just isn't that widespread. Going to close this for now.
