### ISSUE TITLE
hash-object is different from ruby's implemention

### ISSUE THREAD

**Issue by jingsam** [progit/progit2#1080]
In https://github.com/progit/progit2/blob/master/book/10-git-internals/sections/objects.asc#object-storage, we use ruby to hash `what is up, doc?` and we get:
```
bd9dbf5aae1a3862dd1526723246b20206e5fc37
```

However, I hash this string with `hash-object`, from which I got a different hash:

```
$ echo "what is up, doc?" | git hash-object --stdin -w
7108f7ecb345ee9d0084193f147cdad4d2998293
$ git cat-file -p 7108f7ecb345ee9d0084193f147cdad4d2998293
what is up, doc?
```

Test on:
macOS 10.13.5
git version 2.15.1 (Apple Git-101)
config: 
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
```

**Comment by krisfremen** [comment]
echo always appends a newline to its output.

use the -n flag to get the output without the trailing newline.

```
$ echo -n "what is up, doc?" | git hash-object --stdin -w
bd9dbf5aae1a3862dd1526723246b20206e5fc37
```

**Comment by jingsam** [comment]
Thanks a lot. I think it would be better to add a paragraph to state this issue. As in this chapter 0f `Git object`, I see:
```
$ echo "version 1" |  git hash-object --stdin -w
$ echo "version 2" |  git hash-object --stdin -w
```

**Comment by krisfremen** [comment]
Pull requests are welcome. :)
