### ISSUE TITLE
How git hash tree object?

### ISSUE THREAD

**Issue by jingsam** [progit/progit2#1086]
I am trying to reproduce how git hash tree object as fellows:

```
$ git cat-file -p d8329fc1cc938780ffdd9f94e0d364e0ea74f579
100644 blob 83baae61804e65cc73a7201a7252750c76066a30  test.txt
$ echo "tree 62\0100644 blob 83baae61804e65cc73a7201a7252750c76066a30  test.txt" | openssl sha1
651711153beb76de6acd1df74d5f28932667030c
```

It shows that the result of `openssl sha1` is not correct. So could you tell me how git hash tree objects or commit objects?

**Comment by jnavila** [comment]
The internal format of objects is not human readable like the output of git cat-file. Please refer to https://stackoverflow.com/questions/14790681/what-is-the-internal-format-of-a-git-tree-object

for more information.

**Comment by KZiemian** [comment]
Can we close this issue?
