### ISSUE TITLE
git rev-list --count HEAD --since yyyy-MM-dd

### ISSUE THREAD

**Issue by JustasSasnauskas** [progit/progit2#1087]
If at particular day for example 2018.06.01 is more that one commit, 
then command  `git rev-list --count HEAD --since 2018.06.01` will return different  number at different time of the day.  
I suppose that `--since` is using current time just replacing years, month and day leaving time current for the system. 
That was very frustrating, as you expect that git suppose to return same number for the same commit no mater what.

$ git --version
git version 2.17.1.windows.2

**Comment by ben** [comment]
Wow. That seems like a Git bug to me. Want to report it to the mailing list? If they decide not to fix it, we might need to make a note of it.

**Comment by Jsasnauskas** [comment]
Thank you, 
reported to mailing list too.

**Comment by KZiemian** [comment]
@JustasSasnauskas Can you write what you remember about further story of your finding? Maybe after that we can close this issue?
