### ISSUE TITLE
Half in italian and half in english

### ISSUE THREAD

**Issue by raffam** [progit/progit2#1095]
Hi,
I have connected to the website, but the PDF i have downloaded (as well asthe HTML file) is sometimes in italian (the first chapter) and sometimes in english (all the following chapters).
I think it should use one language only.
Anyway I would like to download the eglish version. Is there a switch to do so or something?

**Comment by ben** [comment]
It looks like you ended up at https://git-scm.com/book/it/v2, which is the Italian translation of the book, and the PDF link is to the `progit2-it` version. If you visit https://git-scm.com/book/en/v2, you'll end up with the English version, and your PDF download will be in English.
