### ISSUE TITLE
Please make sure that what I am trying to do is not against this repo's license.

### ISSUE THREAD

**Issue by Juneyoung-Kang** [progit/progit2#1103]
I want to use ProGit to create an online class on [goorm edu](http://edu.goorm.io/), an online lecture website in S.Korea. It will be provided for free, and the lecturer will not earn any profit. The license will also be created with the same license as the CC BY-NC-SA 3.0 license that ProGit pursues.

The purpose of the lecture will be to explain to developers the deep technical skills of Git and to make it easy for the beginner to understand.

I'm still worried that it's okay to make lectures this way.
Please let me know if there is any violation of the license or other policy.

**Comment by ben** [comment]
As far as I can tell, the CC BY-NC-SA license allows you to "remix, transform, or build upon" the content, so long as it's not a commercial purpose, you release the course under the same license, and you link back to this repo. So it sounds like you're in the clear (although I'm not a lawyer, so take that statement with a grain of salt).

Entirely apart from the legal considerations, this sounds like a fun project, and I wish you well!
