### ISSUE TITLE
Mention tig in Appendix A

### ISSUE THREAD

**Issue by ffes** [progit/progit2#1105]
As far as I can see there is no mentioning of the curses based "gui" [tig](https://github.com/jonas/tig/). 

I find that a very useful tool and use it every day. I think it should be mentioned in Appendix A, especially since it is [included in Git for Windows](https://github.com/git-for-windows/build-extra/commit/04c667662e3177d2681b403a3d47025b9cbb3c4e) and available as a package on every major Linux distribution.

**Comment by ben** [comment]
Want to write up a blurb to include in the [graphical interfaces](https://git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Graphical-Interfaces) section? It's either that or create a new section for more command-line tools, which seems like overkill for just `tig`.

**Comment by ffes** [comment]
I will give it a try.

Another possibility is to join the bash and zsh sections into that command line section as well.

Know that English is not my first language, so somebody proofreading it is important.

**Comment by katrinleinweber** [comment]
[There is already a mention](https://github.com/progit/progit2/blame/6956b0cca09f11932a67cc4782015b33efa7f3ae/book/A-git-in-other-environments/sections/guis.asc#L152) of the probably most exhaustive list of GUIs (which also lists tig).

**Comment by KZiemian** [comment]
Can this issue be close now?
