### ISSUE TITLE
Option to select VS Code as a default Git editor is grayed out

### ISSUE THREAD

**Issue by illusive-man** [progit/progit2#1106]
Git 2.19.0 for Windows x64 (I can select Vim or Nano, but not VS code)
Windows 10 Pro x64
VS code: 1.27.2 (installed to default dir)

Pretty much what topic says.

I think the problem is that couple months back Microsoft has switched to new type of installation distributive which doesn't require admin access in order to install/update VS Code. I believe Git installer is looking for VS Code installed "old way" and obviously just can't find it.

**Comment by ben** [comment]
Unfortunately you're in the wrong place. This is the repo for the Pro Git book, not for the Git for Windows distribution. You probably want to be over at https://github.com/git-for-windows/git.
