### ISSUE TITLE
Add how to delete tags in section 2.6 of the book

### ISSUE THREAD

**Issue by alex-koziell** [progit/progit2#1111]
When reading through section 2.6-Tagging of the book I accidentally made an unwanted tag in my test repository. I had to use the method here: https://gist.github.com/mobilemind/7883996.

That seemed fairly straightforward. If this is generally considered the best way to delete tags locally and/or remotely, perhaps it should be added to this section?

**Comment by ben** [comment]
I agree, we could use a section on how to remove unwanted tags, both local and remote. Would you like to write something up and submit a PR so we can hash it out?

And yeah, the gist you found shows two good ways to solve this.

**Comment by alex-koziell** [comment]
Done! I've made it brief to avoid adding unnecessary clutter to the section.
