### ISSUE TITLE
in Figure 69. John is Josie and vice versa.

### ISSUE THREAD

**Issue by vuGitH** [progit/progit2#1113]
The labels of John and Josie in " Figure 69. Basic sequence of this managed-team workflow. "  are misnamed and should be changed one another. Otherwise there is no consistency between the text content and the figure.
(This errata takes place on site page https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project as well as in pdf version of book ProGit on page 127)

**Comment by YueLinHo** [comment]
Duplicate #694

**Comment by YueLinHo** [comment]
Should be closed for duplicate #357.

**Comment by YueLinHo** [comment]
Should be closed for duplicate issue #950 and it was fixed by PR #955 (at least the pdf file)
