### ISSUE TITLE
Backward Example?

### ISSUE THREAD

**Issue by nobozo** [progit/progit2#1125]
In https://github.com/progit/progit2/blob/master/book/08-customizing-git/sections/policy.asc there's a section that shows how the get_acl_access_data() call has to be modified because it's being called "from your working directory, not from your .git directory". However, the example code below it shows the modification as if it's being called from the .git directory, and not the working directory. In other words, shouldn't the two example lines be swapped?

**Comment by ben** [comment]
I assume you're talking about [this section](https://github.com/progit/progit2/blob/master/book/08-customizing-git/sections/policy.asc#client-side-hooks). The answer to your question is no. 

```shell
$ cd repo/.git
$ ls acl
acl

$ cd ..
$ ls .git/acl
.git/acl
```

That snippet is saying "before, when the script was being run from the `.git` directory, we could just call the file `acl`. But now that we're running from the repo's working directory root, we have to call it `.git/acl`. Does that make sense?

**Comment by nobozo** [comment]
You're absolutely right. Sorry for the noise.
