### ISSUE TITLE
TortoiseGit bugtraq

### ISSUE THREAD

**Issue by aollier** [progit/progit2#1126]
Related to #541:

The current configuration of TortoiseGit (.tgitconfig) does not create links when the commit message contains something like `closes #XXX` or `fixes #XXX` where XXX is a bug ID.
[Closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/) is the way users should mention issues so we should use a pattern that recognizes bugs in this format.

Examples are:
`closes #541`, `fixes: #541`, `resolved #783`.

I know the pattern to use so if you agree with that I may open a Pull Request that fixes this.

**Comment by aollier** [comment]
Here is the result after my change:
![image](https://user-images.githubusercontent.com/13087713/48586320-e3d63080-e92f-11e8-981f-510ae3d0d3e0.png)

As you can see, the bug ID 1080 has become a link and 1080 appears in the column Bug-ID of TortoiseGit.

**Comment by aollier** [comment]
Here is another example:
![image](https://user-images.githubusercontent.com/13087713/48586522-7bd41a00-e930-11e8-9adb-8bcef86d7082.png)

We can't see the cursor but it pointed to 1057 and you can see that the link is correct.

**Comment by ben** [comment]
Absolutely, go right ahead!
