### ISSUE TITLE
In "Initializing a Repository in an Existing Directory" is the wrong directory mentioned for Windows?

### ISSUE THREAD

**Issue by jsilverm** [progit/progit2#1128]
There are so many ways to install / use git, and even more on Windows, but I think this applies to all of them.

In the section:
Initializing a Repository in an Existing Directory

The instructions for Windows specify that:
$ cd /c/user/my_project

But on my Windows 10 1803 build with git bash 2.19 it is found under:
 /c/users
specifically:
/c/Users/username/my_project
i.e. ~ is = to /c/Users/username
when viewed under git bash.

I think this is standard on Windows 10, no?
i.e.
HOME=/c/Users//username
HOMEPATH='\Users\jusername

**Comment by ben** [comment]
We should definitely fix this if the behavior has changed. Does anyone have a Windows environment they can test on?

**Comment by limdor** [comment]
Not sure when the behavior changed but definetly would be more accurate:
cd /c/Users/user/my_project/
Usually the user folder is under Users in windows

**Comment by ben** [comment]
OK, if that's confirmed, do either of you want to submit a PR to fix this? I'd love for you to get the credit.

**Comment by Morganov** [comment]
> sually the user folder is under Users in window

Both variants are possible in Windows 10:
`cd c:/Users/user/my_project`
and
`cd /c/Users/user/my_project`

Anyway, it's already fixed in #1370
