### ISSUE TITLE
Is "smart HTTP" strictly a Git enhancement, nothing to do with HTTP protocol?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#1135]
Just want to confirm that smart HTTP, as it is covered in Progit book, is strictly a Git enhancement in how it uses HTTP, and does not involve any enhancements in the basic HTTP/HTTPS protocol. I ask since, as that section is worded, a reader might come away with the impression that it was an improvement in HTTP itself that is being described as "smart HTTP" and which Git is taking advantage of.

rday

**Comment by ben** [comment]
Correct. HTTP is just HTTP, but Git used to do it stupidly, then got smart. Feel free to spruce up the prose so it doesn't seem that way.
