### ISSUE TITLE
Is it worth introducing a TODO file to keep track of potential improvements?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#1137]
I've asked an equivalent question a time or two, but is there any value to starting a top-level TODO file to simply keep track of improvements that could be made to the book, just so one does not forget them?

For example, in Chapter 4, I think it's worth mentioning that, in Fedora, there are independent packages "git-daemon" and "git-instaweb" that add support for, respectively, systemd and the "git instaweb" command. At some point, I can come back and fix that but, until then, it would be nice to have a place to track this.

Another TODO would be to add an entire section on "git subtree" -- I can do that at some point but not right this instant so, again, it would be nice to be able to remind myself what I thought about doing.

Finally, such a file would at least remind readers that there are some things that are currently not covered in the book, and that they're invited to go off and research them for themselves.

Thoughts?

rday

**Comment by lazarljubenovic** [comment]
Opening an issue and using the label [Enhancement](https://github.com/progit/progit2/labels/enhancement) should be enough.
