### ISSUE TITLE
Does "git describe" simply "favor" annotated tags?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#1140]
"Generating a Build Number" (PDF, p. 161), we read:

"The git describe command favors annotated tags (tags created with the -a or -s flag), so release tags should be created this way if you’re using git describe, to ensure the commit is named properly when described."

But if you try this on the ProGit book Git repo itself, you get:

$ git describe
fatal: No annotated tags can describe '73a294fbbece9d6dc0167a9bbecb3d474eca19ac'.
However, there were unannotated tags: try --tags.
$

It seems that generic "git describe" *requires* (not just "favors") annotated tags unless (as the message states) you use "--tags". Is that a fair statement, such that that section should be reworded?

**Comment by ben** [comment]
Looks like that behavior has changed, and I'd agree with you.

**Comment by rpjday** [comment]
OK, I'll get around to fixing that.
