### ISSUE TITLE
irc.freenode.net mentioned in `1.7 - getting help` a C&C server?

### ISSUE THREAD

**Issue by inwenis** [progit/progit2#1154]
hi,

I have accessed the http://irc.freenode.net mentioned in 1.7 and it was blocked by my compny's antivirus.
Supposedly it's a C&C server.
https://tmcm6-threatconnect.trendmicro.com/portal/cnc_report?q=rq7GK-usEJIkJ3Mg9A9lt0namQBEZcOIZGpMSgDwFkhtpo4HU-woGfpGxtw_S9hgMhqDw-QS7Ced_Ov-WpyWYWeAweFaAw0JQL2EuUTRlOLb2J-bFreNVEa9wohpaYodL2d9jlJrQ28NF-bGTYyPeWF6_BsKyS2vTFirskiHT1wi6IYkqXdYAz0ZESOZCY5L

Maybe the url should point to https://webchat.freenode.net/ insted?

**Comment by ben** [comment]
I'd _love_ to review a PR that fixes this, but I'm not up-to-date on the latest best practices for IRC. Is that a popular server that'll be consistently accessible to readers?

**Comment by inwenis** [comment]
thanks for the response :)
I'm not sure how the IRC infrastructure works.
If one of the servers from the freenode servers is a C&C server, I'm guessing I might be unlucky and get load-balanced to the same server via https://webchat.freenode.net/.
Still I never got blockat at https://webchat.freenode.net/.
Anyway I have created a PR https://github.com/progit/progit2/pull/1171.
It replaces the url irc.freenode.net with https://freenode.net/ which might be more helpful to people not familiar with IRC.
