### ISSUE TITLE
Missing --status-name in description

### ISSUE THREAD

**Issue by kolya182** [progit/progit2#1166]
I have installed git version 2.20.1 for mac and missing `--status-name` https://git-scm.com/docs/git-log#git-log---name-status param in the description
Here is the video:
https://www.dropbox.com/s/o67gucutsi93yaw/Screen%20Recording%202019-01-22%20at%203.42.44%20PM.mov?dl=0

**Comment by jnavila** [comment]
This issue tracker is dedicated to the Progit book.

The issue you have raised is related to the macOSX port of the git program. Please see https://github.com/timcharper/git_osx_installer for reporting bugs.

Thanks.
