### ISSUE TITLE
Typo on https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks.

### ISSUE THREAD

**Issue by Zapados** [progit/progit2#1169]
Typo on this page: https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

"In the last section of this chapter, **We’ll** demonstrate using this hook to check that your commit message is conformant to a required pattern."

**Comment by ben** [comment]
Hey, nice catch! Want to submit a small PR to fix it? I'd love for you to get `git blame` credit for this.

**Comment by Zapados** [comment]
@ben yes!  Give me that sweet, sweet blame.  :)
