### ISSUE TITLE
The book conflict with the git-remote man .

### ISSUE THREAD

**Issue by Splarv** [progit/progit2#1173]
Cite from the book

«If the QA team wants to push their master branch to qa/master on the remote server, they can run
```bash
$ git push origin master:refs/heads/qa/master
```
If they want Git to do that automatically each time they run git push origin, they can add a push value to their config file:
```
[remote "origin"]
	url = https://github.com/schacon/simplegit-progit
	fetch = +refs/heads/*:refs/remotes/origin/*
	push = refs/heads/master:refs/heads/qa/master
```
Again, this will cause a git push origin to push the local master branch to the remote qa/master branch by default.»

Отрывок из книги: Scott Chacon. «Pro Git». Apple Books. 

But here is cite from man git-remote:
           Note that the push URL and the fetch URL, even though they can
           set differently, must still refer to the same place. What you
           pushed to the push URL should be what you would see if you
           immediately fetched from the fetch URL. If you are trying to fe
           from one place (e.g. your upstream) and push to another (e.g. y
           publishing repository), use two separate remotes.

Obviously, that in the book case commit will be pushed to qa/master and not will be fetched by fetch = `+refs/heads/*:refs/remotes/origin/*`

**Comment by ben** [comment]
This particular section is in the Git Internals chapter (the last one in the book), and it's about learning what a push spec is, rather than actual practical advice on how to use one. There might be a case where you want to push to a place where fetch won't fetch from, that's why the `push` and `fetch` parts of the config are separate.

It doesn't look like there's anything to fix here. Was there a specific change you wanted to propose?

**Comment by Splarv** [comment]
Heh, I want an explanation, in the book, of cause. I like your idea to use git in such way. For instance I want to set git to pull from the GitHub official repository and to push to the GitHub my fork in such way. But this is forbidden by the official man. And it worth to explain why this is forbidden and what will be consequences if I violate this forbiddance and do in the same way as in your book.

**Comment by aollier** [comment]
@Splarv there are 2 questions:

1. The given configuration in the book is the following:
[remote "origin"]
&nbsp;&nbsp;&nbsp;&nbsp;url = https://github.com/schacon/simplegit-progit
&nbsp;&nbsp;&nbsp;&nbsp;fetch = +refs/heads/&ast;:refs/remotes/origin/&ast;
&nbsp;&nbsp;&nbsp;&nbsp;push = refs/heads/master:refs/heads/qa/master
With this configuration, a fetch will get all commits from every branch, so I am pretty sure that the commits pushed in branch qa/master will be fetched with the git-fetch command, but they will appear in the `qa` namespace.
2. It is possible to pull from one repository and push in another one. To achieve that, you need a few configuration.
    1. You need to name your two repositories. You already have a first repository, named `origin`. Add the other one. For example, I named the source repository `progit`:
    ```bash
    $ git remote add progit https://github.com/progit/progit2.git
    ```
    2. Set you master branch follow `progit`:
        ```bash
        $ git branch --set-upstream-to=progit/master master
        ```
        Then your future fetches will fetch from `progit`.
    3. Define the default push repository to `origin`:
        ```bash
        $ git config --local remote.pushDefault origin
        ```
        Now you can fetch from `progit` and push to `origin` when you are on master branch as simply as:
        ```bash
        $ git pull # will fetch changes from progit
        $ git push # will push to origin
       ```

@ben Do you want me to add such a section that gives this explanation?

**Comment by ben** [comment]
Sure, that sounds like it would be a great addition to this section. Thanks, @aollier!

**Comment by Splarv** [comment]
Yep, remote.pushDefault is what I need. But I prefer to mark origin github repository (https://github.com/progit/progit2.git for instance) as origin and fetch from it by default (not by --set-upstream for only one branch) and push all changed to my own fork (I name it as fork) to create pull requests. Now this is very simple indeed, I just need to create clone from origin and add fork to remote.pushDefault. This is a common use case for every newbie github user who don't have a write access to an origin repository.

What is not obvious is why the man page strictly forbid the use case that used in the book.
