### ISSUE TITLE
Korean translation (ko)

### ISSUE THREAD

**Issue by pismute** [progit/progit2#118]
We've started to translate:
- Repository: https://github.com/progit-ko/progit2-ko
- Guidelines: https://github.com/progit-ko/progit2-ko/wiki

**Comment by pismute** [comment]
Hi. We have done almost half of KO.

How it could be included in https://progit.org/translations?

**Comment by schacon** [comment]
Awesome. I got it all set up for you and builds are starting https://progit.org/translations/lang/ko

Builds will be triggered by pushing to the progit/progit2-ko repository master branch, which you should now have write access to.

**Comment by pismute** [comment]
Thank you a lot.

**Comment by pismute** [comment]
@schacon, Could I have write access and permissions managing issues of progit/progit2-ko?

**Comment by schacon** [comment]
I sent you an invitation to the team. If you accept that, you'll get write access.
