### ISSUE TITLE
Newer(?) way to delete remote tags

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#1180]
Currently, book explains how to delete remote tags with "git push remote :refs/tags/tagname", but there is the more intuitive way, "git push --delete remote tagname". Is that latter form a newer form? I can add a note about the second form, but it would be useful to explain when it came into existence.

**Comment by ben** [comment]
Looks like Git learned this syntax in [1.7.0](https://github.com/git/git/blob/53f9a3e157dbbc901a02ac2c73346d375e24978c/Documentation/RelNotes/1.7.0.txt#L154) way back in 2010, so it should be safe to recommend it.

**Comment by rpjday** [comment]
Roger that.

**Comment by rpjday** [comment]
Whoops, one more question ... just want to confirm that, WRT tags, there is no *simple* way to distinguish between pushing lightweight tags versus pushing annotated tags, is that correct? I know there are solutions involving first listing the type of tag, then driving that through "git push", but there is no simple option to "git push" that lets you select one tag type or the other, correct?

**Comment by ben** [comment]
Nope, as far as `push` is concerned they're just refs. Whether they're annotated or not is up to project-local conventions.

**Comment by rpjday** [comment]
Right, that's what I thought. I ask only because asking how to selectively push only one type of tag is a fairly common question everywhere, so I just want to clarify that in the tagging section as well.

**Comment by rpjday** [comment]
Sorry to keep re-opening, I'm just in an editing mood these days. I am *assuming* that, when tags are pushed, they end up at the remote as the same type they started with -- light tags stay light, annotated tags stay annotated, yes? It would make little sense for that not to be true, but I just want to make sure there are no subtleties here I'm missing.

**Comment by ben** [comment]
Correct. Tags can't change type, the annotated and ref-only tag are pretty different beasts.
