### ISSUE TITLE
There is a small inconsistency in deprecation message with "git reset --mixed"

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#1187]
Currently working my way through "Reset Demystified", and I would like to draw the Court's attention to an exchange I had a couple months back on the Git ML:
[https://marc.info/?l=git&m=154428515423409&w=2](https://marc.info/?l=git&m=154428515423409&w=2)
where, even though "--mixed" is the default mode for reset, specifying that mode versus not specifying it generates different behaviour, even if the end result is equivalent.
Not sure what to do about this, is it worth explaining?

**Comment by ben** [comment]
I don't think so. The only discernible difference in the behavior is the deprecation warning, which few users should run into.

The distinction Junio is drawing there is purely an implementation one, and in my view, if the end behavior is the same, the user shouldn't have to care.
