### ISSUE TITLE
Is "git alias" not a part of Git core?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#1189]
Was just going over Git aliases and, long story short, on my Fedora 29 system, it is not a part of Git core. Turns out it is supported by the Fedora "git-extras" package and, once I removed that package as a test, I no longer have Git aliases. I was completely unaware that Git aliases are (apparently) not a fundamental part of Git. Thoughts?

To be clear, this is what is provided by that git-extras package on Fedora:

Description  : git-extras adds the following extra-commands to git:
             : 
             : alias, archive-file, bug, changelog, commits-since, contrib, count,
             : create-branch, delete-branch, delete-submodule, delete-tag, effort,
             : extras, feature, fresh-branch, gh-pages, graft, ignore, info,
             : local-commits, obliterate, promote, refactor, release, repl, setup,
             : squash, summary, touch, undo

I'm just baffled that "git alias" has, all this time, been provided by a supplemental package.

Never mind, I should never have been using that Git command in the first place.

**Comment by ben** [comment]
Looks like the in-the-box and Homebrew versions of Git don't come with this either. However, it doesn't look like we mention it in the book anywhere, so I'm going to go ahead and close this.
