### ISSUE TITLE
A few questions about hooks

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#1190]
Planning on adding/clarifying a few things in the hooks section, so I just want to make sure I understand *exactly* how things work.

First observation I'll add is that not all of the hook scripts supported by Git come as sample scripts with Git core -- I did not realize that until now. Examples include post-commit and post-receive, which were removed as samples way back in 2011 (even though they are clearly still supported if they exist):

```
commit 8d714b11df2b65e5f4272c1616e561930010be90
Author: Gerrit Pape <pape@smarden.org>
Date:   Tue Sep 27 11:56:53 2011 +0000

    templates/hooks--*: remove sample hooks without any functionality
```
Next thing I want to clarify; regarding "git init", the _only_ ways to override the installation of default "template" info in a newly-initialized Git repo is via one of:

1. --template=
2. init.templateDir=

correct? What the above does is copy (with the exception of hidden content) all of the identified directory into the .git directory, "hooks" subdirectory and all, overriding entirely the default content in /usr/share/git-core/templates/. And, as I read it, there's no (easy) way to select partial contents to be overridden, it's all or nothing, yes? And the behaviour is entirely independent of any setting of core.hooksPath, correct?

Next clarification: "git clone" also supports specifying a non-default templates directory when cloning, but this _must_ be done on the command line via the "--template" option, correct? That is, cloning does not respect the config setting init.templateDir value, and there is no corresponding clone.templateDir config setting AFAICT. So far, so good?

Finally, to override the default hooks _during normal operation_ is what core.hooksPath is for, yes? As in, that setting has no effect on the preceding operations, init and clone?

I think that's all I wanted to confirm.

**Comment by rpjday** [comment]
Whoops, forgot about env var GIT_TEMPLATE_DIR for setting template directory for "git init".

**Comment by ben** [comment]
Ha, I'm actually learning some things reading through this; I think Scott handled this part of the 2e rewrite.

> not all of the hook scripts supported by Git come as sample scripts with Git core

This appears to be sadly true. You have to look at the `githooks` manpage to get a full list of all the hooks you can use.

> the _only_ ways to override the installation of default "template" info in a newly-initialized Git repo is via one of

Looks like you've got the list correct, with your second comment.

> there's no (easy) way to select partial contents to be overridden, it's all or nothing

Yup, looks like Git stops after it copies just one of the templates in its fallback order; there's no "the default but with this one thing different" option.

> And the behaviour is entirely independent of any setting of core.hooksPath, correct?

Correct, see below.

> "git clone" also supports specifying a non-default templates directory when cloning, but this _must_ be done on the command line via the "--template" option, correct? That is, cloning does not respect the config setting init.templateDir value, and there is no corresponding clone.templateDir config setting AFAICT. So far, so good?

Looks that way, yes.

> Finally, to override the default hooks _during normal operation_ is what core.hooksPath is for, yes? As in, that setting has no effect on the preceding operations, init and clone?

Correct, `core.hooksPath` overrides where Git will look for hooks when it comes time to execute them.
