### ISSUE TITLE
A few questions about github.

### ISSUE THREAD

**Issue by ju-hyun-park** [progit/progit2#1191]
Let's assume the following scenario.

There is a common(organization) remote repository. For convenience of explanation, its address(url) is `org/project-archive`. It currently contains three directories `projectA, projectB` and `projectC`.

I know that if I fork this repo(`org/project-archive`), then forked repo has username/project-archive url like `user1/project-archive`. I can easily push PR(pull request) from `user1/project-archive` to `org/project-archive`.

-----

There is an another remote repository. It is my project repository. So it has the following url(`user1/projectD`).  
### I want to connect `user1/projectD` with `org/project-archive`.

so that I can easily push PR to `org/project-archive`.

----

To sum it all, I want to do the following two things.

1. want to make directory named **_projectD_** in `org/project-archive` repository.  
2. want to connect `user1/projectD` repo with `org/project-archive` repo.

I would appreciate your kind help.

**Comment by ben** [comment]
Wait, are you looking to connect the `projectD` subdirectory in `org`'s repo with a separate repo that belongs to `user1`? The only manageable way of doing that is using a submodule. You would create `org/projectD`, connect `org/project-archive` to it using a submodule, then fork `projectD` into `user1`'s ownership. 

The downside of submodules is that there is a manual step to make sure `project-archive` gets updated when `org/projectD` changes. That extra step needs a human to remember it, or code to be written to automate it (which can break and needs maintenance).

Does that help? Or am I misunderstanding the question?

**Comment by ju-hyun-park** [comment]
Thanks @ben , your comment is great. I have a one more question. When I read your comment, I think that "In general, when using git submodule, org/projectD rarely changes..."

Is it correct?

**Comment by ben** [comment]
You can track a fast-moving project using a submodule, but it takes more manual work to keep up-to-date with it. Submodules are at their best if they never or rarely update to new versions of the other repo.

**Comment by ju-hyun-park** [comment]
Thank you for your answer. I learned a lot.
