### ISSUE TITLE
What about .git/logs/ directory in "Git Internals"?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#1195]
I'm currently working my way through "Git Internals" and, near the beginning, there's a short discussion about Git repo layout, talking about the "refs/" directory: "the refs directory stores pointers into commit objects in that data (branches, tags, remotes and more)."

Playing with the actual Pro Git repo and testing, and I created two local branches, "3rd" and "4th", but when I examine refs/, all I see is:

```
$ tree .git/refs
.git/refs
├── heads
│   ├── master
│   └── t
├── remotes
│   ├── origin
│   ├── progit
│   │   └── master
│   └── rpjday
│       └── HEAD
└── tags
    └── 2.1.117
```
However, when I examine logs/, I see:

```
$ tree .git/logs
.git/logs
├── HEAD
└── refs
    ├── heads
    │   ├── 3rd
    │   ├── 4th
    │   ├── master
    │   └── t
    ├── remotes
    │   ├── progit
    │   │   └── master
    │   └── rpjday
    │       ├── HEAD
    │       └── master
    └── stash
```

It's unclear from the internals chapter the difference between .,git/refs and .git/logs. I'm reading "man gitrepository-layout", but that also seems unclear.

Thoughts?

**Comment by ben** [comment]
The `refs` directory contains the actual references:

```
» cat .git/refs/heads/3rd
040233f5a593560db8501404bbc6aceb3f139cb5
```

And the `logs` directory contains the [reflogs](https://git-scm.com/docs/git-reflog):

```
» cat .git/logs/refs/heads/3rd
0000000000000000000000000000000000000000 040233f5a593560db8501404bbc6aceb3f139cb5 Ben Straub <ben@straub.cc> 1551801935 -0800	branch: Created from master
```

Which is why `logs` will sometimes contain files related to branches that don't exist any longer – Git keeps a history of where those refs have pointed, and deleting a ref doesn't delete its reflog.

**Comment by rpjday** [comment]
Except in my situation, there *is* no .git/refs/heads/3rd file, even though I still have a branch by that name. But in my case, my log for that branch shows a commit:
$ cat .git/logs/refs/heads/3rd 
0000000000000000000000000000000000000000 5df317d020a4fa97d42321fd8a8b6cdd8b19ced7 Robert P. J. Day <rpjday@crashcourse.ca> 1551444884 -0500	branch: Created from master^
5df317d020a4fa97d42321fd8a8b6cdd8b19ced7 7b5949a7833b17be9398d51c4ba73939a2a19ba3 Robert P. J. Day <rpjday@crashcourse.ca> 1551444917 -0500	commit: branch third edition

Is that a reason that that branch would be dropped from refs/heads? I will investigate further.

**Comment by ben** [comment]
Ha, looks like your refs got [packed](https://git-scm.com/docs/git-pack-refs). That's a thing I don't think we spend much time on in the book, but it is mentioned in the [maintenance](https://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery) chapter.

**Comment by rpjday** [comment]
Ah, got it, should have thought of that, thanks. I was unaware that refs themselves could be packed.
