### ISSUE TITLE
Pedantry regarding tags in "Git References"

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#1196]
Couple possibilities for improving clarity. In "Git References", subsection "Tags", one reads that one can create a lightweight tag with:

`git update-ref refs/tags/v1.0 cac0cab538b970a37ea1e769cbbde608743bc96d`

Is there some reason to not just use:

`git tag v1.0 cac0cab538b970a37ea1e769cbbde608743bc96d`

Or is this example specifically using `git update-ref` to demonstrate something?

Also, same section further down, 

"You can see this by creating an annotated tag (using the -a option):

`$ git tag -a v1.1 1a410efbd13591db07496601ebc7a059dd55cfe9 -m 'test tag'`

Sure, that will work, but using `-m` automatically makes it an annotated tag, regardless of the `-a`. Worth clarifying?

rday

**Comment by ben** [comment]
> Is there some reason to not just use:
> 
> `git tag`

Well, this _is_ part of the "Git Internals" chapter, and the rest of that section is dealing with using `update-ref` to create and manage refs, so it seems appropriate to demonstrate that it works with lightweight tags as well.

> using `-m` automatically makes it an annotated tag, regardless of the `-a`. Worth clarifying?

We do cover this in the [section on tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging#_lightweight_tags) earlier in the book. This is an advanced chapter, and the reader is expected to know quite a bit about the porcelain commands at this point, so it's not worth getting into here.
