### ISSUE TITLE
There are some problem with an affirmation at 03-git-branching/sections/basic-branching-and-merging... 

### ISSUE THREAD

**Issue by Calkines** [progit/progit2#1199]
In this section (title), more specifically on line 63:

> However, before you do that, note that if your working directory or staging area has uncommitted changes that conflict with the branch you're checking out, Git won't let you switch branches.

Someone tried to do it ?
Git does not block me to change between branches on it happens, but it brings the modification into changed branch.

Could you help me to confirm my suspect?

Want to reproduce?

1. Create a new directory
2. Initiate the Git over it
3. Create 3 files: 'f1.txt; f2.txt; f3.txt'
4. Create a new branch (testing)
5. Change the HEAD to testing
6. Change the content of f3.txt
7. Add f3.txt to staged area
8. Try checkout to master branch

The file was modified over testing branch (f3.txt) is passed to master.

Is that affirmation in quotation above wrong?

**Comment by aollier** [comment]
In your test you did not create a conflict. To get a conflict, do the following:

steps 1 to 3: as you did
step 4: create a commit on master branch
step 5: create a branch 'testing'
step 6: modify line 1 of file1.txt
step 7: create a commit (still on master branch)
step 8: checkout testing branch
step 9: modify line 1 of file1.txt but differently from step 6
step 10: try to checkout master → the conflict should appear and you shouldn't be able to switch on master

Right ?

**Comment by Calkines** [comment]
error: Your local changes to the following files would be overwritten by checkout:
        f1.txt
Please commit your changes or stash them before you switch branches.
Aborting
