### ISSUE TITLE
Change http links to https.

### ISSUE THREAD

**Issue by HonkingGoose** [progit/progit2#1210]
I searched for all matches of the string **http://** in the progit2/master source. The result was 529 matches across 74 files.

Shouldn't we use the more secure https links instead? Is there a reason that there are still http links? Is this something that you want fixed?

**Comment by ben** [comment]
This sounds like it would be a great change. We should be using SSL links wherever possible.

**Comment by HonkingGoose** [comment]
@ben Would you like me to go through the lot and change them?

**Comment by ben** [comment]
I don't want you to feel like you have to do this all at once. If you want to, maybe take it a chapter at a time? Or do a search/replace for a single hostname all at once? But if you've got time and want to, I'd love to review a PR that does it in one big patch.

**Comment by HonkingGoose** [comment]
Let's suppose I want to change the lot. What would be the logical way to make that change?

Which one of these would be preferred:

---

### Commit often:
1. Make new branch.
1. Make a lot of commits for each change.
1. Run Travis CI.
1. Merge into master.

---

### Commit often, but squash at the end:
1. Make new branch.
1. Make a lot of commits for each change.
1. Squash all commits into one large commit. (This would need to be done by you, I don't yet know how to use git to rebase anything without getting my ``head`` detached :smile: .
1. Run Travis CI.
1. Merge into master.

---

### Commit once for all changes:
1. Make new branch.
1. Make one big commit for all changes.
1. Run Travis CI.
1. Merge into master.

---

### Commit once per chapter:
1. Make new branch per chapter.
1. Make one big commit for all changes in chapter.
1. Run Travis CI.
1. Merge into master.

---

For reference, this is my current level of git understanding:
I just use ``git add -p``, ``git commit -v``, and ``git push``, and ``git fetch`` and ``git merge`` in my current usage of git. So interactively rebasing things is a bridge too far, for now.

---

So if you can tell me which workflow (or your own better workflow) I should use, I can decide if I want to get this underway. :+1:

**Comment by ben** [comment]
My personal style for this repo is "lots of commits, not necessarily focused." In short I just take an action that I might want to undo, then make a commit. Sometimes that means I just finished an hour of work and have to go do something else, sometimes that means I just ran `sed` and made a hundred automated fixes.

In short, we're not super pedantic here. Go ahead and open a PR, and start pushing commits however feels best to you, and ping me when you'd like feedback.

Regarding the choice of "one PR per chapter" or "one PR to rule them all", I'll leave that up to you. But when taking on a biggish project it always helps to get to know the system involved. Maybe start with just one chapter, get familiar with the tools, then take bigger bites as you get more experienced.

As a meta note, it's fun to see someone learning Git by contributing to the book they're reading to learn Git. 😃

**Comment by HonkingGoose** [comment]
I've done a new search for ```http://``` in all .asc files on ```master```, there are now 19 hits remaining. 

Most of the hits remaining are for user entered commands to domains that the user (presumably) owns. Some of those hits are legitimate ```http://``` sites for projects that don't yet use a ```https://``` site (bazaar, zsh),

The main issue is now chapter 9. There are three hits for the  ```client-p4.asc``` file. Like I said in my comment regarding my pull request for chapter 9, I don't know anything about perforce, so somebody else should get the correct ```https://``` links in there.

**Comment by ben** [comment]
Yeah it looks like they've renamed some things and moved some other things around. Git Fusion is now called Helix4Git?

I also am not a Perforce user, so I'll leave this to someone who knows more about what they're doing.

**Comment by HonkingGoose** [comment]
Hi @ben,

Yeah they renamed/moved things around on the Perforce website. So we'll leave that for somebody else. :smiley: 

The 529 hits of ``http://`` uncluded all the .pdf files, they have a lot of http:// links, but I guess that's not harmful?

**Comment by HonkingGoose** [comment]
Closing this issue in favor of #1349 
I'm also making a new issue for a rewrite for the Perforce sections of the book.

That way this issue can be closed, and the work remaining to do is visible for anybody wanting to help on the Perforce sections.
