### ISSUE TITLE
Tim Pope's blog is not quoted properly.

### ISSUE THREAD

**Issue by HonkingGoose** [progit/progit2#1217]
I saw that there is a difference between the book and the blog here. I've pasted the source from both progit2/master and Tim Pope's blog, so you can see the difference.

The biggest change is this one:

### The blog says:
Typically a hyphen or asterisk is used for the bullet, **followed** by a
  single space, with blank lines in between, but conventions vary here

### Book says:
Typically a hyphen or asterisk is used for the bullet,
    **preceded** by a single space, with blank lines in
    between, but conventions vary here

---

### Book says:
Short (50 chars or less) summary of changes

More detailed explanatory text, if necessary.  Wrap it to
about 72 characters or so.  In some contexts, the first
line is treated as the subject of an email and the rest of
the text as the body.  The blank line separating the
summary from the body is critical (unless you omit the body
entirely); tools like rebase can get confused if you run
the two together.

Further paragraphs come after blank lines.

  - Bullet points are okay, too

  - Typically a hyphen or asterisk is used for the bullet,
    preceded by a single space, with blank lines in
    between, but conventions vary here

---

### Tim Pope's blog says:

Capitalized, short (50 chars or less) summary

More detailed explanatory text, if necessary.  Wrap it to about 72
characters or so.  In some contexts, the first line is treated as the
subject of an email and the rest of the text as the body.  The blank
line separating the summary from the body is critical (unless you omit
the body entirely); tools like rebase can get confused if you run the
two together.

Write your commit message in the imperative: "Fix bug" and not "Fixed bug"
or "Fixes bug."  This convention matches up with commit messages generated
by commands like git merge and git revert.

Further paragraphs come after blank lines.

- Bullet points are okay, too

- Typically a hyphen or asterisk is used for the bullet, followed by a
  single space, with blank lines in between, but conventions vary here

- Use a hanging indent

---
Source: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by ben** [comment]
Hmm, could have sworn I copy-pasted this at the time. It's possible Tim updated it since this was done.

Want to submit a PR that updates the quote?

**Comment by HonkingGoose** [comment]
Do you want the full quotes from his website? I noticed the blog-part:
>Write your commit message in the imperative: "Fix bug" and not "Fixed bug"
or "Fixes bug." This convention matches up with commit messages generated
by commands like git merge and git revert.

is already re-written in the progit/master source:
>It's also a good idea to use the imperative present tense in these messages.
In other words, use commands.
Instead of ``I added tests for'' or ``Adding tests for,'' use ``Add tests for.''

**Comment by ben** [comment]
We should probably be using direct quotes instead of doing a poor rephrasing.

**Comment by HonkingGoose** [comment]
Hello @tpope, 

As I understand it, you're the author of: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

A (nearly) full quote of your blog-post has been included in this book for some time now see https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project (search for "Tim Pope" on the page)

I saw the quote was not up to date and want to update it to the current text on your blog. However, I would like to have your blessing/permission first. (For more on this, see the top post of this issue.)

The Pro Git book v2 is licensed as: https://creativecommons.org/licenses/by-nc-sa/3.0/
Do you give permission for the Pro Git book v2 project to keep using your quote, and for us/me to update the quote to the current version? We'll of course mention you as the author of the quote, as we're doing already.

Greetings,

HonkingGoose

**Comment by tpope** [comment]
Sure!

**Comment by HonkingGoose** [comment]
@tpope Thank you! :+1: I'll go fix the quote.
