### ISSUE TITLE
Chapter 10 http links.

### ISSUE THREAD

**Issue by HonkingGoose** [progit/progit2#1221]
From my search for ``http://``, there are still hits here, but I think it's supposed to be http for the "dumb protocol". I'm not sure what the "smart protocol" would use.

I know exactly nothing about http/https handshakes, so I'll leave this to you @ben.

**progit2/book/10-git-internals/sections/transfer-protocols.asc:**

```
   20  [source,console]
   21  ----
   22: $ git clone http://server/simplegit-progit.git
   23  ----
   24  
   ..
  191  [source]
  192  ----
  193: => GET http://server/simplegit-progit.git/info/refs?service=git-receive-pack
  194  001f# service=git-receive-pack
  195  00ab6c5f0e45abd7832bf23074a333f739977c9e8188 refs/heads/master□report-status \
  ...
  204  [source]
  205  ----
  206: => POST http://server/simplegit-progit.git/git-receive-pack
  207  ----
  208  
```

**Comment by ben** [comment]
Let's leave it as plain HTTP for now. Adding SSL to intranet server names is getting easier, but it's still not what I'd call easy, so an unencrypted connection is probably as far as we should take this.

The Smart Protocol can work over HTTPS as well, but the same caveats apply.
