### ISSUE TITLE
introduction.asc file, Appendix A related text is outdated.

### ISSUE THREAD

**Issue by HonkingGoose** [progit/progit2#1225]
The current text from /progit2/book/**introduction.asc** is:
>In *Appendix A*, we look at a number of examples of using Git in various specific environments. We cover a number of different GUIs and IDE programming environments that you may want to use Git in and what is available for you. If you're interested in an overview of using Git in your shell, in Visual Studio or **Eclipse**, take a look here.

I've since added a section on Sublime Text and Visual Studio Code, also #1205 mentions that the sections on Eclipse IDE will be retired. Those changes are not yet reflected in the introduction.

Also listing every editor/IDE will get tiresome, and get in the way of actually providing a overview. So maybe we should list the two/three new "killer apps" that we will have added at the end of #1205, and leave it there. Or we could not mention any editor/IDE, and just refer to the list, that will make future updates easier, because you don't have to update the introductory blurb every time a editor/IDE is removed/added.

So this is just a heads up that this section will need a rewrite. :smile:

**Comment by ben** [comment]
Noted. Something like this would do:

> If you're interested in an overview of using Git in your shell, your IDE, or your text editor, take a look here.

**Comment by HonkingGoose** [comment]
I'll go fix it then. :+1:
