### ISSUE TITLE
fatal: Out of memory, malloc failed (tried to allocate 18446744072362497024 bytes)

### ISSUE THREAD

**Issue by ouyangxx10** [progit/progit2#1250]
when I use the git to download remote repository, it always appear:

> git clone https://github.com/openbmc/qemu.git build

> Cloning into 'build'...

> fatal: Out of memory, malloc failed (tried to allocate 18446744072362497024 bytes)

how can I resolve it?

`gitconfig

> [http]

>       postBuffer = 7242880000

> [core]

>         packedGitLimit = 128m

 

>        packedGitWindowSize = 128m

> [pack]

 

>        deltaCacheSize = 128m

>         packSizeLimit = 128m

>         windowMemory = 128m

`
`free  -h`

>              total       used       free     shared    buffers     cached

> Mem:           62G       1.7G        60G        31M       162M       869M

> -/+ buffers/cache:       711M        61G

> Swap:          63G         0B        63G

**Comment by ben** [comment]
That sounds serious! Unfortunately you're not in the right place – this repo is the Pro Git book, not the Git software itself. If you'd like to report a bug, you'll want to start at https://git-scm.com/community.
