### ISSUE TITLE
English grammar online checker?

### ISSUE THREAD

**Issue by udyzr** [progit/progit2#1257]
1. Which grammar online checker for English is recommended when working on this book's text?
2. Output of what English grammar online checkers is honoured in this Github project as discussion argumentation in issues and pull requests?

**Comment by ben** [comment]
We don't have one set up just now, but it'd be pretty rad to get spelling and grammar checking as a commit check.

**Comment by udyzr** [comment]
So are contributors free in choice of which grammar checker to use? No English grammar checker recommendations exist in this project?

**Comment by ben** [comment]
You're free to use whatever tools you like. As the author, I'm the keeper of the tone of the book, so I make the final decisions on grammar questions.

**Comment by KZiemian** [comment]
Can this issue be close?
