### ISSUE TITLE
Why the same command execute in cmd.exe and a bat file gets different result?

### ISSUE THREAD

**Issue by laball** [progit/progit2#1262]
I got some problem with the git cli.
First command is : git log -1 --pretty=format:"%H" > 222.txt
This command works fine in cmd, but I only got an 'H' if it execute in a bat file.
Another command is :git config --list > 333.txt
I got same result both in  cmd and bat file.
These two command have same pattern,but why got different result,I got confused.

I find one way to fix it by add '%',but it dose not work for all command,why?
How dose the git design?

- Operating system: Windows 10
- Software version: git version 2.21.0.windows.1

**Comment by andtit2001** [comment]
If you want to use the first command in a `.bat` or `.cmd` file, you need to write two `%`'s:  
`git log -1 --pretty=format:"%%H" > 222.txt`

This problem is related to `cmd.exe` only, not Git.

**Comment by ben** [comment]
Thanks, @andtit2001! Going to close this for now.
