### ISSUE TITLE
I want to contribute to the PT-BR translation, but the repository seems inactive

### ISSUE THREAD

**Issue by carlosschults** [progit/progit2#1266]
Years ago I contributed to the first edition of the progit book, helping with the Brazilian Portuguese translation. So, I'd like to contribute to the second edition as well, but I am currently unable to do so.

The [repository for the translation](https://github.com/progit2-pt-br/progit2) seems to be inactive. The [last commit](https://github.com/progit2-pt-br/progit2/commit/91515c4717d380c5f8547b7689dfdc9405723b43) is about one year and a half old. It's currently not possible to open issues on that repository.

I emailed the owner of the repository asking whether they're still accepting pull requests, but it's been almost 2 weeks and I haven't received any replies. 

What is the recommended approach here? I'd really like to help but am currently unable to do so. The progit book is a very valuable resource for learning Git,  but many developers in Brazil and other Portuguese speaking countries still can't read English, specially beginners.

**Comment by jnavila** [comment]
Unfortunately, I cannot fork into progit org a project which is already of fork of a project of progit (hard to read hey?). So, I'll create a progit-pt-BR under progit and push the content of the repo. Then, you'll be given the right to push. Is it ok?

**Comment by carlosschults** [comment]
Sounds good to me. Thanks!

**Comment by jnavila** [comment]
Done.

**Comment by carlosschults** [comment]
Awesome. I'm closing this issue then. Thanks!

**Comment by jnavila** [comment]
I'm migrating the structure of the book to an architecture compatible with a publication on git-scm.com

**Comment by jnavila** [comment]
Well, I was waiting for the repo to be revived but nothing happened in the end.

**Comment by carlosschults** [comment]
@jnavila Hi! Unfortunately, I wasn't able to start working on the translation, due to some personal commitments. I intend to start actively working on it before the end of the year, though.
