### ISSUE TITLE
Why can the status of files be both staged and unstaged?

### ISSUE THREAD

**Issue by bmxbmx3** [progit/progit2#1276]
I'm a newbie learning git from your books,and I have a question about why the status of files can be both staged and unstaged?When I read something said "If you commit now, the version of CONTRIBUTING.md as it was when you last ran the git add command is how it will go
 into the commit, not the version of the file as it looks in your working directory when you run git commit." from the title "Staging Modified Files" in Chapter 2,which explains when you add files and make some changes before commiting them then the status of files can be both staged and unstaged,I couldn't get it.Could you please give a more clearly explanation about it?Thank you.

**Comment by ben** [comment]
Yeah, in Chapter 2 we're trying to keep things simple, but they're not actually simple.

Here's the order of events from that section:

1. Modify `CONTRIBUTING.md`
1. `git add`
1. Modify `CONTRIBUTING.md` again

When you run `git add` in step 2, it copies the file _as it exists right then_ into the index, so the changes performed in step 1 are "staged". The changes introduced in step 3 are only in the working directory, not in the index.

Another way to read the `git status` "modified" flag is _this file has changes that are staged_ and _this file has changes that are not staged_. The flag isn't about the whole file, it's about the changes in it. Does that help?

**Comment by ben** [comment]
Closing this for now, since there's nothing really actionable right now. Let me know if you're still confused.
