### ISSUE TITLE
Pro Git Two (Spanish version)

### ISSUE THREAD

**Issue by DiegoFRamirez** [progit/progit2#1280]
Hi there!
I'm Git user, and speak native Spanish language. But, sorry. My English is not very good.
I'm read the last edition book Pro Git (in Spanish), and I see errors traduction. Not very important, but errors finally. I would like to contribute with corrections (if this is possible). I do not want to be disrespectful. Mostly I have seen small typographical and syntax errors.
I'm wait for your response for start this task. And last time send the result for compare and aprove (or not) the changes and corrections.
Thanks for read!!
Sincerily,
Diego Ramírez.

PD: The e-mail address "git@vger.kernel.org" is rejected for some email servers.

**Comment by jnavila** [comment]
Hi Diego,

The translation of the Progit book in Spanish is made [here](https://github.com/progit/progit2-es).

To submit your corrections, you will need to use git. But first, open an issue in this repository, present yourself (you can write in Spanish), your corrections and the maintainers will surely help you.

**Comment by DiegoFRamirez** [comment]
Thank you so much for your response. 
Ok, I will follow your instructions.
