### ISSUE TITLE
The current font-family not good for Vietnamese language

### ISSUE THREAD

**Issue by henryonsoftware** [progit/progit2#1282]
**Which version of the book is affected?**
v2

**Describe the bug:**
The font-family isn't good with Vietnamese. Some character was broken.

**Steps to reproduce:**
1. Go to https://git-scm.com/book/vi/v1/Ph%C3%A2n-Nh%C3%A1nh-Trong-Git-Rebasing
2. We can see some character broken like "Nếu bạn xem lại ví dụ trước trong phần"

**Expected behavior:**
Can we change to another font? My suggestion is the font github is using know, it can display well with many language.
`font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol`

**Comment by ben** [comment]
I believe this is set over in the [website repo](https://github.com/git/git-scm.com). We only store the content, not the display CSS.
