### ISSUE TITLE
Diagram links incorrect for display at Github website

### ISSUE THREAD

**Issue by max123kl** [progit/progit2#1286]
If the raw file says, e.g.:
`image::images/lifecycle.png[The lifecycle of the status of your files.]`
the link leads to a 404 error page.

If I insert a slash at the beginning (like here):
`image::/images/lifecycle.png[The lifecycle of the status of your files.]`
the image is displayed correctly on the page.

**Comment by jnavila** [comment]
The links are designed for working when the document is compiled to ebook, pdf or website. The fact that they do not point to the corresponding URL on Github is something we do not care about, because it's source file, not supposed to be viewed as a compiled document.

**Comment by max123kl** [comment]
Is it possible to customize the HTML, PDF and ePUP script so that everything works?
It's just a link address.

BTW
When I look at the caption texts, the distance to the following paragraph is too small in the HTML view, but OK in the PDF view.
