### ISSUE TITLE
German Translation (file and directory updated)

### ISSUE THREAD

**Issue by max123kl** [progit/progit2#1290]
As jnavila already noticed in this [post](https://github.com/progit-de/progit2/pull/8#issuecomment-519889362rl), the structure of the German repo is broken. 
I cloned the progit/progit2/master branch as a template to my fork and transferred this structure into my ["de"](https://github.com/max123kl/progit2-de/tree/de) branch. Then I inserted the content of ["progit-de/progit2/master"](https://github.com/progit-de/progit2), as far as it was still up to date, into this branch.
Is it possible, before I start a PR, to check if any preliminary work needs to be done?
The present status is:
files in the root translated + 2 additional files
files in /book (not the directories) translated
chapter01 translated
chapter02 partially translated
chapter03 there is an open PR from "Sternenstauner"

**Comment by jnavila** [comment]
What I can do, if the maintainers of the repo grant me the rights to manage, is to set up automatic compilation, the same as the one used by all published books on git-scm.com. There are two positive outcome:

* every PR is compiled when opened, prior to merging, so breaking stuff does not end up in `master`.
* the pdfs and ebooks can be available for download, as soon as the changes are merged into `master` (this can be disabled)

*Note*: usually, I don't set up this compilation process until the translation has reached a certain level (trade-off my time vs. translators will to work) but it's really a pity that Progit version 2 is still not available in German, knowing that it was one of the first translations available for the first edition.

**Comment by max123kl** [comment]
I think that the current status of the translation is not yet sufficient to be integrated into the automatic process.
Actually, it is too premature to start a PR. But as there are bigger differences to the current progit-de/progit2 repo, I think it's better to check now, if my work is headed into the right direction.

On the other hand, a somewhat more current state of the German repository could attract further contributors, who want to collaborate.
Once the finished translations have reached, let's say, 50%+, the automatic process could be started.

In the meantime it might be possible to somehow publish a notice on the website referring to the repo and saying that work on the German translation will be resumed.

**Comment by jnavila** [comment]
The first point is still relevant: merging translation works while still having a backstop may help attract translators.

**Comment by max123kl** [comment]
What's your advice now?
Should I start a PR now, or should I wait until I reach the next point?

**Comment by jnavila** [comment]
Try first and see if the maintainers are still active. If there's no hope there, we'll start a new repo under the progit organization and we'll be able to push and merge our own changes.

**Comment by pastatopf** [comment]
I would like to help translating the book into german. Is there a new status on this?

**Comment by max123kl** [comment]
22 days ago I opened a [PullRequest](https://github.com/progit-de/progit2/pull/10) at the [German Repo](https://github.com/progit-de/progit2).
So far a maintainer only labeled the PR with "help wanted" and showed no further reaction to my later question. It is, like an older PR from March 13th, still left untouched.
I am in doubt whether the maintainers of the German repo are still sufficiently active to move the German translation forward and finish it.

@jnavila: As suggested, I ask you to start a new German repo in order to finally finish the German translation as well.

@pastatopf: Help is always welcome. If you like, you can inform yourself about the current status in the meantime in [my repo ("de" branch)](https://github.com/max123kl/progit2-de/tree/de). Currently, I'm working on chapter 4. The above mentioned PR of "Sternenstauner" obviously contains chapter 3. If you want to start helping now, I suggest that you start with one of the next chapters.

**Comment by pastatopf** [comment]
@max123kl : Perfect, I will start with chapter 5 then

**Comment by jnavila** [comment]
@max123kl That's an aggressive fork, it seems that the maintainer replied. Do you still want to fork?

**Comment by max123kl** [comment]
@jnavila That's right, the maintainer's been in touch.
Let's wait a bit more, maybe we can get on there.
As I am just at the beginning of my work with Git, I would prefer an experienced maintainer to control the work.
I also have contact with "pastatopf". He has already translated a file.
I hope we can finally move on now.

**Comment by pastatopf** [comment]
If it is ok for everyone I would like to take the role of the maintainer of the project, if a new one is needed.

**Comment by max123kl** [comment]
My patience is now slowly running out.
Again 2 days have passed without reaction from mynetx.

@jnavila I suggest that you create a repo for German (called progit2-de) at progit, as you did for French and Spanish. Then the link in the TRANSLATION.md file should be modified.
If you agree, you will grant write permission there for me and pastatopf, who offered himself as a maintainer.
I hope we will get technical support if we run into any problems.
Then the German translation could finally progress.

In the (present) German repo there is a second open PR (#8 by Sternenstauner). I copied the German content from his repo and will edit the texts according to the current source.
Unfortunately Sternenstauner didn't publish an e-mail in his GitHub profile, so I can't inform him about my activities. Maybe it is possible to send him a message via GitHub.
I don't want to adorn myself with borrowed plumes.

If other contributors then want to join, this would of course be helpful.

**Comment by jnavila** [comment]
OK. Let's move on.

**Comment by pastatopf** [comment]
@jnavila We have now a first german version which can be published to the public. Of course it is still not ready, but especially @max123kl is pushing it forward with a lot of power. :-)

I generated the docs manually with the bundle commands and eliminated all errors.
Additionally I run a travis build on my copy of the project (Is it correct that I'm not allowed to run the Travis build on our [german main repo](https://github.com/progit/progit2-de)?

If you think everything is fine you can change the link to the german translation [here](https://github.com/progit/progit2/blob/master/TRANSLATING.md).

Thanks

**Comment by jnavila** [comment]
@pastatopf You don't have admin rights on this repo. My TODO list has the task of adding automatic compilation for the german repo. Good to read that it already compiles fine (usually, I have to fix things). Will do shortly.

**Comment by mynetx** [comment]
@max123kl @jnavila I had granted the two of you respective rights to access the existing repo?
