### ISSUE TITLE
GitHub’s paid plans no longer required for private projects

### ISSUE THREAD

**Issue by andres-mancera** [progit/progit2#1293]
One of the translators working on the Spanish project has brought to my attention ([#141](https://github.com/progit/progit2-es/issues/141)) the fact that [Section 6.1](https://github.com/progit/progit2/blob/master/book/06-github/sections/1-setting-up-account.asc) (GitHub - Account Setup and Configuration) has a note about private repositories that is no longer true:

"_GitHub provides all of its functionality with free accounts, with the limitation that all of your projects are fully public (everyone has read access). GitHub’s paid plans also include the option of creating private projects, but we won’t be covering those in this book._"

As per GitHub's latest pricing [info](https://github.com/pricing), they are offering unlimited private repositories with a limit of 3 collaborators now.  @ben , should I go ahead and create a PR for this?

**Comment by ben** [comment]
Hey, nice catch! Want to submit a PR that fixes it? I'd :heart: for you to get `blame` credit for the correction.

**Comment by tabathap** [comment]
👌

**Comment by Morganov** [comment]
There is still no any updates about GitHub's free private repositories. Therefore, I've created the #1346

**Comment by HonkingGoose** [comment]
Hi @ben, 

The merging of pull-request #1346 fixes this issue. Therefore this issue can probably be closed.

Greetings,

HonkinGoose

**Comment by ben** [comment]
😁
