### ISSUE TITLE
Simplified Chinese Translation (zh_CN)

### ISSUE THREAD

**Issue by devbean** [progit/progit2#130]
I'm working on the Simplified Chinese translation of ProGit 2 at https://github.com/devbean/progit2

**Comment by networm** [comment]
hi @schacon I have translated about 18 sections to Chinese. You could look it at [Commits · networm/progit2-zh](https://github.com/networm/progit2-zh/commits/first-translation)
But I also want to help others involving translating these, and manage the assigned tasks. So could you give me the write access to the progit/progit-zh?
