### ISSUE TITLE
Authors mapping list creation command does not redirect result to a file anymore

### ISSUE THREAD

**Issue by CodingSpiderFox** [progit/progit2#1311]
**Which version of the book is affected?**
v2: https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git

**Describe the bug:**
There is this command suggested for creating an authors mapping file `svn log --xml --quiet | grep author | sort -u | \
  perl -pe 's/.*>(.*?)<.*/$1 = /'` 
The previous version (v1 of the documentation) redirected the output to a file. Now, it seems like it would be printed to STDOUT (did not test it though because I don't have access to a Linux box at the moment). The subsequent descriptive text also still suggests writing the result to a file (while it doesn't claim that the suggested command would do that).

**Expected behavior:**
I'd suggest to use the `tee` command for the Linux command line string. To both show the output and print it to a file.

**Additional context:**
Somehow related to #1310 

**Desktop:**
Windows 10

**Comment by ben** [comment]
I have mixed feelings about this. On one hand, this content is in chapter 9, where presumably the reader has some experience working with Git and the command line, and will know how to pipe to a file. On the other hand, a google search might lead readers directly here with no other context.

In the end, I think keeping the content focused is more important than providing a complete solution. We're in the business of providing readable advice, and going off in the weeds with a `tee` and then mentioning `cat` or pagers doesn't seem to fit that goal.
