### ISSUE TITLE
Mention abbreviating long options

### ISSUE THREAD

**Issue by phil-blain** [progit/progit2#1315]
I just learned that any long options (`--option`) in Git can be abbreviated (ex. `--opt`, `--o`) as long as it's resolvable (see https://git-scm.com/docs/gitcli#_abbreviating_long_options). I did a search and I don't think this is mentionned in the book. I think it would be valuable to mention that (some options are quite long!), though I'm not sure where best it would fit (maybe at the beggining of Appendix C ?)

**Comment by ben** [comment]
Yeah, that seems like the right place.
