### ISSUE TITLE
Git-tfs no longer actively maintained

### ISSUE THREAD

**Issue by HonkingGoose** [progit/progit2#1323]
**Which version of the book is affected?**

Bug is present on `master`.

**Describe the bug:**

I noticed that [git-tfs](https://github.com/git-tfs/git-tfs), is on "life-support":
> This project is no more actively maintained because we are no more users of TFS.

There is still a section on git-tfs in the book, though.

**Steps to reproduce:**

1. Open `book/09-git-and-other-scms/sections/client-tfs.asc`.
2. There are still sections about git-tfs.

From @aollier:
> ⚠️ If we remove it, we must also remove the section in https://github.com/git-tfs/git-tfs#more-advanced-use-cases that links to this section.

**Expected behavior:**

I would expect this section to either have a warning about the maintenance status, or be removed entirely.

**Screenshots:**

**Additional context:**

The [git-tfs readme.md](https://github.com/git-tfs/git-tfs#more-advanced-use-cases) still links to our book for instructions.

The progit2 team will have to decide what to do with this.

**Comment by ben** [comment]
Related: #1326. We may want to retire all TFS-related content altogether.
