### ISSUE TITLE
Retire git-tf content

### ISSUE THREAD

**Issue by ben** [progit/progit2#1326]
In #1322 @HonkingGoose recommended removing the git-tf content, because git-tf is now EOL. Is anyone interested in keeping it?

**Comment by aollier** [comment]
codeplex.com itself is EOL, it was closed in 2017. Microsoft switched to github.com the same year I think.
So I totally agree with @HonkingGoose, I also recommend to remove this part.

**Comment by aollier** [comment]
:warning: If we remove it, we must also remove the section in https://github.com/git-tfs/git-tfs#more-advanced-use-cases that links to this section.
