### ISSUE TITLE
Please add the book to openlibrary.org?

### ISSUE THREAD

**Issue by KamarajuKusumanchi** [progit/progit2#1334]
I am wondering if you can add the "Pro Git" book to https://openlibrary.org ? Currently, I do not see anything that is representative of the latest version (say 2.1.176). The closest I see are 
* https://openlibrary.org/books/OL26372169M/Pro_Git which says that there is no ebook available
* https://openlibrary.org/books/OL26422503M/Pro_Git which says that the latest version is from 2015

If you are interested, the following FAQs might be relevant:
* https://openlibrary.org/help/faq/about#upload
* https://openlibrary.org/help/faq/about#mybook

Thanks in advance
raju

**Comment by ben** [comment]
I've created a "November 2019" edition of the book, and I'm working on the steps needed to contribute ebook editions.

**Comment by ben** [comment]
It's up! https://openlibrary.org/books/OL27737331M/Pro_Git

**Comment by KamarajuKusumanchi** [comment]
Thank you so much!
