### ISSUE TITLE
Migrate from Dependabot preview to Dependabot

### ISSUE THREAD

**Issue by HonkingGoose** [progit/progit2#1356]
EDIT: This post is now outdated due to Dependabot being integrated into GitHub. Please check the linked pull-request to migrate to the new version of Dependabot.

---

I'm noticing that Dependabot does not seem to take the configuration file and apply it properly:

- Dependabot is not applying the default label correctly, the config file says the label should be: `dependabot`. Instead it only applies the `dependencies` label.
- Dependabot also didn't create the reviewer `ben` correctly.

I've validated the current config file at https://dependabot.com/docs/config-file/validator/ and that says that everything is fine.

I think you should check the Dependabot dashboard, to see what that says:
https://app.dependabot.com
![dependabot_dashboard_overview](https://user-images.githubusercontent.com/34918129/71579208-ccd6ab80-2afb-11ea-84dc-fea7e20484e3.png)

----

I would expect you to see something similar to the dependabot configuration screenshot (on the dashboard click on the gear/cog next to the repository name):

![dependabot_config](https://user-images.githubusercontent.com/34918129/71579201-c811f780-2afb-11ea-8ae6-4652d93d119c.png)

---

See #1355 for the Dependabot pull-request that's not working right.

**Comment by ben** [comment]
Sadly no, this is what we see:

![image](https://user-images.githubusercontent.com/39902/71593186-ebcb4280-2ae7-11ea-9a29-764f85975de1.png)

**Comment by HonkingGoose** [comment]
It seems that the Dependabot config file will only work when you have installed **Dependabot Preview** on the GitHub Marketplace.

So try this:
1. Install *Dependabot Preview* from https://github.com/marketplace/dependabot-preview
2. Configure the repository access of Dependabot Preview at https://github.com/settings/installations 
![dependabot_preview_configuration_github](https://user-images.githubusercontent.com/34918129/71622912-55774980-2bd9-11ea-9902-3c3034a27c6c.png)
3. And then click on the yellow highlighted button to select the ProGit2 repository:
![dependabot_preview_repository_access](https://user-images.githubusercontent.com/34918129/71622959-8d7e8c80-2bd9-11ea-9700-241491da9261.png)

Source for statement:
https://github.community/t5/How-to-use-Git-and-GitHub/dependabot-config-file-is-valid-but-dependabot-isn-t-creating/td-p/31145

**Comment by HonkingGoose** [comment]
Dependabot is now added to the base GitHub functionality.

You'll need to convert from the Dependabot-preview to the new built--in Dependabot. Instructions can be found here: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/#moving-forward-from-dependabot-com-and-dependabot-preview
