### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by chrillof** [progit/progit2#1357]
Good day!

I'm a Swedish software engineer and use Git both at work and for my home projects. As I've spent some time teaching Git to colleagues and friends, translating the book seemed like a reasonable thing to do.

The translation is far from done (as only the first chapter is fully translated), however it makes sense to list it among "translations in progress". It can be found at https://github.com/progit2-sv/progit2/.

Please notify me if there is anyting more I ought to do.

Cheers,
Christoffer

**Comment by jnavila** [comment]
Hi, would you like to have swedish published on git-scm.com?

**Comment by jnavila** [comment]
As for "Translation in progress" please submit a PR.

**Comment by chrillof** [comment]
I've merged your PR in the swedish repository. Do you need me to do anything else?

**Comment by jnavila** [comment]
I'm about to update git-scm.com, is your language *Svenska*?

**Comment by chrillof** [comment]
Yes, it is :)

**Comment by jnavila** [comment]
https://git-scm.com/book/sv/v2
