### ISSUE TITLE
`git checkout <branch>` with wrong casing will create new branch

### ISSUE THREAD

**Issue by hknielsen** [progit/progit2#1366]
**Which version of the book is affected?**
2.24.0.windows.2

**Describe the bug:**
If I fetched, or have a branch locally, fx something like `master`. And on another branch.
Doing `git checkout mAster` will checkout `mAster` as if you did `git checkout -b mAster`.

**Steps to reproduce:**
git branch yo
git checkout Yo
Now the branch is `Yo` and if you commit `yo` will be unchanged

**Expected behavior:**
Not being able to checkout branch, when not using `-b`, when casing do not match, as that is treated as a new branch.

**Desktop:**
Windows

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the Windows port of the git program. Please see https://git-for-windows.github.io/ for reporting bugs.
