### ISSUE TITLE
Access denied for files under Git repositories after migration to Git 2.25.0.windows.1

### ISSUE THREAD

**Issue by frederic-meyrou** [progit/progit2#1369]
Context : I use git to maintain and deploy portable tools under many windows target servers.

Under Windows server 2K8 / 2K12 / 2K16 or Windows 7/10 all my repositories get corrupted after I pull in certain conditions just after I did the migration to latest Windows git client to cover a CVE.

Files rights get a strange "**NULL SID**" and the other windows users have incorrect permissions.
This impact all staged files but also the .git folder, for example the ".git\config" file.

This leads for application using thoses files to "**Access denied**".

The only way to fix the problem is to delete everything and clone again the repository from the server.

**Comment by jnavila** [comment]
This issue tracker is dedicated to the ProGit book.

The issue you have raised is related to the Windows port of the git program. Please see https://git-for-windows.github.io/ for reporting bugs.

**Comment by frederic-meyrou** [comment]
oups! : https://github.com/git-for-windows/git/issues/2500
