### ISSUE TITLE
Git Internals - Git Objects: Missing "remove" instruction

### ISSUE THREAD

**Issue by andreybleme** [progit/progit2#1372]
The page [10.2 Git Internals - Git Objects](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects), where the text explain about the `objects` directory, it's written:

> Now, you can add content to Git and pull it back out again. You can also do this with content in files. For example, you can do some simple version control on a file. First, create a new file and save its contents in your database:
> 
> $ echo 'version 1' > test.txt
> $ git hash-object -w test.txt
> 83baae61804e65cc73a7201a7252750c76066a30
>
> Then, write some new content to the file, and save it again:
> 
> $ echo 'version 2' > test.txt
> $ git hash-object -w test.txt
> 1f7a7a472abf3dd9643fd615f6da379c4acb3e3a

But this sequence of steps shown in the code snippets does not work.
We need to remove the file `test.txt` first before running `echo 'version 2' > test.txt` for the second time, otherwise the terminal returns an error.

---

As a suggestion to fix this is to change the line between the snippets, and the second snippet to:

> Then, delete the file, write some new content to a new file with the same name, and save it again:
> 
> $ rm test.txt
> $ echo 'version 2' > test.txt
> $ git hash-object -w test.txt
> 1f7a7a472abf3dd9643fd615f6da379c4acb3e3a

If this makes any sense, I can create a PR right away.

**Comment by ben** [comment]
What OS are you running? This works just fine for me, using bash on Mac OS:

```bash
bash-3.2$ cd /tmp
bash-3.2$ git init temp
Initialized empty Git repository in /private/tmp/temp/.git/
bash-3.2$ cd temp
bash-3.2$ echo 'version 1' > test.txt
bash-3.2$ git hash-object -w test.txt
83baae61804e65cc73a7201a7252750c76066a30
bash-3.2$ echo 'version 2' > test.txt
bash-3.2$ git hash-object -w test.txt
1f7a7a472abf3dd9643fd615f6da379c4acb3e3a
```

**Comment by andreybleme** [comment]
I was in a Ubuntu using Fish. I've retested using bash and it seems to work.
Thanks anyway, I'll close the issue.
