### ISSUE TITLE
Missing .gitignore entry

### ISSUE THREAD

**Issue by fkrunic** [progit/progit2#1385]
**Which version of the book is affected?**

Online Book

**Describe the bug:**

Missing `.gitignore` entry in _2.2 Git Basics - Recording Changes to the Repository_. 

**Steps to reproduce:**

1. Go to `https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository`
2. Scroll down about half-way to the code-block underneath the line "Here's another example .gitignore file:".
3. The `# ignore doc/notes.txt, but not doc/server/arch.txt` section is missing a negation entry for `server/arch.txt`. 

**Expected behavior:**

The code `.gitignore` block should read: 

```
...

# ignore doc/notes.txt, but not doc/server/arch.txt
doc/*.txt
!doc/server/arch.txt

...
```

or something similar.

**Desktop:**

- Operating system:
MacOS Mojave
- Browser/application:
Chrome
- Browser/application version:
Version 79.0.3945.130 (Official Build) (64-bit)

(edit: removed empty sections)

**Comment by ben** [comment]
No, the code as written is correct. Here's the relevant part of that sample `.gitignore` file:

```
# ignore doc/notes.txt, but not doc/server/arch.txt
doc/*.txt

# ignore all .pdf files in the doc/ directory and any of its subdirectories
doc/**/*.pdf
```

In the first rule, the `*` matches filenames, but **_not_** directories, so it would ignore `doc/abc.txt` but not `doc/a/b/c/xyz.txt`. That's what the `**` operator is for, as in the second rule. Does that make sense?

**Comment by fkrunic** [comment]
Gotcha - Thank you for clarifying!

**Comment by moriy535** [comment]
> **أي إصدار من الكتاب يتأثر؟**
> 
> كتاب على الانترنت
> 
> **وصف الخطأ:**
> 
> `.gitignore`الإدخال المفقود في _2.2 Git Basics - تسجيل التغييرات في المستودع_ .
> 
> **خطوات إعادة الإنتاج:**
> 
> 1. اذهب إلى `https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository`
> 2. قم بالتمرير لأسفل نحو منتصف الطريق إلى كتلة التعليمات البرمجية أسفل السطر "فيما يلي مثال لملف .gitignore آخر:".
> 3. في `# ignore doc/notes.txt, but not doc/server/arch.txt`القسم مفقود إدخال نفي ل `server/arch.txt`.
> 
> **سلوك متوقع:**
> 
> `.gitignore`يجب قراءة الكود :
> 
> ```
> ...
> 
> # ignore doc/notes.txt, but not doc/server/arch.txt
> doc/*.txt
> !doc/server/arch.txt
> 
> ...
> ```
> 
> أو شيئا من هذا القبيل.
> 
> **سطح المكتب:**
> 
> * نظام التشغيل: 
>   MacOS Mojave
> * المتصفح / التطبيق: 
>   كروم
> * إصدار المتصفح / التطبيق: 
>   الإصدار 79.0.3945.130 (التصميم الرسمي) (64 بت)
> 
> (تحرير: إزالة المقاطع الفارغة)
