### ISSUE TITLE
The Refspec page says globbing in refspec is not supported, but it is since git 2.6.0

### ISSUE THREAD

**Issue by JanecekPetr** [progit/progit2#1395]
**Which version of the book is affected?**
Online book, https://git-scm.com/book/en/v2/Git-Internals-The-Refspec 

**Describe the bug:**
The https://git-scm.com/book/en/v2/Git-Internals-The-Refspec page says:

> You can’t use partial globs in the pattern, so this would be invalid:
> `fetch = +refs/heads/qa*:refs/remotes/origin/qa*`

but since [git 2.6.0](https://github.com/git/git/blob/master/Documentation/RelNotes/2.6.0.txt) this is no longer true, and simple substring (starts-with?) search is possible:

> An asterisk as a substring (as opposed to the entirety) of a path component for both side of a refspec, e.g. `"refs/heads/o*:refs/remotes/heads/i*"`, is now allowed.

**Steps to reproduce:**
Run `git fetch origin "+refs/heads/m*:refs/remotes/origin/m*"`. It works.

**Expected behavior:**
I expected the command to fail with "invalid refspec" error.

**Additional context:**
This problem is mentioned as one example in #855. This is a concrete bug, though, as opposed to a #855 being a discussion.

**Comment by ben** [comment]
Hey, nice catch! Want to submit a PR that fixes the text? I'd love for you to get `git blame` credit for this. [Here's](https://github.com/progit/progit2/blob/master/book/10-git-internals/sections/refspec.asc#L78) the place you'd need to edit.
