### ISSUE TITLE
Budaksarawakgamer

### ISSUE THREAD

**Issue by Budaksarawakgamer** [progit/progit2#1396]
**Which version of the book is affected?**

**Describe the bug:**

**Steps to reproduce:**

**Expected behavior:**

**Screenshots:**

**Additional context:**

**Desktop:**

- Operating system:
- Browser/application:
- Browser/application version:

**Smartphone:**

- Device:
- OS:
- Browser/application:
- Browser/application version:

**E-book reader:**

- Device:
- Software Update:

**Comment by Morganov** [comment]
I assume, this issue could be safely deleted.
