### ISSUE TITLE
BUG: GIT Gui .gitconfig file (GIT Portable Windows 10)

### ISSUE THREAD

**Issue by homezonebenny** [progit/progit2#1398]
### I'm using [Git Portable](https://github.com/git-for-windows/git/releases/download/v2.25.1.windows.1/PortableGit-2.25.1-64-bit.7z.exe) on Windows 10

I simply followed this [GUIDE](https://markb.uk/portable-git-windows-setting-home-environment-variable.html) to change my $HOME to Git Portable.
Since the drive letter on USB Stick could change all the time!

### **1. I changed the $HOME path to make it fully portable!**

> Open this file with editor:
`\PortableGit\etc\profile`

and then

> Add this line to it:
`HOME="/home/portable"`

**Now Git Portable takes the new path:**
`\PortableGit\home\portable`
as the new HOME directory instead of using windows home directory.

You can simply create a .ssh folder inside \portable and use SSH-Keys!

### **2. Use `git-bash.exe` to write global variable**

> Open \PortableGit\git-bash.exe and type
`git config --global user.name "Your Name"`

**This will create a `.gitconfig` file into:**
`\PortableGit\home\portable\.gitconfig`

This shows that the `$HOME` change **worked** (for **git-bash**) and we have a new (portable) HOME directory!

**If you type now:**
`git config --list`
into the `git-bash.exe` you will see "Your Name" as the new Username!

This shows that the new created `.gitconfig` file **is taken** from `git-bash.exe`!

### 3. Open `git-gui.exe` and chose a repository

> Open \PortableGit\cmd\git-gui.exe

Open an existinig repository to get the "Edit - Options..." menu see:
[Screenshot of Git-GUI](https://i.imgur.com/E8FROzB.png)

When you config your Name / E-Mail see ( 1 ) and you save it see ( 2 ) then it will not be saved into:
`\PortableGit\home\portable`
instead it will be saved into:
`C:\Users\<WinLoginName>\.gitconfig`

### **4. There are 3 `.gitconfig` files now**

**File 1** (default Git Portable - global config):
`\PortableGit\etc\gitconfig`

**File 2** (windows - global config):
`C:\Users\<WinLoginName>\.gitconfig`

**File 3 (our new custom - global config):**
`\PortableGit\home\portable.gitconfig`

> Let's check the priority of those files...

**File 1:**
If no config file exists this file is taken.
If you enter your Usernamen there this will be shown in `git-gui.exe` aswell as in `git-bash.exe`!

**File 2:**
If you edit entries with `git-gui.exe` in the options (see [Screenshot](https://i.imgur.com/E8FROzB.png)) this will create a new `.gitconfig` into windows user and this have a higher priority than our **File 1** and will be shown in `git-gui.exe` options and `git-bash.exe` aswell!

**File 3:**
This file will be shown in `git-bash.exe` as **highest priority** when you use
`git config --list`

### 5. Conclusion

There's something wrong with the `git-gui.exe` since it will not see the new created home path!

**For `git-bash.exe` the priority looks like:**
File 3 > File 1 (File 2 doesn't exit at all!)

**For git-gui.exe the priority looks like:**
File 2 > File 1 (File 3 doesn't exit at all!)

> **Question:**
> Is this a bug of git gui or do I miss something big here?!

### EDIT:
I found the solution and it seems not to be a bug at all!
I will write something and make it public here and close this issue.

**Comment by ben** [comment]
It sounds like this issue belongs over on the [git portable](https://github.com/sheabunge/GitPortable) repo. This repo is for the Pro Git book content, and I don't think there's anything that we can do about it. :) Closing this for now.
