### ISSUE TITLE
(Chapter A1.5)Figure 162 missing

### ISSUE THREAD

**Issue by agrexgh** [progit/progit2#1421]
**Which version of the book is affected?**

html ver.

**Describe the bug:**

![image](https://user-images.githubusercontent.com/47779973/80662610-a9813480-8acc-11ea-8401-c4652e1fe3ca.png)Figure above "Figure 162 ***" is not shown,
but text "Version Control ToolWindow in JetBrains IDEs." is shown.

**Steps to reproduce:**

Access below via chrome.
https://git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-IntelliJ-%2F-PyCharm-%2F-WebStorm-%2F-PhpStorm-%2F-RubyMine

**Expected behavior:**

Figure above "Figure 162 ***" is shown.

**Screenshots:**

Screenshot is attached.

**Additional context:**

It seems simply the picture file is lost.
404 error occurs when I access "https://git-scm.com/book/en/v2/images/jb.png", it is Figure 162 image source file.

**Desktop:**

- Operating system:
- Browser/application:
- Browser/application version:

**Smartphone:**

- Device:iPhone
- OS:iOS
- Browser/application:chrome
- Browser/application version: 81.0.4044.124

**E-book reader:**

- Device:
- Software Update:

**Comment by jnavila** [comment]
Ah, the image was not copied on git-scm server...

**Comment by ben** [comment]
@jnavila is this a problem we can fix here, or does it belong to the [git/git-scm.com](https://github.com/git/git-scm.com) repo?

**Comment by jnavila** [comment]
https://github.com/git/git-scm.com/pull/1456 was merged.

**Comment by agrexgh** [comment]
![2AFA0814-2673-4F81-AFE5-2F2B98B72F40](https://user-images.githubusercontent.com/47779973/81269356-2770ad00-9084-11ea-9aa2-008f7bd34686.png)

I can see it!
Thank you!

I'll close this issue.
