### ISSUE TITLE
07-git-tools-rewriting-history-Splitting a Commit rebase bug

### ISSUE THREAD

**Issue by Sharpiro** [progit/progit2#1431]
**Which version of the book is affected?**

the online book
**Describe the bug:**

In the [Splitting a Commit](https://github.com/progit/progit2/blob/8512004fcd1b494ce855e668771163dc73ef6b86/book/07-git-tools/sections/rewriting-history.asc#splitting-a-commit) section:

I believe the line `f3cc40e Change my name a bit` should instead be `f7f3f6d Change my name a bit`  Because `f7f3f6d` was `pick` during the interactive rebase, and it is older than `310154e` which was marked as `edit`, that commit should not change.

Context:
This:
```sh
$ git log -4 --pretty=format:"%h %s"
1c002dd Add cat-file
9b29157 Add blame
35cfb2b Update README formatting
f3cc40e Change my name a bit
```

Should be:
```sh
$ git log -4 --pretty=format:"%h %s"
1c002dd Add cat-file
9b29157 Add blame
35cfb2b Update README formatting
f7f3f6d Change my name a bit
```
And then the explanation below would need to explain that all child commits of `f7f3f6d` were modified in the rebase, rather than "all" the ones seen in the rebase menu.

**Comment by ben** [comment]
Oooh, good catch! Want to submit a PR to fix it? I'd love for you to get `git blame` credit for finding this.

**Comment by Sharpiro** [comment]
Yea I’ll take a stab at it, thanks.

**Comment by Sharpiro** [comment]
Hey @ben, I created  #1433 to address this. Thanks.
