### ISSUE TITLE
Include link in book to Martin Fowlers page on branching patterns

### ISSUE THREAD

**Issue by HonkingGoose** [progit/progit2#1434]
I think the book could be improved by comparing the different workflows that are possible with git, and highlighting the benefits and trade-offs that each flow has. However this might be considered "scope/feature-creep"... Luckily somebody else already made a good resource on this, so that we don't have to duplicate the effort! 😄

This website explains the different git branching patterns that you can choose from, and the pros/cons of each: https://martinfowler.com/articles/branching-patterns.html

The page is still being worked on by Martin Fowler, but what's already there is of high quality and very helpful. Quote from bottom of linked page:
>I'm releasing this article in installments. I've now finished describing all the patterns on my todo list. Next week I'll briefly talk about how they tie into the popular branching strategies gitflow, github flow, and trunk-based development.

I suggest adding a link to Martin Fowlers website in the https://github.com/progit/progit2/blob/master/book/03-git-branching/sections/workflows.asc section of the book.

If this is something that the ProGit teams want, I'll open a pull-request with the suggested change for review. 👍

**Comment by ben** [comment]
That seems like a good idea to me. Let's see that PR!
