### ISSUE TITLE
detached HEAD or detatched HEAD

### ISSUE THREAD

**Issue by slothjun** [progit/progit2#1436]
**Describe the bug:**

translation available in chinase.

the English full name of the separated head pointer of Section 2.6 is detached HEAD or detatched HEAD?

**Steps to reproduce:**

1.Go to 'https://git-scm.com/book/zh/v2'

2.Click on '2.6打标签'

3.Scroll down to '检出标签'

4.See error '离头指针（detacthed HEAD）'

**Comment by jnavila** [comment]
The correct term is "detached HEAD".

This project is the english version of Progit v2. Please report this typo to https://github.com/progit/progit2-zh
