### ISSUE TITLE
Double full stop, at end of paragraph

### ISSUE THREAD

**Issue by finn0** [progit/progit2#1437]
**Which version of the book is affected?**

Both

**Describe the bug:**

If paragraph ends with a captions, it has double full stop symbol, at end of the paragraph. See

![double-full-stop](https://user-images.githubusercontent.com/28824347/84555363-05fe8300-ad0c-11ea-8095-a8e1f080f239.png)
Fig: Screenshot of [double dot](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#double_dot) section in Git tools revision selection chapter.

**Steps to reproduce:**

- Go to any paragraph which ends with a caption
- See end of the paragraph

**Actual Behavior**
There are two full stop symbols at end of the paragraph.

**Expected behavior:**
There should be only one full stop at end of paragraph

**Screenshots:**

Adding same screenshot as above, but there are other places also paragraph ends with double full stop.
![double-full-stop](https://user-images.githubusercontent.com/28824347/84555363-05fe8300-ad0c-11ea-8095-a8e1f080f239.png)
Fig 1: Screenshot of [double dot](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#double_dot) section in Git tools revision selection chapter.

![triple_dot](https://user-images.githubusercontent.com/28824347/84556828-e6b82380-ad14-11ea-8b8b-cc1283580f4b.png)
Fig 2: Screenshot of triple dot section in Git tools revision selection chapter

**Desktop:**

- Operating system: Any
- Browser/application: Any
- Browser/application version: Any

**Smartphone:**

- Device: Any
- OS: Any
- Browser/application: Any
- Browser/application version: Any

**E-book reader:**

- Device: Any
- Software Update: Any

**Comment by finn0** [comment]
I think, this happens because caption itself contains a full stop.

**Comment by ben** [comment]
🤔 [Here](https://github.com/progit/progit2/blob/master/book/07-git-tools/sections/revision-selection.asc#L291-L295) is the section in question. It's easy to fix in this case, but maybe we should remove punctuation from the figure captions? Would you care to submit a pull request that does one of those things? I'd love for you to get credit for the fix.

**Comment by finn0** [comment]
> we should remove punctuation from the figure captions?

That would be great idea.

> Would you care to submit a pull request that does one of those things?

I would love to.
