### ISSUE TITLE
Text is hard to read on Kindle Oasis

### ISSUE THREAD

**Issue by nscheer** [progit/progit2#1438]
**Which version of the book is affected?**
I downloaded the book here:
https://github.com/progit/progit2/releases/download/2.1.227/progit.mobi

**Describe the bug:**
I'm trying to read the book on a 2019er Kindle Oasis.
Unfortunately, the text seems grey-ish and as such, the contrast is very low.
The page gets inverted on every turn, which also indicated, that there's grayscale involved.

**Steps to reproduce:**
Just use the mobi file provided on the website.

**Expected behavior:**
The body text should be black (i.e. as black as it could get on a kindle).

**E-book reader:**
Amazon Kindle Oasis 2019
Firmware 5.12.5

**Screenshots**
The first pictures shows the problem. The second shows how I'd expect the text to look like (from another book).

![a](https://user-images.githubusercontent.com/5212218/84576895-59c6a600-adb8-11ea-8bd1-6291e26d898f.jpg)
![b](https://user-images.githubusercontent.com/5212218/84576896-5af7d300-adb8-11ea-970b-233636d505db.jpg)

**Comment by jnavila** [comment]
This is mostly related to https://github.com/asciidoctor/asciidoctor-epub3/issues/67

So it seems difficult to fix and it seems to be more related to asciidoctor-epub3

**Comment by nscheer** [comment]
Turns out, there's already a media query in asciidoctor to fix that - it's just the resolution of the device that needs to be added.

I added the resolution manually and re-build the mobi file - now everything looks great!
Guess this will be available soon in ascidoctor.

Thanks @jnavila !

**Comment by jnavila** [comment]
Just reopening the issue to keep us aware that we'll need to update our Gemfile.

**Comment by nscheer** [comment]
Ups, sorry if that was too hasty 😊

**Comment by slonopotamus** [comment]
You don't need to update Gemfile because it automatically picks up latest 1.5.x releases of asciidoctor-epub3.

**Comment by jnavila** [comment]
Good catch! Thanks!
