### ISSUE TITLE
Punctuation mark before parentheses

### ISSUE THREAD

**Issue by finn0** [progit/progit2#1443]
**Which version of the book is affected?**

**Describe the bug:**

At some places, there is a punctuation mark before parentheses. I quickly look for it on web, found that we shouldn't put any punctuation mark before parentheses mark, see [Common Errors - Parentheses](https://brians.wsu.edu/2016/05/30/parentheses/).

**Steps to reproduce:**
1. Run `grep -nr . -e ".)"` command on project directory.
For example, see [this](https://github.com/progit/progit2/blame/master/book/02-git-basics/sections/remotes.asc#L106) line of code.

**Expected behavior:**
I think, it's not a good idea to use a punctuation mark before parenthesis. What do you think?

**Screenshots:**
![punctuation-mark-before-parentheses](https://user-images.githubusercontent.com/28824347/85530468-7c995b80-b5fd-11ea-8ca5-5e729ca928cf.png)

**Desktop:**

- Operating system: Any
- Browser/application: Any
- Browser/application version: Any

**Smartphone:**

- Device: Any
- OS: Any
- Browser/application: Any
- Browser/application version: Any

**E-book reader:**

- Device: Any
- Software Update: Any

**Comment by Morganov** [comment]
I assume, in this particular case parentheses could be removed. Possibly, in other cases too as well.

**Comment by finn0** [comment]
@Morganov Can I make pull request for this by removing parentheses, if possible?

**Comment by Morganov** [comment]
Sure, pull requests are welcome.
