### ISSUE TITLE
'pu' has been renamed to 'seen'

### ISSUE THREAD

**Issue by sivaraam** [progit/progit2#1447]
**Which version of the book is affected?**
The v2 version of the book accessible via the website.

**Describe the bug:**
The Git maintainer has renamed the `pu`branch to `seen`. See: https://public-inbox.org/git/xmqqimfid2l1.fsf@gitster.c.googlers.com/

The `pu` branch is referenced in the book in a few places. So, they need to updated.

**Comment by ben** [comment]
Ooh, nice catch. Want to submit a PR? I'd love for you to get credit for the update.

**Comment by sivaraam** [comment]
Sure! I'll try submitting a PR when I'm free. Hopefully this weekend. 🙂
