### ISSUE TITLE
Section on using git within Visual Studio is 6 years out of date

### ISSUE THREAD

**Issue by HonkingGoose** [progit/progit2#1451]
**Which version of the book is affected?**

The version that's present on `master`.

**Describe the bug:**

https://github.com/progit/progit2/blob/master/book/A-git-in-other-environments/sections/visualstudio.asc
is out of date, and contains outdated pictures.

**Steps to reproduce:**

1. Go to: https://github.com/progit/progit2/blob/master/book/A-git-in-other-environments/sections/visualstudio.asc
2. Notice last commit was 6 years ago.
3. Notice picture are outdated.

**Expected behavior:**

1. Section up to date with current version of Visual Studio 2019 **or** no Progit2 custom section at all, just a link to current docs for Visual Studio 2019.

**Screenshots:**

**Additional context:**

**Desktop:**

- Operating system:
- Browser/application:
- Browser/application version:

**Smartphone:**

- Device:
- OS:
- Browser/application:
- Browser/application version:

**E-book reader:**

- Device:
- Software Update:

---

# Discussion:

The outdated Visual Studio section was also noted in #1205.

EDIT: The dead link that I originally reported is fixed with the merge of #1450.
I also updated this issue report to take that into account, as not to confuse readers after the merge. 😄

**Comment by prnadago** [comment]
@HonkingGoose Hi, I was just about to create an issue for this and happily found yours first. I work on the Visual Studio team and would love to help update this section. Our team is building a new Git experience in Visual Studio 2019, and we've recently added documentation for it - https://docs.microsoft.com/en-us/visualstudio/ide/git-with-visual-studio?view=vs-2019. We can start by updating the link but I agree the page needs a rewrite, including new screenshots. How can I help? 😃

**Comment by HonkingGoose** [comment]
Hi @prnadago! 👋 

Thank you very much for your help to update this section! 🎉 🚀 

I suggest you start with a PR to update the link first as that is easiest to do, and will get your feet wet with AsciiDoctor.

I don't know if you've ever worked with AsciiDoctor, but you can find the docs for AsciiDoctor here: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Our readme has some help on setting up how to use Ruby to build the book: https://github.com/progit/progit2/blob/master/README.asc

Keep in mind that we follow the "one sentence per line" rule here.
That means that we create a newline when we encounter a `.`
That will be important for when you're working on the rewrite.

We keep our images here: https://github.com/progit/progit2/tree/master/images
And you can read here how to link to the new images: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#images
You should delete the old images as well, as we won't be using those again... 😄 

If you need more help feel free to ping me again. 😄
