### ISSUE TITLE
A question of understanding

### ISSUE THREAD

**Issue by max123kl** [progit/progit2#1453]
While @Mo-Gul is checking the German translation for style and typing errors, he noticed the following paragraph.

Reference: book/02-git-basics/sections/aliases.asc - lines 5+6:

```
Before we finish this chapter on basic Git, there's just one little tip that can make your Git experience simpler, easier, and more familiar: aliases.
We won't refer to them or assume you've used them later in the book, but you should probably know how to use them.
```
Especially line 6 is not entirely comprehensible to us.
@ben 
Would you please describe this sentence a bit easier for non-native English speaking readers.

**Comment by ben** [comment]
Absolutely, and sorry for the confusion. Here's a rewritten version of those lines that hopefully makes more sense.

> Before we move on to the next chapter, we want to introduce a feature that can make your Git experience simpler, easier, and more familiar: aliases. For clarity's sake, we won't be using them anywhere else in this book, but if you go on to use Git with any regularity, aliases are something you should know about.

Does that help?

**Comment by Mo-Gul** [comment]
That sounds much better. Thank you for the quick fix.

**Comment by HonkingGoose** [comment]
Hi @Mo-Gul do you want me to make a pull-request that fixes this, or do you want to do it yourself?

**Comment by Mo-Gul** [comment]
@HonkingGoose, you are welcome to do so.
(If there should arise more of these stuff I'll come along when having a look at the German translation, you are (all) free to fix it here (in the English version) yourself. That saves me time which I'll invest in *more reading* :)

**Comment by HonkingGoose** [comment]
I'll go make a pull-request then. :smile:
