### ISSUE TITLE
Add a GitHub Action to build book?

### ISSUE THREAD

**Issue by Mo-Gul** [progit/progit2#1458]
I am not sure about my request so opinions are welcome.

How about adding a GitHub Action to build the HTML and PDF output on commits which are then somehow/somewhere available to others, so also the (real) results can be checked?

I have no clue if this is possible for AsciiDoctor files and how that would be done. But I know, that this can be done for LaTeX files. A quick search for a starting point on AsciiDoctor Actions revealed

- https://github.com/marketplace/actions/build-asciidoctor-action
- https://github.com/marketplace/actions/hugo-asciidoctor-action
- https://github.com/mgred/asciidoctor-action
- https://github.com/asciidoctor/asciidoctor.js/pull/807

Maybe there is something useful in it.

---
Background:

In the German book it was found that some figures where not shown in the PDF output (only) (see https://github.com/progit/progit2-de/issues/113) I guess most of the contributors don't have AsciiDoctor installed and "just" use the preview, so not all details like that PDF checking can be done quickly/easily.

**Comment by jnavila** [comment]
This check should be done by asciidoctor itself, and running the compilation on GitHub Actions instead of Travis (presently) will not change anything. Please note that presently, the book is built by travis on all branches and pull requests. This is mainly an issue with asciidoctor which raises no warnings/errors when not processing correctly an image.

**Comment by Mo-Gul** [comment]
Aah, of course the book is build (by Travis). Sorry.
May I ask if the Travis output is available somewhere?

**Comment by jnavila** [comment]
https://travis-ci.org/progit/progit2

**Comment by ben** [comment]
Having just gone through this at `$DAYJOB`, I'd say that it's not _difficult_ to replace Travis with GitHub Actions, but it is tedious, and in the end you have mostly the same thing you had before. We already auto-publish to git-scm.com and the Releases tab, so unless something breaks I don't see a good reason to go through that work.

**Comment by Mo-Gul** [comment]
I already excused myself that I have forgotten that there was the Travis CI. And then of course there is no need to replace it with GitHub Actions.

The missing info was that the builds are auto-published. Thank you guys!!
