### ISSUE TITLE
 Doubts: What is the difference between `reference` and `pointer` and `named pointer`?

### ISSUE THREAD

**Issue by xjnotxj** [progit/progit2#1460]
First of all thanks to the author, this book is great. But in the process of reading, I have a question, that is, the difference between the concepts of `reference` and `pointer` and `named pointer` (I will simply and roughly think that reference is equal to pointer)

The descriptions related to these in this book are：（Source：https://git-scm.com/book/en/v2/Git-Internals-Git-References）

> That’s basically what a branch in Git is: a simple `pointer` or `reference` to the head of a line of work. To create a branch back at the second commit, you can do this:

> Usually the HEAD file is a symbolic `reference` to the branch you’re currently on. By symbolic `reference`, we mean that unlike a normal `reference`, it contains a `pointer` to another `reference`.

> The tag object is very much like a commit object — it contains a tagger, a date, a message, and a `pointer`.

Descriptions elsewhere：（Source：https://git-scm.com/docs/git）

> A Git project normally consists of a working directory with a ".git" subdirectory at the top level. The .git directory contains, among other things, a compressed object database representing the complete history of the project, an "index" file which links that history to the current contents of the working tree, and `named pointers` into that history such as tags and branch heads.

To put it more, there are concepts like `reference` and `pointer` in programming languages. What are the similarities and differences?

**Comment by ben** [comment]
In the English version, we definitely treat "pointer" and "reference" as interchangeable. The Git documentation does the same kind of thing — the [`cherry-pick`](https://git-scm.com/docs/git-cherry-pick) documentation uses "pointer" and "ref" to mean the same thing. "Ref" is the internal concept with the most specific technical meaning; the others are mainly used for prose descriptions.

Does that help? Or did I just make it worse? 😄

**Comment by KZiemian** [comment]
Can this issue be close now?
