### ISSUE TITLE
licensing question to reuse image

### ISSUE THREAD

**Issue by white-gecko** [progit/progit2#1471]
The book is licensed with the cc by-nc-sa license, as discussed here: https://github.com/progit/progit2/issues/372

I want to use one figure in my dissertation. Now it is going to be printed by our open access university press. Since the paper version of the book will be sold they say I can not use a figure with "nc". The resulting book shall be licensed unter cc-by-sa or cc-by-sa-nc.
Are you able to pr vide individual licenses for such cases?

Dpecifically I'm speaking about [data-model-4.svg](https://github.com/progit/progit2/blob/master/images/data-model-4.svg).

**Comment by ben** [comment]
IANAL, so I don't want to get into relicensing individual files. But if you draw a figure that looks _a lot like_ that diagram, nobody is going to file a suit. Just don't use the exact version from here or the git-scm.com website. 😄

**Comment by HonkingGoose** [comment]
I think this issue can be closed, as the question is answered by the project maintainer.

**Comment by white-gecko** [comment]
@ben Thank you for the reply.
