### ISSUE TITLE
Proposal: merge content of README.asc and CONTRIBUTING.md

### ISSUE THREAD

**Issue by HonkingGoose** [progit/progit2#1478]
**Which version of the book is affected?**

The version that's hosted on GitHub.
Present on `master`.

**Describe the bug:**

The documentation for contributing is split between the landing page [README.asc](https://github.com/progit/progit2/blob/master/README.asc) and the [CONTRIBUTING.md](https://github.com/progit/progit2/blob/master/CONTRIBUTING.md)

**Steps to reproduce:**

1. Go to https://github.com/progit/progit2.
1. A contributor reads the section that displays the README.asc
1. But then also the contributor needs to click trough to another guide, to find out how to really contribute.

**Expected behavior:**

1. Go to https://github.com/progit/progit2
2. The README.asc contains everything a contributor needs to get started, so the content of README.asc and CONTRIBUTING.md are merged.

**Screenshots:**

**Additional context:**

I noticed the split between the files when working on the text of the contributing guide in this PR:  https://github.com/progit/progit2/pull/1477.

**Discussion:**

What is the reason that the content is spread around in two files, instead of merged into one README?
If you want to merge the content, I'll make a pull-request that merges the content together.

**Comment by ben** [comment]
Probably the biggest reason is this feature of GitHub:

![image](https://user-images.githubusercontent.com/39902/89743538-edcf8980-da58-11ea-8936-7b400418fb4d.png)

This shows up even more prominently when you're opening a new PR. I know that the audience for both documents is pretty similar, but this one feature means that having a specific document for contribution guidelines makes a lot of sense.

**Comment by HonkingGoose** [comment]
Ah okay, I'll close this issue in favor of making a PR template, as I suggested, and you wanted in #1479

Thanks for merging in my work on a lot of pull-requests! 😄
