### ISSUE TITLE
Feature proposal: create a pull-request template

### ISSUE THREAD

**Issue by HonkingGoose** [progit/progit2#1479]
**Which version of the book is affected?**

Problem is present on `master`.
Problem is with the pull-request workflow on GitHub.

**Describe the bug:**

By opening a pull-request, you agree to license your work to the ProGit2 project under a Creative Commons license, and give permission to include the work in a print edition.
This is only mentioned in a [CONTRIBUTING.md](https://github.com/progit/progit2/blob/master/CONTRIBUTING.md), that not all contributors might actually read before making a pull-request.

**Steps to reproduce:**

1. Go to the GitHub pull-request interface.
1. Open new pull-request.
1. Note that there is no notice given in the pull-request process that I'm licensing my work, or that I'm giving permission to include the work in a print edition.

**Expected behavior:**

1. Go to the GitHub pull-request interface.
1. Open a new pull-request.
1. The pull-request has a lightweight template, that explains that you grant a license to use your work under the Creative Commons license, and that you give permission to include the work in a print edition.
1. PR template contains a checkbox that the user is licensing their work to the project.
1. The pull-request template also warns against making a large rewrite (The CONTRIBUTING guide says that those changes should have a issue for discussion first).

**Screenshots:**

**Additional context:**

I noticed this issue when I was opening a PR for: https://github.com/progit/progit2/pull/1477
And I thought, maybe we should just put this info straight into the PR process instead of requiring a contributor to go hunt around for the info.

Of course if this is something the project wants, I'll be more than happy to create a PR for this change. 😄 👍

**Comment by ben** [comment]
Yeah, this would be great. Adding a checkbox for licensing would help everybody know what they're agreeing to as well.

**Comment by HonkingGoose** [comment]
I'll go make  a PR template then. 😄
