### ISSUE TITLE
Breaking builds: Kindlegen dependency no longer available

### ISSUE THREAD

**Issue by HonkingGoose** [progit/progit2#1496]
**Which version of the book is affected?**

:warning: This issue affects all builds! :warning: 
Problem will be present on all future builds/releases once the Travis CI cache is expired. Problem is with source files.

**Describe the bug:**

The 'kindlegen' binary that we depend on to build/validate the Kindle files is no longer available to download from the rubygems.org website. Because this dependency is no longer available, Travis CI cannot build new releases of the book.

I'm specifically talking about this entry in the Gemfile:
https://github.com/progit/progit2/blob/8b361da3b1d4424180d5ba3a204f8616436bdd01/Gemfile#L16

**Steps to reproduce:**

1. Try to run a build on Travis CI.
2. Build fails with:

```
mAn error occurred while installing kindlegen (3.0.5), and Bundler

cannot continue.

Make sure that `gem install kindlegen -v '3.0.5' --source

'https://rubygems.org/'` succeeds before bundling.

In Gemfile:

  kindlegen

The command "bundle install" failed and exited with 5 during .
```

Example of failed build: https://travis-ci.org/github/HonkingGoose/progit2/builds/721079601

**Expected behavior:**

Build passes.

**Screenshots:**

**Additional context:**

Upstream issue reports: https://github.com/tdtds/kindlegen/issues/42 https://github.com/asciidoctor/asciidoctor-epub3/issues/363
We also have some other issues outstanding with dependencies at: #1373 #1358 

Amazon says to use Kindle Previewer instead, to get the same functionality: 
https://www.amazon.com/gp/feature.html?docId=1000765211
This will not work for our project, as according to @slonopotamus the Kindle Previewer does not exist for Linux.

This problem is also present when I try to download the Kindlegen dependency locally. So it's not just Travis CI that's broken...

**Comment by slonopotamus** [comment]
I've also created asciidoctor/asciidoctor-epub3#363 because chances that there will be any fix to tdtds/kindlegen#42 are very low. `kindlegen` gem is just a thin wrapper that downloads KindleGen binary to comply with EULA, but now there isn't anything to download unless someone publishes KindleGen binaries on their own website.

And the problem with Kindle Previewer is that it doesn't exist for Linux.

**Comment by HonkingGoose** [comment]
Thanks for your feedback @slonopotamus! :smile: 
I've edited my top post to include your findings.

https://github.com/progit/progit2/blob/8b361da3b1d4424180d5ba3a204f8616436bdd01/Rakefile#L19-L25

@slonopotamus I noticed that you removed the kindlegen dependency with https://github.com/asciidoctor/asciidoctor-epub3/pull/364 to get `asciidoctor-epub3` working again?

We're using: https://github.com/progit/progit2/blob/8b361da3b1d4424180d5ba3a204f8616436bdd01/Gemfile#L9

Could the ProGit2 project fix the broken builds, by upgrading to a newer version of the `asciidoctor-epub3` dependency and dropping the `kindlegen` dependency from our Gemfile? Or would some further step(s) be needed? We're on: https://github.com/progit/progit2/blob/8b361da3b1d4424180d5ba3a204f8616436bdd01/Gemfile#L4

I do recall there being some issue with cross-reference links not working on newer versions of epub3. So we would also maybe need to run the migration script that @jnavila is working on.

I'm trying to get a sense of what would be needed to fix this. :smile: I hope I'm not bothering you to much with this. :+1:

**Comment by slonopotamus** [comment]
> I noticed that you removed the kindlegen dependency with asciidoctor/asciidoctor-epub3#364 to get asciidoctor-epub3 working again?

Yes, this is an emergency measure to unbreak CI builds until there is a solution for Mobi. Obviously it means that Mobi generation is no longer possible.

WRT progit2, you don't need a new version of asciidoctor-epub3. Dropping dependency on `kindlegen` and disabling Mobi creation in Rakefile is enough.

I'm currently trying to find out an exit from current situation on asciidoctor-epub3 side. Stay tuned.

**Comment by HonkingGoose** [comment]
I'll make a pull-request to get the build at least functional until we can do more. :smile:

**Comment by HonkingGoose** [comment]
I'm closing this issue, as the build is not breaking anymore with the quick-fix of just not providing a `mobi` build anymore.

**Comment by KZiemian** [comment]
I just found this problem with Kindlegen and following this discussion I commented out line
`gem 'kindlegen', '3.1.1'`
from Gemfile.
