### ISSUE TITLE
U

### ISSUE THREAD

**Issue by mazid12345** [progit/progit2#1499]
**Which version of the book is affected?**

**Describe the bug:**

**Steps to reproduce:**

**Expected behavior:**

**Screenshots:**

**Additional context:**

**Desktop:**

- Operating system:
- Browser/application:
- Browser/application version:

**Smartphone:**

- Device:
- OS:
- Browser/application:
- Browser/application version:

**E-book reader:**

- Device:
- Software Update:

**Comment by mazid12345** [comment]
- @mazid12345

**Comment by lazarljubenovic** [comment]
Erm...

**Comment by HonkingGoose** [comment]
@ben, this issue can be closed.
