### ISSUE TITLE
Git/book

### ISSUE THREAD

**Issue by PhongLion** [progit/progit2#1505]
**Which version of the book is affected?**

**Describe the bug:**

**Steps to reproduce:**

**Expected behavior:**

#1201 
**Screenshots:**

https://appr.tc
**Additional context:**

APP:FFmpeg
**Desktop:**

- Operating system:
- Browser/application:
- Browser/application version:
UI/UX:10
**Smartphone:**

- Device:
- OS:
- Browser/application:
- Browser/application version:
Version:12.1.1.36
**E-book reader:**

- Device:
- Software Update:August 1 2020

**Comment by mazid12345** [comment]
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> **Which version of the book is affected?**
> 
> 
> 
> 
> 
> 
> 
> **Describe the bug:**
> 
> 
> 
> 
> 
> **Steps to reproduce:**
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> **Expected behavior:**
> 
> 
> 
> #1201 
> 
> **Screenshots:**
> 
> 
> 
> https://appr.tc
> 
> **Additional context:**
> 
> 
> 
> 
> 
> APP:FFmpeg
> 
> **Desktop:**
> 
> 
> 
> 
> 
> - Operating system:
> 
> - Browser/application:
> 
> - Browser/application version:
> 
> UI/UX:10
> 
> **Smartphone:**
> 
> 
> 
> 
> 
> - Device:
> 
> - OS:
> 
> - Browser/application:
> 
> - Browser/application version:
> 
> Version:12.1.1.36
> 
> **E-book reader:**
> 
> 
> 
> 
> 
> - Device:
> 
> - Software Update:August 1 2020
