### ISSUE TITLE
Add new 'git switch' command

### ISSUE THREAD

**Issue by Paebbels** [progit/progit2#1515]
Git has a new command called `switch` to change branches instead of using `checkout`.

Please add this command to the book.

----------
Related to:
* #1084

**Comment by HonkingGoose** [comment]
Issue #1441 also talks about `git switch`.

---

@ben Do you want a pull request from me to include `git switch`? And if so, do you want a NOTE, or full section?

You said a while back https://github.com/progit/progit2/issues/1441#issuecomment-653256248:

> My recommendation is that while there's a non-trivial chance that our readers will be running a version of Git that doesn't include switch, we add a NOTE section saying "there's an easier way of doing this." When it's reasonably certain that everybody can use the new commands, that's when we can remove references to git checkout -- <file>.
> 
> These commands were introduced in Git 2.27, but my MacOS system (the latest 10.5.5) comes bundled with Git 2.24.3, so we're not there yet. Most people will update Git, but some will not, and we don't want them to have a super frustrating experience as they're trying to learn.

**Comment by ben** [comment]
> Do you want a pull request from me to include `git switch`?

Sure! Probably just a note for now. We can rewrite to recommend `switch` first and `checkout` as a note when MacOS and (apparently) Debian stable have newer versions.

**Comment by HonkingGoose** [comment]
Hi @ben, I made a new issue to track the pending rewrite that we'll need to do once `git switch` is available on MacOS and Debian stable: #1524, seeing as you'll close this issue when you merge pull #1523. :smile:
