### ISSUE TITLE
Missing dash in a Git command example

### ISSUE THREAD

**Issue by FlyingDutchman1965** [progit/progit2#1532]
Hi there,

In chapter 2, section "Undoing Things" is the example

$ git commit -amend

There is a hyphen missing before the amend keyword option. Should be:

$ git commit --amend

Right. Back to ploughing through the basics

**Comment by HonkingGoose** [comment]
Hi @FlyingDutchman1965,

Thanks for the issue report. :smile: :+1: 

Can you provide a link to the exact place you're seeing this problem?
I searched for all instances of the string `amend` in the current `master` branch, and I have not found your issue.

I also checked: https://github.com/progit/progit2/blob/master/book/02-git-basics/sections/undoing.asc but that's all good as well.

**Comment by FlyingDutchman1965** [comment]
Looks OK in the html but in the PDF downloaded from the link on the git-scm website:


Undoing Things
At any stage, you may want to undo something. Here, we’ll review a few basic tools for undoing changes that you’ve
made. Be careful, because you can’t always undo some of these undos. This is one of the few areas in Git where you
may lose some work if you do it wrong.
One of the common undos takes place when you commit too early and possibly forget to add some files, or you
mess up your commit message. If you want to try that commit again, you can run commit with the --amend option:
$ git commit –amend

Hope this helps


Sent from Mail for Windows 10

**Comment by FlyingDutchman1965** [comment]
OK, looks like it’s already been corrected and not published as PDF to the website yet.

Lesson learned for the day. I’ll check within the .asc files first next time.

Next task, try to build the PDF from scratch.

Thanks.

Sent from Mail for Windows 10

**Comment by HonkingGoose** [comment]
Yeah it's definitely fixed already. I downloaded the latest pdf file from the git-scm site, and that's fine as well.

The Git-scm website refreshes the ProGit2 content on a nightly cron job, it's not fully live. So keep in mind that the git-scm site can serve outdated ProGit2 content until they refresh.

Good luck with learning Git!

If you find some other problems with the book, feel free to open a new issue. :+1:

**Comment by HonkingGoose** [comment]
@ben this issue can be closed, as it is already fixed on `master`.
