### ISSUE TITLE
Appendix C: core.editor command for TextEdit incorrectly uses --add

### ISSUE THREAD

**Issue by Sophismata** [progit/progit2#1537]
**Which version of the book is affected?**

The online book: https://git-scm.com/book/en/v2/Appendix-C:-Git-Commands-Setup-and-Config

**Describe the bug:**

The command to set your core.editor setting for Text Edit is listed as
`git config --global --add core.editor "open -W -n"`
it should be
`git config --global core.editor "open -W -n"` (no --add parameter)

**Steps to reproduce:**

View Appendix C and look at the line for TextEdit (macOS)

**Expected behavior:**

The command should be `git config --global core.editor "open -W -n"`, which is in line with all the other core.editor commands and won't accidentally add (potentially) two entries for the setting.

**Desktop:**

- Operating system: Windows 10 Pro
- Browser/application: Chrome
- Browser/application version: 85.0.4183.121 (64 Bit)

**Comment by Sophismata** [comment]
Still editing, accidentally hit ctrl-enter.

**Comment by saleh711-png** [comment]
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> **Which version of the book is affected?**
> 
> 
> 
> 
> 
> The online book: https://git-scm.com/book/en/v2/Appendix-C:-Git-Commands-Setup-and-Config
> 
> 
> 
> **Describe the bug:**
> 
> 
> 
> The command to set your core.editor setting for Text Edit is listed as
> 
> `git config --global --add core.editor "open -W -n"`
> 
> it should be
> 
> `git config --global core.editor "open -W -n"` (no --add parameter)
> 
> 
> 
> **Steps to reproduce:**
> 
> 
> 
> View Appendix C and look at the line for TextEdit (macOS)
> 
> 
> 
> **Expected behavior:**
> 
> 
> 
> The command should be `git config --global core.editor "open -W -n"`, which is in line with all the other core.editor commands and won't accidentally add (potentially) two entries for the setting.
> 
> 
> 
> **Desktop:**
> 
> 
> 
> 
> 
> - Operating system: Windows 10 Pro
> 
> - Browser/application: Chrome
> 
> - Browser/application version: 85.0.4183.121 (64 Bit)
