### ISSUE TITLE
Figure 46, p.102/515 - Commit order after rebasing

### ISSUE THREAD

**Issue by mihailm94** [progit/progit2#1552]
Hello!

I am using the Pro Git book to learn more about Git. First of all, thank you for this amazing source of information!

On page 102, in Figure 46 (upper figure), in the "The Perils of Rebasing" subchapter, I believe that after rebasing, the "master" branch of the "git.team1.ourcompany.com" repository should have the following order:

`C1 <- C4 <- C5'`

Whereas right now, it looks like this:

`C1 <- C5 <- C4'`,

which to my opinion contradicts rebasing, as explained in the  beginning of the "Rebasing" chapter, in particular in figure 37 on page 97.

Thank you in advance.

Kind regards,
Mihail

**Comment by HonkingGoose** [comment]
Hi @mihailm94,

I've taken some screenshots to help illustrate what you're talking about:

## Figure 46

![figure_46_for_reference](https://user-images.githubusercontent.com/34918129/97870238-ff9c9200-1d12-11eb-865c-770d505f97cb.png)

## Figure 37

![figure_37](https://user-images.githubusercontent.com/34918129/97870483-51ddb300-1d13-11eb-8ee8-1610952885ad.png)

**Comment by ben** [comment]
Well, figures 37 and 46 belong to two separate usage examples. The "perils of rebasing" example is meant to stand alone, and doesn't even have an `experiment` branch. If that's confusing, maybe we could make it more clear?

Second, notice the grayed- out commits in figure 46. `C4'` is meant to be a squashed-and-rebased amalgam of `C4` and `C6`. I know the numeric ordering is a little weird, but it was originally intended to convey chronological order, but maybe that was a mistake. Here, I've annotated the screenshot with the intent:

![CleanShot 2020-11-02 at 09 47 27@2x](https://user-images.githubusercontent.com/39902/97901132-93a93200-1cf0-11eb-8564-fd7e1ca27c71.png)

Does that make sense? Can you think of a way we could explain this better? It's a difficult topic to get right.

**Comment by mihailm94** [comment]
Hello!

First of all, sorry for my delayed response, and many thanks for the elaborate reply from Your side!

I do understand the underlying logic, even more so with the visual representation.

I am marking this issue as closed!

Kind regards
