### ISSUE TITLE
Migrate away from travis-ci.org

### ISSUE THREAD

**Issue by slonopotamus** [progit/progit2#1566]
travis-ci.**org** is going to be shut down on **December, 31**:

https://docs.travis-ci.com/user/migrate/open-source-repository-migration#frequently-asked-questions

> Q. When will the migration from travis-ci.org to travis-ci.com be completed?
> A. In an effort to ensure that all of our users - whether you build open-source, public or private repositories - receive regular feature updates, security patches and UX/UI enhancements, we are announcing that travis-ci.org will be officially closed down completely no later than December 31st, 2020, allowing us to focus all our efforts on bringing new features and fixes to travis-ci.com and all of our awesome users like yourself on the travis-ci.com domain.

> Q. What will happen to travis-ci.org after December 31st, 2020?
> A. Travis-ci.org will be switched to a read-only platform, allowing you to see your jobs build history from all repositories previously connected to travis-ci.org.

Also, note that travis-ci.**com**, while being the most logical place to move to, has **build time limits** for public repositories:

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).

I saw that multiple projects (for example, major part of Asciidoctor ecosystem) moved from Travis to GitHub Actions in last month or two, though this is not a single option available nowadays.

**Comment by HonkingGoose** [comment]
Hi @ben have you seen this issue?

Summary: Travis CI from the `.org` domain is shutting down. This means that tests and builds will no longer work after December 31st, 2020.

Action is needed to either:

- Migrate to Travis CI on the `.com` domain, and get 1000 free build minutes on Linux a month from their free trial plan
- Migrate to GitHub Actions and get unlimited build minutes for free

I just wanted to ping you to make sure that you have seen this issue. 😄

**Comment by slonopotamus** [comment]
> get 1000 free build minutes on Linux *a month* from their free trial plan

I never saw Travis to say *a month*. According to my googling, I believe it is a one-time credit.

**Comment by HonkingGoose** [comment]
> I never saw Travis to say **a month**. According to my googling, I believe it is a one-time credit.

I think you're right, the Pricing FAQ on https://travis-ci.com/plans says:

> **Why don't you have a Trial period?**
>
> New customers are assigned the Free plan by default. You will be given 10,000 credits to try out the system. Linux, Windows, macOS, FreeBSD builds all supported.

I don't see anything on their plans page that say that those credits get topped up for free...
So it seems that this is a one-time credit, if it's used up, it's gone.

---

But there is a way to get free credits for open-source projects that have public builds, if you ask them, according to a section on https://travis-ci.com/plans:

> Free for open source. We love the Open Source Community, and to show how much we love it, upon validated request placed with our Support Team you may receive free OSS credits for your public builds.

I don't know how generous this plan is, and what the requirements are to "validate". So that's something for the head maintainer to ask Travis support.

**Comment by jnavila** [comment]
I have a branch at https://github.com/progit/progit2-fr/tree/github-actions to start the migration. It is not workable yet, but the required work on it is not that much.

**Comment by slonopotamus** [comment]
> Also it seems that you will have to ask for new credits each time you run out.

This

1. Feels inconvenient
2. Imposes a risk of Travis rejecting quota request for random reasons and progit2 ending up without a CI suddenly
3. Is unpredictable. You can't predict how many PRs will be opened against progit2 and when given credits will run out.

Though it's up to project maintainers to decide whether they want to go with travis-ci.**com** or not. Maybe they like Travis so much that want to go payed plan for OSS project.
