### ISSUE TITLE
I've squashed the changes that I and @jnavila made on #1373, and also merged #1541 into this branch.

### ISSUE THREAD

**Issue by APinfinite** [progit/progit2#1570]
I've squashed the changes that I and @jnavila made on #1373, and also merged #1541 into this branch.
I've also updated to the latest version of Asciidoctor (2.0.11) which seems to work just fine.

I manually migrated some missing legacy double quoted syntax to the modern syntax.

I think this is ready to go, but @jnavila can you please run that migration script again on this branch, and see what it catches?

@ben can you take a look at this and tell me what you think of it?

_Originally posted by @HonkingGoose in https://github.com/progit/progit2/pull/1554#issuecomment-721099442_

**Comment by HonkingGoose** [comment]
@jnavila This can be closed as well.
