### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by APinfinite** [progit/progit2#1571]
**Which version of the book is affected?**

**Describe the bug:**

**Steps to reproduce:**

**Expected behavior:**

**Screenshots:**

**Additional context:**

**Desktop:**

- Operating system:
- Browser/application:
- Browser/application version:

**Smartphone:**

- Device:
- OS:
- Browser/application:
- Browser/application version:

**E-book reader:**

- Device:
- Software Update:

**Comment by APinfinite** [comment]
https://github.com/progit/progit2/blob/1882031bd77b27c248c0af3fb61f7087bfab9d01/CONTRIBUTING.md

**Comment by HonkingGoose** [comment]
@jnavila This can be closed.
