### ISSUE TITLE
FTBFS: External link timeout when building HTML format

### ISSUE THREAD

**Issue by bagasme** [progit/progit2#1593]
**Which version of the book is affected?**

commit 1cf691ef7a775c919587b8079124156defd56c40

**Describe the bug:**

Building the book by `bundle exec rake book:build` (as suggested by README) cause FTBFS (fail to build) on HTML book format because of external-link timeout.

Ruby version: 2.7.0 (rvm), Ubuntu 20.04

**Steps to reproduce:**

- Build (generate the book) by `bundle exec rake book:build`

**Expected behavior:**

Successfully generate the book.

**Screenshots:**

**Additional context:**

Build log: [build log](https://github.com/progit/progit2/files/5842031/progit2.log)

**Comment by jnavila** [comment]
External links of the book are checked so, you need to have access to internet when building it.

**Comment by bagasme** [comment]
@jnavila I connected to internet network by wi-fi (good signal).

Tested one of problematic links by `curl` and by using browser, such as [Git Sublime integration](https://www.sublimetext.com/docs/3/git_integration.html), it worked, however

**Comment by bagasme** [comment]
In summary, we need to update links.

**Comment by bagasme** [comment]
Here's another: If there are the first link that throw error (such as 404s or timeout), the subsequent link will probably throw error too.

For timeout errors, network may be culprit.

**Comment by jnavila** [comment]
I don't experience the issues you have. And the automatic CI script neither. I'm not sure the html checker is supposed to follow redirects.

**Comment by bagasme** [comment]
@jnavila so the problem lies on my network.

but what surprise me that the problematic links can be accessed in the browser.

**Comment by jnavila** [comment]
So I would guess, it has more to do with the ruby gem.

**Comment by bagasme** [comment]
@jnavila did you mean `html-proofer` (the culprit gem)?

**Comment by jnavila** [comment]
Yes, I do. If you can open the URLs from another client on your computer, then, it's the client's fault, although I don't understand how. I'm running Debian Testing (which is parent to Ubuntu) and have never experienced such behavior.

**Comment by bagasme** [comment]
closing for now without response.

**Comment by bu632ada** [comment]
One more

Pada Jum, 19 Mac 2021 5:36 PTG Bagas Sanjaya ***@***.***>
menulis:
