### ISSUE TITLE
Refactoring `book:build`

### ISSUE THREAD

**Issue by bagasme** [progit/progit2#1595]
I'm proposing to refactor `book:build` task on `Rakefile`.

The task will be split into:
  1. generating `book/contributors.txt` (as prerequisites)
  2. one build task for each supported formats (html, epub, and pdf)

Also introduce `book:clean` task, which will remove all generated artifacts (`book/contributors.txt`, `progit.{html,epub,pdf}`)

**Comment by jnavila** [comment]
While you are at it, I would also like to split the tasks of checking some artifacts (html, epub), from the task of building all of them (pdf). PDF takes a lot of time and does not check anything, so it is useless for CI.

**Comment by bagasme** [comment]
@jnavila ok, but should `book:build` still check artifacts, right?

**Comment by jnavila** [comment]
We could hava a target `book:ci` which only build for checking and `book:build` which only focus on artifacts. The check could be performed for `book:build` but errors would not lead to failure.

**Comment by bagasme** [comment]
@jnavila did you mean `book:ci` only for checking the generated books?

**Comment by flyzoner** [comment]
- [ ] [Kt](jav)
