### ISSUE TITLE
Create a "feature" issue template?

### ISSUE THREAD

**Issue by HonkingGoose** [progit/progit2#1606]
I was thinking it might be nice to have a "feature" issue template that contributors can use to propose new features for the book and/or repo.

After PR #1605 gets merged, we can then remove the option to create a "blank" issue completely by adding `blank_issues_enabled: false` to the `config.yml` in the `ISSUE_TEMPLATES` directory.
This would ensure that every issue/feature request is using a template.

Do you want me to make a rough draft for a feature issue template?

**Comment by ben** [comment]
Yeah!

**Comment by HonkingGoose** [comment]
I'll go make a feature template then. 😄
