### ISSUE TITLE
Desktop:** <!-- If you've used a desktop/laptop to access the content, please fill in this form. --> <!-- Example: Windows 10 Home Edition, Firefox, version 66.0.2 --> - Operating system: - Browser/application: - Browser/application version:

### ISSUE THREAD

**Issue by luismene** [progit/progit2#1624]
**Which version of the book is affected?**

**Describe the bug:**

**Steps to reproduce:**

**Expected behavior:**

**Screenshots:**

**Additional context:**

**Desktop:**

- Operating system:
- Browser/application:
- Browser/application version:

**Smartphone:**

- Device:
- OS:
- Browser/application:
- Browser/application version:

**E-book reader:**

- Device:
- Software Update:

**Comment by HonkingGoose** [comment]
@ben or @jnavila This issue can be closed.
