### ISSUE TITLE
👋

### ISSUE THREAD

**Issue by LaosPaklay** [progit/progit2#1653]
**Which version of the book is affected?**

**Describe the bug:**

**Steps to reproduce:**

**Expected behavior:**

**Screenshots:**

**Additional context:**

**Desktop:**

- Operating system:
- Browser/application:
- Browser/application version:

**Smartphone:**

- Device:
- OS:
- Browser/application:
- Browser/application version:

**E-book reader:**

- Device:
- Software Update:

**Comment by LaosPaklay** [comment]
.

**Comment by LaosPaklay** [comment]
1653

**Comment by lazarljubenovic** [comment]
I'm glad you're having fun.

**Comment by HonkingGoose** [comment]
@ben or @jnavila you can close this issue, it's just spam.
