### ISSUE TITLE
Asciidoc parser (AsciidocToGo) confused by many hyphens

### ISSUE THREAD

**Issue by BravoBaldo** [progit/progit2#167]
In some cases, the parser Asciidoc (AsciidocToGo) confuses the rows with many hyphens '---------...' with the line of the end tag ('-----' 4 hyphen).
 This happens in:
 maintaining.asc Rows 174, 176
 signing.asc Row 14
 Client-svn.asc 394, 399, 404,
 import-custom.asc 316, 329, 337
 import-hg.asc 84, 97, 105

A tab at the beginning, it solves the problem.

Ciao
	Baldo

**Comment by YueLinHo** [comment]
I checked all places where more than 4 hyphens.
All of them are part of [source,console].
So, this issue is a invalid one.

**Comment by ben** [comment]
Oh, thanks @YueLinHo! Closing for now, feel free to reopen if there's still a problem.

**Comment by jaafarexcz** [comment]
#167

**Comment by jaafarexcz** [comment]
167
