### ISSUE TITLE
Archive/delete project board for Asciidoctor 2 migration

### ISSUE THREAD

**Issue by HonkingGoose** [progit/progit2#1670]
Hi @ben,

Can you please delete the old "Asciidoctor 2.0 migration board? We never even used it, and we're finished with the migration anyways. 😄 

Link to board: https://github.com/progit/progit2/projects/1

Link to GitHub docs on deleting a project board: https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/deleting-a-project-board

**Comment by ben** [comment]
Done!
