### ISSUE TITLE
`.mobi` build process is not creating the `.mobi` files for release

### ISSUE THREAD

**Issue by HonkingGoose** [progit/progit2#1671]
**Which version of the book is affected?**

Problem is with source files on `main` branch.

https://github.com/progit/progit2/tree/main/.github/workflows

**Describe the bug:**

Our GitHub Action is somehow still not creating `.mobi` releases.
It seems to be related to `kindlegen`, according to the Action log output.

**Steps to reproduce:**

Go to GitHub releases tab, see no `.mobi` files for download.
The `Release on push to main` action is giving a error message on the `Build release assets` step:

```
Converting to Mobi (kf8)...
Unable to run KindleGen. Either install the kindlegen gem or place `kindlegen` executable on PATH or set KINDLEGEN environment variable with path to it (RuntimeError)
```

Link to error message on a recent run: https://github.com/progit/progit2/runs/2942333250?check_suite_focus=true#step:5:13

**Expected behavior:**

`.mobi` files are building and releasing properly.

**Screenshots:**

**Additional context:**

Maybe try running the rake build script locally, to confirm it works.
I have a feeling that maybe the github action is barred from downloading from the web archive that we use to grab the `kindlegen`, but I can't confirm/deny this. 😄

**Comment by HonkingGoose** [comment]
@slonopotamus Are you willing to help out with fixing this? Maybe you have an idea what's going wrong here?

**Comment by slonopotamus** [comment]
See #1672. I didn't notice that because I had kindlegen installed in advance.
