### ISSUE TITLE
aux.sh--this file could make the clone failed

### ISSUE THREAD

**Issue by cruise2018** [progit/progit2#1690]
### There's no existing/similar bug report.

- [X] I have searched the existing issues

### This report is about a single actionable bug.

- [X] I'm reporting a single actionable bug

### This report is about the ProGit book, version 2, English language.

- [X] This bug is not about a translation or old version

### Bug covers book website/pdf

- [ ] I confirm the bug is about the book as found on the website/pdf

### Problem is present in the Pro Git book on the website?

- [X] This bug also affects the Pro Git book as published on the website.

### Which version of the book is affected?

Tooling

### Describe the bug:

when i use the gitbash in windows10 and i clone the code from https://github.com/lvmteam/lvm2.git , and an error happens:
$ git clone https://gitee.com/Cruise2019/test.git
Cloning into 'test'...
warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcmcore-tlsverify for more information.
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 24 (delta 6), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (24/24), 17.82 KiB | 5.94 MiB/s, done.
Resolving deltas: 100% (6/6), done.
error: invalid path 'aux.sh'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

And this happens in version 2.26.2 and 2.32.0. I don't know why this happens. 

### Steps to reproduce:

method1:In windows， install the gitbash， 2.26.2.window1, or 2.32.0.maybe another version also get this.
open the gitbash, and git clone https://github.com/lvmteam/lvm2.git
 you will find it failed. 

method2: you could make a reponsity in github, and make a file named aux.sh, any position and any content in it.

### Expected behavior:

download the content success

### Screenshots:

$ git clone https://gitee.com/Cruise2019/test.git
Cloning into 'test'...
warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcmcore-tlsverify for more information.
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 24 (delta 6), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (24/24), 17.82 KiB | 5.94 MiB/s, done.
Resolving deltas: 100% (6/6), done.
error: invalid path 'aux.sh'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

### Additional context:

alone

### Device

laptop

### Operating system

win10 professionnal

### Browser/application + version

Google Chrome

**Comment by ben** [comment]
I'm not sure what the error you're seeing is, but it's probably to do with the filename. I'd recommend you visit [the repo you're trying to clone](https://github.com/lvmteam/lvm2) and see if you can get help from them.

I'm going to close this, because there's nothing we can do in the text of this book to fix this for you. 😀
