### ISSUE TITLE
Emphasize that assume-unchanged and skip-worktree bits are not propagated to origin with git push

### ISSUE THREAD

**Issue by bruzina** [progit/progit2#1713]
### General overview of your idea.

Reference https://git-scm.com/docs/git-update-index describes **assume-unchanged and skip-worktree bits** and should include clear information on whether they are propagated to remotes with `git push` or not.

### What problem will this solve?

From https://git-scm.com/docs/git-update-index it is unclear, how **assume-unchanged and skip-worktree bits** work in relation to remotes - if they are local only, or propagated to a remote as well.

From other documentation - https://git-scm.com/docs/git-sparse-checkout#_sparse_checkout or https://git-scm.com/docs/gitfaq, it might be deducible, but it would be convenient to mention it in https://git-scm.com/docs/git-update-index#_notes as well.

### Have you thought about other solutions?

- Use Google - it's not easy to find the fact by Google
- Search for the information by on-page search - https://git-scm.com/search/results?search=skip-worktree and https://git-scm.com/search/results?search=assume-unchanged top results are not helpful, but I admit that from the bottom ones it is deducible
- Write a blog about it - http://blog.stephan-partzsch.de/how-to-ignore-changes-in-tracked-files-with-git/ already posted the information:

> But no matter which option (assume-unchanged and skip-worktree bits) you choose there is one point to consider: The chosen bit will not be propagated by git push.

### Do you want to help with this enhancement idea?

No

**Comment by HonkingGoose** [comment]
Hi @bruzina 👋 

I think you're in the wrong place with your issue unfortunately. This repository covers the Pro Git 2 book content. The Git program, manual and documentation are a separate project.

I think you should post your suggestion on the Git mailing list instead: [^git-community]

> **Mailing List**
>
> General questions or comments for the Git community can be sent to the mailing list by using the email address git@vger.kernel.org.

I recommend you check out the Git Community page. [^git-community]

[^git-community]: https://git-scm.com/community

**Comment by bruzina** [comment]
Thank you for pointing me in the right direction!
