### ISSUE TITLE
Broken link in 'Git Commands' appendix

### ISSUE THREAD

**Issue by zigarn** [progit/progit2#176]
[Git-Commands-Basic-Snapshotting#git-difftool](http://git-scm.com/book/en/v2/Git-Commands-Basic-Snapshotting#git-difftool): broken link to '_git_difftool'
Should be a link to:
 - [Customizing-Git-Git-Configuration#External-Merge-and-Diff-Tools](http://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#External-Merge-and-Diff-Tools)
 - or 'Git Diff in an External Tool' note in [Git-Basics-Recording-Changes-to-the-Repository#Viewing-Your-Staged-and-Unstaged-Changes](http://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository#Viewing-Your-Staged-and-Unstaged-Changes)

**Comment by YueLinHo** [comment]
The same issue with #454.
Let's close this and go there?
