### ISSUE TITLE
Fix type in

### ISSUE THREAD

**Issue by frijger** [progit/progit2#1764]
# Pro Git >
#### Initializing a Repository in an Existing Directory:
...
for Windows:
```
$ cd C:/Users/user/my_project
```
![Screenshot from 2022-06-19 13-00-33](https://user-images.githubusercontent.com/98513455/174477753-3fc74c52-5712-4cc4-ba6e-30684bac26d5.png)
Expected:
```
cd C:\Users\user\my_project
```

**Comment by Morganov** [comment]
CMD in Windows supports both types of slashes, but git-bash in Windows supports forward-slashes only, so for better compatibility forward slashes are used here and there is no mistake.

**Comment by KZiemian** [comment]
In the light of words of @Morganov I think we can close this issue.
