### ISSUE TITLE
Gitosis is not mentioned anywhere

### ISSUE THREAD

**Issue by harupong** [progit/progit2#180]
> For the sake of simplicity we'll simply run it as the same 'git' user that Gitosis is running as.
https://github.com/progit/progit2/blob/31b9ca8b505398f7688146c12ed35e6b4fd16812/book/04-git-server/sections/git-daemon.asc#L44

In 1st edition, this sentence made sense because the section containing it was located 2 sections after the Gitosis section. Since it is removed from 2nd edition, sudden appearance of the word "Gitosis" in this way is really confusing.

**Comment by dennisschagt** [comment]
This issue can be closed. This is fixed in 9f852b8b0ee9dd06066bcb52923a9b913fa9e8fd by replacing `Gitosis` by `git-shell`.
