### ISSUE TITLE
No toc01.html in current html ebook

### ISSUE THREAD

**Issue by rahrah** [progit/progit2#182]
There is no toc01.html in current ebook.

This means that the table of contents link on any page does not work.

**Comment by WalterGR** [comment]
This still repros as of right now.

The download URL on http://git-scm.com/book/en/v2 is https://progit2.s3.amazonaws.com/en/2015-05-02-7ddee/progit-en.478.zip

Here's the file listing of that ZIP.  There is no toc*.html.

.gitignore
app01.html
app02.html
app03.html
atlas.json
ch01.html
ch02.html
ch03.html
ch04.html
ch05.html
ch06.html
ch07.html
ch08.html
ch09.html
ch10.html
Gemfile
Gemfile.lock
ix01.html
preface01.html
preface02.html
preface03.html
preface04.html
preface05.html
Rakefile
status.json
book/cover.png
book/01-introduction/images/areas.png
book/01-introduction/images/centralized.png
book/01-introduction/images/deltas.png
book/01-introduction/images/distributed.png
book/01-introduction/images/git-osx-installer.png
book/01-introduction/images/local.png
book/01-introduction/images/snapshots.png
book/02-git-basics/images/lifecycle.png
book/03-git-branching/images/advance-master.png
book/03-git-branching/images/advance-testing.png
book/03-git-branching/images/basic-branching-1.png
book/03-git-branching/images/basic-branching-2.png
book/03-git-branching/images/basic-branching-3.png
book/03-git-branching/images/basic-branching-4.png
book/03-git-branching/images/basic-branching-5.png
book/03-git-branching/images/basic-branching-6.png
book/03-git-branching/images/basic-merging-1.png
book/03-git-branching/images/basic-merging-2.png
book/03-git-branching/images/basic-rebase-1.png
book/03-git-branching/images/basic-rebase-2.png
book/03-git-branching/images/basic-rebase-3.png
book/03-git-branching/images/basic-rebase-4.png
book/03-git-branching/images/branch-and-history.png
book/03-git-branching/images/checkout-master.png
book/03-git-branching/images/commit-and-tree.png
book/03-git-branching/images/commits-and-parents.png
book/03-git-branching/images/head-to-master.png
book/03-git-branching/images/head-to-testing.png
book/03-git-branching/images/interesting-rebase-1.png
book/03-git-branching/images/interesting-rebase-2.png
book/03-git-branching/images/interesting-rebase-3.png
book/03-git-branching/images/interesting-rebase-4.png
book/03-git-branching/images/interesting-rebase-5.png
book/03-git-branching/images/lr-branches-1.png
book/03-git-branching/images/lr-branches-2.png
book/03-git-branching/images/perils-of-rebasing-1.png
book/03-git-branching/images/perils-of-rebasing-2.png
book/03-git-branching/images/perils-of-rebasing-3.png
book/03-git-branching/images/perils-of-rebasing-4.png
book/03-git-branching/images/perils-of-rebasing-5.png
book/03-git-branching/images/remote-branches-1.png
book/03-git-branching/images/remote-branches-2.png
book/03-git-branching/images/remote-branches-3.png
book/03-git-branching/images/remote-branches-4.png
book/03-git-branching/images/remote-branches-5.png
book/03-git-branching/images/topic-branches-1.png
book/03-git-branching/images/topic-branches-2.png
book/03-git-branching/images/two-branches.png
book/04-git-server/images/bitnami.png
book/04-git-server/images/git-instaweb.png
book/04-git-server/images/gitlab-broadcast.png
book/04-git-server/images/gitlab-groups.png
book/04-git-server/images/gitlab-menu.png
book/04-git-server/images/gitlab-users.png
book/05-distributed-git/images/benevolent-dictator.png
book/05-distributed-git/images/centralized_workflow.png
book/05-distributed-git/images/git-diff-check.png
book/05-distributed-git/images/integration-manager.png
book/05-distributed-git/images/large-merges-1.png
book/05-distributed-git/images/large-merges-2.png
book/05-distributed-git/images/managed-team-1.png
book/05-distributed-git/images/managed-team-2.png
book/05-distributed-git/images/managed-team-3.png
book/05-distributed-git/images/managed-team-flow.png
book/05-distributed-git/images/merging-workflows-1.png
book/05-distributed-git/images/merging-workflows-2.png
book/05-distributed-git/images/merging-workflows-3.png
book/05-distributed-git/images/merging-workflows-4 2.png
book/05-distributed-git/images/merging-workflows-4.png
book/05-distributed-git/images/merging-workflows-5.png
book/05-distributed-git/images/public-small-1.png
book/05-distributed-git/images/public-small-2.png
book/05-distributed-git/images/public-small-3.png
book/05-distributed-git/images/rebasing-1.png
book/05-distributed-git/images/rebasing-2.png
book/05-distributed-git/images/small-team-1.png
book/05-distributed-git/images/small-team-2.png
book/05-distributed-git/images/small-team-3.png
book/05-distributed-git/images/small-team-4.png
book/05-distributed-git/images/small-team-5.png
book/05-distributed-git/images/small-team-6.png
book/05-distributed-git/images/small-team-7.png
book/05-distributed-git/images/small-team-flow.png
book/06-github/callouts/1.pdf
book/06-github/callouts/1.png
book/06-github/callouts/10.pdf
book/06-github/callouts/10.png
book/06-github/callouts/2.pdf
book/06-github/callouts/2.png
book/06-github/callouts/3.pdf
book/06-github/callouts/3.png
book/06-github/callouts/4.pdf
book/06-github/callouts/4.png
book/06-github/callouts/5.pdf
book/06-github/callouts/5.png
book/06-github/callouts/6.pdf
book/06-github/callouts/6.png
book/06-github/callouts/7.pdf
book/06-github/callouts/7.png
book/06-github/callouts/8.pdf
book/06-github/callouts/8.png
book/06-github/callouts/9.pdf
book/06-github/callouts/9.png
book/06-github/images/2fa-1.png
book/06-github/images/account-settings.png
book/06-github/images/avatar-crop.png
book/06-github/images/blink-01-start.png
book/06-github/images/blink-02-pr.png
book/06-github/images/blink-03-pull-request-open.png
book/06-github/images/blink-04-email.png
book/06-github/images/blink-04-pr-comment.png
book/06-github/images/blink-05-general-comment.png
book/06-github/images/blink-06-final.png
book/06-github/images/blink-pull-request-open copy.png
book/06-github/images/blink-pull-request-open.png
book/06-github/images/collaborators.png
book/06-github/images/email-settings.png
book/06-github/images/emoji.png
book/06-github/images/forkbutton.png
book/06-github/images/hubot.png
book/06-github/images/maint-01-email.png
book/06-github/images/maint-02-merge.png
book/06-github/images/maint-03-email-resp.png
book/06-github/images/maint-04-target.png
book/06-github/images/maint-05-mentions.png
book/06-github/images/maint-06-unsubscribe.png
book/06-github/images/maint-07-notifications.png
book/06-github/images/maint-08-notifications-page.png
book/06-github/images/maint-09-contrib.png
book/06-github/images/maint-10-default-branch.png
book/06-github/images/maint-11-transfer.png
book/06-github/images/markdown-01-example.png
book/06-github/images/markdown-02-tasks.png
book/06-github/images/markdown-03-task-summary.png
book/06-github/images/markdown-04-fenced-code.png
book/06-github/images/markdown-05-quote.png
book/06-github/images/markdown-06-emoji-complete.png
book/06-github/images/markdown-07-emoji.png
book/06-github/images/markdown-08-drag-drop.png
book/06-github/images/mentions-01-syntax.png
book/06-github/images/mentions-02-render.png
book/06-github/images/mentions-03-closed.png
book/06-github/images/neworg.png
book/06-github/images/newrepo.png
book/06-github/images/new-repo.png
book/06-github/images/newrepoform.png
book/06-github/images/notifications.png
book/06-github/images/orgs-01-page.png
book/06-github/images/orgs-02-teams.png
book/06-github/images/orgs-03-audit.png
book/06-github/images/pr-01-fail.png
book/06-github/images/pr-02-merge-fix.png
book/06-github/images/reposettingslink.png
book/06-github/images/scripting-01-services.png
book/06-github/images/scripting-02-email-service.png
book/06-github/images/scripting-03-webhook.png
book/06-github/images/scripting-04-webhook-debug.png
book/06-github/images/scripting-05-access-token.png
book/06-github/images/scripting-06-comment.png
book/06-github/images/scripting-07-status.png
book/06-github/images/signup.png
book/06-github/images/ssh-keys.png
book/06-github/images/your-profile.png
book/07-git-tools/git-credential-read-only
book/07-git-tools/callouts/1.pdf
book/07-git-tools/callouts/1.png
book/07-git-tools/callouts/10.pdf
book/07-git-tools/callouts/10.png
book/07-git-tools/callouts/2.pdf
book/07-git-tools/callouts/2.png
book/07-git-tools/callouts/3.pdf
book/07-git-tools/callouts/3.png
book/07-git-tools/callouts/4.pdf
book/07-git-tools/callouts/4.png
book/07-git-tools/callouts/5.pdf
book/07-git-tools/callouts/5.png
book/07-git-tools/callouts/6.pdf
book/07-git-tools/callouts/6.png
book/07-git-tools/callouts/7.pdf
book/07-git-tools/callouts/7.png
book/07-git-tools/callouts/8.pdf
book/07-git-tools/callouts/8.png
book/07-git-tools/callouts/9.pdf
book/07-git-tools/callouts/9.png
book/07-git-tools/images/double-dot.png
book/07-git-tools/images/replace1.png
book/07-git-tools/images/replace2.png
book/07-git-tools/images/replace3.png
book/07-git-tools/images/replace4.png
book/07-git-tools/images/replace5.png
book/07-git-tools/images/rerere1.png
book/07-git-tools/images/rerere2.png
book/07-git-tools/images/rerere3.png
book/07-git-tools/images/reset-checkout.png
book/07-git-tools/images/reset-ex1.png
book/07-git-tools/images/reset-ex2.png
book/07-git-tools/images/reset-ex3.png
book/07-git-tools/images/reset-ex4.png
book/07-git-tools/images/reset-ex5.png
book/07-git-tools/images/reset-ex6.png
book/07-git-tools/images/reset-hard.png
book/07-git-tools/images/reset-mixed.png
book/07-git-tools/images/reset-path1.png
book/07-git-tools/images/reset-path2.png
book/07-git-tools/images/reset-path3.png
book/07-git-tools/images/reset-soft.png
book/07-git-tools/images/reset-squash-r1.png
book/07-git-tools/images/reset-squash-r2.png
book/07-git-tools/images/reset-squash-r3.png
book/07-git-tools/images/reset-start.png
book/07-git-tools/images/reset-workflow.png
book/07-git-tools/images/undomerge-reset.png
book/07-git-tools/images/undomerge-revert.png
book/07-git-tools/images/undomerge-revert2.png
book/07-git-tools/images/undomerge-revert3.png
book/07-git-tools/images/undomerge-start.png
book/08-customizing-git/images/clean.png
book/08-customizing-git/images/p4merge.png
book/08-customizing-git/images/smudge.png
book/09-git-and-other-scms/images/git-fusion-boot.png
book/09-git-and-other-scms/images/git-fusion-perforce-graph.png
book/09-git-and-other-scms/images/git-tfs-ct.png
book/10-git-internals/images/data-model-1.png
book/10-git-internals/images/data-model-2.png
book/10-git-internals/images/data-model-3.png
book/10-git-internals/images/data-model-4.png
book/A-git-in-other-environments/images/branch_widget_mac.png
book/A-git-in-other-environments/images/branch_widget_win.png
book/A-git-in-other-environments/images/egit.png
book/A-git-in-other-environments/images/git-bash.png
book/A-git-in-other-environments/images/git-gui.png
book/A-git-in-other-environments/images/github_mac.png
book/A-git-in-other-environments/images/github_win.png
book/A-git-in-other-environments/images/gitk.png
book/A-git-in-other-environments/images/posh-git.png
book/A-git-in-other-environments/images/vs-1.png
book/A-git-in-other-environments/images/vs-2.png
book/A-git-in-other-environments/images/zsh-oh-my.png
book/A-git-in-other-environments/images/zsh-prompt.png
book/B-embedding-git/callouts/1.pdf
book/B-embedding-git/callouts/1.png
book/B-embedding-git/callouts/10.pdf
book/B-embedding-git/callouts/10.png
book/B-embedding-git/callouts/2.pdf
book/B-embedding-git/callouts/2.png
book/B-embedding-git/callouts/3.pdf
book/B-embedding-git/callouts/3.png
book/B-embedding-git/callouts/4.pdf
book/B-embedding-git/callouts/4.png
book/B-embedding-git/callouts/5.pdf
book/B-embedding-git/callouts/5.png
book/B-embedding-git/callouts/6.pdf
book/B-embedding-git/callouts/6.png
book/B-embedding-git/callouts/7.pdf
book/B-embedding-git/callouts/7.png
book/B-embedding-git/callouts/8.pdf
book/B-embedding-git/callouts/8.png
book/B-embedding-git/callouts/9.pdf
book/B-embedding-git/callouts/9.png
callouts/1.pdf
callouts/1.png
callouts/10.pdf
callouts/10.png
callouts/2.pdf
callouts/2.png
callouts/3.pdf
callouts/3.png
callouts/4.pdf
callouts/4.png
callouts/5.pdf
callouts/5.png
callouts/6.pdf
callouts/6.png
callouts/7.pdf
callouts/7.png
callouts/8.pdf
callouts/8.png
callouts/9.pdf
callouts/9.png
diagram-source/progit.sketch
includes/_vimeo.liquid
includes/_youtube.liquid
theme/epub/epub.css
theme/html/html.css
theme/mobi/mobi.css
theme/pdf/pdf.css
theme/pdf/pdf.xsl~

end of comment

**Comment by WalterGR** [comment]
I looked at some of the past snapshots of progit.org on Archive.org - since the release of 2ed - to get older download URLs.  Spot-checking, I don't think the HTML ZIPs have ever contained any toc*.html files.

**Comment by YueLinHo** [comment]
html download does not exist anymore.

**Comment by ben** [comment]
It does, it's right here:

![image](https://cloud.githubusercontent.com/assets/39902/13826923/31ed4150-eb77-11e5-82cc-4d9e50a80589.png)

I just downloaded that one, and `toc.html` does exist, and the navigation links at the bottom of every page point to it. Closing for now, feel free to re-open if this becomes a problem again.

**Comment by YueLinHo** [comment]
@ben Thanks for pointing it out. :+1:

**Comment by rahrah** [comment]
Hi,

The links at the bottom of every page on the files in the distributed html zip archive are only to Next and Previous.  There are no links to the table of contents (as there were in earlier versions - links but broken links).  

However, the toc.html file does now exist and does have valid links inside it.

Building from the source on github using:

bundle exec rake book:build

creates a single html file with the contents at the top.  The pdf created does not have page
numbers (at least not with my toolchain).

Thanks for addressing all this.

Cheers,

===Rich

**Comment by YueLinHo** [comment]
> I would say that these issues should be reopened.

Could you please point them out? I mean which existed issue? or are them new issue but not yet create a new one for them?

**Comment by rahrah** [comment]
@YueLinHo I'll open new issues.  I cannot reopen this one.

===Rich

**Comment by YueLinHo** [comment]
> I cannot reopen this one.

@rahrah In my opinion, no need to reopen this issue, because there should be a rule: one issue for one problem.
