### ISSUE TITLE
Redirect incoming request for https://git-scm.com/book/en/v1 to https://git-scm.com/book/en/v2

### ISSUE THREAD

**Issue by derberg** [progit/progit2#1836]
### There's no existing/similar bug report.

- [X] I have searched the existing issues

### This report is about a single actionable bug.

- [X] I'm reporting a single actionable bug

### This report is about the ProGit book, version 2, English language.

- [X] This bug is not about a translation or old version

### Bug covers book website/pdf

- [ ] I confirm the bug is about the book as found on the website/pdf

### Problem is present in the Pro Git book on the website?

- [X] This bug also affects the Pro Git book as published on the website.

### Which version of the book is affected?

I don't know

### Describe the bug:

There is a bunch of links pointing to https://git-scm.com/book/en/v1 like for example https://git-scm.com/book/en/v1/Git-Internals-Git-Objects#Commit-Objects. This particular is mentioned in many GitHub docs. I think it is a good practice to maintain redirects on server side

### Steps to reproduce:

just go to https://git-scm.com/book/en/v1/Git-Internals-Git-Objects#Commit-Objects

### Expected behavior:

`https://git-scm.com/book/en/v1/Git-Internals-Git-Objects#Commit-Objects` should be redirected to the same but v2 `https://git-scm.com/book/en/v2/Git-Internals-Git-Objects#Commit-Objects`

**Comment by HonkingGoose** [comment]
This is a good bug report, but you're in the wrong place. 😉 

The `progit/progit2` repository is about the book's content.

It sounds like you're reporting a problem with the `git-scm.com` website. Please create a new issue in the [git/git-scm.com repository](https://github.com/git/git-scm.com) to report the missing redirects.

**Comment by HonkingGoose** [comment]
@ben you should close this issue as `not planned`, I've filed a new issue in the correct place for us:

- https://github.com/git/git-scm.com/issues/1782
