### ISSUE TITLE
Improve readability with some minor style adjustments for images

### ISSUE THREAD

**Issue by ericdrobinson** [progit/progit2#1889]
### General overview of your idea.

Images in the book include [title text](https://docs.asciidoctor.org/asciidoc/latest/macros/images/#ex-attributes) to provide a description of the content. Readability of this title text in the HTML version of the book can be _greatly_ enhanced with a few very minor adjustments to the book's [styling](https://docs.asciidoctor.org/asciidoctor/latest/html-backend/custom-stylesheet/).

Specifically, applying this CSS to the book in browser dev tools:

```css
div.title {
    padding-bottom: 1rem;   /* Separate from main text */
    text-align: center;     /* Center the text */
    font-style: italic;     /* Italic styling */
}
```

is all that was necessary to take the page rendering from this:

<img width="669" alt="image" src="https://github.com/progit/progit2/assets/9142587/11f51e7f-3d34-4170-8e2e-8cf157524eaf">

to this:

<img width="665" alt="image" src="https://github.com/progit/progit2/assets/9142587/8031b003-7350-464e-97a7-0ac738bf3b5e">

Such adjustments would bring the HTML version of the book closer to the PDF one (which has much better readability for image titles already):

<img width="685" alt="image" src="https://github.com/progit/progit2/assets/9142587/cfba8afd-261d-441f-813c-0bb2d182ac5f">

### What problem will this solve?

When reading the HTML version of the book today, I found that I was continuously getting thrown off by the image title text. The text is currently rendered in such a way that it appears inline with normal paragraph text. I manually adjusted it so that I could stop getting distracted by it and found that my reading experience was dramatically improved with such a small change.

### Do you want to help with this enhancement idea?

No

**Comment by ben** [comment]
I think you'll have to file this over at https://github.com/git/git-scm.com. That site's CSS isn't generated from this repo, only the HTML content is.

**Comment by ericdrobinson** [comment]
> I think you'll have to file this over at https://github.com/git/git-scm.com. That site's CSS isn't generated from this repo, only the HTML content is.

@ben Are you sure about that? I took a look at the bundled CSS used by on that site and found that [the HTML theme CSS](https://github.com/progit/progit2/blob/main/theme/html/html.css) appears to be included in the CSS bundle directly:

```css
/* ... */
/* ... */
```

**Comment by ericdrobinson** [comment]
> I think you'll have to file this over at https://github.com/git/git-scm.com. That site's CSS isn't generated from this repo, only the HTML content is.

@ben Are you sure about that? I took a look at the bundled CSS used by on that site and found that [the HTML theme CSS](https://github.com/progit/progit2/blob/a581e03352f9b6aaf196d41cc99c439d78b87743/theme/html/html.css) appears to be [included in the CSS bundle directly](https://github.com/git/git-scm.com/blob/036f27d17b53de177fb74ebcdcdecbf0f1e0070e/app/assets/stylesheets/book2.scss#L612-L705).

With this in mind, is it still appropriate to open a similar Issue over on the main site's repository?
