### ISSUE TITLE
Using `git config --global core.editor "kate"` leads to "Aborting commit due to empty commit message" error

### ISSUE THREAD

**Issue by andrei-korshikov** [progit/progit2#1893]
**Checks:**
(Sorry, I created the issue with `Reference in new issue` in `Code view`, so I crafted this section manually.)
- There's no existing/similar bug report (I've searched for `kate` in issues).
- This report is about a single actionable bug.
- This report is about the ProGit book, version 2, English language.
- Bug covers **both** book **website and pdf**
- Problem is present in the Pro Git book on the website - **YES**
- Which version of the book is affected? - **Source files**, at [this very line](https://github.com/progit/progit2/blob/a581e03352f9b6aaf196d41cc99c439d78b87743/C-git-commands.asc?plain=1#L59)

**Steps to reproduce:**
1. Execute `git config --global core.editor "kate"` as written in Appendix C, [core editor configuration commands](https://github.com/progit/progit2/blob/a581e03352f9b6aaf196d41cc99c439d78b87743/C-git-commands.asc?plain=1#L59)
2. Execute `git commit`. At this moment `Kate` is started, but `git` **doesn't wait for Kate exiting,** immediately complain with error `Aborting commit due to empty commit message.`

**Solution:**
Use `git config --global core.editor "kate --block"` instead. Now git says `hint: Waiting for your editor to close the file...` and everything is working as expected.

**Additional info:**
The same problem and the same [solution](https://www.linuxquestions.org/questions/linux-software-2/problem-using-kate-as-git-editor-4175581416/#post5576597) proposed on LinuxQuestions.org.

**Comment by ben** [comment]
oooh, nice find. Want to submit a PR? I'd love for you to get `git blame` credit for fixing this.

**Comment by andrei-korshikov** [comment]
> Want to submit a PR?

Ok, in a couple of days. Thank you for the opportunity to learn something new:)
