### ISSUE TITLE
git: 'credential-read-only' is not a git command

### ISSUE THREAD

**Issue by Sherry520** [progit/progit2#1969]
### There's no existing/similar bug report.

- [X] I have searched the existing issues

### This report is about a single actionable bug.

- [X] I'm reporting a single actionable bug

### This report is about the ProGit book, version 2, English language.

- [X] This bug is not about a translation or old version

### Bug covers book website/pdf

- [X] I confirm the bug is about the book as found on the website/pdf

### Problem is present in the Pro Git book on the website?

- [X] This bug also affects the Pro Git book as published on the website.

### Which version of the book is affected?

Source files

### Describe the bug:

In section "Git Tools" -> "Credential Storage" -> "A Custom Credential Cache" 
When I run the command `git credential-read-only --file=./ get` , error occured:
`git: 'credential-read-only' is not a git command. See 'git --help'.`

### Steps to reproduce:

1. `vim git-credential-read-only`
2. paste the following code as show in section "Git Tools" -> "Credential Storage" -> "A Custom Credential Cache" 
![image](https://github.com/user-attachments/assets/2e5720b2-a0e9-4eeb-8c4e-68023b3289fc)

4. `export PAHT=~:$PATH`
5. `git credential-read-only --file=git.store get`
6. See error
![image](https://github.com/user-attachments/assets/e7a507e0-6371-480e-a25b-779ab310776d)

### Expected behavior:

In my case, it doesn't show the input and occurred error.

![image](https://github.com/user-attachments/assets/3e25f573-dce4-44dc-9eaf-d0e4c10f9457)

**Comment by Sherry520** [comment]
When I read this section [10-git-internals/sections/environment.asc](https://github.com/progit/progit2/blob/main/book/10-git-internals/sections/environment.asc#global-behavior), I know why there is this error, and what I really need to do is change the environment variable `GIT_EXEC_PATH`, not `PATH`.
Therefore, I recommend revising this section and stating in advance that this will be covered in more detail in subsequent chapters.

**Comment by ben** [comment]
In your reproduction, you typed this:

> `export PAHT=~:$PATH`

Is this typo the source of your issue? Because I'm able to do this:

```
$ echo $PATH
# (includes ~/bin)
$ cat > ~/bin/git-test-command
#!/bin/sh
echo hello git
^D
$ chmod a+x ~/bin/git-test-command
$ git test-command
hello git
$ 
```

**Comment by Sherry520** [comment]
@ben Yes, it's weird. Now I can modify `PATH` to run the commend without modifying `GIT_EXEC_PATH`, maybe because I didn't have ruby installed before.  But now there's another error, unless I change `File.exists?` to `File.exist?`.
![image](https://github.com/user-attachments/assets/7c63ea89-f114-4c0f-a7db-e1958bfd0e0c)

**Comment by ben** [comment]
Yup, looks like `File.exists?` was deprecated in Ruby 2.2, and removed in Ruby 3.2. You probably ended up with a 3.3 Ruby. If you'd like to submit a PR that fixes that line I'd accept it.
