### ISSUE TITLE
improve visibility date of last edit/revision

### ISSUE THREAD

**Issue by nbehrnd** [progit/progit2#1996]
### General overview of your idea.

The pdf _file_ on <https://git-scm.com/book/en/v2> prominently states e.g., `Version 2.1.439, 2024-12-03`, the page `2nd Edition (2014)`.  In other words, only _after_ the successful download of the document one can infer the document's maintenance continues to the present day and didn't stop years ago.

### What problem will this solve?

I suggest the addition of a note to close this gap.  To me, a plausible improvement to the web site's display could be `2nd Edition (2014, last revision by 2024-12-03)`.

### Have you thought about other solutions?

One could provide a note about the last revision in form of `Version 2.1.439`, or the abbreviated git hash like e.g., `051ae88`.  But to a human visitor of the web site, presumably without any knowledge about version control in general, and git in particular, these strings are less meaningful, too technical.

### Do you want to help with this enhancement idea?

Maybe

**Comment by ben** [comment]
This is a good idea! But we can't fix it here, this is just the book source. That page is served up in this repo: https://github.com/git/git-scm.com
