### ISSUE TITLE
Improve contrast

### ISSUE THREAD

**Issue by dsbos** [progit/progit2#200]
Please make the main text black instead of gray (in the HTML version).  

(The text in the PDF version seems to be fully black.  Why use lower-contrast (harder-to-read) gray instead of black in the HTML version?)

**Comment by jnavila** [comment]
If it's on the git-scm.com website, please report it to git/git-scm.com

**Comment by HonkingGoose** [comment]
Hi @dsbos I've opened a issue in the correct place for this: https://github.com/git/git-scm.com/issues/1334

---

@ben you can close this issue, because the problem seems to be "upstream" on the git-scm markup/html/CSS/whatever.
