### ISSUE TITLE
Dutch Translation

### ISSUE THREAD

**Issue by Cpt-xx** [progit/progit2#220]
Hi,

As soon as times permits I will try and translate the progit-2 to Dutch. As soon as I've got something done I will want to open an issue, however the page telling me to open an issue leads me to the page which tells me to open an issue... etc. 

I have already forked the progit2 repository and I assume that I will translate in the master and that this will automagically lead to this master being merged into the progit 2 family.

I am aware that this forum may not be the correct one to report this issue, but as I can't open an issue at that translation page I see no other possibility.

Kind regards,

Cor

p.s. Thanks for mentioning me in the credits :)

**Comment by schacon** [comment]
I'm not sure I follow you exactly, but yes, if you start translating PG2 and let me know when at least a chapter or two is complete, I will set up the automatic builds.  Where is the translation fork?

**Comment by Cpt-xx** [comment]
The fork is at git@github.com:progit/progit2.git. I've done about 3 chapters so far, but haven't pushed yet.

There are some other questions I'd like to ask, such as: 
- Is it wise/advisable to also translate the texts between ((( and ))). I'm in two minds at the moment. If my presumption is correct, these are/can be used for generating indexes and it may be useful to see these texts in the target language. However, I can also imagine that this will make the relation with the English text more distant/vague. 
- Is it wise/advisable to also translate the texts between << and >> (and of course the [[ and ]] to which they relate)
- At the moment I'm using an Idea plugin to show the text in final format, but the `'and '' (which seem not not really to be used consistently by the way) don't seem to show up correctly. I couldn't find the formatting attempted with these and I'm not sure what to do with them, for now I've translated them into `" and "`.
- Is there a recommended workflow to be followed by the language maintainer? I'm waiting to push my translations until I'm sure how to setup my workflow.

This turned out to be a heck of a cross-posting, but I'm hoping you can help me with these questions (and with that anybody else translating).

**Comment by Cpt-xx** [comment]
I've pushed the first 5 chapters to my fork, so if you please: link and run tests. 

Note that I've replaced "backtick backtick <some word or command> single quote single quote" with "double quote backtick <come word or command> backtick double quote" as I am assuming that the former is actually trying to achieve what is described in http://asciidoctor.org/docs/user-manual/ section 21.2 (so reversed double quotes).

**Comment by Cpt-xx** [comment]
@schacon Scott, if you would add the Dutch translation fork as progit-nl (and/or tell me what I need to do at my end to facilitate this) I would be grateful.

**Comment by schacon** [comment]
OK, I'll add this now. Also, the new smart quoting syntax is not supported by the version of Asciidoctor used by Atlas, so they won't render properly if you change them to the new syntax. I have to use compat-mode when I write.

**Comment by schacon** [comment]
- [ ] create the repository
- [ ] push to the repo
- [ ] create the language team
- [ ] add the maintainer(s) and repo
- [ ] add the git-scm.com entry
- [ ] add the progit.org entry
- [ ] add the web hook
- [ ] test the hook


The build hook is now also setup - every time you push to or merge into the master branch you should be able to check the progress and output of the build here:

https://progit.org/translations/lang/zh

**Comment by schacon** [comment]
done

**Comment by Cpt-xx** [comment]
Okay, thanks for creating it. Now for the following "dumb" questions:
- I've already read/translated the part with the tick-boxes (md-support in GitHub) so I see that you've created the task-list (for me I presume). I have already created a fork of the English repo, do I need to re-create a fork of the newly created Dutch version, or do I reset the ref from my local repo to this new dutch-subproject, or ... in other words: where would I push to?
- I don't have the project at hand at the moment, so I can't check, but where do I add the maintainers and repo? Where do I add the git-scm.com and progit.org entry? And the web hook? And how do I test the hook? Or is this the hook you are talking about having setup.

Again: sorry if these questions are showing some ignorance, my inexperience with GitHub and this process does this sometimes. :blush: :cry:

**Comment by Cpt-xx** [comment]
:+1:  I will see if I can get used to this flow :smiley:
