### ISSUE TITLE
checkout or clone?

### ISSUE THREAD

**Issue by jon-freed** [progit/progit2#226]
On this page:  http://git-scm.com/book/en/v2/Getting-Started-About-Version-Control

And in this sentence:  "Every checkout is really a full backup of all the data."

Shouldn't it be using the word "clone" instead of checkout?

**Comment by jon-freed** [comment]
"Clone", please.  

Yes, I am a git beginner.  And with my background -- and particularly with substantial Microsoft SharePoint usage in my history -- "check out" is more synonymous with "lock" than it is with "clone" or "copy".  So, yes, I think "clone" is more appropriate in these circumstances.

**Comment by ben** [comment]
Okay, I'm down. Want to submit a pull request that fixes this?

**Comment by schacon** [comment]
:+1:
