### ISSUE TITLE
Installing Git: asciidoc & xmlto

### ISSUE THREAD

**Issue by austerus** [progit/progit2#227]
Hello,

In the chapter "1.5 Getting Started - Installing Git" that describes compiling Git from the archive sources, the compile example tries to also create doc & info, which require packages "asciidoc", " docbook2x" and "xmlto" which aren't included in all distros.

I would suggest to add them to the apt-get install line.

Current line:

    apt-get install libcurl4-gnutls-dev libexpat1-dev gettext \
      libz-dev libssl-dev

Improved line:

    apt-get install libcurl4-gnutls-dev libexpat1-dev gettext \
      libz-dev libssl-dev asciidoc xmlto docbook2x

While these additions are not required to have a working git installation, they are needed to follow the installation procedure as-is.

Cheers!

**Comment by austerus** [comment]
Hi,

sorry for the late reaction, I've submitted the addition

**Comment by ben** [comment]
Nice, thanks!
