### ISSUE TITLE
-date option in the section 2.3 contains the unicode dash symbol

### ISSUE THREAD

**Issue by Vest** [progit/progit2#237]
Hello,

There is a minor error in the section 2.3 ([Git Basics - Viewing the Commit History](https://github.com/progit/progit2/blob/master/book/02-git-basics/sections/viewing-history.asc)). The line below

`%ad` | Author date (format respects the –date= option)
---------- | ------------

uses the "dash" symbol from the Unicode page, and a simple copy-paste operation in Windows detects it as an error. The correct syntax should be "--dash=option".

Kind regards,
Vest

**Comment by peterkokot** [comment]
Hello, I've opened pull request for you as noted above if that's ok.

**Comment by Vest** [comment]
Hi, the fix looks fine, but I would remove the space character between = and "option" as it is written in the help: --date=(...)

**Comment by peterkokot** [comment]
Ok, thanks. Space is removed.

**Comment by Vest** [comment]
Thanks, I am closing the bug.
