### ISSUE TITLE
progit.org/translations

### ISSUE THREAD

**Issue by petk** [progit/progit2#239]
I've found a typo most likely at progit.org/translations. Sentence:

```
Once that's been started, open an issue [here](https://progit.org/translations) with...
```

should be:

```
Once that's been started, open an issue [here](https://github.com/progit/progit2) with...
```

**Comment by YueLinHo** [comment]
![image](https://cloud.githubusercontent.com/assets/5831804/13772929/b626c5e6-ead1-11e5-861b-7a6cba9ab459.png)

new issue link: https://github.com/progit/progit2/issues/new

**Comment by ben** [comment]
This is actually fixed in the source code for progit.org, but it hasn't been deployed yet. @schacon, can you spare a minute?

**Comment by petk** [comment]
Ok, thanks for the feedback. Closing this then.
