### ISSUE TITLE
Probably a bug

### ISSUE THREAD

**Issue by prijutme4ty** [progit/progit2#241]
In Git Internals --> The Refspec section (https://github.com/progit/progit2/blob/master/book/10-git-internals/sections/refspec.asc) there is an odd text. I don't know git well enough to say it firmly, but it looks like a bug.

```
[remote "origin"]
url = https://github.com/schacon/simplegit-progit
fetch = +refs/heads/*:refs/remotes/origin/*

The format of the refspec is an optional +, followed by <src>:<dst>, where
<src> is the pattern for references on the remote side and <dst> is where
those references will be written locally. The + tells Git to update the reference
even if it isn’t a fast-forward.
```

If that's true, `refs/heads/` is a remote source and `refs/remotes/origin/` is a local destination, though their names say the opposite.

**Comment by ben** [comment]
No, that's correct. What it's saying is that, when fetching, everything (`*`) that lives in `refs/heads` on the remote will be copied to `refs/remotes/origin` in the local repository. Try it: do a `find .git/refs/remotes -type f` and a `git ls-remote`, and see how they compare.

**Comment by ben** [comment]
Going to close this for now, but feel free to ask more questions if you're still confused.

**Comment by prijutme4ty** [comment]
Thank you, @ben. Didn't thought that /ref/heads refer to remote server's pointer. Definitely need to reread other parts of the book. :)
