### ISSUE TITLE
Repository for Spanish (es) translation

### ISSUE THREAD

**Issue by andres-mancera** [progit/progit2#243]
Hi @ben & @schacon : 
I would like to work on the Spanish translation of this book and become a maintainer of the Spanish repo.  I noticed over at the [Pro Git Book page](https://github.com/progit) that a Spanish repository has not yet been created.  I also checked the [build status page](https://progit.org/translations) and I could not see any Spanish build, which makes me think that it is currently not getting built because there is no content.

Can you please create the Spanish repository so that I can fork it and start working on it?  Or how do you suggest I start working on this?  Please advise on how to proceed.

Cheers!

**Comment by jnavila** [comment]
Basically, you should fork the present project and start the translation in place. Most of the text is taken from version 1, so it is more a matter of translating the original Markdown syntax to the new asciidoc one, while still checking whether some texts have been corrected.

Then at some point, open an issue here so that your repo is transfered to the progit project.

All this is explained at https://progit.org/translations

**Comment by andres-mancera** [comment]
Thanks @jnavila .  I am closing this issue now and will open a new one once I get something going for the Spanish translation.

**Comment by andres-mancera** [comment]
Actually, I've got one more question for you:  Once I fork the project, should I create another branch and start working on it a we usually do in the normal Pull Request workflow?  Or I can just start working directly on the master branch since it will eventually become a new repository?  Please let me know.

**Comment by ben** [comment]
Just work on `master`. You can see this in the [French version's commit history](https://github.com/progit/progit2-fr/commits/master); most of the commits are from @schacon and I, and the most recent ones are converting the text into French.

**Comment by andres-mancera** [comment]
Cool, I will do that.  Thanks @ben

**Comment by andres-mancera** [comment]
Folks:  I have begun the Spanish translation of the book in my forked repository over [here](https://github.com/andres-mancera/progit2).  I have already translated and committed both the [README](https://github.com/andres-mancera/progit2/blob/master/README.asc) and the [TRANSLATION_NOTES](https://github.com/andres-mancera/progit2/blob/master/TRANSLATION_NOTES.asc) files.  These two should be enough to get things going and to start accepting contributions to the project.  Can you please transfer my repository to the progit2 proyect now?

I am an Spanish Language Coordinator at Coursera's [Global Translator Community](https://www.coursera.org/about/translate).  I'd like to pull some of the best translators from there so that they can give us a hand with the Spanish translation here.  :smiling_imp:

**Comment by andres-mancera** [comment]
FYI... Fully translated version of [01-introduction.asc](https://github.com/andres-mancera/progit2/blob/master/book/01-introduction/1-introduction.asc) and [about-version-control.asc](https://github.com/andres-mancera/progit2/blob/master/book/01-introduction/sections/about-version-control.asc) are now available in my [forked repository](https://github.com/andres-mancera/progit2).

**Comment by andres-mancera** [comment]
A very productive weekend!  I have finished the translation of the [first chapter](https://github.com/andres-mancera/progit2/tree/master/book/01-introduction).  A significant amount of work was taken directly from the version 1, but there were some sections where I had to re-write the whole thing. 

I have also updated the translation status in the [status.json](https://github.com/andres-mancera/progit2/blob/master/status.json) file as requested by you.  Do you guys think that my repository can now be transferred over to the progit2 project?  Let me know.

**Comment by schacon** [comment]
- [ ] create the repository
- [ ] push to the repo
- [ ] create the language team
- [ ] add the maintainer(s) and repo
- [ ] add the git-scm.com entry
- [ ] add the progit.org entry
- [ ] add the web hook
- [ ] test the hook

**Comment by schacon** [comment]
done

**Comment by andres-mancera** [comment]
Thanks!
