### ISSUE TITLE
superscript for exponentiation not visible

### ISSUE THREAD

**Issue by VynceMontgomery** [progit/progit2#244]
at http://git-scm.com/book/en/v2/Git-Tools-Revision-Selection

e.g., 2^80 is written as 2&lt;sup&gt;80&lt;/sup&gt;, but the stylesheet renders &lt;sup&gt; as plain text, so instead of 2<sup>80</sup> it looks like 280. I'm not sure whether the best approach is to use a more semantic markup, or to change the stylesheet used so that superscript is actually rendered as a superscript, or what, but it makes the sidebar about how many commits are needed before a likely conflict quite confusing; in particular, it appears to claim that there's a 50% chance after only 280 commits.

**Comment by jnavila** [comment]
It is a matter of CSS. The PDF is OK. Please report to git /git-scm.com .
