### ISSUE TITLE
Turkish Translation (tr)

### ISSUE THREAD

**Issue by gokaygurcan** [progit/progit2#247]
Hi, 
I'd like to contribute by translating the book to Turkish. 
I already checked the old repository and found the first five chapters' translations (with small errors and/or differences). And also checked [translations](https://progit.org/translations) page and couldn't find _tr_ translations there. I just [forked](https://github.com/gokaygurcan/progit2) the repository and I'm going to re-apply translated parts first and then edit if necessary. 
Thanks in advance.

**Comment by schacon** [comment]
Awesome, thanks!

**Comment by schacon** [comment]
- [ ] create the repository
- [ ] push to the repo
- [ ] create the language team
- [ ] add the maintainer(s) and repo
- [ ] add the git-scm.com entry
- [ ] add the progit.org entry
- [ ] add the web hook
- [ ] test the hook

**Comment by schacon** [comment]
done.

**Comment by gokaygurcan** [comment]
Thanks a lot. ^_^
