### ISSUE TITLE
Ch 3.6 on website, All Figure links broken

### ISSUE THREAD

**Issue by Rajat-Agrawal** [progit/progit2#253]
http://git-scm.com/book/en/v2/Git-Branching-Rebasing

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:24.0) Gecko/20100101 Firefox/24.0
E.g. The figure ref for Fig 3-31 is http://git-scm.com/book/en/v2/ch00/rbdiag_e instead of http://git-scm.com/book/en/v2/Git-Branching-Rebasing#rbdiag_e

Similar problem with all Figure links on the page.

[EDIT] I believe the problem is with all figure links in all chapters.

**Comment by jnavila** [comment]
This is an issue with the git-scm.com project, not with progit2. Please report to git/git-scm.com
