### ISSUE TITLE
Incorrect Graph $3.1 Divergent history

### ISSUE THREAD

**Issue by qizhang1** [progit/progit2#257]
* c2b9e (HEAD, master) made other changes
| * 87ab2 (testing) made a change
|/

HEAD and master should both pointing at commit obj c2b9e, Testing branch is at 87ab2. Your diagram above switched the pointers.

**Comment by filipegoncalves** [comment]
Yep, I can confirm this. I was reading section 3.1 and noticed that as well.

It's the figure captioned "Divergent history". The commit hashes for `testing` and `master` are switched.

**Comment by YueLinHo** [comment]
Duplicate #136
