### ISSUE TITLE
I'm not able to change font face in Kindle Paperwhite.

### ISSUE THREAD

**Issue by tiagox** [progit/progit2#259]
Hello,

I've just downloaded the .mobi from http://git-scm.com/book/en/v2. When I open that book in my Kindle Paperwhite, the text is being displayed as Helvetica, no matter what font face I'm choosing in my reader. It's like the style of the text is hard-coded.

Thanks in advance.

**Comment by HonkingGoose** [comment]
This issue seems related: https://github.com/progit/progit2/issues/410

**Comment by jnavila** [comment]
I'm not even sure this is still relevant. At the time the issue was opened, the ebooks were generated by O'reilly's edition workflow, whereas they are now produced with asciidoctor.

**Comment by pbodnar** [comment]
Yes, I would propose to close this issue.

My Kindle PW 3 (2015; with the latest December 2019 software update) displays fonts just fine and I can switch to whatever font is offered in the "PAGE DISPLAY -> Font & Page Settings" dialog.
