### ISSUE TITLE
German translation (de)

### ISSUE THREAD

**Issue by fernsehkind** [progit/progit2#261]
Hi,

I'd like to contribute by translating the book to german. I already helped translating the first edition. I created a repo at https://github.com/progit-de/progit2.git.

The first edition is translated almost completely into german but there are many issues in this translation: Different chapters use formal or informal communication or technical Git terms are sometimes translated and sometimes the english term is used. I would like to standardize that and use the same terms as the executable git uses. 

What I did so far:
- Created the repository
- Translated CONTRIBUTING.md, README.asc, TRANSLATION_NOTES.asc
- Adapted status.json

What do you need to setup progit/progit2-de ?

Thanks in advance.

**Comment by mkloeckner** [comment]
Hi, @schacon.

I'm also interested in the german translation of progit/progit2 to german and would like to contribute.

Could you create a repo progit/progit2-de based on the forked repository of @fernsehkind (https://github.com/progit-de/progit2.git )?

Do you need additional information?

**Comment by Sternenstauner** [comment]
Hi,
I would like to contribute to the german translation of progit/progit2 too. Could you please create a repo progit/progit2-de based on the forked repository of @fernsehkind (https://github.com/progit-de/progit2.git )? Thanks!

**Comment by nullinger** [comment]
I’d also like to see progit/progit2-de :+1:

**Comment by jnavila** [comment]
The scripts for publishing translations of progit2 were changed to allow direct access from github repos. So, if you still wish to have your translation published on git-scm.com (no pdf or ebooks yet), please create an organization progit2-de, transfer the repo in it and ask for an addition to the generation.

**Comment by techMod** [comment]
Hi everybody!
if you want to, you can clone my repository of progit2-de and contribute to it. Unfortunately we will have to start over anew, but I think it is worth the hasle and manageable.

Just fork github.com/techmod/progit2-de

**Comment by jnavila** [comment]
@techMod  @fernsehkind has already created the progit-de organization. Ask to join it and have the rights to push to the progit repo. 

@fernsehkind is progit-de/progit2 ready?

**Comment by techMod** [comment]
Hi @fernsehkind, please allow write access to your repo so i can contribute thanks

**Comment by fernsehkind** [comment]
Hi @techMod and @jnavila . Sorry for the late response. I'm a little bit too busy for progit at the moment. The progit-de/progit2 is very old and not up to date. So maybe @techMod can fix that. You have now write access to the progit-de/progit2 repository.

**Comment by jnavila** [comment]
Done :wink:
