### ISSUE TITLE
Uzbek translation (uz)

### ISSUE THREAD

**Issue by faxriddin** [progit/progit2#262]
Can I upgrade my repo ( https://github.com/faxriddin/progit2 ) to official git?

**Comment by schacon** [comment]
OK, the https://github.com/progit/progit2-uz repo is now setup and you've been invited as a team member with write access.

The build hook is now also setup - every time you push to or merge into the master branch you should be able to check the progress and output of the build here:

https://progit.org/translations/lang/uz

**Comment by jnavila** [comment]
How do write Uzbek in Uzbek, so that I add it to git-scm site?

**Comment by faxriddin** [comment]
Ok.

**Comment by jnavila** [comment]
Sorry for not being clear. Can you provide me with the term for Uzbek language in Uzbek language? As an example, "French" is "Français". Thanks.

**Comment by faxriddin** [comment]
Uzbek in Ўзбек

**Comment by jnavila** [comment]
Thanks. I am pushing a patch to git-scm.

@schacon , http://git-scm.com/book/uz/v2 does not seem to show the pages? Is there some other thing needed?

**Comment by faxriddin** [comment]
May be I  missed. What is it thing? Can you help me?

**Comment by jnavila** [comment]
The pages have been updated. You can check them at http://git-scm.com/book/uz/v2

I opened a pull request for inclusion of Uzbek to the site at git/git-scm.com#514

So everything is on track for completion. You can go ahead and continue the translation.

Best regards

**Comment by faxriddin** [comment]
Why did not chapter "Introduction"  open? What can I doing that  chapter "Introduction" will open in http://git-scm.com/book/uz/v2 page?

**Comment by faxriddin** [comment]
I understood you. Thank you. I will wait.
