### ISSUE TITLE
Brazilian Portuguese translation [pt-br]

### ISSUE THREAD

**Issue by deniscostadsc** [progit/progit2#265]
I'm starting now to translate progit2 to Brazilian Portuguese.

I've already forked the repository at https://github.com/deniscostadsc/progit2.

The translation is in the beginning, but I going to work on this.

I want to know if is possible replicate the repo to progit organization profile as soon as possible or should I translate some chapters before?

Thanx

**Comment by rogeriopradoj** [comment]
@deniscostadsc are you going to be the maintainer for pt-br?

If yes, I have some parts translated that I'd like to sent Pull Requests.

@progit & @schacon & @jnavila, : If @deniscostadsc says it's going to be the maintainer, I'd like to be a "backup maintainer" for it. I'm involved in various translation of technical projects in Brazil (even maintainer in some of them), but can candidate for one more. Anyway, I'd like to support @deniscostadsc on this.

Could you open the progit/progit2-pt-br?

**Comment by jnavila** [comment]
Unfortunately, I cannot upgrade switch repos to progit. Please add some more translated content (a few sections) and hopefully Scott will convert it.

**Comment by deniscostadsc** [comment]
@rogeriopradoj I can be the maintainer.

@jnavila I'll translate more chapters.

**Comment by rogeriopradoj** [comment]
Thanks for the info, @jnavila .

Awesome, @deniscostadsc , I see you on https://github.com/deniscostadsc/progit2 !

See ya!

**Comment by andregirol** [comment]
Hello @deniscostadsc and @rogeriopradoj may I help you with the translation?

See ya'll

**Comment by deniscostadsc** [comment]
Of course! Just pull request your changes.

**Comment by andregirol** [comment]
I will fork you repository then :+1:

**Comment by lukBarros** [comment]
Hi Mans! How into in tranlate project pt-br? Thanks!

**Comment by jnavila** [comment]
Now the book can more easily be published on git-scm.com. If you wish so, please create an organization progit2-pt-br and move your translation repo to it. Then, I will update the git-scm repo to pull from your organization's repo.

**Comment by rogeriopradoj** [comment]
@jnavila done: https://github.com/progit2-pt-br/progit2. I've already put together all the translations I found in another splited repos, and will start to ask for help in Brazilian community! Thanks for letting us know.

For possible maintainers, please get in touch in order to make that organization more open, ok?

See ya!

**Comment by jnavila** [comment]
The book does not compile.

**Comment by rogeriopradoj** [comment]
@jnavila I'll take a look as soon as possible to inspect this. Thanks for letting us know.

**Comment by rogeriopradoj** [comment]
Hi, @jnavila , I found the problem: some of the files are encoded as `us-ascii` instead of `utf-8`.

I'm solving that, I'll let you know when it's done again, right?

Thanks a lot!

**Comment by rogeriopradoj** [comment]
Hi, @jnavila , any news on this?

See ya!

**Comment by jnavila** [comment]
You are now online! The second edition is not fully translated, but the link for full translations was kept.

You just need to push to master on your repo and the new page is built every day.

https://git-scm.com/book/pt-br/v2
