### ISSUE TITLE
Small correction in chap. 10 section "Transfer protocols"

### ISSUE THREAD

**Issue by fabienhinault** [progit/progit2#266]
In subsection "The Smart Protocol / Downloading Data / SSH", it is writen:
"If you're doing the fetch over SSH, `fetch-pack` instead runs something like this:"
I think the "instead" was there when some sentences were written above in version 1, but should disappear now.

**Comment by ben** [comment]
Actually, looking at it, it seems like I meant to write it that way, but I can see how it might not flow well for a non-native English reader. Which of these seems best to you?

* If you're doing the fetch over SSH, `fetch-pack` will instead run something like this:
* If you're doing the fetch over SSH, `fetch-pack` runs something like this instead:
* If you're doing the fetch over SSH, `fetch-pack` runs something like this:

**Comment by daftano** [comment]
To me the best seems to be the third.
The first could be. Would definitely avoid the second.

My two cents.

**Comment by ben** [comment]
Done!

**Comment by fabienhinault** [comment]
Perfect! Sorry to be so unreactive.
