### ISSUE TITLE
Traditional Chinese translation [zh-tw]

### ISSUE THREAD

**Issue by taichunmin** [progit/progit2#267]
Hello,

I'd like to start translate progit2 to traditional chinese version. 

My forked repo url is <https://github.com/taichunmin/progit2>. 

The translation is in the beginning.

May I have a Traditional Chinese translation repo in progit organization? Maybe `progit/progit2-zh-tw`.

**Comment by PeterDaveHello** [comment]
:+1: 
Any updates?

**Comment by taichunmin** [comment]
@PeterDaveHello: I still work on it.

**Comment by PeterDaveHello** [comment]
I think progit can open a repo for it first.

**Comment by taichunmin** [comment]
I don't know how to ask @progit for a progit2 repo.

**Comment by PeterDaveHello** [comment]
Let's mention @schacon, would you please open an repo for us? Thanks!

**Comment by fntsrlike** [comment]
Cool, expect it! 

@schacon & @jnavila: 
May we have `progit/progit2-zh-tw` repository? 
The repository `progit/progit2-zh` is `Simple Chinese` translation, but we wanna maintain `Traditional Chinese` version, they are different not only words but also proper noun. It is helpful if there have a `Traditional Chinese` version for people learning about git .

Thank you so much. =)

**Comment by jnavila** [comment]
Hello,

Unfortunately, I cannot upgrade repos to progit. We have to wait for Scott on this one.

**Comment by schacon** [comment]
Sorry, I'll work on that right now.

**Comment by schacon** [comment]
Done.

**Comment by taichunmin** [comment]
Hello @schacon .
May I become a collaborator of this repo?

I don't have push permission right now.
I will continue working on this repo and delete old taichunmin/progit2.

**Comment by schacon** [comment]
You need to check your email - I sent you an invite to the team that has write permissions to this repository.

**Comment by taichunmin** [comment]
I'm in, thanks!

**Comment by PeterDaveHello** [comment]
May I join it?

**Comment by fntsrlike** [comment]
@PeterDaveHello  You may ask @schacon. I think @taichunmin have no permission to add member?

**Comment by taichunmin** [comment]
I have only write permission.
Maybe ask @schacon for a permission?

**Comment by taichunmin** [comment]
Hello, @schacon.

May I change the translation name from Chinese Traditional to 繁體中文 on https://progit.org/translations ?

**Comment by taichunmin** [comment]
Thanks @schacon .
