### ISSUE TITLE
404 in chapter 4

### ISSUE THREAD

**Issue by amaiorano** [progit/progit2#270]
Following this commit: https://github.com/progit/progit2/commit/074ccb0c08c64b0cdb5142da200b6c82ebf8d4c6

It looks like the asc file got updated in the online version of the book, but not the png...

We get a 404 on: http://git-scm.com/book/en/v2/book/05-distributed-git/images/centralized_workflow.png

But this still works: http://git-scm.com/book/en/v2/book/05-distributed-git/images/centralized.png

You can see the image missing on the page here: http://git-scm.com/book/ch5-1.html

**Comment by jnavila** [comment]
We are aware of this issue. This commit was an attempt to fix a problem of name clashes. The referred picture 
https://github.com/progit/progit2/blob/master/book/05-distributed-git/images/centralized_workflow.png

was overriding another one:

https://github.com/progit/progit2/blob/master/book/01-introduction/images/centralized.png

You can see that it works properly in the pdf book. Sadly, the git-scm.com site does not seem to update the resources correctly. This is mainly an issue with git /git-scm.com project.

**Comment by amaiorano** [comment]
Ah sorry! Didn't realize git-scm.com was a separate project. Thanks.

**Comment by rybak** [comment]
git-scm links to this repository on github, so is it even possible to fix this?
