### ISSUE TITLE
Automatic builds failure

### ISSUE THREAD

**Issue by harupong** [progit/progit2#271]
Automatic builds by Atlas have been failing for a couple of months on a few languages:

- French https://progit.org/translations/lang/fr cc @jnavila 
- Italian https://progit.org/translations/lang/it cc @daftano
- Japanese https://progit.org/translations/lang/ja

@schacon @ben Could you check on the build log to see what's causing the build failure? The funny thing is, automatic builds for others(including English) have been working just fine. There might be something specific to those languages listed above.

**Comment by jnavila** [comment]
The less funny thing is that we don't have any clue about the source of the failures. Is a compilation log available anywhere?

**Comment by schacon** [comment]
Sorry - I need to add this feedback to the UI, I'm pretty sure I can get the failure logs via the API. For now though I checked it manually and it was 91d4ecee244945afdffb3fac32ddefffe6f5b5bf, which added files to the atlas.json that don't exist. Does this not break the manual build too?

**Comment by jnavila** [comment]
I have an issue with pygments.rb but the pdf is generated without visible errors.

**Comment by schacon** [comment]
OK, FR is fixed (content error) and IT is fixed (not sure, but kicking off the last hook again seems to build fine). JA is still busted with an "invalid byte sequence" error, but I have to reach out to Atlas to figure out what it might be. Probably a file was saved in the wrong encoding.

**Comment by harupong** [comment]
Thank you @jnavila and @schacon for looking into this. JA is fixed as well,  with progit/progit2-ja#51 :tada:
