### ISSUE TITLE
404 on "Centralized workflow." image in 5.1 Distributed Git - Distributed Workflows

### ISSUE THREAD

**Issue by jnareb** [progit/progit2#281]
The "Centralized workflow" image with URL http://git-scm.com/book/en/v2/book/05-distributed-git/images/centralized_workflow.png does not exist in [Chapter 5.1 Distributed Git - Distributed Workflows](http://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows)

**Comment by ben** [comment]
We know. :disappointed:  See #250, a fix was merged (but apparently not deployed) in https://github.com/git/git-scm.com/pull/505.
