### ISSUE TITLE
Overlap

### ISSUE THREAD

**Issue by YueLinHo** [progit/progit2#285]
![word_overlap](https://cloud.githubusercontent.com/assets/5831804/7131755/664c11c2-e2b5-11e4-8628-8cd3eed2e1d4.png)

screenshot is captured from http://git-scm.com/book/en/v2/Git-Branching-Remote-Branches

**Comment by Spartan-196** [comment]
Currently I do not see this behavior in IE, Chrome, or Firefox. I also do not see it present in the epub or PDF versions of the book. This may already be resolved.

**Comment by ben** [comment]
Yeah, since this isn't really an issue with any of the code in this repo, I'm going to close it. If you see anything like this again, feel free to post a bug over at [git/git-scm.com](https://github.com/git/git-scm.com).
