### ISSUE TITLE
Section 3.2: Wrong commit number in final image for merging

### ISSUE THREAD

**Issue by sambou** [progit/progit2#286]
In the final image there seems to be a mistake: the commit history shows the final merge commit as c5, which is the same name/id as the last commit of the iss53 branch. Shouldn't it be c6 in order to indicate that this is a unique (merge) commit?

Image attached for clarity:
![](http://git-scm.com/book/en/v2/book/03-git-branching/images/basic-merging-2.png)

**Comment by bobbingwide** [comment]
In the physical book, page 55, figure 3-17. 'A merge commit', the diagram is exactly the same as figure 3-16. I think it should be the one mentioned here, with the fix applied.

**Comment by Tibo75** [comment]
In the PDF version, the wrong C5 (merge commit) has been corrected to C6.

It should be also fixed on web documentation (https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) where C5 is still shown as in sambou's snapshot.

**Comment by YueLinHo** [comment]
It has been fixed in commit 3491527 by @ben on 2014-11-25, but git-scm still has some problem on it.

**Comment by YueLinHo** [comment]
@jnavila Should not we keep this issue opened to remind us git-scm has problem?

**Comment by jnavila** [comment]
I think we have enough reminders that the git-scm site is broken :laughing:

**Comment by YueLinHo** [comment]
OK. :smile:
