### ISSUE TITLE
Figure references broken

### ISSUE THREAD

**Issue by peterjacobson** [progit/progit2#291]
![Screenshot of a page in the book with a figure, and a link to the figure embedded in the paragraph below](https://cloud.githubusercontent.com/assets/5624277/5893133/8fc71f82-a4fe-11e4-865e-068018019c63.png)

As per [issue #502 in the git-scm.com repo](https://github.com/git/git-scm.com/issues/502), there are two current issues:

1. Clicking on the link to a figure throws a 500 error

2. The image captions do not include the figure number.

With both of these issues, it can be very hard to understand some of the discussion, such as in [this Rebasing section](http://git-scm.com/book/en/v2/Git-Branching-Rebasing#Rebase-When-You-Rebase)

I think that resolving either one of these issues would be useful. I had a look into making a patch, but couldn't understand the how the images/captions/links are pulled together into the final html.

**Comment by jnavila** [comment]
Fixed
