### ISSUE TITLE
tilde (~) should be escaped before running LaTeX

### ISSUE THREAD

**Issue by xinmeng** [progit/progit2#293]
In PDF version of __Pro Git__ (July 29, 2009), page 142. "The other main ancestry specification is the ~." Tilde character in LaTeX will be converted to a white space, so there is nothing printed in PDF, which is a little confusing.

**Comment by jnavila** [comment]
The PDF of the latest edition of the book isn't produced with LaTeX, so the problem should be solved.

**Comment by ben** [comment]
Confirmed. The [latest PDF build](https://progit2.s3.amazonaws.com/en/2015-04-22-540e8/progit-en.457.pdf) shows the `~` character properly on page 258. @xinmeng, it seems like you're referring to the first edition of the book.
