### ISSUE TITLE
section 5.1: centralized workflow diagram missing

### ISSUE THREAD

**Issue by pennello** [progit/progit2#294]
The centralized workflow diagram in section 5.1 looks like it's 404ing.  I'm not sure if this is the right place to report this, but I thought somebody should be made aware.

![Screenshot of missing diagram](http://i.imgur.com/XdN3n8a.png)

    curl -LI http://git-scm.org/book/en/v2/book/05-distributed-git/images/centralized_workflow.png
    HTTP/1.1 301 Moved Permanently
    Server: Varnish
    Location: http://git-scm.com//book/en/v2/book/05-distributed-git/images/centralized_workflow.png
    Content-Type: text/html; charset=utf-8
    Content-Length: 315
    Accept-Ranges: bytes
    Date: Thu, 30 Apr 2015 21:32:18 GMT
    Via: 1.1 varnish
    Connection: close
    Age: 0
    
    HTTP/1.1 404 Not Found
    Server: Cowboy
    Connection: keep-alive
    Date: Thu, 30 Apr 2015 21:32:22 GMT
    Status: 404 Not Found
    Content-Type: text/html; charset=utf-8
    Content-Length: 1235
    X-Request-Id: 792f375a-b5c5-4179-a098-2f852972338b
    X-Runtime: 0.070343
    Via: 1.1 vegur

**Comment by ben** [comment]
Yup. :grin: #250 introduced this, and it was supposed to have been fixed in https://github.com/git/git-scm.com/pull/505, but apparently there's a deployment problem. I'll ping that issue again.

**Comment by pennello** [comment]
Cool, thanks Ben.

**Comment by ben** [comment]
No problem. thanks for reporting!
