### ISSUE TITLE
How often is http://git-scm.com/ updated

### ISSUE THREAD

**Issue by jarl-dk** [progit/progit2#296]
Please write a note in the README file about how often http://git-scm.com/ is updated.

I see a commit (https://github.com/progit/progit2/commit/06ea626340ea8a896b58e461320dd1ceec58fde6) from 2. march and is still not shown on http://git-scm.com/

Jarl

**Comment by jnavila** [comment]
Well, the publishing process is hooked to the O'Reilly Atlas publishing service and it seems that Atlas is frozen.

**Comment by HonkingGoose** [comment]
@ben I think this can be closed? I think nowadays you merge any pull-request straight into ```master``` and then run a new build to update the webpage?

**Comment by jnavila** [comment]
:checkered_flag:
