### ISSUE TITLE
A2.3 shows wrong code to create a repository in JGit

### ISSUE THREAD

**Issue by rherrmann** [progit/progit2#297]
The chapter _A2.3 Embedding Git in your Applications - JGit_ shows this snippet
```java
// Create a new repository; the path must exist
Repository newlyCreatedRepo = FileRepositoryBuilder.create(
    new File("/tmp/new_repo/.git"));
```
to create a new repository.

Adding the line `newlyCreatedRepo.create()` will actually create a repository (like `git init /path/to/repo` would). Without that, the code creates a JGit Repository instance that points to the given directory.

In addition the note _the path must exist_ is not neccesary, because `create()` will create missing path segments.

I suggest to change the snippet to 
```java
// Create a new repository
Repository newlyCreatedRepo = FileRepositoryBuilder.create(
    new File("/tmp/new_repo/.git"));
newlyCreatedRepo.create();
```

**Comment by ben** [comment]
Hey, nice catch. Want to fix it? Just hit the "edit" button on [the file](https://github.com/progit/progit2/blob/master/book/B-embedding-git/sections/jgit.asc), and submit a pull request.

**Comment by rherrmann** [comment]
I've opened [this pull request](https://github.com/progit/progit2/pull/300) for review.
