### ISSUE TITLE
Image missing in chapter 1.1 Getting Started - About Version Control, section Centralized Version Control Systems 

### ISSUE THREAD

**Issue by christianbalzer** [progit/progit2#298]
The image in the following section is missing (the resource at the URL provided, http://git-scm.com/book/en/v2/book/01-introduction/images/centralized.png, can't be found; error 404 is returned): http://git-scm.com/book/en/v2/Getting-Started-About-Version-Control#Centralized-Version-Control-Systems

**Comment by ben** [comment]
Yup. :grin: #250 introduced this, and it was supposed to have been fixed in https://github.com/git/git-scm.com/pull/505, but apparently there's a deployment problem.
