### ISSUE TITLE
Ukrainian translation (ua)

### ISSUE THREAD

**Issue by greatehop** [progit/progit2#304]
I've started with Ukrainian translation of progit. Here is my fork of progit2 repo:
https://github.com/greatehop/progit2

**Comment by greatehop** [comment]
What do you need to set up progit/progit2-ua ?
Thanks.

**Comment by jnavila** [comment]
1. Add a few more translated sections 
2. Summon @schacon and wait for the magic to happen :laughing:

**Comment by tbudurovych** [comment]
@greatehop - I've forked https://github.com/greatehop/progit2 and will help translating too.

**Comment by tbudurovych** [comment]
Thanks for merging my PRs @greatehop, I hope we are closer now to get a repo.

**Comment by tbudurovych** [comment]
@schacon, @jnavila - it's three of us now that started translating concurrently and found about this issue :) 

@greatehop, @hedrok  and me. I hope there are no more doing ~~double~~ triple work. So just friendly asking how many "more translated sections" are a criteria to get an official repo?

**Comment by jnavila** [comment]
Sadly, I can't do much about that.

**Comment by hedrok** [comment]
Ok, we are translating and hoping :)
Thanks for your time.

**Comment by greatehop** [comment]
Hi. How do you pick name for repository, by country domain name (UA) or by https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes (UK) ?

**Comment by tbudurovych** [comment]
I'm thinking more of "uk" as ISO code says. I think that's the practice with other language repos.
/cc @schacon, @jnavila

**Comment by jnavila** [comment]
In progit first edition, the usage was to take the ISO code. On git-scm, we use the ISO code. And anyway, if we have to deal with local flavours of a language, only ISO can deal with it.

**Comment by tbudurovych** [comment]
@schacon, @jnavila - we have so much more translated in https://github.com/greatehop/progit2
please have a look

**Comment by schacon** [comment]
Super sorry I didn't get to this. This is all set up now.  You can find the repo at https://github.com/progit/progit2-uk and once the first build is done you can read it online at: http://git-scm.com/book/uk/v2

You can also check on build status after every push to the master branch here:

https://progit.org/translations/lang/uk

**Comment by tbudurovych** [comment]
Super thanks
