### ISSUE TITLE
Translation for trade publication

### ISSUE THREAD

**Issue by lukBarros** [progit/progit2#305]
Hello I'm want to translate it into Portuguese, giving a fork in private repository, then return in the form of pull requests my translations for protugues of Brazil en-US.

I would seaber, if I publish in a printed book publisher via my country, to be sold in shops and traditional and online bookstores, getting profit from this, both for me and for the publisher, in which case, I would that profit have some percentage rate for the original book creators in the form of royalties. Thus it seems fair for everyone.

What reflection of core supporters about this?

**Comment by jnavila** [comment]
The license forbids commercial usage. See https://github.com/progit/progit2/blob/master/LICENSE.asc

**Comment by lukBarros** [comment]
ok, thanks!
