### ISSUE TITLE
/srv/git instead of /opt/git for server repositories

### ISSUE THREAD

**Issue by donpellegrino** [progit/progit2#312]
Section, "4.2 Git on the Server - Getting Git on a Server" uses /opt/git as the example location for putting repositories on a Linux server. Based on hier(7) it seems that /srv/git would be more consistent with filesystem conventions.

**Comment by ben** [comment]
:+1: Want to submit a PR?

**Comment by johnhar** [comment]
The subsequent sections continue to use /opt/git for building a Git server.  What is the correct one to use?

**Comment by ben** [comment]
Ooh, good catch. Reopening this. Any chance you'd want to submit a PR to fix it?

**Comment by johnhar** [comment]
I'm a real newbie to GitHub, but I'd be willing to try. So is the correct location /srv/git or is it /opt/git?

**Comment by ben** [comment]
From the original author of this issue, it sounds like `/srv` is more idiomatic.

**Comment by jnavila** [comment]
`/opt` is really not the right place to put working data. It is meant to be the place for installing optional or external applications.

for data, the choice is usually either `/var` (historically) or `/srv` which has been advocated by the Linux Standard Base, but is very slowly adopted by distribution integrators. I don't know if it makes sense to stress on this linux peculiarity.
