### ISSUE TITLE
Pro Git book picture error

### ISSUE THREAD

**Issue by warriorkitty** [progit/progit2#315]
Hi all,

I don't know if I'm at the right place but I'm reading the book Pro Git book online and the chapter:

Centralized Version Control Systems (https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control#Centralized-Version-Control-Systems) doesn't show the picture "Centralized version control diagram".

**Comment by randomecho** [comment]
Related: #294 which is related to git/git-scm.com#505

**Comment by YueLinHo** [comment]
Dulicate #294. And that figure shows now.

**Comment by YueLinHo** [comment]
@ben I think this issue can be closed!
