### ISSUE TITLE
I want to be a collaborator for progit2-zh

### ISSUE THREAD

**Issue by networm** [progit/progit2#316]
I have translated about 21 sections to Simplified Chinese. You could look it at [Commits · networm/progit2-zh](https://github.com/networm/progit2-zh/commits/first-translation)
And I have worked and continued as a full time job on translating until it's complete.
But I also want to help others involving translating these, manage assigner and update assigner status. So please add me to progit2-zh collaborator team.

**Comment by networm** [comment]
@schacon @ben Could you help me?

**Comment by ben** [comment]
Found https://github.com/progit/progit2-zh/issues/69, seems like you're welcome there. Check your email for the invitation, and sorry for the delay!

**Comment by networm** [comment]
@ben Thank you very much!
