### ISSUE TITLE
change file extension from ".asc" to ".adoc"

### ISSUE THREAD

**Issue by zaxebo1** [progit/progit2#325]
**As per asciidoc recommended practices** at url  http://asciidoctor.org/docs/asciidoc-recommended-practices/   : 

"" AsciiDoc doesn’t care which extension you use. GitHub supports the extensions .asciidoc, .adoc and .asc.   **Recommend against using the .asc extension. it gets identified as a PGP file on Linux** ""

---

NOW,
Literally on ubuntu if we click on few ".asc" files of your book source , like clicking on progit2-master/book/02-git-basics/1-git-basics.asc  gives an error related "no application installed for PGP/MIME-encrypted message header". Though we may associate .asc files to gedit, **but it will better if you rename all your file extensions from *.asc to *.adoc" as per recomemndation of best practices on asciidoctor home page**

**Comment by HonkingGoose** [comment]
Hi @ben, do you want a pull-request from me that converts all ```.asc``` to ```.adoc```? That would be a major rewrite, so I won't start doing things until I get the go-ahead. It would touch pretty much the whole project, there are a lot of mentions of ```.asc``` in ```progit2/master``` (Currently 230 matches for the string ```.asc``` across 20 files.) Also all ```.asc``` files would need to be renamed to end on ```.adoc```.

The current version of [Asciidoctor best practices](https://asciidoctor.org/docs/asciidoc-recommended-practices/) states:
>.adoc seems to be the most often used extension and the one we prefer. It does not conflict with other well known applications, is distinct, and not excessively long (like .asciidoc). It also reads as “a doc”. Our recommendation, therefore, is to use .adoc.

And also:
>We strongly recommend against using the .asc extension. The connection to AsciiDoc isn’t immediately obvious and it gets falsely identified as a PGP file on Linux.

**Comment by jnavila** [comment]
Be careful that:

- There are translations which won't follow this move
- The git-scm.com scripts expect files in .asc. Moving here needs to be synchronised with changing the scripts on git-scm.com

**Comment by HonkingGoose** [comment]
Thanks for the warnings! :smile: 

Given the warning signs, is this still something we want to fix, or does the project prefer to leave it as-is? It will at least require coordinating with the git-scm side of things, because they would need to change things on their end too (scripts on git-scm.com).

Good thing I asked around, before starting anything... :+1:

**Comment by jnavila** [comment]
I'd let it as it is now. It's working, the README is advertising that it is asciidoc and there are too many ties with related projects. The `.adoc` suffix is a preferred suffix, but with no specific use case for requiring to be enforced.
