### ISSUE TITLE
diagram in section 5.1 is 404-ing

### ISSUE THREAD

**Issue by tycho** [progit/progit2#335]
The "centralized workflow" diagram on http://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows is 404-ing:

http://git-scm.com/book/en/v2/book/05-distributed-git/images/centralized_workflow.png

**Comment by ben** [comment]
Yup. :grin: #250 introduced this, and it was supposed to have been fixed in https://github.com/git/git-scm.com/pull/505, but apparently there's a deployment problem.
