### ISSUE TITLE
Slight Mistake in 'git status' Output

### ISSUE THREAD

**Issue by nobozo** [progit/progit2#338]
In "recording-changes.asc" it says:

"Let’s say you edit and stage the README file again and then edit the CONTRIBUTING.md file without staging it. If you run your git status command, you once again see something like this:"

But, the 'git status' output shows README as a "new file". Shouldn't this be "modified" since README is not a new file?

**Comment by ben** [comment]
Yeah, you're right. :blush: Want to fix it? :wink:

**Comment by ben** [comment]
Fixed in #347.
