### ISSUE TITLE
An Incorrect Reference to 'git status' Output

### ISSUE THREAD

**Issue by nobozo** [progit/progit2#340]
In recording-changes.asc it says removing a file causes output in the "Changed but not updated" area of the 'git status' command. There is no such section. It's actually "Changes not staged for commit", as the example under this statement shows.

**Comment by ben** [comment]
Oooh, nice catch. Want to open a PR? It'd be nice if you got credit in the commit log.

**Comment by ben** [comment]
Fixed in #347.
