### ISSUE TITLE
Hard copy page vii chapter 1: Gettingg Started

### ISSUE THREAD

**Issue by bobbingwide** [progit/progit2#342]
Too many g's in Getting

**Comment by YueLinHo** [comment]
What does "g's" mean? this?
```
$ git help &lt;verb&gt;
$ git &lt;verb&gt; --help
$ man git-&lt;verb&gt;
```

**Comment by bobbingwide** [comment]
See the title of the issue: Gettingg started.

**Comment by ben** [comment]
Unfortunately we can't ship a patch to the dead-tree books. This appears to be fixed in the electronic versions, though.

**Comment by YueLinHo** [comment]
Now, I see. Double `g` in word `Gettingg`.
