### ISSUE TITLE
Perforce to Git migration example is not correct

### ISSUE THREAD

**Issue by RomanTsegelskyi** [progit/progit2#349]
I was trying to follow the example of migrating `perforce` repo to `git`, but it seems that links in the book are not correct. 

```
{ f }  » P4PORT=public.perforce.com:1666
{ f }  » git p4 clone //guest/perforce_software/jam@all p4import
Importing from //guest/perforce_software/jam@all into p4import
Reinitialized existing Git repository in /cygdrive/f/p4import/.git/
//guest/perforce_software/jam/... - must refer to client 'romants-main'.
Command failed: ['p4', 'changes', '//guest/perforce_software/jam/...']
```

When I try to simply clone that repo using `p4 clone`, I still get an error

```
{ f }  » p4 clone -p public.perforce.com:1666 -r //guest/perforce_software/jam@all                                 TCP receive failed.
read: socket: WSAECONNRESET
```

Is it possible that links provided are not correct? Or what am I doing wrong?

**Comment by gsajwan** [comment]
open git bash where you want to clone
p4 login
set P4CLIENT=MOBILE_export_b2b_mobile_ios_ws   # perfoce workspace you want to copy
git p4 clone  --use-client-spec //MOBILE/@all    #path to depo u want to clone

**Comment by gsajwan** [comment]
error u getting is for  perforce server not connected

**Comment by HonkingGoose** [comment]
I think this issue can be closed as the error was due to a connection issue to the Perforce server, not with the content of the book.
> error u getting is for perforce server not connected

**Comment by ben** [comment]
Agreed. And thanks for scrubbing 4-year-old issues!

**Comment by HonkingGoose** [comment]
I'll go clean out the grimy parts some more then. 😄
