### ISSUE TITLE
All images links are broken

### ISSUE THREAD

**Issue by dasaveliev** [progit/progit2#354]
To resolve the issue, all the 
>image::images/

should be replaced for 

>image::../images/

in all files in all */sections/ dir

**Comment by ben** [comment]
This is an unfortunate side-effect of how Atlas builds the book. All the image references are resolved relative to the chapter files (like [this one](https://github.com/progit/progit2/blob/master/book/03-git-branching/1-git-branching.asc#L1)), not the section files (like [this one](https://github.com/progit/progit2/blob/master/book/03-git-branching/sections/nutshell.asc)). The images appear properly in the rendered PDF and HTML, but not when you read the files on GitHub.

Reading the book by browsing the source on GitHub was never a use case we considered. If you want to read the book, you should go to [the website](http://git-scm.com/book/en/v2) or [download a PDF](https://progit.org/). If you want to edit the files, try running asciidoctor on a chapter file, from that chapter's directory.
