### ISSUE TITLE
500 errors for a couple of links

### ISSUE THREAD

**Issue by bernars** [progit/progit2#355]
The GitHub Help is seeing failures for a couple of links:

- External link http://git-scm.com/book/ch4-1.html#The-Git-Protocol failed: 500 No error
- External link http://git-scm.com/book/ch5-2.html failed: 500 No error

Are there better pages we should be linking to?

**Comment by ben** [comment]
No, those URLs seem fine, but [the site](http://git-scm.com/book/en/v2) seems to be broken right now. I've filed https://github.com/git/git-scm.com/issues/567, hopefully we'll get to the bottom soon.

**Comment by bernars** [comment]
Thanks, @ben! :sparkles:

**Comment by schacon** [comment]
OK, these links are fixed now, but the images are still busted. Working on that now.

**Comment by bernars** [comment]
Many thanks, @schacon!
