### ISSUE TITLE
Thai Translation (th)

### ISSUE THREAD

**Issue by pallat** [progit/progit2#361]
Our team would like to be contributor to translate progit2 to Thai.
Here is my fork  https://github.com/Pallat/progit2:

Thank you.

**Comment by officephuket** [comment]
https://github.com/Pallat/progit2  Out teamword link to me

**Comment by jnavila** [comment]
Now the book can more easily be published on git-scm.com. If you wish so, please create an organization progit2-th and move your translation repo to it. Then, I will update the git-scm repo to pull from your organization's repo.

**Comment by wingyplus** [comment]
@jnavila Thanks for your reply. Now organization is here https://github.com/progit2-th .

**Comment by jnavila** [comment]
Could @pallat push the changes to this repo?

**Comment by wingyplus** [comment]
@pallat I will tell him (I work with him in the same company). :)

**Comment by HonkingGoose** [comment]
@wingyplus and @officephuket For your reference: the docs for contributing a translation can be found here: https://github.com/progit/progit2/blob/master/TRANSLATING.md

---

@jnavila Is this still an issue that needs tracking here? They set up their organization at https://github.com/progit2-th. So I would think this issue can be closed, as they can go start on their project and get it merged on git-scm when ready.

**Comment by jnavila** [comment]
:checkered_flag:
