### ISSUE TITLE
core.editor documentation windows.

### ISSUE THREAD

**Issue by un1versal** [progit/progit2#365]
This is for discussion only to determine whats the best way to proceed.

Following up on https://github.com/git-for-windows/git/issues/278 where currently there is a issue of edits being terminated prematurely before their concluded while on Windows with notepad++ as a default editor not set as core.editor with ```-multiInst```

I had a look at [core.editor](https://github.com/progit/progit2/blob/master/book/08-customizing-git/sections/config.asc#coreeditor) (presuming this is right place to document this? Any suggestions?

The suggestion is to add some note to documentation on how to workaround the issue which seems to be resolved  by adding/settings Notepad++ with ```-multiInst``` until this is resolved in core and the installer detects and sets the editor properly as to avoid the issue in first place.

The reason this would be best in meanwhile is because https://github.com/msysgit/msysgit/issues/218 is now over a year old and no solution exists in core atm.

x86
```
 git config --global core.editor "'C:/Program Files/Notepad++/notepad++.exe' -multiInst" 
```
x64
```
 git config --global core.editor "'C:/Program Files (x86)/Notepad++/notepad++.exe' -multiInst" 
```

I dont mid making the edit and submitting the PR if someone points me to right page in case or suggest a better alternative or even additional documentation.

**Comment by YueLinHo** [comment]
Perhaps improve [this section: First-Time Git Setup, Your Editor](https://github.com/progit/progit2/blob/master/book/01-introduction/sections/first-time-setup.asc#your-editor)
or [this section: Git Configuration, Basic Client Configuration, core.editor](https://github.com/progit/progit2/blob/master/book/08-customizing-git/sections/config.asc#coreeditor)

**Comment by uNiversaI** [comment]
Does anyone else have any more feedback? Should I go ahead and make a PR adding this info to documentation or not?

**Comment by YueLinHo** [comment]
> Should I go ahead and make a PR adding this info to documentation or not?

Submit a PR. Go! Go! Go! :smiley:

**Comment by uNiversaI** [comment]
There we go https://github.com/progit/progit2/pull/382

**Comment by un1versal** [comment]
I guess this is pretty much dead here, closing.
