### ISSUE TITLE
The description of /etc/gitconfig is not ture for Git for Windows 2.x

### ISSUE THREAD

**Issue by YueLinHo** [progit/progit2#368]
This is not true for GfW 2.x anymore:
```
It also still looks for /etc/gitconfig, although it’s relative to the MSys root, 
which is wherever you decide to install Git on your Windows system when you 
run the installer. 
```
See section [First-Time Git Setup](https://github.com/progit/progit2/blob/8a15027bbfc7b823d08396a5a0e33ee5c4bf0ef9/book/01-introduction/sections/first-time-setup.asc#first-time-git-setup)

On my test:
In **XPP 32** which installed the GfW 2.x **32bit**, 
```/etc/gitconfig``` is ```C:\Doucuments and Settings\All Users\Application Data\Git\config```
In **Win7 Pro 64** which installed the GfW 2.x **64bit**, 
```/etc/gitconfig``` is ```C:\ProgramData\Git\config```
([Here](https://github.com/libgit2/libgit2/pull/3040) is a very long discussion, if you are interested.)

Consider Cygwin git and Msys2 git are also available. (Never use them.)
I am not really sure how to fix it.

Add one more sentence???
```
However, if you are using Git for Windows 2.x, it is 
C:\Doucuments and Settings\All Users\Application Data\Git\config on Windows XP, 
and it is C:\ProgramData\Git\config on Windows Vista and newer.
```

Any suggestion?

**Comment by ben** [comment]
That sounds like it would solve the problem neatly. Want to submit a PR?

**Comment by YueLinHo** [comment]
@ben submit a PR #373. :smiley: 

/cc @dscho
