### ISSUE TITLE
Code Example error - double escaped

### ISSUE THREAD

**Issue by ryanjmccall** [progit/progit2#371]
On https://git-scm.com/book/en/v2/Git-Basics-Tagging

The example code looks like:
`git tag -l &apos;v1.8.5*&apos;`

Think it should be something like `git tag -l 'v1.8.5*'`

Line 682 of source `<pre data-type="programlisting" data-code-language="console"><code class="gp">$</code> git tag -l <code class="p">&amp;</code>apos<code class="p">;</code>v1.8.5*<code class="p">&amp;</code>apos<code class="p">;</code>`

**Comment by ben** [comment]
Looks like you've found a bug with Atlas' Asciidoc parser; [here](https://github.com/progit/progit2/blob/master/book/02-git-basics/sections/tagging.asc#listing-your-tags) is the source file, and it appears correct. I'll bring it up in the forum.

**Comment by wolfgang42** [comment]
In #444 @ben linked to [this Atlas forum post](http://forum.atlas.oreilly.com/t/angle-brackets-inside-source-block-are-replaced-with-entities-html-only/254) which says a fix is coming out shortly.

**Comment by YueLinHo** [comment]
[Atlas forum post ](http://forum.atlas.oreilly.com/t/angle-brackets-inside-source-block-are-replaced-with-entities-html-only/254): **Effective March 2016, the Atlas forum is no longer available.**

![image](https://cloud.githubusercontent.com/assets/5831804/13840403/563f4f30-ec5d-11e5-9d6b-cf3573872e2e.png)

**Comment by anatolyborodin** [comment]
Hi @ben!

> I've logged it [here] (http://forum.atlas.oreilly.com/t/angle-brackets-inside-source-block-are-replaced-with-entities-html-only/254), hopefully it'll get resolved soon and I can just hit "rebuild."

Is there a new version with the fix? https://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery still has `Reflog: HEAD@{0} (Scott Chacon &lt;schacon@gmail.com&gt;)` etc.

PS

> Effective March 2016, the Atlas forum is no longer available.

LOL!

**Comment by HonkingGoose** [comment]
The issue with ```git tag -l &apos;v1.8.5*&apos;``` is fixed, from https://git-scm.com/book/en/v2/Git-Basics-Tagging:

```
$ git tag -l "v1.8.5*"
v1.8.5
v1.8.5-rc0
v1.8.5-rc1
v1.8.5-rc2
v1.8.5-rc3
v1.8.5.1
v1.8.5.2
v1.8.5.3
v1.8.5.4
v1.8.5.5
```
---

The issue with ```Reflog: HEAD@{0} (Scott Chacon &lt;schacon@gmail.com&gt;)``` is also fixed, from https://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery:

```
$ git log -g
commit 1a410efbd13591db07496601ebc7a059dd55cfe9
Reflog: HEAD@{0} (Scott Chacon <schacon@gmail.com>)
Reflog message: updating HEAD
Author: Scott Chacon <schacon@gmail.com>
Date:   Fri May 22 18:22:37 2009 -0700
```

**Comment by ben** [comment]
✨
