### ISSUE TITLE
Incorrect claim about commit notifications?

### ISSUE THREAD

**Issue by rmzelle** [progit/progit2#374]
https://github.com/progit/progit2/blob/master/book/06-github/sections/2-contributing.asc currently reads:

> with GitHub you simply commit to the topic branch again and push.
> 
> If the contributor does that then the project owner will get notified again and when they visit the page they will see that it’s been addressed.

It's my understanding that there is no simple way to get notified about commits made to pull requests. Is there? If not, I'll create a PR to remove this claim. For my repositories I always warn contributors to leave a comment in their PRs so I get notified when they make a new commit.

**Comment by ben** [comment]
Yeah, you're right, there's no notification on a push. I'd definitely accept a PR that clarifies this.
