### ISSUE TITLE
Code is double escaped on git-scm.com/book

### ISSUE THREAD

**Issue by benofbrown** [progit/progit2#378]
I'm not sure if this is the right place to raise this but I couldn't find any other method on git-scm.com/book. There's at least one page where the code examples are being double escaped, e.g. [Git Internals - Git Objects](http://www.git-scm.com/book/en/v2/Git-Internals-Git-Objects)

If you look down to the second code block it says:

    $ echo &apos;test content&apos; | git hash-object -w --stdin

The ampersand is being escaped in the html code so it's breaking it.

I've tried building the HTML myself and this is handled correctly, I get:

    $ echo 'test content' | git hash-object -w --stdin

So this seems to be a problem with whatever's rendering this text for the book on the git-scm.com website rather than the source code itself.

**Comment by wolfgang42** [comment]
This is a duplicate of #371.

**Comment by benofbrown** [comment]
Apologies, I did try to see if there was a pre-existing issue but failed to find it. I'll close this down now.
