### ISSUE TITLE
Apostrophes seem to display incorrectly in example code in section 2.1

### ISSUE THREAD

**Issue by MichaelBlume** [progit/progit2#383]
![screenshot 2015-08-26 10 28 03](https://cloud.githubusercontent.com/assets/208853/9500954/3b921bc0-4bdd-11e5-9a28-cb9989217a60.png)

**Comment by tessiof** [comment]
Same problem at **1.6 Getting Started - First-Time Git Setup**:
![git-1 6](https://cloud.githubusercontent.com/assets/2301644/9507297/a4b3dec2-4c23-11e5-9b93-3583fac2f1a3.png)

and at **1.7 Getting Started - Getting Help**:
![git-1 7](https://cloud.githubusercontent.com/assets/2301644/9507307/b29d46ea-4c23-11e5-8b1e-8ba2da6a9439.png)

**Comment by wolfgang42** [comment]
I think this is caused by the same issue as #371.

**Comment by jnavila** [comment]
Close as duplicate
