### ISSUE TITLE
There's no Git for Windows 2.x

### ISSUE THREAD

**Issue by tessiof** [progit/progit2#384]
> On Windows systems, Git looks for the .gitconfig file in the $HOME directory (C:\Users\$USER for most people). It also still looks for /etc/gitconfig, although it’s relative to the MSys root, which is wherever you decide to install Git on your Windows system when you run the installer. However, **if you are using Git for Windows 2.x**, it is C:\Documents and Settings\All Users\Application Data\Git\config on Windows XP, and it is C:\ProgramData\Git\config on Windows Vista and newer.

I'm pretty sure there's no Git for Windows 2.x, nor Windows 3.x, Windows 95, etc..
I assume the author was going for:
> if you are using Git 2.x for Windows

In this case, since the book is about Git 2.0 onwards, a better way would be: 
> On Windows systems, Git looks for the .gitconfig file in the $HOME directory (C:\Users\$USER for most people). *It also still looks for C:\Documents and Settings\All Users\Application Data\Git\config on Windows XP, and C:\ProgramData\Git\config on Windows Vista and newer.*

**Comment by i-give-up** [comment]
"Git for Windows 2.x" here means "version 2.x of Git for Windows". 

Given the context, I doubt people would think that it's referring to an operating system, but I might be mistaken.

**Comment by ben** [comment]
Yeah, I doubt people will think Git was written for an OS that was released in 1987. :grinning: I'd accept a PR that fixes the grammar, though.

**Comment by YueLinHo** [comment]
**Git for Windows** is a term. perhaps using `Git for Windows` 2.x?

**Comment by ben** [comment]
No, I think we have enough acronyms. I think "version 2.x of Git for Windows" is the least-awkward-while-still-being-correct thing I can think of.
