### ISSUE TITLE
Commands highlighted in section: "'origin' is not special" seem cramped

### ISSUE THREAD

**Issue by elbaloo** [progit/progit2#394]
Section content uses a different type than the rest of the text in other sections, this causes the git commands (which are highlighted) to seem cramped and partially covering the section text.

**Comment by YueLinHo** [comment]
[Section 3.5 - Remote Branches](https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches)
File: \book\03-git-branching\sections\remote-branches.asc
Line: 23

I can't tell how it's cramped. That [NOTE] is pretty clear for me.

**Comment by elbaloo** [comment]
This is no longer happening. Issue can be closed.
