### ISSUE TITLE
Link to Stashing and Cleaning in Basic Branching and Merging section broken

### ISSUE THREAD

**Issue by elbaloo** [progit/progit2#395]
Link is on second paragraph after Figure 3.

**Comment by crd** [comment]
Hi @elbaloo -- I'm assuming you're referring to the link in this sentence? 

> There are ways to get around this (namely, stashing and commit amending) that we’ll cover later on, in “Stashing and Cleaning”.

If so, are you referring to the .html or .pdf version? The .html version at http://git-scm.com/ has problems rendering the content. I've opened up an Issue on their github project for this. See https://github.com/git/git-scm.com/issues/575

**Comment by ben** [comment]
Thanks, @crd. I'll close this for now.
