### ISSUE TITLE
Serbian translation (sr)

### ISSUE THREAD

**Issue by Lazar95** [progit/progit2#401]
Started the translation [here](https://github.com/Lazar95/progit2); currently the fully translated chapters are 1, 2, 3 and 5. Changed the `status.json` file as well. Not sure if there is anything else that needs to be done at the moment.

**Comment by jnavila** [comment]
Ask @schacon to transfert your  repo to progit

**Comment by schacon** [comment]
@Lazar95 it's all set up and ready to go.  Any pushes to the master branch will trigger a new build which will update the book online here: http://git-scm.com/book/sr/v2, including the ebook options.  You have write access currently - if you need anyone else added with write access, just let me know.

**Comment by Lazar95** [comment]
Thanks!

**Comment by Lazar95** [comment]
@schacon: Sorry to bother; not sure if I'm doing something wrong, but looks like I don't have the write access to [progit2-sr](https://github.com/progit/progit2-sr). I tried adding the remote but when that didn't work I tried cloning the whole repository again and tried pushing then but it still doesn't allow me.

```console
$ git push origin
remote: Permission to progit/progit2-sr.git denied to Lazar95.
fatal: unable to access 'https://github.com/progit/progit2-sr/': The requested URL returned error: 403
```
