### ISSUE TITLE
Missing gitolite section in server setup part?

### ISSUE THREAD

**Issue by jdehaan** [progit/progit2#402]
In v1 I enjoyed the good introduction of gilotite. For that reason gitolite is currently the lightweight and yet powerful setup we are using. Is it missing in v2 or is there any good reason why this part is not anymore in v2 of "Pro Git". In the latter case it would be good to mention the reason shortly somewhere.

**Comment by ben** [comment]
When the first edition was written, Git servers were thin on the ground, and the user base hadn't really decided what it wanted. Gitolite was an amazing experiment with hosting Git repos over SSH with advanced permissions.

However, it seems like the market has settled, and people want more than SSH-based Git hosting. They want issues, discussions, pull requests, rendered documents, _and_ permissions — all the stuff you get with a modern web hosting package. Given this, we decided to cover (a) straight SSH hosting, for those who just want to make a Git repo available to someone else, (b) a GUI web host that gets installed on your own machine (GitLab), and (c) a GUI web host that's in the cloud (GitHub).

Gitolite hasn't gone away, but it seems like it's done. In fact, the chapter from the first edition is still mostly applicable. If that's a thing you want, you'll probably find it. But the second edition was meant as a guide for using Git in 2015, and gitolite isn't part of that experience for 99.5% of Git users and administrators.
