### ISSUE TITLE
Wrong link on Translations page

### ISSUE THREAD

**Issue by Lazar95** [progit/progit2#404]
On the [Translations page](https://progit.org/translations), the linked page on the word **here** is the page itself.

> Once that's been started, open an issue **here** with the URL of[...]

It should link to https://github.com/progit/progit2/issues?q=is%3Aissue.

It might also be helpful to link to a page with a list language codes we're using here since there are so many of them.

**Comment by ben** [comment]
The code is fixed, deployment is a mystery. I've filed an issue, we'll get it done. Thanks!
