### ISSUE TITLE
Callouts on the site

### ISSUE THREAD

**Issue by Lazar95** [progit/progit2#406]
Callouts on the site aren't working since they're treated as a part of the code.

![screenshot from 2015-09-03 15 45 40](https://cloud.githubusercontent.com/assets/7661457/9659896/292234a8-5253-11e5-890a-5b6d8fa2c8a8.png)

Also their "explanations"  below the code snippet have awkward positions.

![screenshot from 2015-09-03 15 47 55](https://cloud.githubusercontent.com/assets/7661457/9659926/52bd96e0-5253-11e5-867a-c5ad32b6e41b.png)

The screenshots were taken using Firefox 40.0.3 for Ubuntu.

**Comment by YueLinHo** [comment]
I conform that they show normally again both on Win7+Chrome and Ubuntu+Firefox.
I think this issue can be closed for now.
