### ISSUE TITLE
Powers incorrectly rendered in "A short note about SHA-1"

### ISSUE THREAD

**Issue by Jubobs** [progit/progit2#409]
In [A short note about SHA-1](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#Short-SHA-1), numbers consisting of an integer raised to a power do not get rendered correctly. Namely,

- 2^80 gets rendered as 280,
- 10^24 gets rendered as 1024.

See the following screenshot (taken in Safari 8 0.7):

![screen shot 2015-09-05 at 08 23 10](https://cloud.githubusercontent.com/assets/7138892/9698294/8d604702-53a7-11e5-9e83-9c461235ec17.png)

**Comment by Lazar95** [comment]
The rending is wrong in Firefox 40.0.3, as well. The `<sup>` tag is present, but the default browser styles which render subscripts and superscripts are overridden with the very first style in [this](https://git-scm.com/assets/git-scm-51dae02d97f150a7e22b24f0c7497beb.css) spreadsheet:

    html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, .man-page p tt, .man-page .listingblock .content, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video

If you remove `sub, sup,` from this style, the superscripts and subscripts will be rendered properly.

**Comment by ben** [comment]
I've reported this over at https://github.com/git/git-scm.com/issues/586.
