### ISSUE TITLE
Bugged mobi output

### ISSUE THREAD

**Issue by Atcold** [progit/progit2#410]
What are the differences between the version on Amazon and the one freely available at `http://git-scm.com/book/en/v2`?
On Amazon, the main font of the book follows the Kindle preferences, whereas the one freely available is stuck on a serif sans font.
![font](https://cloud.githubusercontent.com/assets/2119355/9711830/ac6821ba-5514-11e5-900e-ab989e2037ca.jpg)
Moreover, on the Amazon version all images are resized in order to be contained by the page of the book, whereas on the freely available one the images are often too big, and they are cropped away by the size of the Kindle itself.
![img](https://cloud.githubusercontent.com/assets/2119355/9711835/b252ae4c-5514-11e5-838c-d79c1d6cf794.jpg)
Both these issues are fixed in the Amazon version.

**Comment by HonkingGoose** [comment]
@jnavila is this fixed with the new Asciidoctor build system? I thought you said so on: https://github.com/progit/progit2/issues/420#issuecomment-479181270

**Comment by pbodnar** [comment]
Hi, my Kindle PW 3 (2015; with the latest December 2019 software update) doesn't seem to have the problems described above when reading the latest version from `http://git-scm.com/book/en/v2`, i. e. with 2.1.216. So the issues are probably fixed.

In fact, the version offered by Amazon as linked from http://git-scm.com/book/en/v2 ([the link](http://www.amazon.com/Pro-Git-Scott-Chacon/dp/1484200772?ie=UTF8&camp=1789&creative=9325&creativeASIN=1430218339&linkCode=as2&tag=git-sfconservancy-20)) has got severe shortcomings, the main being it seems to be really from the year 2014 (?!). I guess I should file a separate issue for that?

**Comment by jnavila** [comment]
The version from Amazon is still the original one, the one that could also be available with paper. It was never refreshed.

 The electronic versions (ebook, pdf) available for direct download are compiled from the latest state of the repo of the book (https://github.com/progit/progit2) with our own publishing workflow. As you say this version does not exhibit the issues stated at the top, I guess we can safely close it.

**Comment by pbodnar** [comment]
@jnavila, thanks for the confirmation.

I still wonder though whether the book's home page shouldn't be amended, so that it warns users about the deprecated version on Amazon. I wonder how many other people besides me downloaded and read the 6 years old book, because there was no clear warning...

**Comment by jnavila** [comment]
@ben what do you think of removing the link to Amazon on git-scm.com ?
