### ISSUE TITLE
Wrong references in Dutch GIT user manual

### ISSUE THREAD

**Issue by Ucamco-DDE** [progit/progit2#415]
Dear,
Within the Dutch translation of the "Pro GIT" manual (URL "https://progit2.s3.amazonaws.com/nl/2015-06-23-4b1c4/progit-nl.560.pdf"), I have found several unexisting references.
They can be recognised as "???" and can be found on the pages 72, 246, 587 and 589.

Best regards
Dominique

(Sorry, I have just seen that there is a special repository, just for this manual (progit-nl), but I don't know how to move this topic around)

**Comment by HonkingGoose** [comment]
Hi @Ucamco-DDE thanks for the report. If this is still an issue in the current version of the Dutch translation, please file a report here: https://github.com/progit/progit2-nl/issues

---

@jnavila This issue is not in the right repository, perhaps it can be moved/closed?

**Comment by jnavila** [comment]
Let's close this.
