### ISSUE TITLE
git@vger.kernel.org DOESNT WORK

### ISSUE THREAD

**Issue by Yousha** [progit/progit2#418]
"This is an automatically generated Delivery Status Notification.
Delivery to the following recipients failed.

git@vger.kernel.org"

**Comment by mjg** [comment]
vger.kernel.org has quite some aggressive filters. Have you tried to send HTML mails or large attachments?
The git mailing list is up and alive :)

**Comment by Yousha** [comment]
No, just a simple text-based mail from Hotmail/Outlook.

**Comment by ben** [comment]
I'm going to close this for now, it doesn't seem like a book issue.
