### ISSUE TITLE
progit-zh.823.pdf, this file totally cannot be read

### ISSUE THREAD

**Issue by PinoTsao** [progit/progit2#420]
Did anyone review the file? you don`t need to know chinese, just see the page, most of pages are messed

**Comment by Vest** [comment]
Could you please tell which OS/PDF Viewer are you using?

**Comment by PinoTsao** [comment]
I opened it on both Win7 and Fedora21, both are messed.
I use sumatraPDF 3.0 in Win7, sorry I forget the exact app name in fedora21, it is the default document viewer in fedora, I need check it out tomorrow.

**Comment by PinoTsao** [comment]
I confirmed it again, get the chinese edition from: https://progit2.s3.amazonaws.com/zh/2015-09-10-63cab/progit-zh.823.pdf , open it under fedora 21 with default Document Viewer, it does is messed up

**Comment by ben** [comment]
Yeah, this is pretty easy to reproduce. The Chrome viewer almost acts like there's an encoding error:

![image](https://cloud.githubusercontent.com/assets/39902/10368389/d2a90492-6d89-11e5-971e-b2dd35b1e2cf.png)

And OSX Preview has a different set of problems. Most of the text is invisible.

![image](https://cloud.githubusercontent.com/assets/39902/10368417/f34f1f2e-6d89-11e5-8aec-9503f1a3f1df.png)

There's an [Atlas forum post](http://forum.atlas.oreilly.com/t/progit2-zh-pdf-font-missing/239/2) that seems related. I've pinged over there, hopefully we'll get some movement soon.

**Comment by pc10201** [comment]
The pdf file lost a font.
I can not read the pdf with Foxit reader or acrobat reader on windows.

**Comment by nanma** [comment]
In the newest version of Chinese pdf file, https://progit2.s3.amazonaws.com/zh/2015-12-02-9d8a9/progit-zh.936.pdf , this problem is still exist.
The epub version is ok, but the pdf losts most Chinese characters.
Please solve this problem，thx：）

**Comment by ben** [comment]
Still no updates on the [forum post](http://forum.atlas.oreilly.com/t/progit2-zh-pdf-font-missing/239), but someone posted a possible workaround:

> I'm on Mac. After download and install all fonts from https://github.com/wweir/source-han-sans-sc, I can now read this using the built-in Preview App.

**Comment by nanma** [comment]
It works. Thanks, ben!

**Comment by zxq1002** [comment]
but still does not work on windows after intalling the fonts

**Comment by sijianwudi** [comment]
It does not work on Foxit Reader for chinese version but taiwan version

**Comment by sijianwudi** [comment]
https://progit2.s3.amazonaws.com/zh/2015-12-02-9d8a9/progit-zh.936.pdf
does work on windows, I use Foxit Reader

**Comment by hank-fan** [comment]
[https://progit2.s3.amazonaws.com/zh/2015-12-02-9d8a9/progit-zh.936.pdf](url)
Cannot display all characters in Adobe Acrobat Pro.
It is working fine if use Microsoft Edge in Windows10.

**Comment by hank-fan** [comment]
@zxq1002 @sijianwudi ,Chinese version in another branch, More details, refer to:
[https://github.com/progit/progit2-zh/releases](url)

**Comment by frogcjn** [comment]
I have installed the font from Adobe CC, but not working for most characters.
Anyone can help with it?

**Comment by anonymouss** [comment]
Has this issue been solved? I met this problem too, and I have installed all the SourceHanSans fonts. Adobe reader still tell me DISOTQ+SourceHanSansSCLight are missing.

**Comment by metalmac** [comment]
I installed the SourceHanSansSCLight ,but still ran into the DISOTQ+SourceHanSansSCLight missing issue, and I reported the issue to adobe-fonts/source-han-sans,I will wait for their reply.

Wish there will be a solution to this issue, I can only read the English version at this momont.

Please check [here](https://github.com/adobe-fonts/source-han-sans/issues/157)

**Comment by HonkingGoose** [comment]
I'm not seeing any wonky text on Evince or Firefox in the current version of the Chinese translation pdf. (https://github.com/progit/progit2-zh/releases/download/2.1.17/progit_v2.1.17.pdf)

I'm using Ubuntu 19.04 (preview for now).

**Comment by jnavila** [comment]
OK. This was an issue with Atlas. I know it works now with Asciidoctor
