### ISSUE TITLE
For Centos, the installation section is missing 'perl-devel' package and workaround for 'docbook2X' package

### ISSUE THREAD

**Issue by i-give-up** [progit/progit2#425]
I discovered some issues with the [installation instruction](https://github.com/progit/progit2/blob/master/book/01-introduction/sections/installing.asc) when compiling git on Centos 6.7. Namely `perl-devel` and `docbook2X` is missing from the `yum install` instruction. Additionally, some workarounds is needed for `docbook2X`.

# perl-devel

Without the package, I get this error when running `make`

    Can't locate ExtUtils/MakeMaker.pm

# docbook2X

Note that the X at the end is uppercase for Fedora/Centos, and lowercase for Ubuntu/Debian. Actually looking into it a bit further, it seems like it depends on which Centos repository you're using - it's uppercase in EPEL and lowercase in RepoForge. Also, EPEL and RepoForge are third-party repositories, I'm not sure if this package is in the default repositories.

Also, the package for Fedora/Centos has a different name for the binary which is `db2x_docbook2texi`. You'll need to create a symlink

    sudo ln -s /usr/bin/db2x_docbook2texi /usr/bin/docbook2x-texi

See [this](https://groups.google.com/forum/#!topic/git-users/DMaDpy8Bpww)

Again, this is using `docbook2X` from EPEL. I'm not sure if this issue applies if you use `docbook2x` from RepoForge.

**Comment by ben** [comment]
Yeah, I didn't test the instructions on every distro, so it's not surprising that they're incomplete for some. If you come to some conclusions, I'd love to see a PR.
