### ISSUE TITLE
broken links in https://git-scm.com/book/en/v2/Getting-Started-Git-Basics

### ISSUE THREAD

**Issue by gitster** [progit/progit2#429]
It seems all three in-text links on the page are broken: "Git Branching", "Undoing Things", and "Git Basics". They all lead to 404.

Reported at git@vger.kernel.org list by Mike Botazzo <mikebotazzo@gmail.com>

**Comment by ben** [comment]
Yeah, this is known. It has to do with the Atlas HTML build, and how it's being integrated into the site. It's being tracked at https://github.com/git/git-scm.com/issues/588.
