### ISSUE TITLE
Section 1.7 Getting help, examples of help commands

### ISSUE THREAD

**Issue by manoonan** [progit/progit2#431]
When I view the help commands, there are references to symbol substitutes which have not been translated. This is on the web site version.

The & lt;  and & gt; text are displayed instead of < and >.

I think this is an error.
![image](https://cloud.githubusercontent.com/assets/15087103/10426232/df2f74aa-7129-11e5-9e85-a04b2aecd02e.jpeg)

Thanks Mark.

**Comment by fingolfin** [comment]
Similar problem pops up in section 10.2, http://git-scm.com/book/en/v2/Git-Internals-Git-Objects#Object-Storage

![screen shot 2015-11-19 at 08 44 12](https://cloud.githubusercontent.com/assets/241512/11265106/cc76ead6-8e99-11e5-8fb9-020b787d784b.png)

**Comment by jnavila** [comment]
This is an issue with git-scm. Please see #371
