### ISSUE TITLE
Broken code formatting

### ISSUE THREAD

**Issue by whitequark** [progit/progit2#433]
See https://git-scm.com/book/en/v2/Git-in-Other-Environments-Git-in-Powershell:
![1336](https://cloud.githubusercontent.com/assets/54771/10493682/209c2cac-72bb-11e5-9c13-08f862e4a5c2.png)

**Comment by ben** [comment]
Atlas bug. I've logged it [here](http://forum.atlas.oreilly.com/t/angle-brackets-inside-source-block-are-replaced-with-entities-html-only/254), hopefully it'll get resolved soon and I can just hit "rebuild."

**Comment by wolfgang42** [comment]
The main bug tracking this problem is #371.

**Comment by ben** [comment]
Nice. Closing this as a duplicate.
