### ISSUE TITLE
Poor contrast/readability of some figures on e-reader (Nook)

### ISSUE THREAD

**Issue by DrChr** [progit/progit2#442]
Hi,
While reading progit2 on my Nook I noticed that the contrast/readability of some of the figures is quite poor. To illustrate I used my phone to take a photograph, see below.

The photos/screenshot are all of figure 2.1 from progit2-en.904. For comparison I looked at the same figure on different devices.

On the Nook (fig. a) I think the main problem is the contrast that results from the chosen colours and that the device does not support colours.  Is the book only intended to be fully readable on colour screens?  

However, looking at the epub using Coolreader3 (fig. b) on my laptop I also notice that the readability of the fonts isn't that good. E.g. look closely at the "h" and "f" in "Add the file",  it's like parts of the letters are missing or only partially shown. 

In the browser (fig. c), the letters are overall better and readability is fine. Although something is still going on with e.g. the "ied" in "Modified".

I'm not sure how things proceed from here. The readability on the HTML version is fine, and on the epub in Coolreader it is ok, so the problem is mainly on the Nook - and maybe you don't care there?

Maybe it'd simply be better to require the reader to use a device that supports colour, in which case I suggest a note about this should be added.  I've read the book on the Nook, so I don't actually know what I've missed by reading it there.

Regards,
Christian

a) Photo (cropped) from epub shown on e-reader (Nook) 
![fig_2 1_epub_photo_on_nook_cropped](https://cloud.githubusercontent.com/assets/5725271/10863616/5c8579c4-7fd3-11e5-8442-dda22d85c9ae.jpg)

b) Screenshot (cropped) from epub shown in Coolreader3 on laptop
![fig_2 1_epub_screenshot_from_coolreader3](https://cloud.githubusercontent.com/assets/5725271/10863628/daed0b10-7fd3-11e5-8ecb-b25ee4432850.png)

c) Screenshot (cropped) from html shown in Opera on laptop 
![fig_2 1_html_screenshot_from_opera](https://cloud.githubusercontent.com/assets/5725271/10863635/084fc534-7fd4-11e5-9aa5-a588245af5fd.png)

d) Photo (not cropped) from epub shown on e-reader (Nook)
![fig_2 1_epub_photo_on_nook](https://cloud.githubusercontent.com/assets/5725271/10863641/2150db5e-7fd4-11e5-86b1-f332ee3e0f78.jpg)

**Comment by ben** [comment]
The background of that image is transparent (which I assume is `RGBA(0,0,0,0)`), so this must be an issue with how the reader is choosing to interpret that color. One fix would be to replace all the transparent pixels with `RGBA(255,255,255,0)` for these cases, but that might break other readers that are displaying white text on a dark background, causing the same issue. That case is probably rare, though.

**Comment by DrChr** [comment]
Hmm, not sure it's just down to a transparent background...  the figure
would be readable if it wasn't for the thing going on with the text.
Perhaps it's poor anti-aliasing, and on the e-reader that together with the
conversion to grey scale make it difficult to read?

Look for example at the characters in figure b), taken from a laptop.

I wouldn't mind trying a few things on the figure to see if there's a way
to have it readable both on laptop screens and an e-reader.  But OTOH,
maybe the book's really intended to be read in colour?



On 1 November 2015 at 16:21, Ben Straub <notifications@github.com> wrote:

> The background of that image is transparent (which I assume is
> RGBA(0,0,0,0)), so this must be an issue with how the reader is choosing
> to interpret that color. One fix would be to replace all the transparent
> pixels with RGBA(255,255,255,0) for these cases, but that might break
> other readers that are displaying white text on a dark background, causing
> the same issue. That case is probably rare, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progit/progit2/issues/442#issuecomment-152834311>.
>



-- 
Christian Ridderström,     +46-70 687 39 44

**Comment by DrChr** [comment]
I cloned to my laptop and built the epub, but then realised I should just look at the images directly.
So I looked at lifecycle.png, and perhaps the problem is with how the .png is generated from the source. Zooming in on e.g. the word "Untracked", the characters look so-so.  To illustrate I cut out the white box with "Untracked" and scaled up a factor of ten in Gimp (with no interpolation). Below's the result. Maybe a higher resolution of the image is needed?  Or some different setting on how the .png is generated.

Note: I'm on Linux and don't have the "Sketch" program.

![excerpt_of_lifecycle_png_scaled_up_by_factor_10](https://cloud.githubusercontent.com/assets/5725271/10894130/f391c6ee-81ac-11e5-8330-7aa093a63eb0.png)

**Comment by DrChr** [comment]
Well, I could anyway play with the .png direclty in Gimp. So I tested modifying the text "Staged" in the PNG, then re-generated the epub and opened it in Coolreader. See the two screenshots below. I think it is more readable in the modified version (b).
My conclusion is that:
i) Readability can be improved. It's not the choice of font, but the rendering to PNG.
ii) White text on red background isn't the best for readability...  A bigger font, i.e. where lines in the ltters take up more pixels, would likely help.

a) Original screenshot
![fig_2 1_epub_screenshot_from_coolreader3](https://cloud.githubusercontent.com/assets/5725271/10895022/28db3632-81b2-11e5-9920-582e24e20751.png)

b) Screenshot from locally modified epub, in which I've replaced "Staged" with "Staged1" using Gimp (DejaVu Sans, 18pt). 
![fig_2 1_epub_screenshot_from_coolreader3_locally_modified_figure](https://cloud.githubusercontent.com/assets/5725271/10895027/3227843e-81b2-11e5-8a8e-27a466d1f280.png)

**Comment by ben** [comment]
Yeah, these images are scaled-down versions of the images generated for print, which are at 300dpi. The fonts aren't hinted for standard-resolution screens. I wonder what they look like on a hidpi kindle?

**Comment by DrChr** [comment]
My nook is certainly high DPI, although I have to say that regular text is very crisp.
How come you're using sketch for the images btw?  
Note: I tried to find software that can handle .sketch-files, but seems that if you e.g. want to import it into Inkscape, you need to have Sketch installed.

**Comment by DrChr** [comment]
Hi again, several of the figures in ch. 3 are very difficult to read on my Nook.
I took a photo of fig 3-29 to illustrate. I'll probably my own version of the e-book/figures just, but not sure it makes sense to share as it'll be modifications of the .png:s and not their sources.
![fig 3-29 on a nook](https://cloud.githubusercontent.com/assets/5725271/11190932/ad73c58a-8c98-11e5-9c5e-beb3698c7f7e.jpg)
