### ISSUE TITLE
Notepad++ x86 and x64 paths swapped

### ISSUE THREAD

**Issue by exbarboss** [progit/progit2#443]
First Time Git Setup chapter has error with path to Notepad++ on x86 and x64 versions of Windows.
It says:
On x86 system "'C:/Program Files/Notepad++...
On x64 system "'C:/Program Files(x86)/Notepad++...
Should be vise versa.

**Comment by i-give-up** [comment]
No, the information there is correct. As far as I know, Notepad++ is only available as a 32-bit program, so it installs to

- `C:/Program Files` on x86 system (32-bit Windows)
- `C:/Program Files (x86)` on x64 system (64-bit Windows)

**Comment by exbarboss** [comment]
You are right. I was under impression that I'm using x64 Notepad. Sorry for confusion.
