### ISSUE TITLE
'>' in section 3.2 is escaped to '&gt;'

### ISSUE THREAD

**Issue by spacewander** [progit/progit2#444]
See https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

For example:

```
&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD:index.html
&lt;div id="footer"&gt;contact : email.support@github.com&lt;/div&gt;
=======
&lt;div id="footer"&gt;
 please contact us at support@github.com
&lt;/div&gt;
&gt;&gt;&gt;&gt;&gt;&gt;&gt; iss53:index.html
```

The source is correct, maybe a rebuild can solve the problem?

**Comment by ben** [comment]
Nope, this is an atlas bug. I've logged it [here](http://forum.atlas.oreilly.com/t/angle-brackets-inside-source-block-are-replaced-with-entities-html-only/254), hopefully it'll get resolved soon and I can just hit "rebuild."

**Comment by rybak** [comment]
Are `&gt;` in [section 7.2](https://git-scm.com/book/en/v2/Git-Tools-Interactive-Staging) part of this issue?

**Comment by wolfgang42** [comment]
I believe this is caused by the same issue as #371.

**Comment by jnavila** [comment]
Close as duplicate

**Comment by anatolyborodin** [comment]
Hi @ben!

> I've logged it here, hopefully it'll get resolved soon and I can just hit "rebuild."

Is there a new version with the fix? https://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery still has `Reflog: HEAD@{0} (Scott Chacon &lt;schacon@gmail.com&gt;)` etc.

**Comment by anatolyborodin** [comment]
> Effective March 2016, the Atlas forum is no longer available.

LOL!

**Comment by YueLinHo** [comment]
@anatolyborodin Since this is a duplicate to issue #371, better comment there. :smile:
