### ISSUE TITLE
All links in Appendix A.3 are broken on git-scm.com

### ISSUE THREAD

**Issue by alistairmgreen** [progit/progit2#445]
Appendix A.3, _Git Commands_, has many links to other chapters of the book.

In the version hosted on [git-scm.com](https://git-scm.com/book/en/v2), all of these links are broken and lead to a 404 error page.

**Comment by dgg-trimit** [comment]
Hi, Also in Section 2, Git Basics - e.g. http://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository link to Git Internals @ http://git-scm.com/book/en/v2/1-git-internals/_git_internals leads to a 404

**Comment by nguyenquangtien83** [comment]
Google docs

**Comment by ben** [comment]
Yup. This is notated over at https://github.com/git/git-scm.com/issues/588, and it has to do with the way the Atlas output is pulled into the Git website; all the xref links work in ebooks. I'm going to close this for now, since the real problem is over there.
