### ISSUE TITLE
Czech translation (cs)

### ISSUE THREAD

**Issue by pepr** [progit/progit2#446]
Hi,

I have started the Czech translation recently. The repository is here https://github.com/pepr/progit2-cs .

First two chapters are almost translated and the `status.json` is set to reflect that. Actually, I have introduced the OmegaT tool for the Czech translation of the first edition, and then did some tweaks to fix the TMX (translation memory) for asciidoc (from markdown). Therefore, some sentences is translated to Czech also in other chapters, but they were not reviewed.

I hope that the `omegat/` subdirectory does not break the process of generating the HTML pages and the other formats.

Have a nice time,
Petr

**Comment by paveljanik** [comment]
Thanks Petr!
