### ISSUE TITLE
3.2 Git Branching -- possibly wrong explanation (upstream vs. downstream)

### ISSUE THREAD

**Issue by pepr** [progit/progit2#448]
Just below the 
[Figure 3-13. Hotfix branch based on `master`](http://git-scm.com/book/en/v2/book/03-git-branching/images/basic-branching-4.png)

In the sentence... 
"Because the commit pointed to by the branch you merged in was directly **upstream** of the commit you’re on, Git simply moves the pointer forward."
Should not it be **downstream**? English is not my first language, but the commit point is newer, created later.

**Comment by YueLinHo** [comment]
book\03-git-branching\images\basic-branching-4.png

![basic-branching-4](https://cloud.githubusercontent.com/assets/5831804/13766769/cc1f8004-ea9f-11e5-99b0-7809b06f31c4.png)

**Is this good?**
```
Because the commit `C4` pointed to by the branch `hotfix` you merged in was directly ahead of 
the commit `C2` you're on, Git simply moves the pointer forward.
```

**Comment by ben** [comment]
Yeah, that's better. Upstream and downstream should be reserved for use with remotes I think.
