### ISSUE TITLE
Figure is wrong

### ISSUE THREAD

**Issue by ratulSharker** [progit/progit2#449]
The `Figure 5-16. Basic sequence of this managed-team workflow.` is given here is wrong. 
Here they proposed 3 character `Jessica`, `John` & `Jossie`. 
`Jessica` & `John` worked on `FeatureA`
`Jessica` & `Jossie` worked on `FeatureBee`

But the image explained it reversely.

**Comment by YueLinHo** [comment]
Fix file: `book\05-distributed-git\images\managed-team-flow.png`

**Comment by YueLinHo** [comment]
OK. This issue is a duplicate and should be closed. See: #357.

**Comment by ratulSharker** [comment]
ok closing it
