### ISSUE TITLE
Link to 'git internals' points to nowhere

### ISSUE THREAD

**Issue by richardbrinkman** [progit/progit2#454]
In the section "8.4 Customizing Git - An Example Git-Enforced Policy" there is a link to _git_internals. However it points to a page that does not exist.

https://github.com/progit/progit2/blob/master/book/08-customizing-git/sections/policy.asc

**Comment by jnavila** [comment]
The PDF is ok, the links are correct.
see https://raw.githubusercontent.com/progit/progit2/master/book/10-git-internals/1-git-internals.asc 
So, it is *again* an issue with html export to git-scm.

**Comment by ben** [comment]
@schacon, have you had a chance to look at any of these xref issues on git-scm.com?

**Comment by YueLinHo** [comment]
cf. [git-scm.com issue 633](https://github.com/git/git-scm.com/issues/633)

**Comment by YueLinHo** [comment]
I'd like to add one more comment which add some keywords `wrong link` & `broken link`, so that I can serach the issue tracking system more quickly. :smile:

**Comment by HonkingGoose** [comment]
Following the mentioned link "Git Internals" starting from https://git-scm.com/book/en/v2/Customizing-Git-An-Example-Git-Enforced-Policy leads to the correct page: https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain#ch10-git-internals
