### ISSUE TITLE
Wrong URL in german translation. It should be https://github.com/git/git/raw/master/contrib/completion/git-completion.bash

### ISSUE THREAD

**Issue by fraengii** [progit/progit2#459]
The file under the URL https://github.com/git/git/blob/master/contrib/completion/git-completion.bash causes an error:
`bash: /home/frank/git-completion.bash: line 1: syntax error near unexpected token 'newline'
 bash: /home/frank/git-completion.bash: line 1: '<!DOCTYPE html>'`

**Comment by ben** [comment]
Yeah, that would actually be better. Want to submit a PR? I'd love for you to get credit for the fix.

**Comment by fraengii** [comment]
Yes, but I'm not yet really familiar with git, so I would like you to give me a hint where to do this. I even haven't found the german translations of the book.

**Comment by ben** [comment]
Turns out we don't have a German translation of the second edition yet. Can you tell me where you found the link to the file? It doesn't look like we link to it anywhere in the English version.

**Comment by fraengii** [comment]
Sorry for answering that late.
I've read version 1 and found the link on https://git-scm.com/book/de/v1/Git-Grundlagen-Tipps-und-Tricks.

**Comment by ben** [comment]
Awesome. I'll close this for now, thanks for looking into it!

**Comment by fraengii** [comment]
You're welcome!
Thanks for the book!!!
