### ISSUE TITLE
Better cover image

### ISSUE THREAD

**Issue by huguenin** [progit/progit2#463]
The image quality of the cover image is quite poor; looks like it was converted from a low-quality JPEG. Can you upload a better version and maybe even include the original PSD or whatever the source file is?

**Comment by huguenin** [comment]
*push*

**Comment by ben** [comment]
You're right, even the [first version](https://raw.githubusercontent.com/progit/progit2/ddbd046eed00fab6d68563266966fdcd4ef35e39/images/cover.png) of this file (which has a typo in the subtitle) has some serious JPEG artifacts. I'll see if we can get a higher-quality version from Apress.

**Comment by huguenin** [comment]
Great thanks!
