### ISSUE TITLE
Several errors on page: 10.2 Git Internals - Git Objects

### ISSUE THREAD

**Issue by shalipoto** [progit/progit2#465]
The use of "\&gt;"  on this page should be replaced with the symbol  ">" , possibly from an HTML entity translation.

The file attached shows a problem with using git update-index as written:

![git_error](https://cloud.githubusercontent.com/assets/16054664/11611024/added1f6-9b7d-11e5-8bd3-cc05abe20e04.png)

**Comment by ben** [comment]
The HTML entities issue is being tracked at #371.

Are you copy-pasting that passage into a terminal? If you do so, does it end up on a single line, or on two? If two, the backslash is necessary to let your shell know the line isn't finished.

**Comment by shalipoto** [comment]
Hey Ben, I looked at #371 and it seems to be what I'm seeing too. I'm only referencing the git manual and seeing the extra escapes in my browser-no copy pasting. Shall I close my ticket?

**Comment by ben** [comment]
No worries. It's unfortunate that it ended up on a single line, but it looks like we're doing approximately the right thing in the text. I'm going to close this out, since there doesn't appear to be a better way to do it.

**Comment by shalipoto** [comment]
Hey Ben,

Thanks for the replies. I'm on the README.md from
git/git-scm.com
and all's well except that the result is I'm getting content from the first
edition. I'd like the second edition content for I have an idea for a
temporary work-around on the Atlas rendering issue. Basically it will be a
script that is triggered when it sees the HTML rendering problems and
substitutes the correct characters.

-Saleem
