### ISSUE TITLE
`sdiff` alias in the Submodules section shows HTML entities in HTML version

### ISSUE THREAD

**Issue by FroZnShiva** [progit/progit2#466]
In the file `book/07-git-tools/sections/submodules.asc` there are some useful aliases listed for working with submodules, but for the following alias the `&&` operator results in HTML entities `&amp;&amp;` being displayed in the [HTML version of the book](http://git-scm.com/book/en/v2/Git-Tools-Submodules):

```sh
$ git config alias.sdiff '!'"git diff && git submodule foreach 'git diff'"
```

**Comment by ben** [comment]
Yup. #371.
