### ISSUE TITLE
Angle brackets display incorrectly in browser view.

### ISSUE THREAD

**Issue by clymbon** [progit/progit2#467]
Here are two images that show how content appears a) in PDF, and b) in browser.  As you can see, there is a problem with the way angle brackets are displayed in the browser view.  Instead of showing up as left and right angle brackets, they show up as "&lt;" and "&gt;".  

(Hopefully this issue report won't get garbled in a similar way...)

Viewing the page source, it looks like instead of "&lt;" and "&lt;" in the HTML, which would display as "<" and ">" the ampersand character has been escaped, as follows:

<code class="ni">&amp;lt;</code>/div<code class="ni">&amp;gt;</code>

![gitbook1](https://cloud.githubusercontent.com/assets/16169227/11640659/b877bb52-9d01-11e5-8d65-53c4a70b83e3.PNG)

![gitbook2](https://cloud.githubusercontent.com/assets/16169227/11640664/be6779d0-9d01-11e5-9ee4-ca531bdebe80.PNG)

**Comment by clymbon** [comment]
Sigh... that didn't work - what I was trying to write got interpreted as markup.  

Just look at the images, you'll see the problem.

**Comment by ben** [comment]
#371. Super frustrating.
