### ISSUE TITLE
Wrong generation of symbols >, <, &(probably if present) in "programlisting" sections of HTML-build.

### ISSUE THREAD

**Issue by Mrak-IW** [progit/progit2#470]
But in common text it's OK. Example:

If you type 2 or u at the What now> prompt, the script prompts you for which files you want to stage:

What now\&gt; 2
           staged     unstaged path
  1:    unchanged        +0/-1 TODO
  2:    unchanged        +1/-1 index.html
  3:    unchanged        +5/-1 lib/simplegit.rb
Update\&gt;\&gt;

**Comment by nguyenquangtien83** [comment]
Network ok

**Comment by ben** [comment]
Yup: #371. Super frustrating.
