### ISSUE TITLE
Watching atlas build log

### ISSUE THREAD

**Issue by jnavila** [progit/progit2#472]
The translation in french has not been successfully building for three days and we have no idea why it is failing. It would be really great to have access to the build log of book in order to diagnose and fix the failures.

**Comment by ben** [comment]
Agreed. It looks like Atlas has shut down our account, I can't even get in. /ping @schacon

**Comment by schacon** [comment]
Yeah, there is some weird object missing issue across all of the translations, including English. I've emailed them and I'll let you know when it's fixed. Ben, I've also asked them to give you access again.

There is a way to get the build error message with the API, so I'll try to pull that into the ProGit website UI soon.

**Comment by schacon** [comment]
OK, it looks like builds have been restored. There was a cached corruption somewhere on their end and they've cleared it.

**Comment by harupong** [comment]
I've just merged https://github.com/progit/progit2-ja/pull/91, and it was successfully built :smile: 

![noname_2015-12-22_14-20-15_no-00](https://cloud.githubusercontent.com/assets/204623/11948422/353a77fe-a8b7-11e5-8abe-85dd11e4d54f.png)
