### ISSUE TITLE
HTML entity &gt; not converted to greater than sign in online book

### ISSUE THREAD

**Issue by hakonhagland** [progit/progit2#475]
In chapter 10.3 "Git Internals - Git References" in the book at 

https://git-scm.com/book/en/v2/Git-Internals-Git-References

There is this code snippet:

![git](https://cloud.githubusercontent.com/assets/6708379/11993816/aec36c14-aa35-11e5-925b-6cb6d827a3d4.png)

as seen `&gt;` should be converted to a `>`

**Comment by jnavila** [comment]
This is a known issue with the process of publishing to git-scm.com. The ebooks and pdfs are correct. Please see #371.
