### ISSUE TITLE
HTML escape characters in git-scm.org

### ISSUE THREAD

**Issue by nadavge** [progit/progit2#478]
I've been reading the tutorial for customization, and in this page
https://github.com/progit/progit2/blob/master/book/08-customizing-git/sections/attributes.asc
the render escaped > for &amp;gt; instead of &gt;

**Comment by Denton-L** [comment]
This seems to be an issue on multiple pages. For example, [this page](https://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server) also escapes rendered literally.

**Comment by ben** [comment]
Yup: #371. This is an issue with the git-scm.com site and the Atlas rendering.
