### ISSUE TITLE
Odd (wrong?) topic sentence of subtree-merges

### ISSUE THREAD

**Issue by rpgoldman** [progit/progit2#486]
The topic sentence of the third paragraph of this section is "The idea of the subtree merge is that you have two projects, and one of the projects maps to a subdirectory of the other one and vice versa."

Are you sure that this is what you meant?  It seems to say "you have two projects and one of them maps to a subdirectory of the other, while the other maps to a subtree of the first."

The meaning of "vice versa" here is not at all clear.  Possibly it would be best to cut the "and vice versa," since I think usually you have a project that includes a second project as subdirectory (for example, because the second project provides a library).

**Comment by ben** [comment]
Yeah, you're probably right. Want to submit a PR? I'd love it if you got the `blame` credit for fixing it.

**Comment by rpgoldman** [comment]
OK.  I hadn't actually forked the book myself, though.  Let me see how difficult it is (i.e., does it require some build tools I don't have) and I'll either get back to you with a pull request or I'll beg off.

**Comment by rpgoldman** [comment]
OK, I submitted PR #491
