### ISSUE TITLE
All links in english online v2 of book are broken (404)

### ISSUE THREAD

**Issue by fingolfin** [progit/progit2#493]
Looking at https://git-scm.com/book/en/v2 it seems that all internal links are currently broken, and give 404 errors. E.g. https://git-scm.com/book/en/v2/Git-Commands-Plumbing-Commands links to https://git-scm.com/book/en/v2/1-github/_pr_refs which does not exist.

Or https://git-scm.com/book/en/v2/Getting-Started-A-Short-History-of-Git which at the end links to the non-existent https://git-scm.com/book/en/v2/1-git-branching/_git_branching

**Comment by ben** [comment]
Yeah: #454. This is an issue on git-scm.com, and there's at least one report there (https://github.com/git/git-scm.com/issues/633). Closing as duplicate for now.
