### ISSUE TITLE
Online version contains scrambled examples

### ISSUE THREAD

**Issue by fingolfin** [progit/progit2#494]
Looking at https://git-scm.com/book/en/v2/Git-Internals-Git-Objects it seems some of the last examples got scrambled (looks as if an ascii-to-html conversion was incorrectly applied). E.g. we see this:
```
&gt;&gt; require 'zlib'
=&gt; true
&gt;&gt; zlib_content = Zlib::Deflate.deflate(store)
=&gt; "x\x9CK\xCA\xC9OR04c(\xCFH,Q\xC8,V(-\xD0QH\xC9O\xB6\a\x00_\x1C\a\x9D"
```

**Comment by ben** [comment]
Yup: #371.
