### ISSUE TITLE
Incomplete image deployment

### ISSUE THREAD

**Issue by julianladisch** [progit/progit2#495]
The images

https://github.com/progit/progit2/blob/master/book/01-introduction/images/centralized.png
https://github.com/progit/progit2/blob/master/book/05-distributed-git/images/centralized_workflow.png

doesn't get deployed to

https://git-scm.com/book/en/v2/book/01-introduction/images/centralized.png
https://git-scm.com/book/en/v2/book/05-distributed-git/images/centralized_workflow.png

resulting in missing Figure 1-2 and Figure 5-1 on

https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control
https://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows

Please do a complete image deployment. Thank you!

**Comment by ben** [comment]
See #250, a fix was merged (but apparently not deployed) in git/git-scm.com#505.

**Comment by julianladisch** [comment]
The images still haven't been deployed. Where should I report this deploy problem?

**Comment by ben** [comment]
The issue is on the git-scm repo. I'd say leave a comment on https://github.com/git/git-scm.com/pull/505.
