### ISSUE TITLE
Broken link at https://git-scm.com/book/en/v2/Git-Commands-Patching

### ISSUE THREAD

**Issue by Morrolan** [progit/progit2#498]
The link under patching titled "Rebasing and Cherry Picking Workflows" is broken.

It would appear that this is meant to link to [[_rebase_cherry_pick]] within section 05-distributed-git/maintaining.asc/[[_rebase_cherry_pick]] section.

**Comment by ben** [comment]
The AsciiDoc has been structured in such a way that the Atlas renderer can assemble it into a finished whole, and render the links correctly. If you're reading the AsciiDoc directly on GitHub, the links that cross chapters are broken, but that's not the primary use case.

It's known that links on git-scm.com are broken (see git/git-scm.com#588), but the links in the PDF versions appear to be working correctly.
