### ISSUE TITLE
greater-than symbol does not render in html version

### ISSUE THREAD

**Issue by 00gavin** [progit/progit2#501]
Great book.  I noticed that the greater-than symbol is not rendering in the chapter 2 html, breaking the first example of using Git.  That might put many new users off!

progit2/book/02-git-basics/sections/recording-changes.asc
https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository

The ascii...
```
$ echo 'My Project' > README
```

becomes the html...
```
$ echo 'My Project' &gt; README
```

Cheers.

**Comment by ben** [comment]
Yup: #371. This is an Atlas issue.
