### ISSUE TITLE
Doubled explanation in one paragraph of 5.2 Contributing..., subsec. Private small team

### ISSUE THREAD

**Issue by pepr** [progit/progit2#502]
It seems to me that there is an unwanted repeating of the same explanation in chapter 5 Distributed Git, section Contributing..., subsection Private small team -- almost last paragraph just before the next subsesction Private managed team. Here it is (bold):

That is one of the simplest workflows. You work for a while, generally in a topic branch,
**and merge into your master branch when it’s ready** to be integrated. **When you want
to share that work, you merge it into your own master branch**, then fetch and merge 
origin/master if it has changed, and finally push to the master branch on the server.
The general sequence is something like this:

**Comment by ben** [comment]
Hey, yeah, that is a bit clunky. Want to submit a PR to fix it?

**Comment by pepr** [comment]
English is not my first language. Someone else should probably formulate it better.

**Comment by YueLinHo** [comment]
Locate:
 - `book\05-distributed-git\sections\contributing.asc` around line 306
 - [5.2 Contributing to a Project - Private Small Team](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#Private-Small-Team)

**Comment by YueLinHo** [comment]
Locate:
 - `book\05-distributed-git\sections\contributing.asc` around line 306
 - [5.2 Contributing to a Project - Private Small Team](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#Private-Small-Team)

For comparing, the origin:
```
You work for a while, generally in a topic branch, 
and merge into your master branch when it's ready to be integrated.
When you want to share that work, 
you merge it into your own master branch, 
then fetch and merge `origin/master` if it has changed, 
and finally push to the `master` branch on the server.
```
Delete line 4, modify line 5, and is this good for you?
```
You work for a while, generally in a topic branch, 
and merge into your master branch when it's ready to be integrated.
When you want to share that work, 
you fetch and merge your master from `origin/master` if it has changed, 
and finally push to the `master` branch on the server.
```

**Comment by ben** [comment]
Nice, that's better.
