### ISSUE TITLE
Figure 1-2 does not show

### ISSUE THREAD

**Issue by YueLinHo** [progit/progit2#508]
See:

![image](https://cloud.githubusercontent.com/assets/5831804/12501721/37d43188-c0fb-11e5-8b3b-e13a65218ed8.png)

(Figure 1-1 does show.)

Related file: \book\01-introduction\sections\\**about-version-control.asc**

**Comment by ben** [comment]
This is a duplicate, see https://github.com/git/git-scm.com/pull/505 :disappointed:

**Comment by YueLinHo** [comment]
@ben Very sorry for that! :fearful:

**Comment by ben** [comment]
No problem, this comes up a lot. I've been hoping they'd fix the deployment for some months now. Thanks for contributing!
