### ISSUE TITLE
Czech translation [cs]

### ISSUE THREAD

**Issue by pepr** [progit/progit2#509]
Hi,

Please, add the progit2-cs to the https://github.com/progit/

I have already translated chapters 1, 2, 3, and almost 5 (see `status.json`).

The repository is https://github.com/pepr/progit2-cs

Thanks,
Petr

**Comment by pepr** [comment]
Translation of the chapter 5 is finished. Now working on chapter 4 (skipped earlier). Parts of the other chapters that remained the same (as in the first edition) were translated automatically (using Omega-T translation tool and the translation memory created from the original/translation of ProGit, first edition).

**Comment by jnavila** [comment]
I changed the script for publishing the books to the git-scm website. As soon as the change is effective, it will be easy to include your language. see github/git-scm.com#927

**Comment by jnavila** [comment]
Can you create an organization `progit2-pl` and migrate the repo to it. Then, we will update the script on git-scm.com (website only).

**Comment by pepr** [comment]
Hi Jean-Noël,
 
I wish you all the best in the new year ;)
 
I have created the progit-cs organization and the progit2-cs repository inside -- by mistake, I did not create the progit2-cs.
(That is, without the 2.) Should I fix it or is it OK?
 
https://github.com/progit-cs/progit2-cs
 
I did not update the repo for a longer time, so that it can be slightly outdated.
I hope, it can be processed by the git-scm tools.
 
The sources are generated from English original and the translation memories
by the Omega-T tool. I did not copy that directory to avoid possible problems
with the toolchain.
 
Have a nice day,
    Petr
 
______________________________________________________________
> Od: Jean-Noël Avila <notifications@github.com>
> Komu: progit/progit2 <progit2@noreply.github.com>
> Datum: 21.01.2017 19:16
> Předmět: Re: [progit/progit2] Czech translation [cs] (#509)
>
Can you create an organization progit2-pl and migrate the repo to it. Then, we will update the script on git-scm.com (website only).

**Comment by jnavila** [comment]
Ok, I'll take your new repo and make the scripts work with it.

**Comment by jnavila** [comment]
Done!

**Comment by pepr** [comment]
Thank you Jean-Noël! Have a nice day.
