### ISSUE TITLE
Chapter 1.1 - Image broken

### ISSUE THREAD

**Issue by arielnoname** [progit/progit2#517]
![screen shot 2016-02-04 at 12 14 11 pm](https://cloud.githubusercontent.com/assets/11996305/12819223/edfb1d18-cb38-11e5-9acf-a214be030fca.png)

**Comment by ben** [comment]
Yup: #294. We've had a lot of reports of this one, feel free to go over to https://github.com/git/git-scm.com/pull/505 and ping the issue.
