### ISSUE TITLE
Problems with entities

### ISSUE THREAD

**Issue by arielnoname** [progit/progit2#518]
This happens trough most of the command examples:

![screen shot 2016-02-06 at 4 09 50 pm](https://cloud.githubusercontent.com/assets/11996305/12868776/74fd5722-ccec-11e5-925b-e281e0be9532.jpg)

**Comment by ben** [comment]
Yup: #371. Feel free to chime in on the [Atlas forum post](http://forum.atlas.oreilly.com/t/angle-brackets-inside-source-block-are-replaced-with-entities-html-only/254).
