### ISSUE TITLE
English (Chapter1.3) 404 error on link Undoing Things

### ISSUE THREAD

**Issue by OutsourcedGuru** [progit/progit2#520]
Looks like a page moved and a reference needs to be updated.

Page:  /book/en/v2/Getting-Started-Git-Basics
Update link on page "Undoing Things" from:

/book/en/v2/1-git-basics/_undoing
...to...
/book/en/v2/Git-Basics-Undoing-Things

Couldn't tell you if other languages suffer similarly.  I tried to detect this error in the /book/be/* version but the link is completely missing from the same paragraph there.

**Comment by ben** [comment]
Yeah, this is known. See #513. Feel free to chime in over on https://github.com/git/git-scm.com/issues/633.
