### ISSUE TITLE
English (Chapter1.7) Unescaped characters in section

### ISSUE THREAD

**Issue by OutsourcedGuru** [progit/progit2#523]
As the attached screenshot indicates, the less-than/greater-than should appear rather than what is displaying.

![git-scm_1dot7](https://cloud.githubusercontent.com/assets/15971213/13023449/eb42e608-d19d-11e5-938f-f203cb36be6e.png)

**Comment by sergio-bobillier** [comment]
Same thing happens everywhere. It seems it is a problem with the Markdown renderer:

From section 2.6:

```
$ git push origin --tags
Counting objects: 1, done.
Writing objects: 100% (1/1), 160 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To git@github.com:schacon/simplegit.git
 * [new tag]         v1.4 -&gt; v1.4
 * [new tag]         v1.4-lw -&gt; v1.4-lw
```

**Comment by ben** [comment]
Yup: #371. It's an Atlas issue; feel free to chime in [over there](http://forum.atlas.oreilly.com/t/angle-brackets-inside-source-block-are-replaced-with-entities-html-only/254).
