### ISSUE TITLE
There is no *adding* remote repositories in previous sections.

### ISSUE THREAD

**Issue by YueLinHo** [progit/progit2#526]
at line 66 of book\02-git-basics\sections\remotes.asc,
`
We've mentioned and given some demonstrations of adding remote repositories in previous sections, but here is how to do it explicitly.(((git commands, remote)))
`

I have checked previous sections, there is no `git add remote`, related command, or statement, but `git clone`.

Does it mean "clone"? Adding first remote repository via clone?

Modify it to?
`
We've mentioned and given some demonstrations of adding first remote repository via clone in previous sections, but here is how to add a new one directly.(((git commands, remote)))
`

**Comment by ben** [comment]
Sure. Want to submit a PR?

**Comment by YueLinHo** [comment]
Fixed in PR #528.
