### ISSUE TITLE
https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging wrong link

### ISSUE THREAD

**Issue by kjeremy** [progit/progit2#527]
The above page has this bit:

    If you need more advanced tools for resolving tricky merge conflicts, we cover more on merging in `Advanced Merging`.

The `Advanced Merging` link to: https://git-scm.com/book/en/v2/1-git-tools/_advanced_merging results in a 404.

**Comment by ben** [comment]
Yup: #513. Feel free to chime in over on https://github.com/git/git-scm.com/issues/633.
