### ISSUE TITLE
links out of date

### ISSUE THREAD

**Issue by becomesaflame** [progit/progit2#539]
Links to the [Rewriting History](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) page from the [Git Internals - Maintenance and Data Recovery](https://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery) page are out of date.  

old url:
https://git-scm.com/book/en/v2/1-git-tools/_rewriting_history

new url:
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by ben** [comment]
Yup: #513. Feel free to chime in over on git/git-scm.com#633.

**Comment by becomesaflame** [comment]
Thanks - sorry for the duplicate.
