### ISSUE TITLE
Add TortoiseGit config for bugtraq and icon

### ISSUE THREAD

**Issue by YueLinHo** [progit/progit2#541]
I use TortoiseGit for my daily git work.

I want to add `.tgitconfig` and `Pro.ico` files into progit2 repository for these things:

**For [bugtraq] config:**

![default](https://cloud.githubusercontent.com/assets/5831804/13274637/ccc51626-dae7-11e5-8d63-ee8385e4e5d4.png)

**For icon config:**

![1](https://cloud.githubusercontent.com/assets/5831804/13274304/32984d86-dae5-11e5-98d1-405ee33b2020.png) (The source of that icon is made from `progit\epub\title.png`)

**May I add them?**

**Comment by ben** [comment]
Yeah, that would be fine. I'm sure there are others that use these tools. Go ahead and submit a PR with before and after screen shots.

**Comment by YueLinHo** [comment]
Fixed with PR #543.
