### ISSUE TITLE
code formatting in "Getting Help" page

### ISSUE THREAD

**Issue by fustigate** [progit/progit2#545]
In the book's section 1.7 (["Getting Started - Getting Help"](https://git-scm.com/book/en/v2/Getting-Started-Getting-Help)), the formatting in the first example is broken.  It's showing the html symbol for angle brackets instead of the actual angle brackets:
```
$ git help &lt;verb&gt;
$ git &lt;verb&gt; --help
$ man git-&lt;verb&gt;
```

It should of course be:
```
$ git help <verb>
$ git <verb> --help
$ man git-<verb>
```
(This is correct in the PDF version of the book.)

**Comment by ben** [comment]
Yup: #371. It's an atlas issue; feel free to chime in on the [forum post](http://forum.atlas.oreilly.com/t/angle-brackets-inside-source-block-are-replaced-with-entities-html-only/254).
