### ISSUE TITLE
git checkout command copy the file for you

### ISSUE THREAD

**Issue by YueLinHo** [progit/progit2#548]
book\02-git-basics\sections\undoing.asc line 125

A note talking about git checkout command:
```
Any changes you made to that file are gone – you just copied another file over it.
```

User runs that command, and git does the copy for user.

Is this better?
```
Any changes you made to that file are gone – Git just copied another file over it.
```
`you` => `Git`

**Comment by ben** [comment]
Yeah, I like it.
