### ISSUE TITLE
Missing notice for a potentially dangerous command

### ISSUE THREAD

**Issue by nemoinho** [progit/progit2#550]
Chapter 9.2 "Migrating to git" has a paragraph which shows the use of `--no-metadata` to not include the metadata from svn. But there is no notice about the potential risk of this parameter if you may have to interact with the svn-repo again. The documentation says about this parameter that it is not recommended but in context of this chapter it seems to be a harmless option.

Documentation: (https://git-scm.com/docs/git-svn)
> --no-metadata
>
>    Set the noMetadata option in the [svn-remote] config. This option is not recommended, please read the svn.noMetadata section of this manpage before using this option.

And futher more the documentation describes why this paramater is risky: (https://git-scm.com/docs/git-svn#_config_file_only_options)
> This option is NOT recommended as it makes it difficult to track down old references to SVN revision numbers in existing documentation, bug reports and archives. If you plan to eventually migrate from SVN to Git and are certain about dropping SVN history, consider git-filter-branch[1] instead. filter-branch also allows reformatting of metadata for ease-of-reading and rewriting authorship info for non "svn.authorsFile" users.

**Comment by YueLinHo** [comment]
Fixed with PR #555

**Comment by nemoinho** [comment]
Thanks for the notice.
