### ISSUE TITLE
Broken link on page Git-Basics-Undoing-Things

### ISSUE THREAD

**Issue by mspncp** [progit/progit2#556]
The page
    http://git-scm.com/book/en/v2/Git-Basics-Undoing-Things
currently contains a broken link to 
    http://git-scm.com/book/en/v2/1-git-tools/_git_reset 
which has moved to
    https://git-scm.com/book/en/v2/Git-Tools-Reset-Demystified

Regards,
MSP

**Comment by ben** [comment]
Yup: #513. Feel free to chime in over on https://github.com/git/git-scm.com/issues/633.
