### ISSUE TITLE
Requesting for Clarification on the "2.2 Git Basics - Recording Changes to the Repository"

### ISSUE THREAD

**Issue by sivajavatechie** [progit/progit2#561]
In the diagram, Figure 2-1. The lifecycle of the status of your files. When user remove the file then  file status should change from unmodified  to **DELETED** not the untraked. Please correct me if I am wrong.

I tried delete the unmodified file from the working copy and see the git status below is the output.

git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)
        deleted:    test7.txt

**Comment by YueLinHo** [comment]
How do you remove the file? `rm`? `git rm`? `rm` + `git add`?

Suppose only you run `git rm`, then the file is deleted and that deletion/removal is staged. That's way you see the file is under "Changes to be committed", also means "staged".

If you use `rm`, it just remove the file from working tree, but the removal is not staged.

cf. [Remove File](https://git-scm.com/book/en/v1/Git-Basics-Recording-Changes-to-the-Repository#Removing-Files)

**Comment by sivajavatechie** [comment]
Thanks for the clarifications. Now I understand it correctly. Actually I removed file from the working copy and ran the git status command. Tried to see how the file status changing from once state to another state.

Once again thanks for your help!!
