### ISSUE TITLE
change marging in pdf

### ISSUE THREAD

**Issue by dcpc007** [progit/progit2#562]
Hi,

Is it possible to have or generate a pdf but without wasting pages with so wide marging ?
I think we could remove 1cm on each side (and maybe bottom) and then reduce the number of pages.
On text pages there is more than 25% width with blank...

For users, i would have a printed edition of some chapters, but don't want to waste too many sheets.
Even if i create  a bound book i have more space than necessary.

Thx

**Comment by ben** [comment]
I honestly don't know how Atlas does this. It probably has something to do with [these theme files](https://github.com/progit/progit2/tree/master/theme/pdf) though.

**Comment by dcpc007** [comment]
Thx.
But don't know Atlas :-( i look quickly on the files, the xslt seems more related on marging for an image's template.

**Comment by HonkingGoose** [comment]
@jnavila This is the margin for a current pdf. I don't think these margins are hugely wasteful. I don't know if you can set a smaller margin in Asciidoctor, their docs don't explicitly state this. Maybe some parameter in the ```.asc``` files would need to be changed?
![margins_pdf_current](https://user-images.githubusercontent.com/34918129/56084791-bc30b900-5e38-11e9-9c73-64f535521158.png)

**Comment by jnavila** [comment]
I think this issue was opened when the book was still compiled with Atlas. The present compilation is less wasteful.
