### ISSUE TITLE
Table of Contents (see issue #182)

### ISSUE THREAD

**Issue by rahrah** [progit/progit2#569]
Hi,

See closed issue #182 

In the current progit-en.1076.zip html format archive of the book, there are no links to the
table of contents on any of the pages.  There are just links to Next and Previous.

In older versions of the progit-en.X.zip html format archive, links to the table did exist, but the contents file was missing.

The content file now exists, but there are no links to it.

===Rich

**Comment by YueLinHo** [comment]
Copy the [download link](https://progit2.s3.amazonaws.com/en/2016-03-16-ec756/progit-en.1076.zip) from [Pro Git v2 en web page](https://git-scm.com/book/en/v2).

@ben Is there any way to get old html version?

**Comment by YueLinHo** [comment]
@rahrah It would be greate that changing the title `Table of Contents (see issue #182)` to something like: `No links to table of contents in html format file progit-en.1076.zip`

**Comment by ben** [comment]
Yeah, Atlas is doing this weirdly. If you open up Chapter 1, the "previous" link at the bottom goes to the table of contents, but other sections' "previous" links go to the chapter before. It's like Atlas thinks of the TOC as "chapter zero."

**Comment by YueLinHo** [comment]
> In older versions of the progit-en.X.zip html format archive, links to the table did exist

@rahrah Could you please email me the old `progit-en.X.zip` which has the TOC link?

**Comment by YueLinHo** [comment]
Last one I can download is https://progit2.s3.amazonaws.com/en/2016-02-19-6346b/progit-en.1037.zip

**Comment by YueLinHo** [comment]
The oldest I can find is [be-64](https://progit2.s3.amazonaws.com/be/2014-10-31-bcb40/progit-be.64.zip)
Then, I compare the the `ch01.html of be-64` with `1-introduction.html of en-1084`:
![compare2](https://cloud.githubusercontent.com/assets/5831804/14448792/8435c4d2-009e-11e6-8d8b-31ef1f20abb8.png)

![compare](https://cloud.githubusercontent.com/assets/5831804/14448700/a225f4cc-009d-11e6-849b-c4179b7265d7.png)

Diff the files:
![compare_file](https://cloud.githubusercontent.com/assets/5831804/14448735/09c04f06-009e-11e6-87cb-b70fbc002495.png)

The previous link:
![compare_file2](https://cloud.githubusercontent.com/assets/5831804/14448743/198a335c-009e-11e6-8a37-753431681fa1.png)

**Comment by HonkingGoose** [comment]
@ben is downloading a zipped .html file still something that you want to support?

If I go to the https://git-scm.com/book/en/v2 page, I see no links to a zipped .html file, only links to download .pdf .epub and .mobi files.

**Comment by ben** [comment]
Yeah I guess it's been deprecated at this point. To generate the git-scm.com HTML version you'd have to use their script.
