### ISSUE TITLE
wrong display of angle brackets in HTML version

### ISSUE THREAD

**Issue by Fornost461** [progit/progit2#572]
Hello, the angle brackets < and > are displayed `&lt;` and `&gt;` on the HTML version of [this page](https://git-scm.com/book/en/v2/Getting-Started-Getting-Help) (at least on my version of Firefox, but I think this is not browser-specific). The corresponding file on github is [here](https://github.com/progit/progit2/blob/master/book/01-introduction/sections/help.asc), but it seems not to be the source of the problem. Rather, I’d guess that whatever generates the HTML files from the .asc ones is responsible.

**Comment by YueLinHo** [comment]
Duplicate to #371, please close it. :smiley:

**Comment by Fornost461** [comment]
Sorry, I searched for a duplicate but didn’t notice this one though.
