### ISSUE TITLE
Broken link to 'reset demystified'

### ISSUE THREAD

**Issue by tailsoft** [progit/progit2#576]
Hi,
The Git Book's chapter '2.4 Git Basics - Undoing Things' contains a broken link to 'Reset Demystified'. (at the end of the second paragraph)

Source page: https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things
Expected page (when clicking link): https://git-scm.com/book/en/v2/Git-Tools-Reset-Demystified

Kind regards,
Remko Seelig

**Comment by YueLinHo** [comment]
Duplicate #454, should be closed.
