### ISSUE TITLE
One command is `git mv`, instead of `mv`.

### ISSUE THREAD

**Issue by YueLinHo** [progit/progit2#577]
Section 2.2 - Git Basics - Recording Changes to the Repository - [Moving Files](https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository#Moving-Files)
File: book\02-git-basics\sections\recording-changes.asc **line 598**

```
The only real difference is that `mv` is one command instead of three
 – it's a convenience function.
```

should `mv` be `git mv`?
```
The only real difference is that `git mv` is one command instead of three
 – it's a convenience function.
```

**Comment by ben** [comment]
Yeah, that's a bit clearer.
