### ISSUE TITLE
Typo in chapter 3

### ISSUE THREAD

**Issue by nadaesposible** [progit/progit2#578]
It reads

> ... as its “killer feature,” and it ...

but it should read

> ... as its “killer feature”, and it ...

In other words, the comma is within the quotes and it should be out of them.

**Comment by YueLinHo** [comment]
Well, I learned some formal English writing which the comma(`,`)/period(`.`) should go inner the quotation marks(`""`), something like `"bla bla,"` or `"bla bla."`. So, suppose it's not a typo. :smiley:

**Comment by nadaesposible** [comment]
Oh, I'm sorry, I didn't know that. I have to admit that I was surprised that nobody had seen it that before. : )

Thanks Yue Lin Ho. Closing the issue.
