### ISSUE TITLE
Need autotools for installing git from source

### ISSUE THREAD

**Issue by YueLinHo** [progit/progit2#579]
Section 1.6 - Getting Started - Installing Git - [Installing from source](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git#Installing-from-Source)
File: \book\01-introduction\sections\installing.asc line: 108
```
$ make configure
```
I created a whole new Ubuntu OS on VM for testing how to install git. 
(Actually, I am going to test `user.useconfigonly` feature on Linux.)
I failed on `make configure`, then I did:
```
$ sudo apt-get install dh-autoreconf
```

Better to mention `autoreconf` in book? Is it a dependency? (I am newbie to Ubuntu. :smiley: )

**Comment by ben** [comment]
Oh, nice catch! Probably we only tested on machines that already had autotools installed. Please do add this dependency to [the section on installing from source](https://github.com/progit/progit2/blob/da44a6c287b75ff3cab43234799aee12a071c45c/book/01-introduction/sections/installing.asc#installing-from-source).

**Comment by YueLinHo** [comment]
Not sure how to add it, but I will try. :smile:
