### ISSUE TITLE
Ch3 - Some sentences does not show on Web

### ISSUE THREAD

**Issue by YueLinHo** [progit/progit2#582]
File: book\03-git-branching\1-git-branching.asc line 9~13
Missing the following content for chapter 3 at the beginning.
```
Some people refer to Git's branching model as its ``killer feature,'' and it certainly sets Git apart in the VCS community.
Why is it so special?
The way Git branches is incredibly lightweight, making branching operations nearly instantaneous, and switching back and forth between branches generally just as fast.
Unlike many other VCSs, Git encourages workflows that branch and merge often, even multiple times in a day.
Understanding and mastering this feature gives you a powerful and unique tool and can entirely change the way that you develop.
```

Web shows:
![image](https://cloud.githubusercontent.com/assets/5831804/14225146/f7ad9cf2-f8ea-11e5-820d-c0bd7f573db8.png)

**Comment by ben** [comment]
Interesting. This must be something to do with the HTML import over on that site. Want to file an issue [over there](https://github.com/git/git-scm.com/issues)?

**Comment by YueLinHo** [comment]
> Interesting. This must be something to do with the HTML import over on that site. Want to file an issue over there?

Sure. Thanks.

**Comment by YueLinHo** [comment]
@ben I found ch 3, 4, 5, 6, 7, 9, 10 have the same problem.
