### ISSUE TITLE
Can not login to bitbucket.org by Git Credential Manager for Windows

### ISSUE THREAD

**Issue by jerrybk108** [progit/progit2#583]
Hello dev team,

I have just installed Git 2.8.0 X64 on windows 10, then the Windows Security pop-up window always show on my screen to input username and password then login to bitbucket.org by Git Credential Manager for Windows, but it seems that the credential can not login or save my credential token in cache, and the pop-up windows always shows on my screen.
![untitled](https://cloud.githubusercontent.com/assets/6925456/14237850/a1f3dfa0-fa53-11e5-9a95-a2d27dc29c2a.png)

Thanks and regards,
Hieu Tran

**Comment by jnavila** [comment]
This issue tracker is dedicated to the progit book.

The issue you have raised is related to the Windows port of the git program. Please see https://git-for-windows.github.io/ for reporting bugs.

**Comment by YueLinHo** [comment]
Better to report to [Git-Credential-Manager-for-Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows) project?
