### ISSUE TITLE
Downloads at https://git-scm.com/book/en/v2 out of sync with master branch

### ISSUE THREAD

**Issue by fortran-favors-the-old** [progit/progit2#585]
Usually the Pro Git downloads available [here](https://git-scm.com/book/en/v2) are kept up-to-date with the master branch, but it appears that they've fallen behind what's in master.

For example, the most recent commit to master was four days ago, but the most recent version available for download [here](https://git-scm.com/book/en/v2) is from over two weeks ago.

**Comment by jnavila** [comment]
@schacon @ben What's the status of O'Reilly publishing engine? Is it possible to restart it or should we switch to another option for git-scm.com and the ebooks?

**Comment by andres-mancera** [comment]
@fortran-favors-the-old : It seems @ben opened an issue to keep track of this problem ([#625](https://github.com/progit/progit2/issues/625)).  Should we close this one so that we don't have too many issues essentially tracking the same thing?
