### ISSUE TITLE
Suggestion: embed font in pdf.

### ISSUE THREAD

**Issue by macarthor** [progit/progit2#586]
hi team,

many people report that localized editions progit-xxx.pdf is unreadable in even acrobat reader or foxit reader.

the root cause is that many platforms miss necessary fonts used by progit pdf.

so i recommend that these fonts should be embedded into pdf. of course the file size would increase, but the benefit is much larger than the size increase.

thx.

**Comment by YueLinHo** [comment]
Related to issue #420.
Better close it, and discuss there?

**Comment by macarthor** [comment]
@YueLinHo yes, i noticed that issue before posting this issue. i think it's better to open a new request to be clear :).

**Comment by YueLinHo** [comment]
> i noticed that issue before posting this issue.

Then, it would be greate to mention it at the beginning, so that @ben can manage the issues easily with that nice issue link. :smile:

**Comment by ben** [comment]
@schacon would know better, but I believe this is out of our control, really. The downloadable PDF on progit.org is generated by Atlas' toolchain.

As for the local build, it's done by Asciidoctor, so embedding the fonts should be theoretically possible, but this would be way less useful than fixing it in the Atlas build.

**Comment by HonkingGoose** [comment]
@jnavila this issue seems to be about fonts not working in the translation PDF's. 

I thought this was fixed in asciidoctor? Issue #420 seems similar, and that was closed as well.

**Comment by jnavila** [comment]
Same here. Talking about O'Reilly's Atlas, but we switched to Asciidoctor and there's no issue now.
