### ISSUE TITLE
Add example for `git rm -f <file>`

### ISSUE THREAD

**Issue by YueLinHo** [progit/progit2#587]
File: `\book\02-git-basics\sections\recording-changes.asc`
Line: 524

```
If you modified the file and added it to the index already, 
you must force the removal with the `-f` option.
```

Better to add some example for it?
Something like:

```
$ echo "modified!" > PROJECTS.md
$ git add PROJECTS.md
$ git rm PROJECTS.md
error: the following file has changes staged in the index:
   PROJECTS.md
(use --cached to keep the file, or -f to force removal)
```

PS. the next example is talking about `--cached` option.

**Comment by HonkingGoose** [comment]
@ben do you want a pull-request to make this change?

I'm not sure it's actually necessary to explain this in detail, because git says what you need to do to force the removal of the file. 

The ```--cached``` option is given a example. Because ```--cached``` and ```-f``` are so similar, do we really need 2 examples here?

```
$ git rm staged_file_not_committed_earlier.md
error: the following file has changes staged in the index:
    staged_file_not_committed_earlier.md
(use --cached to keep the file, or -f to force removal)
```

**Comment by ben** [comment]
Yeah probably not. We don't need to be encyclopedic in this book. Going to close this one out.
