### ISSUE TITLE
Possible misspelling in Chapter 3

### ISSUE THREAD

**Issue by YueLinHo** [progit/progit2#590]
First page of **Chapter 3** under the _Branches in a Nutshell_ section 5th paragraph:

"When you create the commit by running git commit, Git checksums each subdirectory (in this case, just the root project directory) and stores those **_tree**_ objects in the Git repository."

Not sure if you really meant "tree" or "three".

(above message is copied from [git-scm.com issue 601](https://github.com/git/git-scm.com/issues/601))

File: book\03-git-branching\sections\nutshell.asc
Line: 20

In my understanding, it talks about **tree** object.
Is this good enough?

```
Git checksums each subdirectory (in this case, just the root project directory) 
and stores them as tree object in the Git repository.
```

**Comment by jnavila** [comment]
I'm pretty sure this part had already been fixed up... your rephrasing is clearer.

**Comment by YueLinHo** [comment]
This is v1:
```
Running git commit checksums all project directories 
and stores them as tree objects in the Git repository.
```

**Comment by HonkingGoose** [comment]
@jnavila this issue about Pro Git v1, which is deprecated.

From progit2/master:
>When you create the commit by running `git commit`, Git checksums each subdirectory (in this case, just the root project directory) and stores those tree objects in the Git repository.

---

I agree with @YueLinHo that there is some possible ambiguity around three (number) or tree (git object or leafy thing in forest :nerd_face: ). I'm not sure on how we could make this clearer?

Maybe we should just use a 1, 3 and 5 when referring to one, three and five. This might remove the ambiguity, and make it instantly clear that whether we're referring to a number 3 or a object tree.

From progit2/master:
>Your Git repository now contains five objects: three _blobs_ (each representing the contents of one of the three files), one _tree_ that lists the contents of the directory and specifies which file names are stored as which blobs, and one _commit_ with the pointer to that root tree and all the commit metadata.

Maybe a rewrite to this is clearer:
>Your Git repository now contains 5 objects: 3 _blobs_ (each representing the contents of one of the three files), 1 _tree_ that lists the contents of the directory and specifies which file names are stored as which blobs, and 1 _commit_ with the pointer to that root tree and all the commit metadata.

**Comment by ben** [comment]
Firstly, I kind of disagree with the premise of this issue. If we had intended the reader to receive the idea of a plant instead of a number, we would have written it that way. 

Standard English style is to use words when referring to numbers less than 10. I think we want to stick to that convention. I'd be fine with @YueLinHo's proposal though.

**Comment by HonkingGoose** [comment]
The thing about the leafy thing in the forest was not meant seriously of course :smile:. 
I'm no native English speaker, so if you find the current text clear, I'll defer to your judgement of course. :+1: 

Do you want a pull-request with @YueLinHo's proposal then?

**Comment by ben** [comment]
Sure! Then we can close this out.
