### ISSUE TITLE
Wrong link (Broken)

### ISSUE THREAD

**Issue by idhamhafidz** [progit/progit2#591]
Hi,

Just got this. Notifying you.

the link for Undoing Things is broken

![screenshot from 2016-04-11 14-33-27](https://cloud.githubusercontent.com/assets/1255203/14418614/92559fbc-fff2-11e5-899f-2a49e6e5df12.png)

**Comment by YueLinHo** [comment]
Which link? The `Undoing Things`? Then, please close this issue as duplicate #454.

**Comment by idhamhafidz** [comment]
Ok
