### ISSUE TITLE
Book cover in other languages

### ISSUE THREAD

**Issue by andres-mancera** [progit/progit2#594]
Folks:  I recently merged a pull request made by @jamj2000 that contained an update to the [book/cover.png](https://github.com/progit/progit2-es/commit/b0d2e745d92b6ce658acbeb7bc92023330293467) image for the Spanish translation of the book.  I believe there have been at least 2 successful builds after that, but the book cover does not seem to change and it still uses the old English version.  [This](https://progit2.s3.amazonaws.com/es/2016-03-23-ea7f6/progit-es.1091.pdf) is the latest build.  Any idea why this is happening?  Cheers!

**Comment by YueLinHo** [comment]
See issue #585.

**Comment by andres-mancera** [comment]
@YueLinHo :  I don't get it.  Can you please provide some context?

**Comment by YueLinHo** [comment]
> Can you please provide some context?

Someone reported #585, and I checked the auto-build for some translations here: https://progit.org/translations
Found that en and zh-tw stop to build downloads on **around 3/20**.

And I knew Atlas said something here: http://forum.atlas.oreilly.com/
(**Effective March 2016, the Atlas forum is no longer available.**)

So I guess that progit2 including translating repositoies rely **Atlas** for auto-building downloads, and Atlas stops to support that unfortunately.

For es version, the last good build is progit/progit2-es@ea7f6453ce9fd83b4e80ba66174709362e9444a5 which is on 3/23.
You can tell that by the link you provided:
https://progit2.s3.amazonaws.com/es/2016-03-23-ea7f6/progit-es.1091.pdf
Say `2016-03-23` and `ea7f6`.
The next commit which is a merge commit and **not built** is progit/progit2-es@59f78f3b607f075fb72b1b7d074da509a99160e5 which is on 3/30.

![tortoisegitproc](https://cloud.githubusercontent.com/assets/5831804/14549924/d6b7c390-02f6-11e6-8bec-92f5b1f1095c.png)

**Comment by jnavila** [comment]
Well, if you're right, then neither git-scm.com nor the pdf are updated with our changes, which means that we are working for nothing at the moment.

**Comment by andres-mancera** [comment]
Good info, thanks for sharing.  Perhaps @ben or @schacon can chime in and shed some light on this?

**Comment by andres-mancera** [comment]
Alright, so it seems like the issue with Atlas has finally gotten enought attention that @ben has opened an issue to keep track of it ([#625](https://github.com/progit/progit2/issues/625)).  Therefore, I am closing thism old issue as it's been opened for ~3 months.  Cheers!
