### ISSUE TITLE
Chapter 3.2 is not translated to Russian

### ISSUE THREAD

**Issue by belgoros** [progit/progit2#596]
The chapter [3.2](https://git-scm.com/book/ru/v2/%D0%92%D0%B5%D1%82%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2-Git-Rebasing) is not translated to Russian, just in the beginning. The rest is still in English.

**Comment by jnavila** [comment]
The translation to Russian is managed in the dedicated repo: 

https://github.com/progit/progit2-ru

At the moment, we have some issues deploying the book to git-scm.com and to the ebook formats.The section you are refering to is not yet translated so your contributions are welcome!

**Comment by RomanKrasavtsev** [comment]
Hi @jnavila,

There are 8 pull requests in repo from Feb and there are no any actions. How can we solve this issue?

**Comment by jnavila** [comment]
Unfortunately, I have push access only on progit/progit2, and no other privilege in the Progit organization. The only option is to try to reach the present maintainer of the repo, @sadfuzzy or even better @schacon to gain some access to this repo.

BTW, Scott, if you read this, is there a way I can have more privilege and unload you of these tedious tasks?

**Comment by jnavila** [comment]
@matthewmccullough , It seems you also have admin privileges in the organization. Can you help here?

**Comment by sadfuzzy** [comment]
Hey! I'll try to sort them out soon

**Comment by sadfuzzy** [comment]
Can you add some links?

**Comment by HonkingGoose** [comment]
@jnavila Is this something you still want open?

**Comment by jnavila** [comment]
I kept them as pointers to translations, but we now have a list in the TRANSLATING page. Thanks for triaging this.
