### ISSUE TITLE
Monospacing the iss53 in Figure 3-12

### ISSUE THREAD

**Issue by YueLinHo** [progit/progit2#598]
File: `book\03-git-branching\sections\basic-branching-and-merging.asc`
Line: 57

```
.The iss53 branch has moved forward with your work
image::images/basic-branching-3.png[The iss53 branch has moved forward with your work.]
```

The `master`, `hotfix`, the others of `iss53` get monospace, except above one.

Change to?

```
.The `iss53` branch has moved forward with your work
image::images/basic-branching-3.png[The `iss53` branch has moved forward with your work.]
```

**Comment by sivaraam** [comment]
I think it's just a image caption and changing that wouldn't be noticeable. I guess the monospace may not have effect as the image captions are italicised.

**Comment by ben** [comment]
I'd say go ahead, for correctness' sake.

**Comment by sivaraam** [comment]
>    I'd say go ahead, for correctness' sake.

As you wish. But is it good to monospace them in both the places mentioned above ? I'm not much familiar with the ASCIIDoc syntax used. What do the following lines do ?

`.The `iss53` branch has moved forward with your work`

 `image::images/basic-branching-3.png[The `iss53` branch has moved forward with your work.]`

**Comment by sivaraam** [comment]
I guess I found that. Just wanted to know, why is the title for that image specified separately if `asciidoctor` provides a syntax for specifying image titles. For example,

    image::sunset.jpg[caption="Figure 1: ", title="A mountain sunset", alt="Sunset", width="300", height="200", link="http://www.flickr.com/photos/javh/5448336655"]

**Comment by ben** [comment]
Remember this isn't just for HTML output, it's also for PDF and book output. So we need `title` and `alt` attributes for the image, but also the figure caption in print. Does that syntax do both?

**Comment by sivaraam** [comment]
>  Does that syntax do both?

I don't know exactly. 

Is it enough to monospace the first line alone ?

**Comment by ben** [comment]
Yeah, this is mostly about the figure title. Monospacing tool tips has no effect I think.

— Ben

**Comment by sivaraam** [comment]
> Monospacing tool tips has no effect I think. 

I had a doubt because other images in the book had monospaced in both places. For example you could find the following in line 138 & 139 in the [basic-branching-and-merging.asc](https://github.com/progit/progit2/edit/master/book/03-git-branching/sections/basic-branching-and-merging.asc) : 

    .Work continues on `iss53`
    image::images/basic-branching-6.png[Work continues on `iss53`.]

So, I thought monospacing is needed at both places but I also thought that adding the text to the second line may break any reference to that image used in other parts of the book. Hence, I wanted to be sure.

**Comment by ben** [comment]
References won't use the title text, you'd see something like `[[_figure_name]]` which would be referenced elsewhere as `<<_figure_name>>`. Go ahead and update both then, for consistency's sake.

**Comment by sivaraam** [comment]
👍
