### ISSUE TITLE
Does the design for distributing GPG pubkey really work?

### ISSUE THREAD

**Issue by zheeeng** [progit/progit2#599]
https://git-scm.com/book/en/v2/Distributed-Git-Maintaining-a-Project#Tagging-Your-Releases

This design don't separate the GPG pubkey from git repo, what if a hacker push a fake project contents which signed by fake private key and a fake pubkey tag annotate to remote repo? self verification?

I still think pub your pubkey on website or keyserver is the only way to distributing your pubkey. Any idea to discuss?

**Comment by YueLinHo** [comment]
I guess it needs a way to **TRUST** the public key stored in git repo. The way may be:

Take the example, the command gives the hash code:
```
$ gpg -a --export F721C45A | git hash-object -w --stdin
659ef797d181633c87ec71ac3f9ba29fe5775b92
```
say `659ef797d181633c87ec71ac3f9ba29fe5775b92`

and this command specifies the tag name
```
$ git tag -a maintainer-pgp-pub 659ef797d181633c87ec71ac3f9ba29fe5775b92
```
say `maintainer-pgp-pub`

Then, the project owner may announce:
```
    The public key is stored in git repo, you can confirm it by

    $ git show-ref maintainer-pgp-pub

    You should see this line:
    659ef797d181633c87ec71ac3f9ba29fe5775b92 refs/tags/maintainer-pgp-pub

    Only trush the public key if the SHA-1 value is exactly the same, 
    otherwise you should not trust it.
```

I think it is the similar way with announcing gpg Key-ID. Good for you?

**Comment by YueLinHo** [comment]
Or comparing the announced content of public key with that tag's content
say
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQENBFcXN...
...
kArXTXI=
=ClcS
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by zheeeng** [comment]
@YueLinHo Thanks for your reply. As you said, it is still necessary for having an announcement published by the owner in some other places? Why not just announce this pubkey on his/her site?

**Comment by YueLinHo** [comment]
To be, or not to be, **trust** is the question.

**Comment by YueLinHo** [comment]
@zheeeng I got one interesting paper for you, see https://mikegerwitz.com/papers/git-horror-story#trust.

**Comment by KZiemian** [comment]
I this issue still relevant today (August 2022)?

**Comment by ben** [comment]
Yeah, let's close it.
