### ISSUE TITLE
PDF version of Simplified Chinese Translation (zh_CN) has a font error

### ISSUE THREAD

**Issue by frogcjn** [progit/progit2#602]
most part of the PDF cannot be read.

https://progit2.s3.amazonaws.com/zh/2015-12-02-9d8a9/progit-zh.936.pdf

This link is from the git official page.
https://git-scm.com/book/zh/v2

**Comment by YueLinHo** [comment]
Please check if it is a duplicate #420. If so, please close it as duplicate.
