### ISSUE TITLE
'Greater than' (>) character in preformatted output displays as &gt; on the web

### ISSUE THREAD

**Issue by saj** [progit/progit2#603]
![screen shot 2016-04-21 at 01 08 20](https://cloud.githubusercontent.com/assets/194389/14679523/9473504c-075d-11e6-81e3-707404124b3d.png)

https://git-scm.com/book/en/v2/Git-Internals-The-Refspec as served up at 2016-04-20T15:10Z.

This may also impact `&` and `<` but this is the particular occurrence that jumped out at me.

**Comment by YueLinHo** [comment]
Please close it as duplicate #371.

**Comment by saj** [comment]
Sorry, I somehow missed that in my search.
