### ISSUE TITLE
Shoud use "he/she" for a partner, instead of "they".

### ISSUE THREAD

**Issue by YueLinHo** [progit/progit2#604]
File: `\book\03-git-branching\sections\remote-branches.asc`
Line: 15
```
If you were working on an issue with a partner and they pushed up an `iss53` branch, [...]
```

change to?
```
If you were working on an issue with a partner and he/she pushed up an `iss53` branch, [...]
```
they -> he/she

**Comment by nobozo** [comment]
On 4/26/2016 11:50 PM, Yue Lin Ho wrote:
> File: |\book\03-git-branching\sections\remote-branches.asc|
> Line: 15
>
> |If you were working on an issue with a partner and they pushed up an
> `iss53` branch, [...] |
>
> change to?
>
> |If you were working on an issue with a partner and he/she pushed up an
> `iss53` branch, [...] |

I recommend against this change. The English language is changing,
and "they" is now a reasonable replacement for he/she (or some variation).

The more important thing, however, is consistency. So, I recommend
making sure that one of the two forms is used consistently
through the book.

Jon Forrest

**Comment by YueLinHo** [comment]
> "they" is now a reasonable replacement for he/she (or some variation).

@nobozo Thanks for your comment! :+1: 

> The more important thing, however, is consistency. So, I recommend
making sure that one of the two forms is used consistently
through the book.

I've confirmed at least that "he/she" does not used at any place of v2.
