### ISSUE TITLE
[Migrate] [SVN] The word "authorization" in msg element

### ISSUE THREAD

**Issue by yelmontaser** [progit/progit2#611]
`$ svn log --xml | grep author | sort -u | perl -pe 's/.*>(.*?)<.*/$1 = /'` This command added the messages containing the word "authorization"

I propose
`$ svn log --xml | grep "<author>" | sort -u | perl -pe 's/.*>(.*?)<.*/$1 = /'``

**Comment by ben** [comment]
[Looks like](https://github.com/progit/progit2/pull/612#issuecomment-472215007) this was resolved by #600.
