### ISSUE TITLE
HTML ebook encodes `>` as `&gt;` in code examples

### ISSUE THREAD

**Issue by peff** [progit/progit2#613]
This was reported in https://github.com/git/git-scm.com/issues/753 as a problem on the git-scm.com site. The Pro Git content there is pulled from a pre-built HTML ebook via AWS.  That pre-built version already has the breakage in it, but I don't know how those are generated. You can see an example in section 9.2, in the `tf history` example. Some more details and wild speculation are in the git-scm issue linked above.

**Comment by YueLinHo** [comment]
This is a duplicate of #371. 
It looks like that it's the Atlas' problem, and Atlas stops to support. :-/

**Comment by peff** [comment]
Thanks, I agree it's the same issue. Closing in favor of #371.
