### ISSUE TITLE
[ja] Website shows "500 Internal server error"

### ISSUE THREAD

**Issue by m-takagi** [progit/progit2#615]
Japanese translation of progit2 ( https://git-scm.com/book/ja/v2 ) shows "500 Internal server error".

It looks like the build has no problem. ( https://progit.org/translations/lang/ja )

**Comment by harupong** [comment]
I've reported this to https://github.com/git/git-scm.com/issues/760

**Comment by crd** [comment]
Recommend closing -- @harupong opened up an issue on the git-scm.com repo.

**Comment by ben** [comment]
Awesome. Thanks!
