### ISSUE TITLE
git push --quiet option does not seem to work

### ISSUE THREAD

**Issue by codearoo** [progit/progit2#618]
Hi I am using 2.8.2.windows.1  and writing Powershell scripts doing some Git stuff.

I have to use the --quiet option for git because it constantly outputs progress to stderr.

However, it seems that --quiet does not actually work in git push. The output still goes to stderr.
When there are changes committed to push it always outputs something to stderr. If there is nothing to push, then it actually is silent.

**Comment by nobozo** [comment]
I'm not in charge but I'd suggest limiting messages to
issues with the book, not with Git itself.

If you think you've found a bug in Git, then there are
other, more appropriate, places to post it.

**Comment by codearoo** [comment]
ha! Yup. :)  I went to the Git site and found "report a bug" link.. and would never thought it would be about reporting bugs in the book. :)

So..  now I'm trying to find where the link from the git site is to report a bug with the software.
I think I found it.

**Comment by codearoo** [comment]
gosh darn it. The book and the website have easy Github issues you can log. But not Git.. gotta use mail list..  I am surprised these things are still used today.

**Comment by codearoo** [comment]
Really hate mail lists.  GMail does not seem to work when emailing to them. I have this issue for other mail lists. Wondering why we need this 1980's technology to log bug reports.

**Comment by codearoo** [comment]
oh.. I have to turn off HTML mode for the mail list to work. Still hate it. :)  An issue tracker seems ideal for this kind of thing.
