### ISSUE TITLE
Typo error regarding the location of Notepad++ on Windows

### ISSUE THREAD

**Issue by Dimitri06** [progit/progit2#623]
Page : 
https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

Error:

On a x86 system
$ git config --global core.editor "'C:/Program Files/Notepad++/notepad++.exe' -multiInst -nosession"
On a x64 system
$ git config --global core.editor "'C:/Program Files (x86)/Notepad++/notepad++.exe' -multiInst -nosession"

Solution:

On a x86 system
$ git config --global core.editor "'C:/Program Files (x86)/Notepad++/notepad++.exe' -multiInst -nosession"
On a x64 system
$ git config --global core.editor "'C:/Program Files/Notepad++/notepad++.exe' -multiInst -nosession"

Note: 
Program Files (x86) for x86 system, Program Files for x64 system

**Comment by YueLinHo** [comment]
There is no `C:/Program Files (x86)/` on x86 Windows.

And x64 Windows supports both win32 and x64 application, so 
`C:/Program Files (x86)/` is for win32 application, such as Notepad++, 
and 
`C:/Program Files/` is for x64 application.

**Comment by KingMax521** [comment]
it is just a typical example.The editor path is up to you.
It means `$ git config --global core.editor "'[notepad++.exe path]' -multiInst -nosession"`
Forget about the x86 or x64

**Comment by Dimitri06** [comment]
Ok, thanks. My bad :). I close the issue then.
