### ISSUE TITLE
Incorrect Rendering of Asciidoc Text

### ISSUE THREAD

**Issue by nobozo** [progit/progit2#626]
In  progit2/book/07-git-tools/sections/revision-selection.asc the Asciidoc text is rendered incorrectly at line 246, e.g. 'This can also be written `HEAD^^^`' comes out as 'This can also be written HEAD^'.
(Note the incorrect number of point characters.)

**Comment by YueLinHo** [comment]
> the Asciidoc text is rendered incorrectly

@nobozo I can't tell that. I see:

The screenshot of [web page](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#Ancestry-References):
![image](https://cloud.githubusercontent.com/assets/5831804/16548638/4db58942-41c6-11e6-9b05-b030863a6ad5.png)

The screenshot of [PDF](https://progit2.s3.amazonaws.com/en/2016-03-22-f3531/progit-en.1084.pdf) (page 258, 259):
![image](https://cloud.githubusercontent.com/assets/5831804/16548676/fdf8ad98-41c6-11e6-8ef0-5201cfacc0dd.png)

**Could you please post some screenshots to point out the issue?**

**Comment by nobozo** [comment]
On 7/3/2016 6:15 PM, Yue Lin Ho wrote:
>     the Asciidoc text is rendered incorrectly
>
> @nobozo <https://github.com/nobozo> I can't tell that. I see:

> *Could you please post some screenshots to point out the issue?*

Attached. This is from looking at the GitHub site for the
book in Chrome 51.0.2704.106 m on Windows 10 64-bit.
The same thing is true with Firefox.

It's correct in the pdf that I generated using the
method described in README.asc

Jon

**Comment by YueLinHo** [comment]
The link: https://github.com/progit/progit2/blob/master/book/07-git-tools/sections/revision-selection.asc

The screenshot:
![image](https://cloud.githubusercontent.com/assets/5831804/16549152/4f22a2f8-41ce-11e6-8802-9be367df65cb.png)

**Comment by nobozo** [comment]
On 7/3/2016 7:02 PM, Yue Lin Ho wrote:
> The link: https://github.com/progit/progit2/blob/master/book/07-git-tools/sections/revision-selection.asc
>
> The screenshot:
> image <https://cloud.githubusercontent.com/assets/5831804/16549152/4f22a2f8-41ce-11e6-8802-9be367df65cb.png>

Right. That shows the problem.

Jon

**Comment by jnavila** [comment]
If I understand correctly, this is a bug in the asciidoc renderer of GitHub, not a problem with the book. I don't know where the landing page for bugs in GitHub is.

**Comment by nobozo** [comment]
On 7/3/2016 11:46 PM, Jean-Noël Avila wrote:
> If I understand correctly, this is a bug in the asciidoc renderer of GitHub, not a problem with the book. I don't know
> where the landing page for bugs in GitHub is.

It's not just the asciidoc renderer on GitHub. I use the
asciidoctorjslivepreview extension for Firefox which also
renders it incorrectly.

Given Scott Chacon's connection with GitHub, I'm wondering
whether he might want to pursue this. It looks very minor but
I wonder how many other such occurrences of this problem exist
in the book, and elsewhere.

Jon

**Comment by jnavila** [comment]
For me, as long as it renders correctly on git-scm.com and in the books, the other renders can have all the bugs they want (because it's clearly a bug in those renderers).

**Comment by HonkingGoose** [comment]
@jnavila What do you want to do with this issue report?

---

From current ProGit2 v2 EN pdf:

![head_3_screenshot](https://user-images.githubusercontent.com/34918129/55517176-dec01680-566f-11e9-8f0d-1940b25193bc.png)

---

This also looks okay: https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection

**Comment by jnavila** [comment]
I guess it can be closed as-is.
