### ISSUE TITLE
Misspelling in chapter 5

### ISSUE THREAD

**Issue by LeonardLaszlo** [progit/progit2#628]
In the sentence below 'Affterthe' should be replaced with 'After the':

"Affter the integrators merge these branches into the mainline, a fetch will bring
down the new merge commit"

**Comment by YueLinHo** [comment]
On [page 168 of PDF (progit-en.1084.pdf)](https://progit2.s3.amazonaws.com/en/2016-03-22-f3531/progit-en.1084.pdf)

![image](https://cloud.githubusercontent.com/assets/5831804/17088072/df61df5c-5248-11e6-9f5a-a37bfe429912.png)

BTW, Looks OK on [web page](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project)

![image](https://cloud.githubusercontent.com/assets/5831804/17088040/64fbc3f4-5248-11e6-990c-45597f99ac58.png)

File: `\book\05-distributed-git\sections\contributing.asc` line 472 (OK, too)

**Comment by jnavila** [comment]
Oh. Another bug in Atlas' rendering engine, it seems.

**Comment by crd** [comment]
Recommending closing this issue as a rendering problem. See @YueLinHo's investigation.
