### ISSUE TITLE
Translation to Vietnamese

### ISSUE THREAD

**Issue by congdanhqx-zz** [progit/progit2#629]
Hi there,

I'm starting to translate progit v2 to Vietnamese at [https://github.com/congdanhqx/progit2-vi](https://github.com/congdanhqx/progit2-vi).

[This link](https://git-scm.com/book/vi/v1) is an incomplete (only 3 chapters) translated version of v1, however, it sounds unnatural to a native Vietnamese. Hence, I'm try to translate everything in this book.

I can translate 3 or more pages per week.

Could you open progit/progit-vi?

**Comment by jnavila** [comment]
The publishing script was updated for git-scm.com. So, if you create an organization for your translation repo, we could update git-scm to include the vietnamese translation.

**Comment by HonkingGoose** [comment]
@jnavila Do you want to have this open? The user @congdanhqx-zz has not been active on github since 2017.

Is this the official vietnamese repo?
https://github.com/progit2-vi/progit2
If so we need to mention it in the TRANSLATING.md file, because it isn't yet listed...

**Comment by jnavila** [comment]
I did not add it then because there was no translation, and it's still the case. Let's close this issue.
