### ISSUE TITLE
Russian translation of chapter 7.1 problem

### ISSUE THREAD

**Issue by NikitaLiashenko** [progit/progit2#632]
In chapter 7.1 of Pro Git 2 there is one big mistake in russian translation. The word "commit" was translated as "fixation" which can cause misunderstandings.

**Comment by hedrok** [comment]
https://github.com/progit/progit2-ru

**Comment by HonkingGoose** [comment]
@jnavila I think this one can be closed, it's not for the English version of the Pro Git 2 book, but for the Russian translation.
