### ISSUE TITLE
FIGURE 3-1 - A commit and its tree - Questions and improvements

### ISSUE THREAD

**Issue by wget** [progit/progit2#640]
Dear *,

The example provided in the chapter "Branches in a nutshell" only covers a situation with a root directory with only 3 files in it.

![progit2_20160808_vnc_sketch_0002_original](https://cloud.githubusercontent.com/assets/2997662/17491977/1a166bce-5daa-11e6-8827-2bba22039975.png)

Could we please change that example and integrate the situation comprising a subfolder with files in it?

I tried to modify the sketch file accordingly. Please correct me if the assumptions I made are correct or need changes.

![progit2_20160808_vnc_sketch_0004_export_modification](https://cloud.githubusercontent.com/assets/2997662/17492327/9941daf4-5dab-11e6-807a-64ea3ae4fb76.png)

I wanted to know if the subdirectory reference link will be stored in the first tree node or in the white/gray git object? And if the reference link of subfolders are usually stored in blob tree node?

**Comment by ben** [comment]
Well, given that this is an introductory chapter, we don't want to overwhelm with too much information. We do cover this later on [in chapter 10](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects#Tree-Objects), so the detail is there when it's appropriate.

**Comment by wget** [comment]
OK Then maybe, it would be cool to add a line in that introduction chapter "for more details how it works internally, please read chapter 10" or something like that. :-) 

Readers like me loves to read books chronologically, but sometimes we like to get the info immediately and having a chapter pointers would have been cool ;-)
