### ISSUE TITLE
Improving german translation

### ISSUE THREAD

**Issue by scytho** [progit/progit2#643]
Hi,

I’m new to Git and learning it by the/this book. Using the german translation I notice some bumps (grammar, spelling, expressions). I cannot put in much time at once, but over the next weeks I could gather corrections I would make and contribute them somehow, if wished. I just don’t know how, yet, as I’m new to Git.

Is there any interest?

**Comment by ben** [comment]
Wow, looks like there's no German translation of the second edition yet. If you'd like to start one, take a look at the directions at https://progit.org/translations.
