### ISSUE TITLE
GIT Submodules section missing a step

### ISSUE THREAD

**Issue by twekberg** [progit/progit2#658]
First of all I'd like to say how much I liked section 7.11 Git Tools - Submodules. It was exactly what I was looking for when I wanted to learn about GIT submodules.

Maybe it is too obvious, but there is a step missing in the first section, 'Starting with Submodules'. The end of the section says to commit your changes, which is great. I would add that the changes need to be pushed, doing something like:

> `git push origin master`

The example is using branch `master`. Now, admittedly, nothing specific to submodules is displayed during the push, but it is still an important step.

**Comment by ben** [comment]
That sounds like a fine idea. Care to submit a PR? I'd love if you got the git-blame credit for the improvement.

**Comment by twekberg** [comment]
Ben,

I don't see where one submits a PR. Would you mind giving me a link?

**Comment by ben** [comment]
Sure! This is one you could probably do in your browser. Just visit [the submodules section file](https://github.com/progit/progit2/blob/master/book/07-git-tools/sections/submodules.asc), and click the pencil icon at the top-right. Make your changes, scroll to the bottom, and click "propose change." That'll open a pull request, and we can discuss from there.

**Comment by twekberg** [comment]
Ben,

Thank your for your detailed instructions. There were a couple of other buttons to press to create the pull request, but intuition prevailed. The pull request is named:

> `GIT Submodules section missing a step.`

You probably already figured that out from the previous comment. I didn't see where one assigns the pull request to someone so I assume that is an automatic part of the workflow.
