### ISSUE TITLE
A possible slip in Chapter3.5

### ISSUE THREAD

**Issue by Carr1005** [progit/progit2#660]
On **Chapter 3.5 Git Branching - Remote Branches** under [Pushing](https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches#Pushing) paragraph :
There is some explanation after
```
$ git push origin serverfix
Counting objects: 24, done.
[...]
```

> This is a bit of a shortcut. Git automatically expands the serverfix branchname out to `refs/heads/serverfix:refs/heads/serverfix`, which means, “Take my serverfix local branch and push it to update the remote’s serverfix branch.”

Shouldn't it be `refs/heads/serverfix:refs/remotes/serverfix` ?
It confused me , sorry in advance if there is my misunderstanding .

**Comment by anatolyborodin** [comment]
@carr1005 did you close it because you got it?

**Comment by Carr1005** [comment]
@anatolyborodin  yes I got it after I read Chapter10 , my shame mistake~
