### ISSUE TITLE
Does "git log" example on p 65 of PDF version actually work?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#661]
Just tried example on p. 65, allegedly displaying commits that Junio Hamano committed to the kernel source "test" directory, but there's no output as it seems there is no such directory back then. What is that example supposed to do?

rday

**Comment by YueLinHo** [comment]
```
$ git log --pretty="%h - %s" --author=gitster --since="2008-10-01" \
 --before="2008-11-01" --no-merges -- t/
```

The ``t/`` means that test folder. See:

![image](https://cloud.githubusercontent.com/assets/5831804/18952416/09827686-867c-11e6-8981-8cbf9729e9e3.png)

(https://github.com/git/git)

**Comment by rpjday** [comment]
Ah, sorry, I read that page as referring to the official kernel source repo. My mistake.

**Comment by ben** [comment]
No worries, I'm glad you figured it out!
