### ISSUE TITLE
Link to http://git-prompt.sh is no longer good

### ISSUE THREAD

**Issue by msheaver** [progit/progit2#662]
In https://github.com/progit/progit2/blob/master/book/A-git-in-other-environments/sections/zsh.asc, the link to http://git-prompt.sh is no longer good. Since I do not know what this should be, I did not create a pull request for this issue. If I should do so, I trust that someone will show me how.

**Comment by ben** [comment]
Ooh, that's a nice catch. It doesn't look like there's a good substitute for that old site, so we can just link to that file in [the Git repository](https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh).

As for creating a PR, you're already in the right place. Visit [that file](https://github.com/progit/progit2/blob/master/book/A-git-in-other-environments/sections/zsh.asc), and click the ✏️ icon at top right. Make the edit, scroll to the bottom, and click "Propose changes".

**Comment by msheaver** [comment]
Ben, thanks for the guidance; I have made the edits and created the PR. One more noobie question: at what point do I close the PR? Now, or after it is either accepted or rejected?

**Comment by ben** [comment]
You did perfectly. PRs are closed when they're either merged or rejected. I went ahead and closed this, since it seems like it's addressed.

Thanks!
