### ISSUE TITLE
Unknown "git status --porcelain" status code

### ISSUE THREAD

**Issue by jean-christophe-manciot** [progit/progit2#664]
On Ubuntu **16.04** 4.4.0-38 with git **2.10.0**

I have encountered for the first time the following T status code:
```
git status --porcelain
 M group_vars/asav/snmp.yml
 T group_vars/ios/snmp.yml
 T group_vars/ios_xev/snmp.yml
 M group_vars/iosv/snmp.yml
 T group_vars/iosv_l2/snmp.yml
...
```
The [official documentation](https://git-scm.com/docs/git-status) does not talk about that new code.

   - Is this an issue or is the documentation incomplete?
   - In the latter case, what does this code mean?

Regards.

**Comment by jnavila** [comment]
This issue tracker is dedicated to the Progit book.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

**Comment by jean-christophe-manciot** [comment]
First off, I have already tried to send an e-mail to git@vger.kernel.org, but received the following message from mailer-daemon@googlemail.com:
```
Delivery to the following recipient failed permanently:
    git@vger.kernel.org

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain vger.kernel.org by vger.kernel.org. [209.132.180.67].

The error that the other server returned was:
550 5.7.1 Content-Policy reject msg: The message contains HTML subpart, therefore we consider it SPAM or Outlook Virus.  TEXT/PLAIN is accepted.! BF:<U 0.490901>; S1754078AbcJDNA0
```
There was nothing special in my e-mail except a link to <https://git-scm.com/docs/git-status>.

Secondly, it **does not look like a git issue**, but rather to an **undocumented upgrade** available only in the **last release**.

**Comment by ben** [comment]
Yeah, the `T` status doesn't seem to be documented anywhere (not even in the man page with 2.10.0). 

> Secondly, it does not look like a git issue, but rather to an undocumented upgrade available only in the last release.

The Git project team does its own documentation, so something that's wrong or missing in the man pages is still a "git issue." 

Whenever we figure out what it is, it might warrant a mention in the book, but until then I'm going to close this out.

**Comment by jnavila** [comment]
The reason your email was rejected is clear from the error message: it contains HTML. Disable HTML in your mail user agent and everything should go smoothly.

**Comment by jean-christophe-manciot** [comment]
Impossible to disable HTML with gmail AFAIK.
I have no clue why HTML is rejected. Why don't they accept it?.

**Comment by jnavila** [comment]
http://vger.kernel.org/majordomo-info.html for more info

**Comment by jean-christophe-manciot** [comment]
I find this "security" measure insane.
The hackers breathe, why don't "security guys" prevent all people from breathing?

**Comment by jnavila** [comment]
It's just a matter of trying to hold back the spam, force people to focus on the messages, have a normalized way to interact: most patches are passed through the mailing list and are consumed by git.

**Comment by jnavila** [comment]
Just for the record the "T" status is an indication of "change of type".
