### ISSUE TITLE
A number of minor observations on first part of Pro Git Book

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#667]
Not really much value in scattering these across several issues, just things I've noted in my travels.
- p. 35: "The working directory is a single checkout of one version of the project." Well, that's the _typical_ situation, sure, but you can always checkout an earlier version of any subset of your working directory.
- EVERYWHERE: References to "yum" for installation should be enhanced with references to "dnf" as well.
- p. 37: "OSX" should be "OS X", no?
- p. 51 (sample .gitignore snippet at top of page): References to "the build/ directory" and "the doc/ directory" ... since those names don't start with a leading slash, would that not be more correctly described as _any_ current or lower-level build/ or doc/ directory?

That's all I have for now, I'll take some time today and create and push a few patches.

rday

**Comment by ben** [comment]
Hey, thanks for the feedback! Some notes:

* Technically speaking this entire sentence isn't true. `HEAD` refers to a place on the commit tree, but the worktree is its own thing. Given that this is literally the first section of the book that explains what the worktree is, I'd give some leeway about technical correctness. Do you think what's there gets the idea across, or could it be better?

* Is `dnf` widespread enough that readers can rely on it being on their system? If so, then yeah, go for it.

* We should probably replace both with "macOS" at this point.

* Yeah, this should probably say things like `ignore all files in any directory named "build"`.

Looking forward to your patches!

**Comment by rpjday** [comment]
Since I'll be incorporating all of this in other pull requests, I can close this off.
