### ISSUE TITLE
Expired SSL cert on https://progit.org/

### ISSUE THREAD

**Issue by Graham42** [progit/progit2#672]
There's an SSL error on https://progit.org/ `NET::ERR_CERT_DATE_INVALID` 
![image](https://cloud.githubusercontent.com/assets/2476733/19706047/d6aa2e9a-9add-11e6-996a-be1f65f39c6d.png)

**Comment by ben** [comment]
Paging @schacon!

**Comment by schacon** [comment]
Uugggggggghhhhhh. So, this was on a DigitalOcean droplet and has not come back up well. It was way too complex so that I could run the Atlas stuff, but since that's now defunct I suppose we should simplify this and just move it to Heroku. I'll work on that asap (and add you to it, @ben). Sorry about this - it will be a day or so.

We should figure out if we want to keep doing automatic builds and if so, how we're going to accomplish it now.

**Comment by jnavila** [comment]
Deploying the html files on the site can be done the same way we were doing it for the first edition. We started a discussion at #625 

The publication to pdf and ebooks is the hard spot in this.

**Comment by kberov** [comment]
I was trying to read  http://progit.org/translations because I want to start translation to Bulgarian, but then I got:
```
progit.org uses an invalid security certificate.
The certificate expired on 18.10.2016 02:14. The current time is 8.11.2016 20:56.
Error code: SEC_ERROR_EXPIRED_CERTIFICATE
```
and after that I got "502 Bad Gateway"

Where can I read about how to start a new translation. How to add the new repo under the progit organisation, etc.?
Thank you and regards

**Comment by jnavila** [comment]
Hey @schacon What's on your mind for this? Do you need a (weak) hand? Should we try to mimic the processing for the first edition?

**Comment by crd** [comment]
I see the ebooks are hosted on s3 -- publishing to s3 is as simple as running a lambda script which is free for the first million calls. I can help with that.

**Comment by KZiemian** [comment]
Should this issue remain open?

**Comment by ben** [comment]
http://progit.org now hosts some kind of magazine in French. Going to close this for now.

**Comment by crd** [comment]
I grepped the source and the original domain is no longer referenced. I agree with closing the issue. Thanks!
