### ISSUE TITLE
Not sure how to start a new translation when http://progit.org/translations is not accesible.

### ISSUE THREAD

**Issue by kberov** [progit/progit2#679]
I was trying to read  http://progit.org/translations because I want to start translation to Bulgarian, but then I got:
```
progit.org uses an invalid security certificate.
The certificate expired on 18.10.2016 02:14. The current time is 8.11.2016 20:56.
Error code: SEC_ERROR_EXPIRED_CERTIFICATE
```
and after that I got "502 Bad Gateway"

Where can I read about how to start a new translation. How to add the new repo under the progit organisation, etc.?
Thank you and regards

**Comment by ben** [comment]
Yeah, this is known. @schacon is working on it over in #672.

**Comment by kberov** [comment]
Yes, I commented there, but there was not answer and I created this issue.
Thanks!

**Comment by kberov** [comment]
@ben , I forked the repository, but I read it should be under the progit organisation. Who can do this for me?
