### ISSUE TITLE
Incorrect examples in commit ranges?

### ISSUE THREAD

**Issue by Chiel92** [progit/progit2#680]
In https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#Commit-Ranges, about commit ranges, the examples seem incorrect to me. E.g. I would expect the first example to be

```
$ git log master..experiment
experiment
D
C
```

instead of just

```
$ git log master..experiment
D
C
```

The end-of-range-marker is inclusive, correct?

**Comment by ben** [comment]
Sometimes. `master` and `experiment` are branch refs, not commits; they're not _nodes_ in the graph, they're _annotations_ on commit nodes. This means that when `git log` walks the graph, it doesn't visit `master` and `experiment`, it only uses those names as pointers for where to start walking.

Having said that, it's possible to get `git log` to output refs using the `--decorate` flag, but they're shown as annotations for a commit:

```
$ git log --oneline --decorate
bea17a4 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #677 from kausar007/master
b0580d2 Merge pull request #678 from patrick96/attributes
27c22f2 Surround docx path with quotes
cb44372 Add git remote remove command
930625e Merge pull request #676 from kausar007/master
# […]
```

Does that make sense?

**Comment by Chiel92** [comment]
> Sometimes. master and experiment are branch refs, not commits; they're not nodes in the graph, they're annotations on commit nodes.

Okay, I interpreted them as separate commits, with incidental branch names. Instead, if I understand correctly, master actually is *at* commit `F`.

If there is a way to make that more clear, I think it would improve the explanation. Maybe be by putting the branch names over the commits, instead of beside them.
