### ISSUE TITLE
Installing git from source requires on ubuntu need addinional packages 

### ISSUE THREAD

**Issue by oliworx** [progit/progit2#682]
Install git from source requires on Ubuntu 16.04 need addinional packages, like `autoconf` and `asciidoc`

**Comment by YueLinHo** [comment]
Is `dh-autoreconf` a superset of `autoconf`?

and about `asciidoc`:

![image](https://cloud.githubusercontent.com/assets/5831804/20584352/bdc4c974-b22c-11e6-89b5-d8b566303439.png)
(See [here](https://github.com/progit/progit2/blob/bea17a4447b34b7a0063ad9e4e3692ffd752a41f/book/01-introduction/sections/installing.asc))

**Comment by YueLinHo** [comment]
cf. issue #579 and PR #581

**Comment by ben** [comment]
Yeah, it looks like this is addressed in the online version. Feel free to reopen or submit a PR if there's more to be done. Thanks!
