### ISSUE TITLE
Bug on creating branch with '/'

### ISSUE THREAD

**Issue by Diagon** [progit/progit2#687]
Branch 1: 'name'
Branch 2: 'name/feature'

error: unable to create directory for .git/logs/refs/remotes/origin/name/feature

**Comment by ben** [comment]
Well, yeah. You can't have a file named `foo` and a directory named `foo` in the same place.

Do we do this somewhere in the text? If so, that should be corrected.

**Comment by YueLinHo** [comment]
> Do we do this somewhere in the text? If so, that should be corrected.

@ben
I search all files with keywords `git branch` and `git checkout`. Looks like we don't have that.

----
@Diagon
Usually, you need to delete the **local branch** `name` first if you want to create a **local branch** `name/feature`.

But, when I see `.git/logs/refs/remotes/origin/name/feature`, I am curious about something:
Which command do you use?

**Comment by ben** [comment]
Going to close this, since it isn't technically a problem with the book. If you'd like to report this as a bug for Git itself, send an email to the mailing list at git@vger.kernel.org.
