### ISSUE TITLE
Build output does not match https://git-scm.com/book/en/v2

### ISSUE THREAD

**Issue by hq6** [progit/progit2#688]
On the [website](https://git-scm.com/book/en/v2) which links to this source, each section of each chapter is a separate HTML page.

However, when I build this source using the directions in the README, I get one monolithic HTML file.

Please add some instructions in the README for building html output that matches the website.

**Comment by jnavila** [comment]
The main html file is split into pieces by a special script that is managed on the git-scm project. There is no simple way to mimic it.

**Comment by hq6** [comment]
Is the script available somewhere public?

Thanks!

**Comment by jnavila** [comment]
Here it is:

https://github.com/git/git-scm.com/blob/master/lib/tasks/book2.rake

The input is the archive processed by Atlas, the service from O'Reilly.
