### ISSUE TITLE
Change section title "Workflows summary"

### ISSUE THREAD

**Issue by sivaraam** [progit/progit2#692]
I guess it the title _Workflows summary_ for the subsection under the _Contributing to a Project_ in Chapter 5 is a bit misleading because a summary is something that summarizes the previously explained text. The section doesn't summarize, though.

**Comment by ben** [comment]
I'm a bit confused. _Contributing to a Project_ doesn't have a section titled "Workflows Summary," it's just called ["Summary"](https://www.git-scm.com/book/tr/v2/Distributed-Git-Contributing-to-a-Project#Summary). The ["Workflows Summary"](https://www.git-scm.com/book/tr/v2/Distributed-Git-Distributed-Workflows#Workflows-Summary) section is in the _Distributed Workflows_ section.

Both of them try to summarize their respective sections. Is the issue here that they're not particularly good summary sections? Or is it that one is better than the other? What kind of action could be taken to close this issue out?

**Comment by sivaraam** [comment]
Sorry, I forgot to mention the section in my comment.

In general I thought that a summary is something that concisely restates what is explained elaborately. From a dictionary,
>Presenting the substance in a condensed form
I don't think that the Workflows Summary does that. In fact there's another subsection called Summary_ in the next section _Contributing to a Project_ , that also doesn't seem to be summarizing. I thought they are more of a _conclusion_ than of _summary_. I can't think of exact words that could fit in well but could only think that the word _summary_ didn't fit in well.

**Comment by ben** [comment]
Yeah, most of our "summary" sections are more like "conclusion" sections. I'd rather the section titles be consistent through the whole book than they pedantically reflect what that section does, though.

**Comment by sivaraam** [comment]
>Yeah, most of our "summary" sections are more like "conclusion" sections. I'd rather the section titles be consistent through the whole book than they pedantically reflect what that section does, though.

Is it be a good idea to replace the section titled _Summary_ in "every part" of the book to something more apt ? That would not confuse the reader who would be expecting a "summary". Sorry, if I am asking something wrong.

**Comment by ben** [comment]
I personally don't think this is a huge deal, or that readers are overly confused by it, but you seem more sensitive to this than I am. Want to put together a PR so we can see what the result would look like?

**Comment by sivaraam** [comment]
>I personally don't think this is a huge deal, or that [readers are overly confused by it], but you seem more sensitive to this than I am. 

I just thought that it would be better if the book were consistent with it's wordings with other books which summarize in the "Summary" section. Anyways instead of providing a "Summary" in each section titled " [*] Summary" in the book, I thought it would better if the title of those sections were changed into something more apt. This was just my thought anyway :)

>Want to put together a PR so we can see what the result would look like?

In case there's no problem for you, I could do that but as I mentioned before I could not think of an apt word that could replace "Summary". Could you provide some suggestions ?

**Comment by HonkingGoose** [comment]
@ben What are your thoughts now on this? Want a pull-request so you can see what it would look like? Or do you want to close this issue?

**Comment by ben** [comment]
I'd be happy to see a proposal for something better, but if there isn't a significant improvement to be made we should close this out as unactionable.
