### ISSUE TITLE
Code samples cross borders in PDF version of the book

### ISSUE THREAD

**Issue by sivaraam** [progit/progit2#695]
The code samples found in the PDF version of the book seems to be crossing the border that's generated around it. A few examples could be found in pages 172, 180, 181, 192. A sample

![image](https://cloud.githubusercontent.com/assets/12448084/21353223/130b8580-c6eb-11e6-81d1-8cfb020d5443.png)

**Comment by sivaraam** [comment]
A even worse version of this problem can be found at `page 272` of the book where the last code sample has some output truncated.

**Comment by HonkingGoose** [comment]
@jnavila I think this was fixed with the Asciidoctor build system now?

**Comment by jnavila** [comment]
Yes, the verbatim lines are broken at the end. The rendering isn't always fine, but at least this issue is fixed.
