### ISSUE TITLE
Adding a footnote regarding the a statement in the commit template

### ISSUE THREAD

**Issue by sivaraam** [progit/progit2#696]
In the commit template found in the _Commit Guidelines_ subsection of the _Contributing to a Project_ section, there's a line that reads like this,

**The blank line separating the summary from the body is critical (unless you omit the body entirely); tools like rebase can get confused if you run the two together.**

It would be better if the reason, why tools like rebase get confused was stated probably as a footnote (concisely, of course). It would help the reader to be more aware of it.

**Comment by HonkingGoose** [comment]
Well I tried breaking the `git rebase -i` tooling by crafting some malformed commits and trying to fixup and squash the malformed commit message, and that worked fine, I got no error messages. 
Maybe the issue of a missing blank line between title and body breaking `git rebase` has been fixed upstream. Or I'm not hitting the right edge-case, that is a possibility also.

I scanned the git scm manual for the [rebase](https://git-scm.com/docs/git-rebase/2.28.0) tool, and the commit message breaking the tooling is not mentioned there. It's not listed as a known [bug](https://git-scm.com/docs/git-rebase/2.28.0) in the rebase docs.

Even if the rebase tool can be broken, I do not think that a section on writing good commit messages should dive into the specifics of the rebase tooling. If this is to be covered, I do not think we should cover it in this part of the book.
Also this seems to be a edge-case, and I couldn't find documentation on when this edge-case occurs, or why it occurs, so I wouldn't be able to add the footnote anyways.

@ben what do you think about this issue?

**Comment by ben** [comment]
I think the reason that "confused" was the verb there is that it won't actually break a rebase, but it does make an interactive rebase harder to do. `git rebase -i` will dump you into a file where every line is a commit, and the commit messages are the first "line" of the commit. If there's no blank line they get all smashed together, and aren't very readable.

So yeah, "critical" isn't exactly the correct word here, but it is a norm with tools built around it.
