### ISSUE TITLE
Probability of getting killed by wolves greatly overestimated

### ISSUE THREAD

**Issue by jwilk** [progit/progit2#700]
`revision-selection.asc` reads:

> If all 6.5 billion humans on Earth were programming, and every second, each one was producing code that was the equivalent of the entire Linux kernel history (3.6 million Git objects) and pushing it into one enormous Git repository, it would take roughly 2 years until that repository contained enough objects to have a 50% probability of a single SHA-1 object collision.

So far so good.

> A higher probability exists that every member of your programming team will be attacked and killed by wolves in unrelated incidents on the same night.

Er, no, I'm pretty sure that probability of the team getting killed by wolves is much less than 50%...

**Comment by ben** [comment]
Ha! Want to submit a PR that fixes that last sentence? Something like:

> A SHA-1 collision is less likely than every member of your programming team being attacked and killed by wolves in unrelated incidents on the same night.

🐺🐺🐺🐺🐺🐺🐺🐺

**Comment by jnavila** [comment]
I'd really like to have a look at the calculation that led to that assertion though :smiling_imp:

**Comment by jwilk** [comment]
> Want to submit a PR that fixes that last sentence?

Sorry, no time for this. :(
