### ISSUE TITLE
An illustration in Chapter 5 is missing an arrow

### ISSUE THREAD

**Issue by sivaraam** [progit/progit2#701]
The [final illustration](https://github.com/sivaraam/progit2/blob/master/book/05-distributed-git/images/small-team-flow.png) in the _Private Small Team_ of the _Contributing to a Project_ section is good but I guess a `git commit` arrow is missing in the flow of Jessica. The illustration is shown below : 

![image](https://cloud.githubusercontent.com/assets/12448084/21512559/de5f41ba-ccd4-11e6-9b0c-bbe027aea92e.png)

**Comment by ben** [comment]
For reference, here are the actual commands Jessica uses in the relevant part of [that section](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#Private-Small-Team):

```shell
$ git fetch origin
$ git log --no-merges issue54..origin/master
$ git checkout master
$ git merge issue54
$ git merge origin/master
$ git push origin master
```

So technically there are two merges between the fetch and the push. However, here's the paragraph just above the figure:

> That is one of the simplest workflows. You work for a while, generally in a topic branch, and merge into your master branch when it’s ready to be integrated. When you want to share that work, you fetch and merge your master from origin/master if it has changed, and finally push to the master branch on the server. The **general sequence** is something like this:

(Emphasis added.) This figure isn't meant to be a transcription of everything each member of the team does, it's meant to show the general pattern of working on a team like this. In that context, it's better to have a consistent visual rhythm than to exactly show all the commands used in the example above it.
