### ISSUE TITLE
Getting a repository section has plain text rendered as monospaced

### ISSUE THREAD

**Issue by I82Much** [progit/progit2#709]
In https://github.com/progit/progit2/blob/master/book/02-git-basics/sections/getting-a-repository.asc, 

all of this text renders incorrectly:

 initializes a .git directory inside it, pulls down all the data for that repository, and checks out a working copy of the latest version. If you go into the new libgit2 directory, you’ll see the project files in there, ready to be worked on or used. If you want to clone the repository into a directory named something other than libgit2

I suspect it's because you use `` to start a quote, and it actually surrounds all of the text from the first ` to the closing ` as monospaced.

**Comment by I82Much** [comment]
Same problem in https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository

Screenshot:

![image](https://cloud.githubusercontent.com/assets/20299/22089369/87b2d7f6-dd9f-11e6-8c93-b3d1d91f3b71.png)

**Comment by ben** [comment]
Looks like a problem with the [new rendering toolchain](https://github.com/git/git-scm.com/pull/917). The backticks _should_ be interpreted as smart quotes, not as monospace delimiters.

**Comment by ben** [comment]
I've reported this [over at the website repo](https://github.com/git/git-scm.com/issues/925), the fix will be in that code.
