### ISSUE TITLE
progit2/book/02-git-basics/sections/remotes.asc

### ISSUE THREAD

**Issue by FellowsDevel** [progit/progit2#717]
Pushing to Your Remotes

When you have your project at a point that you want to share, you have to push it upstream. The command for this is simple: git push [remote-name] [branch-name]. **If you want to push your master branch to your origin server** (again, cloning generally sets up both of those names for you automatically), then you can run this to push any commits you’ve done back up to the server:

$ git push origin master

******************************************************************
Is this sentence correct? "If you want to push your master branch to your origin server"

Or should be: "If you want to push your **origin** branch to your **master** server"

**Comment by ben** [comment]
Nope, it's correct. `master` is a branch name, `origin` is the name of a remote. You push branches to remotes, not the other way around.

**Comment by FellowsDevel** [comment]
okay then, but seems confusing because of the command:

$ git push origin master

Feels like this direction: origin -> master

Is "origin" a local alias to a remote branch name "master"?


Thanks anyways!

**Comment by ben** [comment]
I think the reasoning there is that you can push more than one branch at a time, like so:

```shell
$ git push origin master feature1 bugfix2
```

But yeah, it can be confusing when you see it first. I still always have to look up the order of arguments to `ln -s`. 😄
