### ISSUE TITLE
dependencies for installing documentation

### ISSUE THREAD

**Issue by flip111** [progit/progit2#718]
http://git-scm.com/book/en/v2/Getting-Started-Installing-Git#Installing-from-Source

this section does not mention you need `asciicode` -> `xmlto` -> `getopt`

original issue from: https://github.com/git/git-scm.com/issues/493

**Comment by ben** [comment]
I'd _love_ for these directions to be more complete and correct. Care to submit a PR? The file you want to modify is [this one](https://github.com/progit/progit2/blob/master/book/01-introduction/sections/installing.asc).

**Comment by flip111** [comment]
ok https://github.com/progit/progit2/pull/719
