### ISSUE TITLE
Clarification needed as to when remote-tracking branches are updated.

### ISSUE THREAD

**Issue by tomekd789** [progit/progit2#721]
https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches
has got

_Remote-tracking branches are references to the state of remote branches. They’re local references that you can’t move; they’re moved automatically for you whenever you do any network communication._

and then, few lines below

_To synchronize your work, you run a git fetch origin command. This command looks up which server “origin” is (in this case, it’s git.ourcompany.com), fetches any data from it that you don’t yet have, and updates your local database, moving your origin/master pointer to its new, more up-to-date position._

Does "any network communication" then mean "git fetch"?

**Comment by ben** [comment]
Basically, yeah. I guess the wording in the first paragraph isn't super exact, but since this is only chapter 2 we wanted to keep it colloquial, and not hammer in too many technical details. I'm open to a PR that increases the readability here, though.
