### ISSUE TITLE
Section 10.2: Git Internals - Git Objects, Figure 3 is not "All the objects in your Git directory."

### ISSUE THREAD

**Issue by saadlu** [progit/progit2#725]
References here:

https://github.com/progit/progit2/blob/master/book/10-git-internals/sections/objects.asc

which points to https://github.com/progit/progit2/blob/master/book/10-git-internals/images/data-model-3.png

is depiction of all the objects but missing the blob

`d670460b4b4aece5915caf5c68d12f560a9fe3e4`

Basically the object listing by `find .git/objects -type f` shows 10 objects, but the figure shows 9. The missing one is the orphan one - not pointed by any other objects. Therefore the caption isn't really "All the objects in your Git directory." :)

**Comment by ben** [comment]
Okay okay, you caught us. Want to submit a PR to correct this? Maybe title it "all the reachable objects in your Git directory."

**Comment by saadlu** [comment]
lol, didn't mean to criticise :P 

Yeah, I will create a pull request for this, unless someone beats me to it :)
