### ISSUE TITLE
Suggest updating Apache configuration

### ISSUE THREAD

**Issue by daviesj** [progit/progit2#730]
I recommend updating the Apache configuration example on the [Smart HTTP](../blob/master/book/04-git-server/sections/smart-http.asc) section. Using the new authorization system in Apache 2.4 would simplify the configuration and remove the dependency on `mod_rewrite`. In fact, the `Order`, `Allow`, and `Deny` directives [are deprecated](https://httpd.apache.org/docs/2.4/howto/access.html). This change would not be backward compatible with Apache 2.2, but 2.4 has been out quite a while now and even Debian stable has been using Apache 2.4 for almost a couple years now.

**Comment by ben** [comment]
Closed with #731.
