### ISSUE TITLE
Not working url to http://progit.org/translations

### ISSUE THREAD

**Issue by akittino** [progit/progit2#735]
https://github.com/progit/progit2/blob/master/CONTRIBUTING.md 
in Translations http://progit.org/translations url is not working. 502 Bad Gateway

**Comment by jnavila** [comment]
Ah. this workflow no longer exist. So I guess the section should be reworked.

**Comment by obitow** [comment]
@jnavila What's the new workflow for adding a new translation?

**Comment by jnavila** [comment]
For now, the workflow only allows to publish to the pages of the git-scm.com site. Create a repository for a given language, then send a PR like https://github.com/git/git-scm.com/pull/869 and https://github.com/git/git-scm.com/pull/933

If you don't feel ok with the last part, I can help.
