### ISSUE TITLE
Please update the outdated information

### ISSUE THREAD

**Issue by Explorare** [progit/progit2#736]
For page https://git-scm.com/book/gr/v2/Git-Tools-Credential-Storage

>If you’re using Windows, you can install a helper called “winstore.” This is similar to the “osxkeychain” helper described above, but uses the Windows Credential Store to control sensitive information. It can be found at https://gitcredentialstore.codeplex.com.

The project "Windows Credential Store" is no longer maintained and has been replaced by [Microsoft/Git Credential Manager for Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows).

**Comment by ben** [comment]
Dang, I hate it when we have outdated information. Want to submit a PR?
