### ISSUE TITLE
PDF link missing?

### ISSUE THREAD

**Issue by Vangelis66** [progit/progit2#747]
> The easiest way is simply to let us do it. A robot is standing by to look for new work on the main branch 
> and automatically build it for everyone.
> 
> You can find the current builds on http://git-scm.com/book.

... Apologies for being ...thick (!), but once I visit referenced link I fail to spot "current builds"; 
I distinctly remember a pdf link being available there, last time I visited I fetched file "**progit-en.1067.pdf**" with a PDF modification timestamp of 20160309 (still on disk today). Is this link not available anymore? 
FWIW, https://github.com/progit/progit2/releases only provide **progit-2.0.0.pdf** with a PDF modification timestamp of 20141021. 

EDIT: Thanks to the Internet Archive, it appears the download links were removed after 20170309 (last capture with the links showing up; PDF link points to file **progit-en.1084.pdf** with a 20160323 PDF timestamp) ; so, if this was intentional, references on README.asc should be removed now...

**Comment by jnavila** [comment]
True, true. Much of the work took place in the git-scm repo, but we forgot to update the README here.

**Comment by Vangelis66** [comment]
> Much of the work took place in the git-scm repo

So I've searched and indeed found https://github.com/git/git-scm.com/pull/983 that was merged on 20170311; 
is that a permanent removal and if not, any speculation as to when the PDF link'll be restored? 
Have always been a fan of the PDF format of the Git Book ...
Thanks.

**Comment by jnavila** [comment]
Unfortunately, the building robot is no longer available. We replaced it with a direct publishing to the git-scm website, but all ebooks are missing. I didn't find a simple way to generate the pdf. What you can do is build the PDF from the repo, the scripts for this are quite accessibles.

**Comment by brunen9** [comment]
Here are ebooks builded at 2016/05/01: https://drive.google.com/drive/folders/0BzAMsjLtoLg-NFFHdGdBb3Qyd1E?usp=sharing

**Comment by Vangelis66** [comment]
@brunen9 

Many thanks for those 👍 
Being on Windows (Vista), it's quite cumbersome to generate the PDF version locally 
from the repo scripts ;-( ; so your offerings are highly appreciated! 

Cheers

**Comment by MichaelTiernan** [comment]
Thanks to brunen9 for providing the prebuilt books.
May I point out that the README file in the source doesn't specify the tools the building the books requires.

I've added asciidoctor to my system and have yet to find the "bundle" command.

It would be nice/important to have a prerequisite section.

**Comment by jnavila** [comment]
@MichaelTiernan You don't need bundle in fact. That's some reminiscence of the "Ruby" everywhere Motto that was hitting at the time of starting the book.

Just type:

```
asciidoctor-pdf progit.asc
 ```

And enjoy !

**Comment by sivaraam** [comment]
Should the `README` be updated to reflect the current state ?

**Comment by justinclift** [comment]
@jnavila That's good info.  Can the README.md please be updated to include that (and other similar info)?

I tried building on FreeBSD earlier today, which barfed as one of the Ruby gems needed for the ebook generation refused to build.  "Host OS not supported" or some similar message (it was a few hours ago).

If the README gave the commands for just building the PDF without needing the ebook bits installed, that would have been nifty. :wink:

**Comment by tyrann0us** [comment]
[progit.pdf](https://github.com/progit/progit2/files/1182726/progit.pdf) @ c337c6afc55a8b5848d44d35e7f2945f95cda912.

**Comment by jtcmedia** [comment]
In case this is of use to someone, I made a quick and dirty YAML CI file that runs on GitLab https://gitlab.com/jc-camosun/pro-git-book-pdf-generator that generates the PDF. Anyone should be able to run the Pipeline to re-generate it if needed.

**Comment by Vangelis66** [comment]
This is awfully nice Jason :+1: 

Downloads -> Artifacts -> Download 'pdf' and unzipping yields a fine progit.pdf file...

**Comment by TimoSolo** [comment]
> Unfortunately, the building robot is no longer available. We replaced it with a direct publishing to the git-scm website, but all ebooks are missing.
~ @jnavila 

Is someone working on a bot to build the ebooks automatically?  It would be a great contribution to humanity! :D I've scoured the web but can't find any that use the latest version.

If I get >10 👍  I will attempt to build it..

**Comment by clfsoft** [comment]
the generated pdf book missing the index part

**Comment by sivaraam** [comment]
> In case this is of use to someone, I made a quick and dirty YAML CI file that runs on GitLab https://gitlab.com/jc-camosun/pro-git-book-pdf-generator that generates the PDF. 

Thanks for the great work! I just made a 'Merge request' to fix a small regression as a consequence of d2152ec39f6ba471bdbe486ef7bafa2511e7f818

> Anyone should be able to run the Pipeline to re-generate it if needed.

@jtcmedia Only part of this statement seems to be true. I could access the Pipeline but I could run it only in my fork of your repository. Am I missing something?

**Comment by jtcmedia** [comment]
@sivaraam thanks for the merge request.  My bad, that's right, you can't run the Pipeline. I've scheduled it to run daily.

**Comment by HonkingGoose** [comment]
@jnavila What do you want to do with this issue?

https://git-scm.com/book/en/v2 has a link to download a PDF file.

**Comment by Vangelis66** [comment]
Belated thanks to everyone involved 👍 

@HonkingGoose :

Closing this now...
