### ISSUE TITLE
Cross references are generated incorrectly for EPUB and MOBI

### ISSUE THREAD

**Issue by georgerbr** [progit/progit2#762]
These were generated from 6fbe525 on a vanilla Ubuntu 16.04 VM, with

```
bundle install
bundle exec rake book:build
```

![epub](https://cloud.githubusercontent.com/assets/4930759/26788993/467fd808-49e5-11e7-91e3-2309c3644dbf.png)

![mobi](https://cloud.githubusercontent.com/assets/4930759/26788999/4ec05da8-49e5-11e7-8ca3-58e17d8e598a.png)

Whereas they are generated correctly for HTML and PDF:

![html](https://cloud.githubusercontent.com/assets/4930759/26789012/5a4963cc-49e5-11e7-88ba-428f067764c2.png)

![pdf](https://cloud.githubusercontent.com/assets/4930759/26789039/701d38d6-49e5-11e7-9399-57a3d8f0829f.png)

**Comment by jnavila** [comment]
Hi,

The problem is reproducible. Unfortunately, I think, it is more a bug in asciidoctor than in the book. For some unknown reasons, cross-links across included contents are not resolved.

**Comment by jnavila** [comment]
Looking further into that matter, it seems that asciidoc-epub3 requires a very stringent structure of the files of the book, which is not followed by Progit2 (https://github.com/asciidoctor/asciidoctor-epub3#composition-rules). So I guess we cannot do anything except start a very heavy lifting of the structure of the book.

**Comment by georgerbr** [comment]
I understand. Thanks!
