### ISSUE TITLE
Please adding group commits feature

### ISSUE THREAD

**Issue by hoangdv** [progit/progit2#772]
I hope that adding group commits feature. 
In currently I have a many many small tickets, it not big for create a new branch and I don't want to create many branches. 
So I want to create a branch and in this branch will have many group, (1 ticket per group), a group have many commits.
**Ex:**
I have 10 tickets is bug so I will create a branch **bug_fix** and 10 group for 10 ticket
and group name will ticket_id
Currently I must add prefix commit by ticket_id.
## Currently
1.  [ticket_id] - Commit message 1
2.  [1034] - Commit message 2
3.  [1034] - Commit message 3
.....
## Expect
- **1034** -> this is group name.
1. Commit message 1
2. Commit message 2
3. Commit message 3
....
When I release theme, I can copy or merge per group will fast and easy. I think it's better.
I'm not sure if it's a good idea, just a little suggestion I wanted to make.
Thank you !

**Comment by ben** [comment]
It sounds like you're proposing a feature for Git. If so, you should engage with [that community](https://git-scm.com/community) to get it done, this is just the source code for the Pro Git book. Good luck!
