### ISSUE TITLE
Please help me for build Smart HTTP Git Server

### ISSUE THREAD

**Issue by wangding** [progit/progit2#779]
## OS

CentOS 7 with apache

## /etc/httpd/conf/httpd.conf  (add the code)

```
SetEnv GIT_PROJECT_ROOT /opt/git
SetEnv GIT_HTTP_EXPORT_ALL
ScriptAlias /git/ /usr/libexec/git-core/git-http-backend/

<Files "git-http-backend">
    AuthType Basic
    AuthName "Git Access"
    AuthUserFile /opt/git/.htpasswd
    Require expr !(%{QUERY_STRING} -strmatch '*service=git-receive-pack*' || %{REQUEST_URI} =~ m#/git-receive-pack$#)
    Require valid-user
</Files>
```

## /opt/

drwxrwsrwx. 4 apache apache 56 Aug   8 18:21 git

## /opt/git/

-rwxrwxrwx. 1 apache apache  42 Aug   8 18:09 .htpasswd
drwxrwxrwx. 7 apache apache 119 Aug   8 17:33 test.git
drwxrwsr-x. 7 apache apache 119 Aug   8 18:21 tools.git

note:
1. folder test.git  and tools.git  execute  `git init --bare`.
2. files and folders in test.git and tools.git with same permission as parent folders.

## .htpasswd  (user:git, password:git)

git:$apr1$FKj6cFJp$L/aMW8lBY4.I8ff7HTTXE1

---
## another computer

```
git clone http://server_ip_address/git/tools.git  (this ok)
```

do some changing.

```
git push origin master
```

Username for 'http://192.168.130.133': git
Password for 'http://git@192.168.130.133': git
Counting objects: 3, done.
Writing objects: 100% (3/3), 208 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
**remote: error: insufficient permission for adding an object to repository database ./objects**
remote: fatal: failed to write object
error: unpack failed: unpack-objects abnormal exit
To http://192.168.130.133/git/tools.git
 ! [remote rejected] master -> master (unpacker error)
error: can not push some reference to 'http://192.168.130.133/git/tools.git'

can you tell me how to solve the problem above. thank you!

**Comment by AlexBaranowski** [comment]
Hi did you check SELinux contexts on directory? `ll -Z` should show it. You can disable SELinux with `setenforce 0` (**disabling SELinux is not best practice!!!**), and then check if it's possible without SELinux being in enforcing mode.

**Comment by wangding** [comment]
```bash
[root@LAB git]# ll -Z
drwxrwxrwx. apache apache unconfined_u:object_r:usr_t:s0   test.git
drwxrwsr-x. apache apache unconfined_u:object_r:usr_t:s0   tools.git
[root@LAB git]# setenforce 0

```

It's OK！thank you！ @AlexBaranowski
