### ISSUE TITLE
Cannot build PDF on Windows, neither through MSYS2 nor asciidoctor ruby gem

### ISSUE THREAD

**Issue by silviubogan** [progit/progit2#781]
`asciidoctor-pdf` is not an available command in both situations. `asciidoctor -b pdf progit2.asc` tells me that the `pdf` backend/plugin is not installed. Similar things happen with `mobi` and other formats that require an asciidoctor plugin.

**Comment by Paebbels** [comment]
You need to install `asciidoctor-pdf`, too. I attached my current build from 00eaa5b.

Here is the line to install it:

> ```cmd
> gem install asciidoctor-pdf --pre
> ```
> Source: https://github.com/asciidoctor/asciidoctor-pdf

Latest build: [Progit2 [2017.08.20].pdf](https://github.com/progit/progit2/files/1237228/Progit2.2017.08.20.pdf)

**Comment by silviubogan** [comment]
Thank you, @Paebbels. I managed to do it myself. 👍 You can close this issue.
