### ISSUE TITLE
2.6 Git Basics - Tagging — Inaccuracies

### ISSUE THREAD

**Issue by TheHeartmann** [progit/progit2#784]
Hey!

I was reading up on tagging today and realized that the book states that you cannot check out tags directly. However, as detailed on the [githowto website](https://githowto.com/tagging_versions), running `git checkout v1.0` (or whatever your tag name) works just fine. I assume this is something that has changed since the section was written, and as such, it would make sense to update it accordingly, I think. If there is some information I'm missing here, however, please let me know.

Edit: Apologies for not reading the guidelines before submitting this. I could not, however, find this issue anywhere else. Furthermore, I was unable to find an actual pdf of this through a quick scan, but the source (in this repo) still has the same issue as reported above.

**Comment by ben** [comment]
Wow, you're right! If the book says that, the book is wrong. Want to submit a PR to correct it? I'd love for you to get credit for fixing it.

— Ben

**Comment by TheHeartmann** [comment]
Sure thing! The PR has been opened. Thanks for your quick response!
