### ISSUE TITLE
Caret in Ancestry references

### ISSUE THREAD

**Issue by borekb** [progit/progit2#785]
I'm reading the [Ancestry References](https://github.com/progit/progit2/blob/master/book/07-git-tools/sections/revision-selection.asc#ancestry-references) section and have these suggestions:

- The name of the characters `^` (caret) and `~` (tilde) could be mentioned once for better googlability.
- The `^` character has a special meaning on Windows `cmd.exe` and it behaves like this:
    - `HEAD^` will NOT work
    - `"HEAD^"` will work
    - `HEAD^^` will work as well (Git will see just a single caret)

**Comment by ben** [comment]
Brilliant, I hadn't tried those examples on Windows. Want to submit a PR?

**Comment by borekb** [comment]
PR submitted: #787
