### ISSUE TITLE
Early explanation of .gitignore doesn't mention possible hierarchy of .gitignore files

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#789]
P. 25 of current book, section "Ignoring Files", leaves the impression that there is just one .gitignore file:

"The rules for the patterns you can put in -->the<-- .gitignore file are as follows ..."

Not saying it's critical to get into a heavy discussion about .gitignore files, but a brief note that there can be more than one might be helpful.

rday

**Comment by ben** [comment]
I see two issues here:

1. This particular section doesn't mention having multiple `.gitignore` files.
1. The book doesn't cover having multiple `.gitignore` files.

The first I don't see as an issue. At this point in the book, we assume the reader is a complete novice to Git (if not version control in general), and we don't want to overwhelm with detail. So it's not really appropriate to cover it there.

The second is a more serious issue. Grepping through the code, I don't see a place where we cover the possibility of having more than one. I'd happily welcome a PR that corrects this.

**Comment by rpjday** [comment]
Hmmmmm ... my thought would be to add a brief note mentioning that a repo can have multiple .gitignore files, then just refer the reader to the man page for the gory details. I don't see any compelling reason for the book to get into all the details when the man page does that, so a single paragraph or note would seem to be sufficient.

**Comment by rpjday** [comment]
Since I submitted a short patch to (briefly) mention multiple .gitignore files, I'll close this off and you can apply the patch if you want. I thought it was easiest to just mention that early and get it out of the way, rather than figuring out where to add it later.
