### ISSUE TITLE
Should references to env variables use a leading '$' or not, for consistency?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#791]
More nitpicky pedantry, but I've noticed that there is an inconsistency when referring to environment variables in the text -- sometimes they include the dollar sign, as in "$EDITOR", and other times not, such as in the chapter on "Git Internals", the section on "Environment Variables."

I'm not talking about sample command lines, which of course would need the '$'; I'm talking about sentences that simply refer to those variables as part of an explanation. Is there a standard?

rday

**Comment by ben** [comment]
No, we never nailed down a typographical standard for this. Mostly we just tried to make sure it was clear that we were talking about environment variables whenever we did. But if you'd like to standardize all of them, I'd accept that PR.

**Comment by rpjday** [comment]
If I see a lot of inconsistency, I'll submit something, but I won't bother if that's the only issue in an entire file. So let's just close this.
