### ISSUE TITLE
Should early section on remotes not mention "git checkout -b pbm pb/master"?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#792]
PDF, p. 41, "Working with remotes," in the midst of all that, if a reader added the remote "pb" and wanted to checkout the master branch, they would almost certainly realize they can't re-use the branch name "master", but there's no mention in that section as to how to do that. AIUI, they could make up a shortname for "pb/master" -- say "pbm", and:

  $ git checkout -b pbm pb/master

no? That's not a deep observation, but shouldn't there be a mention in that section as to how to do that? It seems like a pretty fundamental issue. Or is the recommended technique to use the combination of remote and branch name?

**Comment by ben** [comment]
I think we cover that later on, and chapter 2 is hardly the place to dive into all the options and modes of `git checkout`. Remember, the reader here is a complete newbie to Git, we don't want to overwhelm.
