### ISSUE TITLE
Is there a difference between "working tree" and "working directory"?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#794]
Most folks I know don't distinguish between those terms, but I'm sure I saw a recent post to the Git mailing list where it was unclear whether untracked files were considered part of the working tree or the working directory, as there was some documentation somewhere that appeared to be ambiguous based on that.

Simplistically, if one uses the phrase "working directory" to refer to what the user sees in front of them, then untracked files would be considered part of that. I notice the book uses the phrase "working directory"  far more frequently than "working tree". Is there any notion of distinguishing between these phrases? Or am I overthinking this?

rday

**Comment by ben** [comment]
You're overthinking it. 😄 

In my mind, those two terms mean exactly the same thing. I don't know if there's a subtle difference within the Git project, but as a user I don't see a difference.

For the purposes of this book, the two terms have been treated as interchangeable. There have been some efforts (i.e. #364) to standardize on "working tree," but it's by no means complete.

**Comment by jnavila** [comment]
Please note that there is a `git worktree` command to allow to work on several branches at the same time in different work directories. The man page only uses the term _work tree_, so I guess we should also stick to it.

>
