### ISSUE TITLE
Chapter 2.2 Short Status  statement is incorrect with the file mentioned

### ISSUE THREAD

**Issue by karthikeyanr** [progit/progit2#795]
I checked the following in the published PDF (progit-en.1084) and known Issues. Since i couldn't find any previous report and the bug exists in the PDF as well, I am reporting here. Chapter 2.2 Short status contains the following command output and description

```
$ git status -s
 M README
MM Rakefile
A  lib/git.rb
M  lib/simplegit.rb
?? LICENSE.txt
```

So for example in that output, the README file is modified in the working directory but not yet staged, while the lib/simplegit.rb file is modified and staged. 

As per the output shown, lib/simplegit.rb file is modified and not yet staged. Probably the author wanted to refer lib/git.rb for this statement.

**Comment by ben** [comment]
Here's what that output means:

- `README` has an "M" (modified) in the right-hand column (not staged)
- `lib/simplegit.rb` has an "M" (modified) in the left-hand column (staged)
- `lib/git.rb` has an "A" (new file) in the left-hand column (staged)

And here's the prose from [that section](https://github.com/progit/progit2/blob/a3ee0a10a427e67a2f6925358daa862e500570ff/book/02-git-basics/sections/recording-changes.asc#short-status):

> There are two columns to the output - the left-hand column indicates the status of the staging area and the right-hand column indicates the status of the working tree. So for example in that output, the `README` file is modified in the working directory but not yet staged, while the `lib/simplegit.rb` file is modified and staged.

That all sounds correct to me. Am I missing something?

**Comment by karthikeyanr** [comment]
Yes @ben you are correct. It was a misunderstanding from my side. Now i see the that MM refers to working area (left-hand column) and staged area (right-hand column) indicator.

**Comment by ben** [comment]
No worries!
