### ISSUE TITLE
Question about the "Detached HEAD" discussion

### ISSUE THREAD

**Issue by 42degrees** [progit/progit2#796]
In tagging.asc section titled, "Checking out Tags," you discuss pulling a tag and ending up in a "Detached HEAD" state.  You mention how this could be very useful to create a bug fix for a specific version (and as far as I can tell the only actual way to do this).

But then you finish the section with an admonition to be careful, but I don't see the danger.  You are legitimately creating a tracked branch.  The fact that it's built from an old version doesn't seem particularly dangerous (in fact, in the specific use case you mentioned that is the only reasonable course of action).

> If you do this and make a commit, your version2 branch will be slightly different than your v2.0.0 tag since it will move forward with your new changes, so do be careful.

Clearly if you are making a bug fix to v2.0.0 you would pull the branch to make the fix, then create a new tag something like v2.0.1, then merge those changes into the HEAD and possibly any other revisions that are being actively supported (wherever it makes sense to do so). Certainly the branch you are working in will be different (slightly or otherwise), and that is the point.

So, where is the danger that you imply here?  I don't believe it's fully described (at least, I am completely missing it).

**Comment by ben** [comment]
The warning is to make sure the reader knows that they aren't moving the `v2.0.0` tag. The workflow you describe is _exactly_ what we want to steer people towards, but just `git checkout v2.0.0; make changes; git commit -m 'fixed bug'; git push` won't do what you might intuitively expect if you're coming from another system.

Remember that this is chapter 2, and the reader is just getting introduced to Git's core concepts. Starting a branch from a tag is a more-complicated workflow, and not something we want to fully dive into just here. Once the reader understands more concepts, they may come back to this and read it the way you did, but at first we just need to make sure they know it's an advanced topic.

Do you think there's a better way to word it that achieves those goals? If so, I'd love to review a PR.

**Comment by 42degrees** [comment]
Thanks for the clarification, I'll give it some thought and if I come up with anything I'll submit a change.
