### ISSUE TITLE
Is the sample project "simplegit" or "simplegit-progit"?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#799]
In "Viewing the Commit History", 

"These examples use a very simple project called “simplegit”. To get the project, run

  $ git clone https://github.com/schacon/simplegit-progit

So the text says "simplegit", but the command says "simplegit-progit", and both of those projects exist under schacon.

rday

**Comment by ben** [comment]
While it is true that both of those projects exist, I don't think the text is ambiguous. It isn't uncommon to have a project with one name, while its repository has a slightly different name, so readers shouldn't be confused by the difference, even in Chapter 2.

**Comment by rpjday** [comment]
Fair enough. I had no problem with this, until I noticed that there actually is a project named "simplegit", but I'll just leave that alone and keep working.
