### ISSUE TITLE
Atlas: callout issues

### ISSUE THREAD

**Issue by ben** [progit/progit2#80]
Check out [this PDF](http://orm-atlas2-prod.s3.amazonaws.com/pdf/d496bc6a19b06a67a6174f8fb47229bd.pdf), page 329. The callout graphics are rendered as missing images. Here's what it looks like when Atom renders it:

![image](https://cloud.githubusercontent.com/assets/39902/4211672/8d40412c-388d-11e4-9ce9-ce5f4e35153d.png)

**Comment by YueLinHo** [comment]
Is this Atom render specific?

Looks OK for me on Windows. See:

![image](https://cloud.githubusercontent.com/assets/5831804/14447697/b417abc0-0094-11e6-8e50-edc6db59ba5d.png)

From last pdf link: https://progit2.s3.amazonaws.com/en/2016-03-22-f3531/progit-en.1084.pdf

**Comment by ben** [comment]
Looks like it's solved!
