### ISSUE TITLE
Some possible clarifications for the "Tagging" section

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#800]
A couple things about that section. First, while the distinction between lightweight and annotated tags is explained early, that distinction is not made for the remainder of that section, so when there is talk of checking out tags and sharing tags, there is no clarification as to whether those commands refer to lightweight tags, annotated tags or both.

(Side note: My understanding is that lightweight tags are philosophically *never* meant to be shared -- they're for personal use only, and if you want to share tags, they should always be annotated tags. Is that a reasonable philosophy?)

And, second, while one does not want to overwhelm the reader with too much detail, it seems there are at least a couple things that could be added to that section, such as "git push --follow-tags", and possibly others.

**Comment by ben** [comment]
1. The rest of the content in that section applies to both lightweight and annotated tags, so while you have two _types_ of tag, they're still conceptually "tags," so it's implied that when we refer to "tags" in the rest of that section that we're talking about both.

1. Possibly, but that seems like an advanced feature for chapter 2. Most of the time when you're creating a tag, you'll push just that tag on its own. `--follow-tags` is most useful when you have lots of tags, and the N branches you're pushing right now have M tags that are reachable from them, and you don't want to specify them manually. Git newbies won't be running into this situation.

As for your side note, this is a stylistic option that depends on how your team works. If you want the cryptographic features of an annotated tag (i.e. who created this, when was it created, and why?), annotated tags are your friend, but if you don't need that stuff, lightweight tags are just fine. I've worked on both kinds of team, and both are valid choices.
