### ISSUE TITLE
What is the syntax for identifying a replaceable term? (), <> or []?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#801]
More pedantry, but what is the standard in the book for showing a replaceable term, as in:

```
  $ git push <remote> <branch>
  $ git push (remote) (branch)
  $ git push [remote] [branch]
```

I've seen all three variations and the book bounces around a bit from one to the other. I can clean those up during my travels if someone wants to pick one.

**Comment by ben** [comment]
We should probably settle on the convention the [manpages seem to use](https://git-scm.com/docs/git-diff), which is `[square brackets]` for optional things, and `<angle brackets>` to denote required things.

**Comment by rpjday** [comment]
Agreed, I'll collect those tweaks and eventually submit as a single patch.
