### ISSUE TITLE
Is it "local-tracking branch" or just "tracking branch"?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#805]
Terminology question here about preferred ways to refer to different types of branches. First, it appears that private (non-shared) branches are typically called "local" or "private" or "topic" or "feature" branches, etc, etc, you the idea.

But what is the standard these days for referring to tracking branches? Is it "local-tracking branch" which is associated with a "remote-tracking branch", or is it just "tracking branch?" I've seen both, just curious what is the more common usage? Some people appear to have very strong opinions on the subject.

rday

P.S. Reading the section on "Tracking Branches" right now -- do the phrases "remote branch" and "upstream branch" mean the same thing? That is, the branch that is actually at the remote?

**Comment by ben** [comment]
We go into this in chapter 3. A "remote branch" is a ref that Git manages, and it reflects the state of that ref in a remote repository (it's synced when you do `git fetch`). These are commonly called "remote tracking branches" as well, which makes colloquial sense.

A "tracking branch" or "upstream branch" is a ref that the user has control over, that has a push/pull association with a remote branch. I.e. `origin/master` is a remote branch, and `master` is a tracking branch.

In my head I think of these as "branches" and "remote branches," and sometimes my branches have an "upstream." However, that's not common usage, so you're better off understanding the terms above.

---

To your second question: no, those things are not the same. The opening section of [section 3.5](https://git-scm.com/book/id/v2/Git-Branching-Remote-Branches) says:

> Remote branches are references (pointers) to the state of branches in your remote repositories.

[Later on](https://git-scm.com/book/id/v2/Git-Branching-Remote-Branches#_tracking_branches):

> Checking out a local branch from a remote branch automatically creates what is called a “tracking branch” (or sometimes an “upstream branch”).

Again, these terms are more-or-less "official," but I'm sure you have words in your head that better describe these concepts.
