### ISSUE TITLE
Objects count

### ISSUE THREAD

**Issue by AndreWin** [progit/progit2#806]
Hello!

https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell

There is the following text on this page:

> Your Git repository now contains five objects: one blob for the contents of each of your three files, one tree that lists the contents of the directory and specifies which file names are stored as which blobs, and one commit with the pointer to that root tree and all the commit metadata.

But it seems for me that only 4 objects are mentioned:

1. one blob for the contents of each of your three files,
2. one tree that lists the contents of the directory and specifies which file names are stored as which blobs,
3. one commit with the pointer to that root tree,
4. one commit with the pointer to that root tree and all the commit metadata.

Am I right?

Best regards,
Anrey.

**Comment by aollier** [comment]
Hello,

No you're wrong. The five objects are:
- 3 blobs, each one representing one file
- 1 tree representing the directory and its content
- 1 commit containing the pointer of the root tree and the metadata (author, date, message, etc.)

That makes 5 objects. So there is no error in the text.

**Comment by AndreWin** [comment]
@aollier, how could I understand that there are 3 blobs, not one? In text there is &laquo;one blob for the contents&raquo;. And why 3 blobs? Why not one blob? I'm learning git now and these questions are dificult for me.

**Comment by AndreWin** [comment]
@aollier, it seems fot me I understand it now. There are three blobs on picture under this text. 1 blob = 1 file in commit. Am I right now?

**Comment by aollier** [comment]
@AndreWin Yes you are right now. You have understood.
The entire sentence you mention is:
> one blob for the contents of each of your three files

which means that you have one blob per file so you have 3 blobs.

1 blob always represents a single file. When several files are present, you have as many blobs as you have files and there is one tree to group them in what represents a directory (it may be the root directory or a subdirectory).

**Comment by ben** [comment]
In that picture there are 5 boxes:

![](https://git-scm.com/book/en/v2/images/commit-and-tree.png)

Each one of those is an object in the repository. Here's another view from [chapter 10](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects) that represents this tree structure:

```
.
├── README
├── Rakefile
└── lib
    └── simplegit.rb
```

![](https://git-scm.com/book/en/v2/images/data-model-1.png)

The commit isn't here, but you could imagine it floating above the topmost tree, and if you include that, there are six objects in that repository.

> 1 blob always represents a single file.

I'll go even further and say that each blob represents a _version_ of a file. Every time you make a commit that changes a file, there's a new blob for that file's contents. If you're feeling up to it, take a read through [section 10.2](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects), it covers all of this in detail, along with a diagram at the end that shows how objects get reused for multiple commits.

**Comment by AndreWin** [comment]
@aollier and @ben, many thanks!
