### ISSUE TITLE
Should Ubuntu reference to Upstart be replaced with systemd?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#807]
Just noticed in section "Git Daemon":

"On an Ubuntu machine, you can use an Upstart script."

Given that Upstart was replaced with systemd on Ubuntu a while back, might you want to update that section? Totally up to you.

rday

**Comment by ben** [comment]
Oh yikes, I hate to give wrong information. Want to submit a PR that fixes that?

**Comment by rpjday** [comment]
OK, let me figure out what to replace it with, systemd-wise.

**Comment by MKaslaan** [comment]
On issue

**Comment by HonkingGoose** [comment]
@ben @jnavila There is already a systemd replacement mentioned at: https://git-scm.com/book/en/v2/Git-on-the-Server-Git-Daemon so this issue can be closed.
