### ISSUE TITLE
typo on the cover?

### ISSUE THREAD

**Issue by beppe9000** [progit/progit2#809]
I'm about to read this ebook so I apologize if `GITT` actually means something like **GIT T**echniques

![typo](https://user-images.githubusercontent.com/6625123/30671753-dea107d8-9e68-11e7-89f2-2a3647ff3676.png)

**Comment by ben** [comment]
Interesting.  Can you tell me where you ran across this? It was a _very_ early version that Apress sent us before the book was published. The [cover](https://github.com/progit/progit2/raw/master/book/cover.png) that gets built into ebooks and HTML is fixed.

**Comment by beppe9000** [comment]
Are you sure that applies to all ebook formats? I downloaded the [latest PDF release](https://github.com/progit/progit2/releases/download/2.0.0/progit-2.0.0.pdf) and *that* is on the cover...

**Comment by ben** [comment]
Ah, that explains it:

![image](https://user-images.githubusercontent.com/39902/30706085-2f4473bc-9eac-11e7-8874-433bb0fd3ba5.png)

I'll draft a new release. One sec.

**Comment by ben** [comment]
[Version 2.1.0](https://github.com/progit/progit2/releases/tag/2.1.0) has freshly-generated binaries. May the Gitt no longer be with you.

**Comment by ben** [comment]
Created #810 to hopefully figure out a way to keep this from happening again. Thanks for the heads up!
