### ISSUE TITLE
Is there an explanation of local cloning across filesystems, where hardlinks don't work?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#813]
Perusing Chapter 4, and I've never been sure about the following. If you use the local protocol with:

` $ git clone /path/to/repo`

the man page for `clone` states that this will use the local protocol and that "The files under .git/objects/ directory are hardlinked to save space when possible." Obviously, though, if the repo is on a different filesystem, or on an NFS mount, that's not going to work. In that case, what happens? Is there a symbolic link option? Or does clone back off to using "--shared"? Or does it make no attempt to share at all?

The man page doesn't seem really clear on that.

WAIT: Upon re-reading, the phrase "when possible" is clearly the important part -- so if the repo is on the same FS, then hardlinks are used; otherwise, ... I guess just regular copies. Still, are symlinks ever an option?

**Comment by ben** [comment]
Depends on the behavior of your filesystem. [This code](https://github.com/git/git/blob/9ddaf86b06a8078420f59aec8cab6daa93cf1a91/builtin/clone.c#L438-L444) seems to suggest that if Git fails to make a hardlink, it just punts back to the user, who then will need to use `--no-hardlinks` to bypass that error.

We probably don't want to dive into this too deeply; the average reader doesn't know the difference between hardlinks and file copies.
