### ISSUE TITLE
Is it worth adding a note about the transition to a new hash function?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#821]
Early Chapter 7 describes features of SHA-1 -- is it worth adding a note about the upcoming transition to a stronger hash function? https://lwn.net/Articles/715716/. Just wondered if readers should at least have a heads-up that something new is coming.

**Comment by ben** [comment]
This doesn't strike me as an important detail to Git users. They do need to know _that_ their data is hashed, but not _how_ it is hashed. When a new algorithm has been chosen, and is used for all new commits, we can start replacing the phrase "SHA-1" with the new one, but there probably isn't a lot else that needs to change.
