### ISSUE TITLE
"Debugging with Git", examples don't work since "simplegit.rb" was shortened

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#829]
Just noticed in the example(s) in "Debugging with Git" section, such as:

`$ git blame -L 12,22 simplegit.rb`

that example does not work as that file from the simplegit repo is only 20 lines long; the latest commit to that file stated, "removed unnecessary test code", which now makes the example commands fail.

**Comment by ben** [comment]
Ha! Nice catch! Want to submit a PR that changes it to `-L 15,19` or something that makes sense?

**Comment by rpjday** [comment]
OK, in my copious free time. :-)

**Comment by rpjday** [comment]
Problem ... the simplegit repo was clearly reorganized, to the point where the entire simplegit.rb file has blame entries of "^a11bef0", which is kind of uninformative. I'll find another example that's a bit more interesting.

**Comment by rpjday** [comment]
Submitted a working example.
