### ISSUE TITLE
Clarifying .gitignore versus .git/info/exclude versus core.excludesfile

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#836]
Just want to make sure I'm interpreting all of the above the right way so I explain it to my students correctly (and I will probably, and unsurprisingly, submit some rewording based on this).

First (and trivially), the one or more .gitignore files in a repository are always related to the fundamental content of the repository itself, and should be kept up to date by the maintainer of that repository. .gitignore files should represent only those files to be ignored related to basic "processing" of that repository content by anyone who clones it.

For example, if it's a C-based repository, .gitignore files should (at the very least) contain "*.o", that short of thing. If a user notices something being generated in their working directory that should be ignored for everyone, that oversight should not be dealt with locally, it should be resolved by submitting a patch for the appropriate .gitignore file to the maintainer (something I've done on occasion with the Linux kernel source when new features were added but no one enhanced the .gitignore file(s) to include the generated content based on that new feature). I would refer to this sort of thing (probably inappropriately) as "server-side" ignores. So far, so good?

At the other end, a user can configure Git with "core.excludesfile" based on (as Pro Git explains) files to be ignored that are purely a result of the user and the way they work regardless of the repository they're working on. As that section suggests, if one uses an editor that generates ".swp" files, then it is the *user* that needs to identify such files to be ignored -- nothing that is user-specific should ever be added to a .gitignore file. (I would call this "client-side" ignores.)

Finally, in the middle ground, there is a repository's ".git/info/exclude" file which (as I understand it and I could be wrong), is also a "client-side" ignore, and should be configured on a user-by-user basis, based on files to be ignored strictly for that repository *and* related to how that user works. Is that correct? If that's correct, that would imply a couple of things for .git/info/exclude that I want to confirm.

First, a repository should never come pre-loaded with anything in .git/info/exclude, is that right? If a repo has fundamental files to be ignored, those should be in .gitignore files; there is no reason for the maintainer of a repository to put anything in .git/info/exclude.

And second, .git/info/exclude should include only those entries that a user wishes to ignore based specifically on that repository. If a user wants to always in general ignore "*.swp" files, that's what core.excludesfile is for, do I have that right?

Sorry for tediously going on about this, I just want to be absolutely sure I understand this.

**Comment by ben** [comment]
> .gitignore files

I think of these as "intrinsic" ignores. They're part of the source code, and should be kept up-to-date as the project evolves. Also think of a parallel with `git config` -- these are the `--local` ignores.

> core.excludesfile

This is like the `--global` git config, it tells git to ignore all matching files _that I use on this computer_ regardless of the repository or directory they're in. If you're working on a Mac, it's common to put `.DS_Store` in this file, for example.

> .git/info/exclude

This set of ignores always struck me as kind of a hack, and not very useful. Nothing in the `info` directory is transmitted when you clone, so these are really hard to share. You're right in that it seems to mostly get used by people who use a specific editor, but don't want to bother the team by changing the `.gitignore` file to exclude the editor's swap files.

> First, a repository should never come pre-loaded with anything in .git/info/exclude,

Correct; in fact, you _can't_ pre-load anything in the `info` directory.

> .git/info/exclude should include only those entries that a user wishes to ignore based specifically on that repository

Yes, it's repo-local.

> If a user wants to always in general ignore "*.swp" files, that's what core.excludesfile is for, do I have that right?

Yup!

**Comment by rpjday** [comment]
I agree with all of the above -- in fact, [I just posted to the Git ML](https://marc.info/?l=git&m=150728488029935&w=2), asking for the rationale for .git/info/exclude, where you can read my one (admittedly uncompelling) rationale for it. Let's see if someone can come up with something better.

**Comment by ben** [comment]
Good old Junio 😆 

> Don't waste time by seeking a "compelling" reason.  A mere "this is
> the most expedite way to gain convenience" back when something was
> introduced could be an answer, and it is way too late to complain
> about such a choice anyway.

**Comment by rpjday** [comment]
Actually, I'm fine with that answer, since it's informative in the sense that he admits there *is* no compelling reason for that file, just as you suggested.

**Comment by chmaynard** [comment]
From chapter 10.1: "... the info directory keeps a global exclude file for ignored patterns that you don’t want to track in a .gitignore file." In light if this discussion, I recommend dropping the word _global_.

**Comment by ben** [comment]
@chmaynard I'd love to see a PR that rewords that section to be more accurate and useful. Want to submit one?

**Comment by chmaynard** [comment]
I'm glad to help. Stay tuned.
