### ISSUE TITLE
Clean install of Git-2.14.2-64-bit disables CRTL+C to kill Commands

### ISSUE THREAD

**Issue by PhilWim** [progit/progit2#837]
On my fresh windows installation i installed Git-2.14.2-64-bit. Then i faces the issue that commands (docker logs) keep on sending to console after i killed them through CRTL+C.

I reinstalled the older version which i know was working (Git-2.10.2-64-bit) on my old windows installation. Still same problem. 

Then i found a issue in mintty tacker where a commend leaded to a probably wrong cygwin dependency. 

And exactly this is the case here. Uninstalling of Git-2.14.2-64-bit didn't wipe C:/Program Files/Git completely. Cygwin libs stayed. 

So probably these broken libs were used also with the working version Git-2.10.2-64-bit. 

Then i did manually clean git folder and reinstalled Git-2.10.2-64-bit and voila no issues anymore.

I guess also for updating to newer versions, old cygwin files stay and some users never face this problem.  Obviously fresh installation leads into problems.

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the Windows port of the git program. Please see https://git-for-windows.github.io/ for reporting bugs.
