### ISSUE TITLE
What is (((...))) asciidoc markup?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#838]
Perusing Git Internals chapter and there's this snippet:

"... the `info` directory keeps a global exclude file (((excludes))) for ignored patterns ..."

I checked asciidoc markup and have no idea what the (((...))) means, it doesn't render anything in the PDF output. Clarify?

rday

**Comment by ben** [comment]
They generate [index entries](http://www.methods.co.nz/asciidoc/chunked/ch19.html). You sprinkle them throughout the book, and when we were using Atlas to generate PDFs, they would end up in the index of the output file. It appears that Asciidoctor doesn't do anything with them, but I'd like to keep them in there for a possible future print edition.
