### ISSUE TITLE
Is there an explanation in Pro Git of the valid modes for files and directories under Git?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#839]
I haven't totally sequentially followed the book, and I'm in the Git Internals chapter where I'm reading about object modes for the first time:

"In this case, you’re specifying a mode of 100644, which means it’s a normal file. Other options are
100755, which means it’s an executable file; and 120000, which specifies a symbolic link. The mode is
taken from normal UNIX modes but is much less flexible – these three modes are the only ones that
are valid for files (blobs) in Git (although other modes are used for directories and submodules)."

I would think that one should know about Git-supported object modes before getting to the Git internals chapter -- is that covered earlier in the book and I just missed it? Seems pretty important for a user to understand what Git will do to his file and directory permissions when stored.

**Comment by ben** [comment]
For the most part this is completely invisible to the user; Git just preserves the executable flag of the file you commit. The `x` flag is something you only run into maybe 10 times in the history of a project, so I don't think it warrants calling out all that much.

If you're teaching UNIX at the same time as Git, your students might wonder what happens to their permissions flags when they're transmitted through the object database. I don't think many other users will wonder.
