### ISSUE TITLE
How do you get the "em" long dash into the text?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#865]
Embarrassed to admit I don't know how to do this, but I see numerous instances of the long dash in the text, but have no idea how to get it in there, there's no such character on the keyboard. Do I need to use an escape sequence or something?

**Comment by lazarljubenovic** [comment]
If my memory serves me well, Asciidoctor transforms two dashes `--` with spaces around it into an em-dash.

**Comment by rpjday** [comment]
First, that can't be right since I'm looking at what appears to be an "em" long dash in one of the source .asc files while in the vi editor, so it's part of the actual source file; perhaps there are keyboards with that character on them but mine isn't one of them.

Also, if asciidoctor transformed "--" with spaces around it to an em, that would result in unspeakable hilarity with respect to a great deal of Git command rendering.

**Comment by lazarljubenovic** [comment]
It's context aware. When inside a code block, it's not transformed. Just checked it and it works for sure. You can also do a quick search and see that `--` is used throughout the book and that in the rendered HTML it s an em-dash.

**Comment by rpjday** [comment]
Again, I'm not talking about the rendered HTML, I'm talking about what is in the .asc source file. I picked a sample file, reduced it to just the apparent "em" dash and two surrounding spaces, and hexdumped it to get `20 e2 80 93 20`. In other words, the source file has three bytes between the two spaces, perhaps Unicode?

**Comment by jnavila** [comment]
The asciidoc text is encoded in UTF-8. How you can generate such code depends on your OS and your keyboard layout. For me, (Ubuntu, french keyboard),  
`AltGr+Shift+!` → −
`AltGr+Shift+(` → –
`AltGr+Shift+'` → —

**Comment by ben** [comment]
On a Mac, `-` is a hyphen, `Alt+-` is an en-dash, and `Alt+Shift+-` is an em-dash. I tend to type those like that, so you're probably seeing that. They seem to work just fine, but it's probably better for new text to use `--`, so we're not depending on people's editors assuming UTF-8.

**Comment by ben** [comment]
Going to close this out, since there isn't anything actionable here.
