### ISSUE TITLE
Some pedantry regarding proper punctuation.

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#868]
As I'm making edits, I notice that there is a mixture of both smart and dumb double quotes. Which is preferred? I'm not going to do any changes for that unless I'm already making some mods to that file, to avoid useless churn.

Oh, and have we settled on using " -- " to generate an EM dash? It seems like that's the solution.

**Comment by ben** [comment]
The "``''" style is preferred. I'd rather Asciidoc decide how to render double quotes, and not have your editor and mine fighting it out.

And yes, the same reasoning applies to dashes; if we're converting, let's do it all in one go.

**Comment by rpjday** [comment]
OK, I'm tweaking some early sections, so I'll make those changes on a section-by-section basis to avoid unnecessary churn.
