### ISSUE TITLE
What newer Git features should be added to book?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#874]
I've asked this before, but I want to create a list of features/topics that are currently missing from the book. (Disclaimer: I am now using this book as part of my Git training courses, so it's in my best interest to add stuff that I want to cover in class later, simply by opening the book to that section. :-)

As a start, I was thinking, at the very least:

- git-subtree
- git-worktree

Thoughts?

rday

**Comment by ben** [comment]
Closing in favor of #1084
