### ISSUE TITLE
What is the official name of the content between "---" and the actual patch?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#888]
What is that stuff called? Commentary? I'm sure there's a word for it, I just don't remember what it is. And while I'm here, is there a way to add that to a commit/pull request?

**Comment by ben** [comment]
I assume you mean the output of say `format-patch`, which looks like this:

```
From a1e95456143704db688602a2d435a5859b26f125 Mon Sep 17 00:00:00 2001
From: Johannes Dewender <github@JonnyJD.net>
Date: Mon, 11 Apr 2016 13:36:58 +0200
Subject: [PATCH 1/5] fix jgit javadoc link

Unfortunately there is no generic javadoc link anymore.
I linked the latest stable version.

The previous link leads to a project page and there is no link to the javadoc on that page.
---
 book/B-embedding-git/sections/jgit.asc | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/book/B-embedding-git/sections/jgit.asc b/book/B-embedding-git/sections/jgit.asc
index 9a86b34e..3d18a92c 100644
--- a/book/B-embedding-git/sections/jgit.asc
+++ b/book/B-embedding-git/sections/jgit.asc
@@ -155,7 +155,7 @@ Many other commands are available through the Git class, including but not limit
 This is only a small sampling of JGit's full capabilities.
 If you're interested and want to learn more, here's where to look for information and inspiration:

-* The official JGit API documentation is available online at http://download.eclipse.org/jgit/docs/latest/apidocs[].
+* The official JGit API documentation is available online at http://download.eclipse.org/jgit/site/4.3.0.201604071810-r/apidocs/[].
```

I don't know of an official term, but I think I'd call it the diffstat. 

OTOH, if you're looking at the lines that start with `---` and `+++`, those just indicate which is the preimage and postimage of the diff that comes after.

**Comment by rpjday** [comment]
No, it's the part that you're describing as "diffstat", but when I'm submitting patches by email to the Linux kernel mailing list, once I add the line "---", I can then blather on informally about stuff before the patch kicks in, wherein that blather is (as you know) not incorporated into the actual commit.

I'm wondering how one can add that kind of blather when submitting pull requests through this forum. Would I add a line of "---" in my actual commit message, and follow that with blather? There are times when I just want to informally mention something for your benefit, but don't want that to go into the commit.

**Comment by ben** [comment]
No, commits are commits, and they'll always go into the commit history of the Git repo. The Git ML is using that area for the same purpose that we use PR descriptions and comments here; to provide context without putting it into the commit history.

**Comment by parkinson101** [comment]
#1016
