### ISSUE TITLE
In some cases, why not use Pro Git codebase itself in examples?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#901]
Just occurred to me that, if you're looking for a Git repo for examples, what about using the progit2 repo itself? Seems only fitting that the book use itself to provide examples for the reader.

And in that vein, might even be worth adding a short section to the book (Appendix?) that walks the reader through how to install the packages needed to build the book. I realize that's in the README.md file, but I think it could be fleshed out a bit more. The README.md file talks about the "bundle" command, but my Fedora system has no such command, so I think it's worth making that documentation more detailed and complete. Just thinking out loud.

**Comment by ben** [comment]
We didn't want to make the book a manual for itself; the readme seems like the right place for build instructions.

As for examples, they almost always fell into two categories:

1. We need a simple example, without too much history or esoterica. We don't want to intimidate the reader.
1. We need a full example, and something a reader might have heard of is perfect.

So we almost always use the `simplegit` repo for case 1. For case 2, the Linux kernel, or Git, or libgit2 are more topical and relevant to the reader, plus they lend a bit of gravitas being such high-profile projects.

**Comment by HonkingGoose** [comment]
I think this issue can be closed?
