### ISSUE TITLE
File Status Lifecycle image wrong arrow? - Portuguese version

### ISSUE THREAD

**Issue by pauloinca** [progit/progit2#903]
Figure 2-1 in the Portuguese version (Figure 8 - English) has an arrow pointing to unmodified when some untracked file is added. However, I believe it should be pointing to staged, right?

![](https://git-scm.com/figures/18333fig0201-tn.png)

**Comment by ben** [comment]
I think you may be looking at [the first edition](https://git-scm.com/book/pt-br/v1/Git-Essencial-Gravando-Altera%C3%A7%C3%B5es-no-Reposit%C3%B3rio). The [second edition](https://git-scm.com/book/pt-br/v2/Git-Basics-Recording-Changes-to-the-Repository) of that chapter uses this figure:

![](https://git-scm.com/book/en/v2/images/lifecycle.png)

In any case, issues with the Portuguese translation should go on [that repository](https://github.com/progit2-pt-br/progit2); we can't do anything about it here.
