### ISSUE TITLE
"GitHub" chapter is missed now and there are two "Git Internals" chapters at git-scm.com.

### ISSUE THREAD

**Issue by MrKsanty** [progit/progit2#914]

**Comment by jnavila** [comment]
I guess this is in fact the chapters of the first edition that where injected.
ping @peff for running once again `remote_genbook2` :disappointed:

**Comment by jnavila** [comment]
This issue has to do with git-scm.com site, not the progit book itself.

**Comment by MrKsanty** [comment]
Ok. I'll let him know. Sorry for false alarm;)

**Comment by peff** [comment]
Hrm. I _did_ run `remote_genbook2` again since then, but I think the bug fixed in https://github.com/git/git-scm.com/pull/1065 corrupted the database in a way that the run won't fix. I'll see if I can wipe and regenerate.

**Comment by jnavila** [comment]
Ah, You're surely right. There are now records in the book table with edition=NULL and they may appear first in the results to the requests of the most complete book:

https://github.com/git/git-scm.com/blob/6b12f053cb7cfa505aab29a12c0a212ebc393b6b/app/controllers/books_controller.rb#L11-L13

according to https://www.postgresql.org/docs/8.3/static/queries-order.html, NULL comes first.

**Comment by peff** [comment]
OK, wiping and regenerating seems to have fixed it. Thanks for reporting @MrKsanty!

**Comment by MrKsanty** [comment]
Not at all!
