### ISSUE TITLE
Persian Translation

### ISSUE THREAD

**Issue by hjavadish** [progit/progit2#931]
Hi.
I started translating into Persian. Here is my fork [https://github.com/progit2-fa/progit2]( https://github.com/progit2-fa/progit2)

**Comment by jnavila** [comment]
Good! When you have translated the first chapter at least, please inform us so that we add your fork for persian translation.

**Comment by gn-ahmad** [comment]
Hi @jnavila 
I like to see this project in persian and I would like to do this because persian is my native language!
if it is OK i will continue @hjavadish 's work and help him to complete translation.
i will happy to have cooperation in this project.

**Comment by jnavila** [comment]
@gn-ahmad Awesome! Keep me updated of your progression.

**Comment by gn-ahmad** [comment]
Ok, I will surely do this

**Comment by mohsen00khani** [comment]
Hi @jnavila 
Hi @gn-ahmad 
I'm also participate to help with you guys...

**Comment by jnavila** [comment]
@mohsen00khani If you want to help progit2-fa/progit2, you'll need at some point to propose a pull request to the project, and for that you'll need a personal fork. That's the way it works.

**Comment by mohsen00khani** [comment]
Yes, Sure

**Comment by jnavila** [comment]
@hjavadish started the project, but i guess you can review each other's pull requests. At the moment, only @hjavadish has push rights to this repository, but he may grant more right to you, so that you can update the book by yourselves.

**Comment by mohsen00khani** [comment]
@jnavila  Now, who can reviewed my translate.?

**Comment by jnavila** [comment]
@mohsen00khani it seems hjavadish already reviewed one of your PRs yesterday. 
See https://github.com/progit2-fa/progit2/pull/2 and reply please.

**Comment by omidnasri** [comment]
@jnavila 
I like to see this project in persian language and I would like to do this because persian is my native language. If it possible, add this repos to ProGit like other GitPro language.

**Comment by jnavila** [comment]
@omidnasri please present yourself at https://github.com/progit2-fa/progit2

**Comment by HonkingGoose** [comment]
@jnavila Is this still something you want open? It seems they all got underway, the linked repository is active (last commit 10th of january of this year). And a start of the translation is pulled into the main git-scm site: https://git-scm.com/book/fa/v2

---

For all people on this issue, the current guidelines for contributing a translation can be found here:
https://github.com/progit/progit2/blob/master/TRANSLATING.md

**Comment by jnavila** [comment]
Let's close it like the others.

**Comment by dscho** [comment]
Hey @jnavila! Over in https://github.com/git/git-scm.com/pull/1943, there is a volunteer (@YasinDehfuli) who is awaiting _some_ form of feedback from the Persian translation maintainer, @hjavadish, but crickets 🦗🦗🦗 .

Maybe @YasinDehfuli could take over?

**Comment by jnavila** [comment]
I'm all for switching repo dev names if it can keep the translations alive.

**Comment by jnavila** [comment]
Ah, my bad. The project progit2-fa/progit2 was never forked under the progit umbrella. So, we do not have any rights on it.

To ensure continuity on the maintenance of the project, let's just fork it under progit organization.

**Comment by jnavila** [comment]
@YasinDehfuli you should now be able to push to https://github.com/progit/progit2-fa/
