### ISSUE TITLE
Problem with online book table of content

### ISSUE THREAD

**Issue by qouoq** [progit/progit2#933]
The online book on git-scm.org seems broken since today or at most a few days.
In the table of content, the chapter titles, 1 to A3, are replaced by the subchapter titles, 1.1 through 2.5, and a number of links point to pages that should be paragraphs.
This is for the revision 2 of the book.

Current table of content:
![image](https://user-images.githubusercontent.com/18516529/33871448-86191f8a-df4d-11e7-99cb-0cb13983703e.png)

Correct table of content:
![image](https://user-images.githubusercontent.com/18516529/33871378-3c7311b0-df4d-11e7-84ac-cb081370a60f.png)

**Comment by jnavila** [comment]
I guess it comes from progit/progit2#932

**Comment by jnavila** [comment]
Before rejoicing, let's check that the issue is gone. :crossed_fingers:

**Comment by qouoq** [comment]
Fantastic, it's good now!
