### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by menelaos** [progit/progit2#935]
The links in the online version are broken.
See e.g. the link to `Customizing Git` at the bottom of https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain

**Comment by jnavila** [comment]
This is due to the script on git-scm.com not accomodating correctly the changes in links introduced in #932 .

**Comment by jnavila** [comment]
Should be fixed now.

**Comment by menelaos** [comment]
Thanks!
