### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by andrew-ts** [progit/progit2#945]
/usr/local/Cellar/git/2.10.2/libexec/git-core/git-stash: line 470: 14946 Segmentation fault: 11  git merge-recursive $b_tree -- $c_tree $w_tree

**Comment by jnavila** [comment]
This issue tracker is dedicated to the progit book.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

If you need help with using git, you can ask the [community](https://git-scm.com/community)

**Comment by andrew-ts** [comment]
Sorry, my fault.
