### ISSUE TITLE
Mislabel in figure 69 - 5.2 Contributing to a Project

### ISSUE THREAD

**Issue by yunhailuo** [progit/progit2#950]
Should Josie and John be switched? The features they worked on in the [figure](https://github.com/progit/progit2/blob/master/images/managed-team-flow.png) don't match the main text: "John and Jessica are working together on one feature (call this “featureA”), while Jessica and a third developer, Josie, are working on a second (say, “featureB”)".

**Comment by ben** [comment]
Aha, you're right! Want to submit a PR?

**Comment by yunhailuo** [comment]
As I explained in the pull request, I'm not good at photo editing and (more than) doubled the image size. I'm sorry. If anyone has a better solution, please help.

**Comment by mtilson** [comment]
It seems that commit # 89522c69dd096098436480700d377aff179c2cf5 "Generate new PNGs" reverts back this issue with Figure 69.
Please see the [history of the "managed-team-flow.png" file](https://github.com/progit/progit2/commits/master/images/managed-team-flow.png)
