### ISSUE TITLE
Missing Image Resource in ePub

### ISSUE THREAD

**Issue by jxramos** [progit/progit2#952]
Seems like all the generated xhtml documents refer to an image that's absent in the directory structure as rendered; all attempt to pull in this **default.jpg** avatar under the following reference in the img tag...

```
<header>
<div class="chapter-header">
<p class="byline"><img src="images/avatars/default.jpg"/> <b class="author"></b></p>
<h1 class="chapter-title"> <small class="subtitle"><b>GIT</b> <b>COMMANDS</b></small></h1>
</div>
</header>
```
When validating the 2.2.20 epub these are appearing with the following errors...

File | Line | Position | Message
-- | -- | -- | --
OEBPS/document-20898940.xhtml | 24 | 58 | Referenced resource could not be found in the   EPUB.
OEBPS/document-21891700.xhtml | 24 | 58 | Referenced resource could not be found in the EPUB.
OEBPS/document-24438840.xhtml | 24 | 58 | Referenced resource could not be found in the EPUB.
OEBPS/document-24502880.xhtml | 24 | 58 | Referenced resource could not be found in the EPUB.
OEBPS/document-24759260.xhtml | 24 | 58 | Referenced resource could not be found in the EPUB.
OEBPS/document-25028680.xhtml | 24 | 58 | Referenced resource could not be found in the EPUB.
OEBPS/document-27863020.xhtml | 24 | 58 | Referenced resource could not be found in the EPUB.
OEBPS/document-28167740.xhtml | 24 | 58 | Referenced resource could not be found in the EPUB.
OEBPS/document-28692880.xhtml | 24 | 58 | Referenced resource could not be found in the EPUB.
OEBPS/document-29909900.xhtml | 24 | 58 | Referenced resource could not be found in the EPUB.
OEBPS/document-30415480.xhtml | 24 | 58 | Referenced resource could not be found in the EPUB.
OEBPS/document-30815420.xhtml | 24 | 58 | Referenced resource could not be found in the EPUB.
OEBPS/document-30951860.xhtml | 24 | 58 | Referenced resource could not be found in the EPUB.
OEBPS/pro-git.xhtml | 24 | 58 | Referenced resource could not be found in the EPUB.

There seems to be a confusion introduced with the directory structure, there is an images  folder but no avatars subfolder. There is however an avatars sibling folder to the images folder which does have the default.jpg image present

![defaultjpgresource](https://user-images.githubusercontent.com/13857038/34501591-6bbc82e4-efc4-11e7-8b08-51d1654c1c1f.jpg)

I tried grepping the asc files to see how this came about but didn't make any headway searching for default.jpg, avatars, etc.

**Comment by jnavila** [comment]
see #954
