### ISSUE TITLE
Missing Fragment Identifiers in ePub

### ISSUE THREAD

**Issue by jxramos** [progit/progit2#953]
Combing over ePub validation errors for the 2.2.20 ePub I'm seeing a set of "Fragment identifier not defined" hits. The Positions you see enumerated in the table below basically all are the closing `>` of the opening anchor tag.

File | Line | Position | Message | Source
-- | -- | -- | -- | --
OEBPS/document-21891700.xhtml | 178 | 117 | Fragment identifier is not defined. | ```<p>Now your project history has diverged (see <a   id="xref-divergent_history" href="#divergent_history"   class="xref">Divergent   history</a>﻿).```
OEBPS/document-27863020.xhtml | 75 | 87 | Fragment identifier is not defined. | ```The process works as follows (see <a id="xref-wfdiag_b"   href="#wfdiag_b" class="xref">Integration-manager workflow.</a>﻿):</p>```
OEBPS/document-27863020.xhtml | 117 | 86 | Fragment identifier is not defined. | ```The process works like this (see <a id="xref-wfdiag_c"   href="#wfdiag_c" class="xref">Benevolent dictator workflow.</a>﻿):</p>```
OEBPS/document-28167740.xhtml | 317 | 79 | Fragment identifier is not defined. | ```Look back at the example commit history in <a   href="#double_dot" class="xref">Example history for range selection.</a>﻿.```
OEBPS/document-28692880.xhtml | 125 | 83 | Fragment identifier is not defined. | ```<p>In <a id="xref-_add_email_addresses"   href="#_add_email_addresses" class="xref">Add email addresses</a>﻿   we can see some of the different states that are possible.```
OEBPS/document-28692880.xhtml | 436 | 419 | Fragment identifier is not defined. | ```<p>Now if Tony goes back and closes out the original Pull Request,   we can see that by mentioning it in the new one, GitHub has automatically   created a trackback event in the Pull Request timeline. This means that   anyone who visits this Pull Request and sees that it is closed can easily   link back to the one that superseded it. The link will look something like   <a id="xref-_pr_closed" href="#_pr_closed"   class="xref">Link   back to the new Pull Request in the closed Pull Request   timeline.</a>﻿.</p>```
OEBPS/document-30951860.xhtml | 215 | 149 | Fragment identifier is not defined. | ```Double clicking on one of the local Git repositories leads you to the   Home view, which looks like <a id="xref-vs_home"   href="#vs_home" class="xref">The "Home" view for a Git repository in Visual   Studio.</a>﻿.```

There seems to be something broken in the fragment identifiers that attempt to navigate within the document. Here's the full search hits in the source followed by the rendered  doc

```
C:\ProGit\source\progit2>findstr /s /i divergent_history *.*
book\03-git-branching\sections\nutshell.asc:Now your project history has diverged (see <<divergent_history>>).
book\03-git-branching\sections\nutshell.asc:[[divergent_history]]

C:\ProGit\progit_2.1.20>findstr /n /s /i divergent_history *.*
OEBPS\document-21891700.xhtml:178:<p>Now your project history has diverged (see <a id="xref-divergent_history" href="#divergent_history" class="xref">Divergent history</a>﻿).




C:\ProGit\source\progit2>findstr /s /i wfdiag *.*
book\05-distributed-git\sections\distributed-workflows.asc:The process works as follows (see <<wfdiag_b>>):
book\05-distributed-git\sections\distributed-workflows.asc:[[wfdiag_b]]
book\05-distributed-git\sections\distributed-workflows.asc:The process works like this (see <<wfdiag_c>>):
book\05-distributed-git\sections\distributed-workflows.asc:[[wfdiag_c]]

C:\ProGit\progit_2.1.20>findstr /n /s /i wfdiag *.*
OEBPS\document-27863020.xhtml:75:The process works as follows (see <a id="xref-wfdiag_b" href="#wfdiag_b" class="xref">Integration-manager workflow.</a>﻿):</p>
OEBPS\document-27863020.xhtml:117:The process works like this (see <a id="xref-wfdiag_c" href="#wfdiag_c" class="xref">Benevolent dictator workflow.</a>﻿):</p>




C:\ProGit\source\progit2>findstr /s /i double_dot *.*
book\07-git-tools\sections\revision-selection.asc:For example, say you have a commit history that looks like <<double_dot>>.
book\07-git-tools\sections\revision-selection.asc:[[double_dot]]
book\07-git-tools\sections\revision-selection.asc:Look back at the example commit history in <<double_dot>>.

C:\ProGit\progit_2.1.20>findstr /n /s /i double_dot *.*
OEBPS\document-28167740.xhtml:261:<h4 id="_double_dot">Double Dot</h4>
OEBPS\document-28167740.xhtml:264:For example, say you have a commit history that looks like <a id="xref-double_dot" href="#double_dot" class="xref">Example history for range selection.</a>﻿.</p>
OEBPS\document-28167740.xhtml:317:Look back at the example commit history in <a href="#double_dot" class="xref">Example history for range selection.</a>﻿.




C:\ProGit\source\progit2>findstr /s /i add_email_addresses *.*
book\06-github\sections\1-setting-up-account.asc:[[_add_email_addresses]]
book\06-github\sections\1-setting-up-account.asc:In <<_add_email_addresses>> we can see some of the different states that are possible.

C:\ProGit\progit_2.1.20>findstr /n /s /i add_email_addresses *.*
OEBPS\document-28692880.xhtml:125:<p>In <a id="xref-_add_email_addresses" href="#_add_email_addresses" class="xref">Add email addresses</a>﻿ we can see some of the different states that are possible.




C:\ProGit\source\progit2>findstr /s /i pr_closed *.*
book\06-github\sections\2-contributing.asc:Now if Tony goes back and closes out the original Pull Request, we can see that by mentioning it in the new one, GitHub has automatically created a trackback event in the P
ull Request timeline. This means that anyone who visits this Pull Request and sees that it is closed can easily link back to the one that superseded it. The link will look something like <<_pr_closed>>.
book\06-github\sections\2-contributing.asc:[[_pr_closed]]

C:\ProGit\progit_2.1.20>findstr /n /s /i pr_closed *.*
OEBPS\document-28692880.xhtml:436:<p>Now if Tony goes back and closes out the original Pull Request, we can see that by mentioning it in the new one, GitHub has automatically created a trackback event in the Pull Request timeline. This means that anyone who visits this Pull Request and sees that it is closed can easily link back to the one that superseded it. The link will look something like <a id="xref-_pr_closed" href="#_pr_closed" class="xref">Link back to the new Pull Request in the closed Pull Request timeline.</a>﻿.</p>




C:\ProGit\source\progit2>findstr /s /i vs_home *.*
book\A-git-in-other-environments\sections\visualstudio.asc:Double clicking on one of the local Git repositories leads you to the Home view, which looks like <<vs_home>>.
book\A-git-in-other-environments\sections\visualstudio.asc:[[vs_home]]

C:\ProGit\progit_2.1.20>findstr /n /s /i vs_home *.*
OEBPS\document-30951860.xhtml:215:Double clicking on one of the local Git repositories leads you to the Home view, which looks like <a id="xref-vs_home" href="#vs_home" class="xref">The "Home" view for a Git repository in Visual Studio.</a>﻿.
```

I'm  not quite sure what's going on with the rendering, most seem entirely absent from the xhtml while another seems like a simple typo where for instance 
`OEBPS\document-28167740.xhtml:261:<h4 id="_double_dot">Double Dot</h4>`
is defined with a leading underscore while its being refered to absent the underscore.

**Comment by jnavila** [comment]
see #954
