### ISSUE TITLE
PDF eBook editing error

### ISSUE THREAD

**Issue by doudoubean** [progit/progit2#956]
An edit error appeared on page 12，line 16。The detail is as follow:
因为 Git 在保持向后兼容方便表现很好
I think  this ought to be modified like this. It's content is below:
因为 Git 在保持向后兼容方面表现很好

**Comment by YueLinHo** [comment]
Please report it to https://github.com/progit/progit2-zh

**Comment by doudoubean** [comment]
OK

**Comment by YueLinHo** [comment]
And please close this issue. :)
