### ISSUE TITLE
Internal links broken by commit e421495

### ISSUE THREAD

**Issue by rahrah** [progit/progit2#966]
Links in the posted pdf version of the book at https://github.com/progit/progit2/releases/download/2.1.31/progit.pdf, on locally generated pdfs and html are broken.

See:

Page 9
`than simply a VCS. We'll explore some of the benefits you gain by thinking of your data this way when we cover Git branching in [_git_branching#_git_branching].`

Page 10
`screwing things up. For a more in-depth look at how Git stores its data and how you can recover data that seems lost, see [_git_basics_chapter#_undoing].`

Indeed, many of the links changed by:

commit e421495f89f889b2eb6f294539b1ca574e541dfb
Author: Yunhai Luo <yunhail@stanford.edu>
Date:   Sun Dec 10 10:51:48 2017 -0800

are broken.  Broken links are where the commit changes all references of this form:

<<_xxxx>>  

to this:

<<_xxxx#_xxxx>>

I believe that correctly formatted inter-document cross references:

<<_section#_subsection>

still work.

Reverting this commit fixes the problem.

**Comment by ben** [comment]
Ping @yunhailuo, can you reproduce this?

**Comment by rahrah** [comment]
Just had a look at: 30.5. Inter-document Cross References in the asciidoctor manual and this:
https://github.com/asciidoctor/asciidoctor-pdf/issues/809 (Unable to include sections from other adoc files).

Links of both these forms definitely work:

<<book/07-git-tools/1-git-tools.asc#_git_reset>>

and
 
<<book/07-git-tools/sections/reset.asc#_git_reset>>

but

<<_git_tools#_git_reset>>

do not.

The example above is in:
book/02-git-basics/sections/undoing.asc line 95.

**Comment by jnavila** [comment]
These changes were made of ebooks internal link to work. I guess having the internal links work correctly for ebooks and pdf will require a bit of reworking again the structure of the files.

**Comment by rahrah** [comment]
Just looked at https://github.com/progit/progit2/releases/download/2.1.31/progit.epub

Internal links (at least the ones I checked) seem to be broken, there, too.

[_git_on_the_server#_getting_git_on_a_server]﻿, not a clickable link.

Using FBreader under linux for epub.

**Comment by jnavila** [comment]
On my computer, with updated Gemfile, the links in the epub work. But the ones in the pdf don't.

**Comment by deoren** [comment]
@rahrah See #954 for details re the updated Gemfile.

@jnavila Any chance that the Gemfile in master can be updated with the settings you're currently using while you wait on upstream to provide an updated "official" version of the affected gems?

**Comment by jnavila** [comment]
@deoren You need more than just Gemfile changes. I started the changes in the branch rework_files. This is still WIP but you can already compile and see that the links to the first chapters are indeed working in pdf and ebooks.

**Comment by deoren** [comment]
@jnavila Thanks! 

I can confirm that using that branch results in successful builds. It was a quick check, but the internal links I checked worked properly in both PDF and epub formats. Additionally I uploaded the epub version to Google Play Books and it had no complaints and displayed (from what I can tell) properly.

**Comment by deoren** [comment]
@jnavila FYI: Looks like the latest master asciidoctor is needed to resolve some other issues (e.g., asciidoctor/asciidoctor#2341). Not directly related, but wanted to share since you were applying some changes to the Gemfile in the `rework_files` branch.

**Comment by yunhailuo** [comment]
@jnavila Thank you for resolving the issue I introduced. Please let me know if I can help.

**Comment by jnavila** [comment]
@deoren @yunhailuo You can test the results from `rework_files`:
 * changed the version for asciidoctor to git HEAD
 * finish the renaming

The output epub was tested with epubcheck. All internal links resolve correctly. But the pdf has only be tested partially. 

Thanks.

**Comment by rahrah** [comment]
@jnavila

Works for html, pdf, and epub as far as I can tell.  No broken links found. Both asciidoctor 1.5.6.1 and asciidoctor git HEAD (4efc99eea) (1.5.7.dev) work fine (though both give two warnings about ids already assigned to sections).

This is a flagship project for asciidoctor and git based documentation authoring; it's brilliant that there are no errors in any generated documentation.  Thank you!

**Comment by jnavila** [comment]
Thanks for the check! The last one: verify that these changes don't upset git-scm.com edition chain.

@ben This branch is rather disruptive. Do you have any remarks?

**Comment by deoren** [comment]
@jnavila Just to echo @rahrah, I was able to build 6d42f6a120be17f5449a1b26c32ce11e362d4c2a without any apparent issue (internal links appeared to work fine). 

That said, an earlier build from your branch had internal links for the epub format style the same way as a pdf (without brackets or preceding underlines), but this latest build does

I've tested with Google Play Books, Atril Document Viewer (Ubuntu) and Calibre

Before:

![before](https://user-images.githubusercontent.com/1550338/35643511-2ab5d37a-068c-11e8-9fc3-614825b2bb21.png)

Now:

![now](https://user-images.githubusercontent.com/1550338/35643510-2aac3036-068c-11e8-8fc4-c0bf6bf04d5b.png)

Does the build process embed the responsible commit anywhere in the generated files?

**Comment by deoren** [comment]
@jnavila I forgot to say, the images I provided were from Calibre, while looking at the "Branches in a Nutshell" section from "Git Branching".

**Comment by jnavila** [comment]
@deoren I managed to reproduce here. There seems to be a regression in asciidoctor. If I revert in the Gemfile

```
gem 'asciidoctor', '1.5.6.1'
```

The good naming of the links is back. So we'll stay with the latest stable.

**Comment by jnavila** [comment]
@deoren BTW can you fill the bug report in asciidoctor 😀 ?

**Comment by deoren** [comment]
@jnavila I can do that. I have a copy of the rework_files branch in my fork that I can point to in the bug report.

**Comment by jnavila** [comment]
Bad news: it turns out that the script of git-scm expects the file names of first level chapters to provide the ordering of chapters. So that means a massive renaming of anchors... 😞

**Comment by ben** [comment]
> This branch is rather disruptive. Do you have any remarks?

The [branch diff](https://github.com/progit/progit2/compare/rework_files) doesn't actually look all that bad to me. Besides, I'm okay with "disruptive" if it gets us where we want to be.

**Comment by deoren** [comment]
> @jnavila: Bad news: it turns out that the script of git-scm expects the file names of first level chapters to provide the ordering of chapters. So that means a massive renaming of anchors...

Bummer. On the bright side, no boredom for you!  ;)

**Comment by deoren** [comment]
> @jnavila: @deoren BTW can you fill the bug report in asciidoctor 😀 ?

FYI: I opened asciidoctor/asciidoctor-epub3#157.

**Comment by jnavila** [comment]
Can we close this?

**Comment by deoren** [comment]
> @jnavila : Can we close this?

Acknowledging your question, but deferring to the OP (responding just in case you were including me in the question).

**Comment by rahrah** [comment]
@deoren @jnavila 

Will close, now.  Thank you for all your had work!

===R
