### ISSUE TITLE
epubcheck errors

### ISSUE THREAD

**Issue by DJViking** [progit/progit2#971]
Using epubcheck v4.0.1 is reporting many errors with the ePub version of this e-book.

There are four distinct type of errors:

    INFO(CSS-007): progit.epub/OEBPS/styles/epub3-fonts.css(5,3): Font-face reference OEBPS/fonts/notoserif-regular-latin.ttf refers to non-standard font type application/x-font-ttf.

    ERROR(OPF-027): progit.epub/OEBPS/document-24883680.xhtml(433,68): Undefined property: 'sect1'.

    ERROR(RSC-007): progit.epub/OEBPS/document-17019000.xhtml(726,182): Referenced resource could not be found in the EPUB.

    ERROR(RSC-012): progit.epub/OEBPS/document-17019000.xhtml(897,73): Fragment identifier is not defined.

[epubcheck.txt](https://github.com/progit/progit2/files/1696110/epubcheck.txt)

**Comment by deoren** [comment]
@DJViking Which version of the book?

**Comment by DJViking** [comment]
v2.1.33

**Comment by deoren** [comment]
@DJViking I don't know for sure, but I suspect that the work that @jnavila is doing on the `rework_files` branch will resolve this.

I built an epub from that branch, wrapped it in a zip file (to meet GitHub requirements) and have posted it here.

What results do you get with this file?

[progit.zip](https://github.com/progit/progit2/files/1696378/progit.zip)

**Comment by DJViking** [comment]
I get no errors on epubcheck with that file.

    Validating using EPUB version 3.0.1 rules.
    No errors or warnings detected.
    epubcheck completed

**Comment by jnavila** [comment]
Yet, there are still some errors lurking in this file 😉 .
