### ISSUE TITLE
book v2.1.33 errata

### ISSUE THREAD

**Issue by DJViking** [progit/progit2#972]
[book/05-distributed-git/sections/contributing.asc](https://github.com/progit/progit2/blob/master/book/05-distributed-git/sections/contributing.asc)
> It’s also a good idea to use the imperative present tense in these messages. In other words, use commands. Instead of “I added tests for” or “Adding tests for,” use “Add tests for.” Here is a template originally written by Tim Pope:

The book do not always follow its own recommondation about proper git commit messages.

The secction "Committing Your Changes" should point a reference to this recommondation section.

Errata:
[book/02-git-basics/sections/viewing-history.asc](https://github.com/progit/progit2/blob/master/book/02-git-basics/sections/viewing-history.asc)
     changed the version number => Change the version number
     removed unnecessary test => Remove unnecessary test
 
[book/03-git-branching/sections/nutshell.asc](https://github.com/progit/progit2/blob/master/book/03-git-branching/sections/nutshell.asc)
  Fixed bug #1328 => Fix bug #1328
  made a change => make a change
  made other changes => make other changes

There are different case in two examples:
34ac2 Fixed bug #1328
34ac2 fixed bug #1328

[book/03-git-branching/sections/basic-branching-and-merging.asc](https://github.com/progit/progit2/blob/master/book/03-git-branching/sections/basic-branching-and-merging.asc)
 added a new footer => add a new footer
 finished the new footer => finish the new footer
 fixed the broken email address => fix the broken email address
 
[book/03-git-branching/sections/remote-branches.asc](https://github.com/progit/progit2/blob/master/book/03-git-branching/sections/remote-branches.asc)
 forgot the brackets =>  add forgotten brackets
 deploying index fix => deploy index fix
 trying something new => try something new
 
[book/05-distributed-git/sections/contributing.asc](https://github.com/progit/progit2/blob/master/book/05-distributed-git/sections/contributing.asc)
 made the ls-tree function recursive => make the ls-tree function recursive
 
[book/05-distributed-git/sections/maintaining.asc](https://github.com/progit/progit2/blob/master/book/05-distributed-git/sections/maintaining.asc)
 seeing if this helps the gem => see if this helps the gem
 updated the gemspec to hopefully work better => update the gemspec to hopefully work better
 
This is all I have for now after gotten to page 153 (PDF v2.1.33).

**Comment by ben** [comment]
Before you spend too much time documenting issues like this, do you want to just submit a pull request? It'll be faster for you _and_ for us.

> The book do not always follow its own recommondation about proper git commit messages.

Yeah, this is a bit of a conundrum. We sacrifice good commit messages for the sake of brevity. We also use the `-m` flag all the time, because it's hard to show dropping into an editor to type in a _real_ message. I think the use of `-m` is appropriate for this book, since it helps keep the focus where it should be, but I'd love to review changes to the short messages we use.

**Comment by DJViking** [comment]
Sure I could submit a pull request.

**Comment by jnavila** [comment]
Maybe a warning at the first use of this form of commit with a link to the appropriate section would be helpful here.
