### ISSUE TITLE
Cebuano Translation Needed?

### ISSUE THREAD

**Issue by caratzky** [progit/progit2#973]
Hello, I am a Cebuano, a major dialect in the Philippines next to Filipino and Tagalog, and I'm a frequent open-source translations contributor being rewarded Utopian.io in these languages.  May I know if you needed a translation for Cebuano? In ISO 639-1, it is coded as "ceb". It would be my pleasure to provide a high-quality translation for your project. Thank you.

**Comment by jnavila** [comment]
The content is under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 license, so you are free to translate it. Deciding if this translation is needed is up to you.

As mentioned in https://github.com/progit/progit2/blob/master/CONTRIBUTING.md#translations, you have to create a new organization to hold your own repository (no local folder in our repository). Then, we'll add a pointer to your repo in our CONTRIBUTING page.
