### ISSUE TITLE
Want to contribute to Indonesian translation

### ISSUE THREAD

**Issue by anaufalm** [progit/progit2#974]
Hi, I wanna join this translation. I will translate this book from original file (english) in folder progit/progit2 into Indonesian in folder progit/progit2-id. If you allow me to translate this book, I will start after you approve my proposal (reply to this issue). I will translate gradually and continuously until everything I translate.
thanks.

Regard.

**Comment by jnavila** [comment]
The content is under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0  license, so you are free to translate it.

As mentionned in https://github.com/progit/progit2/blob/master/CONTRIBUTING.md#translations, you have to create a new  organization to hold your own repository (no local folder). Then, we'll add a pointer to your repo in our CONTRIBUTING page.

**Comment by jnavila** [comment]
In fact, there's already a translation repo here: https://github.com/progit/progit2-id
