### ISSUE TITLE
Localization/Translation to German

### ISSUE THREAD

**Issue by agentzero1** [progit/progit2#979]
Good day sir i want to contribute in translation

**Comment by jnavila** [comment]
Please follow the guidelines in CONTRIBUTING.md

**Comment by jnavila** [comment]
Just to check: are you a native german speaker?

**Comment by agentzero1** [comment]
No, but I can understand German language

**Comment by jnavila** [comment]
FYI, there the repo [progit-de/progit2](https://github.com/progit-de/progit2)

**Comment by lazarljubenovic** [comment]
Even professional translators often only translate _into_ their native language. I'd suggest carefully thinking about your German language level before translating, so the translaton sounds as natural as possible. Especially since the tone of the book is supposed to remain friendly.
