### ISSUE TITLE
Translation to Italian language

### ISSUE THREAD

**Issue by agentzero1** [progit/progit2#981]
I want to contribute in translation

**Comment by daftano** [comment]
Ciao, benvenuto!

**Comment by jnavila** [comment]
@agentzero1 Ealier, you proposed to translate to german. What game are you playing?

**Comment by agentzero1** [comment]
Sorry i thought  you will not accept German language base on my understanding

**Comment by agentzero1** [comment]
Just ignore this I will continue my  German translation , Im so sorry for that matter

**Comment by daftano** [comment]
No worries
