### ISSUE TITLE
Adding Vietnamese Translation

### ISSUE THREAD

**Issue by chrisli88** [progit/progit2#988]
Hello everyone!
I'm a Vietnamese software developer and i want to contribute translating this book into Vietnamese. I've created a new organization and fork this project as requested in CONTRIBUTING.md. You can check it here 
[https://github.com/progit2-vi/progit2](https://github.com/progit2-vi/progit2).

Thanks,

**Comment by jnavila** [comment]
Good ! Start translating and when you already have at least the first chapter, we'll integrate the pointer to your repository.

Don't forget to post an update when you're ready.

**Comment by chrisli88** [comment]
You mean i need to have translated at least the first chapter in my repository then you'll integrate the pointer to my repository, right?

**Comment by jnavila** [comment]
Yes, exactly. Your repository will be the reference for the vietnamese translation.

**Comment by parkinson101** [comment]
#1016

**Comment by vietstone** [comment]
Hi, I want to participate in this translation. I don't see any way to get in touch in https://github.com/progit2-vi/progit2
@chrisli88 how can I get in touch with you

**Comment by bohsen** [comment]
Related to #629

**Comment by HonkingGoose** [comment]
@jnavila What are your thoughts on this issue? The translation at https://github.com/progit2-vi/progit2 still needs more work to be pulled into git-scm.

**Comment by jnavila** [comment]
Repo where no work was done don't qualify for inclusion in TRANSLATING. They are just dead forks.
