### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by bengtsteemit** [progit/progit2#995]
Hello, I started to make Italian translation for the project. But no one answered my PR. And latest activity 3 years ago. Does anyone look at the Italian section?

**Comment by daftano** [comment]
Hi there, where are your PR?

**Comment by bengtsteemit** [comment]
Hello, thank you for your attention. 

Sono uno studente di lingua e letteratura italiana in Turchia.

**Comment by daftano** [comment]
c'è un gruppo per i traduttori in italiano (indicato su http://github.com/progit/progit2-it).
E invece di tradurre tutto da zero, ti consiglio di vedere la traduzione precedente e rivedere i contenuti in considerazione della nuova versione.
E magari spezzettare le modifiche in più commit, in modo da rivederle meglio.
Che te ne pare?

**Comment by bengtsteemit** [comment]
Ho inviato una richiesta per far parte del gruppo. Dovrei chiudere la mia
richiesta di PR?

2018-02-15 23:29 GMT+03:00 David <notifications@github.com>:

**Comment by daftano** [comment]
Ho approvato la tua richiesta: ora sei parte del gruppo. Benvenuta! 😀
Se chiudi questa issue continuiamo nel nostro progetto e sul gruppo.

**Comment by jnavila** [comment]
Cool!
